# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [5]:
### [your code here]
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [8]:
### [your code here]
np.__version__

'1.26.4'

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [16]:
### [your code here]
a = np.random.random((2,3,5))
a = np.random.rand(2,3,5)
a = np.random.randn(2,3,5)



### 4. Print a.


In [18]:
### [your code here]
print (a)


[[[ 2.92716798  1.58147723 -0.73904497  0.69037633  0.33377478]
  [-0.41771278  1.19430794 -0.20841123 -0.83451426  1.38637028]
  [-0.46200644 -0.5438298  -0.75903463  0.81398108 -0.54433797]]

 [[ 0.68287479  1.3918397  -0.34871236  0.53184102  0.50045689]
  [ 0.86541832 -0.98663126  0.22410229 -0.08497003  0.35904514]
  [ 0.34974098 -0.44929979 -0.76040402  1.15885121  1.86243424]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [20]:
### [your code here]
b = np.full((5,3,2) , 1 )
print (b)


[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]



### 6. Print b.


In [22]:
### [your code here]
print(b)

[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [24]:
### [your code here]
print (a)
print (b)

print("The Size of A: ", a.size)
print("The Size of B: ", b.size)

print("Do They Have The Same Size ?  ", a.size == b.size)

[[[ 2.92716798  1.58147723 -0.73904497  0.69037633  0.33377478]
  [-0.41771278  1.19430794 -0.20841123 -0.83451426  1.38637028]
  [-0.46200644 -0.5438298  -0.75903463  0.81398108 -0.54433797]]

 [[ 0.68287479  1.3918397  -0.34871236  0.53184102  0.50045689]
  [ 0.86541832 -0.98663126  0.22410229 -0.08497003  0.35904514]
  [ 0.34974098 -0.44929979 -0.76040402  1.15885121  1.86243424]]]
[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]
The Size of A:  30
The Size of B:  30
Do They Have The Same Size ?   True



### 8. Are you able to add a and b? Why or why not?


In [26]:
### [your code here]
try:
    result = a + b
    print(" Addition Successuful ! ")

except ValueError as e:
    print(" ERROR : ", e)


 ERROR :  operands could not be broadcast together with shapes (2,3,5) (5,3,2) 




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [32]:
### [your code here]
print(a.shape)
print(b.shape)


(2, 3, 5)
(5, 3, 2)


In [42]:
### [your code here]
c = np.transpose(b ,( 2 , 1 , 0))

print( a.shape)
print(b.shape)
print(c.shape)

(2, 3, 5)
(5, 3, 2)
(2, 3, 5)



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [77]:
### [your code here]
try:
    d = a + c 
    print(" Addition Successful ! ")
    print(d)

except ValueError as e :
    print(" ERROR : " , e)

print( " Addition Successful because Array a AND c have the same Size " , a.shape == c.shape)




 Addition Successful ! 
[[[3.92716798 2.58147723 0.26095503 1.69037633 1.33377478]
  [0.58228722 2.19430794 0.79158877 0.16548574 2.38637028]
  [0.53799356 0.4561702  0.24096537 1.81398108 0.45566203]]

 [[1.68287479 2.3918397  0.65128764 1.53184102 1.50045689]
  [1.86541832 0.01336874 1.22410229 0.91502997 1.35904514]
  [1.34974098 0.55070021 0.23959598 2.15885121 2.86243424]]]
 Addition Successful because Array a AND c have the same Size  True



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [80]:
### [your code here]
print("Array a : \n" ,a)
print("Array b : \n" ,b)



Array a : 
 [[[ 2.92716798  1.58147723 -0.73904497  0.69037633  0.33377478]
  [-0.41771278  1.19430794 -0.20841123 -0.83451426  1.38637028]
  [-0.46200644 -0.5438298  -0.75903463  0.81398108 -0.54433797]]

 [[ 0.68287479  1.3918397  -0.34871236  0.53184102  0.50045689]
  [ 0.86541832 -0.98663126  0.22410229 -0.08497003  0.35904514]
  [ 0.34974098 -0.44929979 -0.76040402  1.15885121  1.86243424]]]
Array b : 
 [[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]



### 12. Multiply a and c. Assign the result to e.


In [83]:
### [your code here]
e = a * c 




### 13. Does e equal to a? Why or why not?


In [86]:
### [your code here]
print(" Does e equal to e ? ", np.array_equal( a , e ))




 Does e equal to e ?  True




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [89]:
### [your code here]

d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(" Max value in d :", d_max)
print(" Min value in d :", d_min)
print(" Mean value in d :",d_mean)


 Max value in d : 3.9271679837937827
 Min value in d : 0.013368741857819
 Mean value in d : 1.323838355508261



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [93]:
### [your code here]
f = np.empty(d.shape)





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [99]:
### [your code here]
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i , j , k] == d_min:
                f[i , j , ] = 0
            elif d[i , j, k] == d_max:
                f[i , j ,k] = 100
            elif d[i , j , k] == d_mean:
                f[ i, j ,k ] == 50
            elif d_min < d[i, j , k] < d_mean:
                f[ i , j , k] = 25
            elif d_mean < d[ i , j , k] < d_max:
                f[i , j , k] = 75

print (" Array f : \n" , f)

 Array f : 
 [[[100.  75.  25.  75.  75.]
  [ 25.  75.  25.  25.  75.]
  [ 25.  25.  25.  75.  25.]]

 [[ 75.  75.  25.  75.  75.]
  [  0.   0.  25.  25.  75.]
  [ 75.  25.  25.  75.  75.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [103]:
### [your code here]
print( d )
print (f )


[[[3.92716798 2.58147723 0.26095503 1.69037633 1.33377478]
  [0.58228722 2.19430794 0.79158877 0.16548574 2.38637028]
  [0.53799356 0.4561702  0.24096537 1.81398108 0.45566203]]

 [[1.68287479 2.3918397  0.65128764 1.53184102 1.50045689]
  [1.86541832 0.01336874 1.22410229 0.91502997 1.35904514]
  [1.34974098 0.55070021 0.23959598 2.15885121 2.86243424]]]
[[[100.  75.  25.  75.  75.]
  [ 25.  75.  25.  25.  75.]
  [ 25.  25.  25.  75.  25.]]

 [[ 75.  75.  25.  75.  75.]
  [  0.   0.  25.  25.  75.]
  [ 75.  25.  25.  75.  75.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [105]:
### [your code here]
print ( f)

[[[100.  75.  25.  75.  75.]
  [ 25.  75.  25.  25.  75.]
  [ 25.  25.  25.  75.  25.]]

 [[ 75.  75.  25.  75.  75.]
  [  0.   0.  25.  25.  75.]
  [ 75.  25.  25.  75.  75.]]]


In [113]:
f_str = np.empty(f.shape , dtype = str)


for i in range (f.shape[0]):
    for j in range (f.shape[1]):
        for k in range (f.shape [2]):
            if f [i , j , k] == 0 : 
                f_str[i , j , k] = "A"
            elif f [ i, j , k ] == 25:
                f_str[i , j , k] = "B"
            elif f [i , j , k] == 50 :
                f_str [i , j , k] = "C"
            elif f[i , j , k] == 75 :
                f_str[i , j , k] = "D"
            elif f[i , j , k] == 100:
                 f_str[i , j , k] = "E"



print (f_str)


[[['E' 'D' 'B' 'D' 'D']
  ['B' 'D' 'B' 'B' 'D']
  ['B' 'B' 'B' 'D' 'B']]

 [['D' 'D' 'B' 'D' 'D']
  ['A' 'A' 'B' 'B' 'D']
  ['D' 'B' 'B' 'D' 'D']]]
