# **Lab-Numpy**

#### 1. Import the numpy package under the name `np` (★☆☆)
`hint: import … as`

#### 2. Create a null vector of size 10 (★☆☆)
`hint: np.zeros`

#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
`hint: array[4]`

#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
`hint: arange`

#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
`hint: reshape`

#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
`hint: np.nonzero`

#### 7. Create a 3x3 identity matrix (★☆☆)
`hint: np.eye`

#### 8. Create a 3x3x3 array with random values (★☆☆)
`hint: np.random.random`

#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
`hint: min, max`

#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
`hint: mean`

#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`hint: np.diag`

#### 12. Normalize a 5x5 random matrix (★☆☆)
`hint: (x -mean)/std`

#### 13. How to find common values between two arrays? (★☆☆)
`hint: np.intersect1d`

#### 14. Create a random vector of size 10 and sort it (★★☆)
`hint: sort`

#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
`hint: argmax`

#### 16. Subtract the mean of each row of a matrix (★★☆)
`hint: mean(axis=,keepdims=)`

#### 17. How to get the n largest values of an array (★★★)
`Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
hint: np.argsort | np.argpartition`

#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
`hint: np.where`


In [3]:
#1
import numpy as np

In [4]:
#2 . Create a null vector of size 10
vector = np.zeros(10)
print(vector)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
#3 Create a null vector of size 10 but the fifth value which is 1
vector[4] = 1
print(vector)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [6]:
#4 Create a vector with values ranging from 10 to 49
vector = np.arange(10, 50)
print(vector)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [7]:
#5 Create a 3x3 matrix with values ranging from 0 to 8
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
#6 Find indices of non-zero elements from [1,2,0,0,4,0]
array=[1,2,0,0,4,0]
non_zero_indices = np.nonzero(array)
print(non_zero_indices)

(array([0, 1, 4]),)


In [9]:
#7 Create a 3x3 identity matrix
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
#8 Create a 3x3x3 array with random values
random_array = np.random.random((3, 3, 3))
print(random_array)

[[[0.21940588 0.73187285 0.34496497]
  [0.53336741 0.0570978  0.52587016]
  [0.51050807 0.66823228 0.19229379]]

 [[0.56059982 0.63771386 0.97170118]
  [0.3026681  0.52713754 0.1448633 ]
  [0.93314466 0.79913221 0.88403887]]

 [[0.17703342 0.94374824 0.40650397]
  [0.91419778 0.73064577 0.48285262]
  [0.42492775 0.14354737 0.28250412]]]


In [11]:
#9 Create a 10x10 array with random values and find the minimum and maximum values 

random_array = np.random.random((10, 10))

# Find the minimum and maximum values
min_value = random_array.min()
max_value = random_array.max()

print("Minimum Value:", min_value)
print("Maximum Value:", max_value)


Minimum Value: 0.009851729709047352
Maximum Value: 0.985412826105582


In [12]:
#10  Create a random vector of size 30 and find the mean value 

random_vector = np.random.random(30)
mean_value = random_vector.mean()

print("Random Vector:", random_vector)
print("Mean Value:", mean_value)

Random Vector: [0.46724049 0.33673294 0.0604591  0.86337027 0.08077978 0.69347931
 0.51048187 0.63990656 0.18470107 0.23582909 0.97718555 0.44114102
 0.87673219 0.04612775 0.14212269 0.10373957 0.35489628 0.08589414
 0.3720373  0.31182765 0.76518163 0.15141776 0.29853727 0.909517
 0.06069947 0.3093576  0.29116741 0.75767736 0.32436492 0.71759703]
Mean Value: 0.41234006986930694


In [23]:
#11 Create a 5x5 matrix with values 1,2,3,4 just below the diagonal
matrix = np.diag([1, 2, 3, 4], k=-1)
print(matrix)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [14]:
#12 Normalize a 5x5 random matrix

random_matrix = np.random.rand(5, 5)

# Normalize the matrix (x - mean) / std
normalized_matrix = (random_matrix - np.mean(random_matrix)) / np.std(random_matrix)
print(normalized_matrix)


[[ 0.62858197  1.59329895 -0.53625902 -0.83791271 -1.46172386]
 [ 0.09538572  0.25080342 -0.10892462 -0.94782233 -1.18981592]
 [-1.23310729  1.58561322  1.02134009  0.37186951  1.27219787]
 [ 0.28383425 -0.83819138  0.16207714 -1.3611429   1.24623782]
 [ 1.38989898 -1.17776928  1.05930956 -0.98567431 -0.28210488]]


In [15]:
#13 How to find common values between two arrays?
array1 = np.array([98, 2, 3, 4, 5])
array2 = np.array([4, 5, 6, 7, 8])

# Find common values between the two arrays
common_values = np.intersect1d(array1, array2)
print(common_values)

[4 5]


In [16]:
#14 Create a random vector of size 10 and sort it
random_vector = np.random.rand(10)

# Sort the vector
sorted_vector = np.sort(random_vector)
print(sorted_vector)

[0.24206463 0.25722433 0.29715762 0.30185096 0.30714489 0.41757883
 0.44545442 0.5795811  0.68371905 0.71463214]


In [17]:
#15 Create random vector of size 10 and replace the maximum value by 0
# Create a random vector of size 10
random_vector = np.random.rand(10)
print(random_vector)

# Replace the maximum value with 0
random_vector[np.argmax(random_vector)] = 0
print(random_vector)

[0.96791624 0.81667168 0.16155326 0.78087583 0.58727786 0.94942698
 0.5425264  0.51223609 0.9159665  0.54908306]
[0.         0.81667168 0.16155326 0.78087583 0.58727786 0.94942698
 0.5425264  0.51223609 0.9159665  0.54908306]


In [18]:
#16 Subtract the mean of each row of a matrix 

# Create a random matrix of size 5x5
matrix = np.random.rand(5, 5)

# Subtract the mean of each row
substraction = matrix - np.mean(matrix, axis=1, keepdims=True)
print(substraction)


[[-0.22516412  0.36613933  0.35757461 -0.27618896 -0.22236087]
 [-0.48174887  0.24263617  0.06170379  0.13031422  0.04709469]
 [-0.29279466  0.11773178  0.29793119  0.41238767 -0.53525598]
 [ 0.25175876 -0.25313073  0.20243128 -0.523059    0.32199969]
 [-0.07857368  0.15385061  0.23688893 -0.30762072 -0.00454513]]


In [19]:
#17 How to get the n largest values of an array

# Create a shuffled array
Z = np.arange(10000)
np.random.shuffle(Z)

# Number of largest values to find
n = 5

# Get the n largest values
n_largest_values = Z[np.argpartition(Z, -n)[-n:]]
n_largest_values_sorted = np.sort(n_largest_values)  # Sort the values if needed
print(n_largest_values_sorted)


[9995 9996 9997 9998 9999]


In [20]:
#18 Create a random 5*3 matrix and replace items that are larger than 4 by their squares

# Create a random 5x3 matrix with values between 0 and 10
matrix = np.random.randint(0, 10, (5, 3))

# Replace items larger than 4 with their squares
result = np.where(matrix > 4, matrix ** 2, matrix)

print("Original Matrix:\n", matrix)
print("Modified Matrix:\n", result)


Original Matrix:
 [[0 6 8]
 [9 9 7]
 [3 0 9]
 [9 5 9]
 [8 0 8]]
Modified Matrix:
 [[ 0 36 64]
 [81 81 49]
 [ 3  0 81]
 [81 25 81]
 [64  0 64]]
