# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [34]:
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [35]:
print(np.__version__)
print(np.show_config())

2.0.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/Admin/anaconda3/envs/albandari1/Library/include
    lib directory: C:/Users/Admin/anaconda3/envs/albandari1/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_6emx8om0_1\croot\numpy_and_numpy_base_1736283274014\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/Admin/anaconda3/envs/albandari1/Library/include
    lib directory: C:/Users/Admin/anaconda3/envs/albandari1/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_6emx8om0_1\croot\numpy_and_numpy_base_1736283274014\_h_env\Library\lib\pkgconfig
    version: '2023.1'
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30157
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30157

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [36]:
a = np.random.random((2, 3, 5))


### 4. Print a.


In [37]:
print (a)

[[[0.65735766 0.71772319 0.32310094 0.26291012 0.89543642]
  [0.54519259 0.07656267 0.21213345 0.24136403 0.21956759]
  [0.24158084 0.35040832 0.09999219 0.23343503 0.8910831 ]]

 [[0.3632287  0.23883569 0.8467135  0.81899811 0.75459088]
  [0.45535212 0.29798067 0.91844088 0.04274148 0.19512631]
  [0.5161612  0.16127406 0.92356644 0.83955378 0.81972703]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [38]:
b = np.ones((5, 2, 3))


### 6. Print b.


In [39]:
print (b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [40]:
print(a.size == b.size)

True



### 8. Are you able to add a and b? Why or why not?


In [88]:
#operands could not be broadcast together with shapes (2,3,5) (5,2,3)
a + b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [89]:
c = np.transpose(b, (1,2,0))
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [90]:
d = a + c



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [106]:
print("a:")
print(a)
print("d:")
print(d)
"""The array a contains random floating-point values, while the array d consists entirely of ones.
The relation between the two arrays is that d is used as a matrix of ones,
and when operations are performed between a and d,
the result is influenced by the values in a since multiplying any value by 1 will leave it unchanged.
This is the key difference: a holds varying data, while d is constant and uniform."""

SyntaxError: invalid syntax (217958860.py, line 7)


### 12. Multiply a and c. Assign the result to e.


In [86]:
e = a * c
print(e)

[[[0.71331519 0.38259266 0.78943388 0.10406541 0.79198517]
  [0.18060671 0.11251677 0.74203692 0.93510058 0.91880951]
  [0.99203504 0.37359703 0.30436606 0.52294285 0.07466315]]

 [[0.47818794 0.74526737 0.27939196 0.53949699 0.12408971]
  [0.39612374 0.13321745 0.28435971 0.59761169 0.35609943]
  [0.12582559 0.31266831 0.0745588  0.38940174 0.71515746]]]




### 13. Does e equal to a? Why or why not?


In [87]:
e == a

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [44]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

In [45]:
print(f"Max value in d: {d_max}")
print(f"Min value in d: {d_min}")
print(f"Mean value in d: {d_mean}")

Max value in d: 1.9921727028623741
Min value in d: 1.0277704035947255
Mean value in d: 1.4095508265945222



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [99]:
emp = np.empty(d.shape)
print(emp)

[[[1.71331519 1.38259266 1.78943388 1.10406541 1.79198517]
  [1.18060671 1.11251677 1.74203692 1.93510058 1.91880951]
  [1.99203504 1.37359703 1.30436606 1.52294285 1.07466315]]

 [[1.47818794 1.74526737 1.27939196 1.53949699 1.12408971]
  [1.39612374 1.13321745 1.28435971 1.59761169 1.35609943]
  [1.12582559 1.31266831 1.0745588  1.38940174 1.71515746]]]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [100]:
for i in range(d.shape[0]):  
    for j in range(d.shape[1]):  
        for k in range(d.shape[2]): 
            value = d[i, j, k]
            if value == d_min:
                f[i, j, k] = 0
            elif value == d_max:
                f[i, j, k] = 100
            elif value == d_mean:
                f[i, j, k] = 50
            elif d_min < value < d_mean:
                f[i, j, k] = 25
            elif d_mean < value < d_max:
                f[i, j, k] = 75
print("Array d:\n", d)
print("Array f:\n", f)

Array d:
 [[[1.71331519 1.38259266 1.78943388 1.10406541 1.79198517]
  [1.18060671 1.11251677 1.74203692 1.93510058 1.91880951]
  [1.99203504 1.37359703 1.30436606 1.52294285 1.07466315]]

 [[1.47818794 1.74526737 1.27939196 1.53949699 1.12408971]
  [1.39612374 1.13321745 1.28435971 1.59761169 1.35609943]
  [1.12582559 1.31266831 1.0745588  1.38940174 1.71515746]]]
Array f:
 [[[75 25 75 25 75]
  [25 25 75 75 75]
  [100 25 25 75 25]]

 [[75 75 25 75 25]
  [25 25 25 75 25]
  [25 25 0 25 75]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [108]:
for i in range(d.shape[0]):  
    for j in range(d.shape[1]):  
        for k in range(d.shape[2]):
            value = d[i, j, k]
            if value == d_min:
                f[i, j, k] = 0
            elif value == d_max:
                f[i, j, k] = 100
            elif value == d_mean:
                f[i, j, k] = 50
            elif d_min < value < d_mean:
                f[i, j, k] = 25
            elif d_mean < value < d_max:
                f[i, j, k] = 75
print("Array d:\n", d)
print("Array f:\n", f)                

Array d:
 [[[1.71331519 1.38259266 1.78943388 1.10406541 1.79198517]
  [1.18060671 1.11251677 1.74203692 1.93510058 1.91880951]
  [1.99203504 1.37359703 1.30436606 1.52294285 1.07466315]]

 [[1.47818794 1.74526737 1.27939196 1.53949699 1.12408971]
  [1.39612374 1.13321745 1.28435971 1.59761169 1.35609943]
  [1.12582559 1.31266831 1.0745588  1.38940174 1.71515746]]]
Array f:
 [[[75 25 75 25 75]
  [25 25 75 75 75]
  [100 25 25 75 25]]

 [[75 75 25 75 25]
  [25 25 25 75 25]
  [25 25 0 25 75]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [109]:
for i in range(d.shape[0]):  
    for j in range(d.shape[1]): 
        for k in range(d.shape[2]):  
            value = d[i, j, k]
            if value == d_min:
                f[i, j, k] = 'A'
            elif value == d_max:
                f[i, j, k] = 'E'
            elif value == d_mean:
                f[i, j, k] = 'C'
            elif d_min < value < d_mean:
                f[i, j, k] = 'B'
            elif d_mean < value < d_max:
                f[i, j, k] = 'D'


print("Array f:\n", f)


Array f:
 [[['D' 'B' 'D' 'B' 'D']
  ['B' 'B' 'D' 'D' 'D']
  ['E' 'B' 'B' 'D' 'B']]

 [['D' 'D' 'B' 'D' 'B']
  ['B' 'B' 'B' 'D' 'B']
  ['B' 'B' 'A' 'B' 'D']]]
