# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [ ]:
### [your code here]
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [1]:
### [your code here]
np.show_config()
print("NumPy Version:", np.__version__)
print("NumPy Configuration:")
np.show_config()

NameError: name 'np' is not defined

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [ ]:
### [your code here]
a = np.random.random((2,3,5))
a1 = np.random.randint(4,size=(5,5,4))

a


array([[[0.33263291, 0.17194177, 0.09545161, 0.07636247, 0.70445134],
        [0.10291983, 0.23109868, 0.84789179, 0.98568446, 0.80393899],
        [0.70805139, 0.43167372, 0.68269194, 0.51836493, 0.11024581]],

       [[0.75940512, 0.86459817, 0.33724737, 0.31685104, 0.01827302],
        [0.45642219, 0.06604215, 0.06681786, 0.40926918, 0.07042877],
        [0.06643929, 0.48037576, 0.41857826, 0.39690963, 0.37139132]]])

In [ ]:
a1

array([[[1, 0, 2, 3],
        [0, 2, 0, 2],
        [2, 3, 0, 3],
        [0, 3, 2, 1],
        [0, 1, 2, 0]],

       [[2, 1, 1, 0],
        [3, 3, 0, 3],
        [2, 1, 1, 0],
        [2, 2, 1, 3],
        [1, 3, 2, 3]],

       [[3, 1, 1, 2],
        [1, 0, 2, 2],
        [1, 1, 0, 1],
        [3, 3, 2, 3],
        [3, 3, 2, 1]],

       [[1, 1, 0, 3],
        [2, 1, 2, 1],
        [0, 0, 3, 2],
        [0, 2, 3, 1],
        [1, 2, 0, 1]],

       [[3, 2, 1, 1],
        [3, 3, 0, 2],
        [3, 2, 2, 2],
        [2, 1, 3, 0],
        [2, 3, 0, 0]]])


### 4. Print a.


In [ ]:
### [your code here]
a

array([[[0.33263291, 0.17194177, 0.09545161, 0.07636247, 0.70445134],
        [0.10291983, 0.23109868, 0.84789179, 0.98568446, 0.80393899],
        [0.70805139, 0.43167372, 0.68269194, 0.51836493, 0.11024581]],

       [[0.75940512, 0.86459817, 0.33724737, 0.31685104, 0.01827302],
        [0.45642219, 0.06604215, 0.06681786, 0.40926918, 0.07042877],
        [0.06643929, 0.48037576, 0.41857826, 0.39690963, 0.37139132]]])

### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [ ]:
### [your code here]
b= np.ones((5,2,3))


### 6. Print b.


In [ ]:
### [your code here]
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])


### 7. Do a and b have the same size? How do you prove that in Python code?


In [ ]:
### [your code here]
if np.shape(a)==np.shape(b):
  print("its same size")
else:
  print("its not same size")


its not same size



### 8. Are you able to add a and b? Why or why not?


In [ ]:
### [your code here]
# no becuse it not same size
if np.shape(a)==np.shape(b):
  a+b
  print("The addition of the two array succeeded because they have the same size 2x3x5")
else:
  print("not equal size")

not equal size




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [ ]:
### [your code here]
c=np.reshape(b,(2,3,5))


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [ ]:
### [your code here]
d = a+c
d

array([[[1.33263291, 1.17194177, 1.09545161, 1.07636247, 1.70445134],
        [1.10291983, 1.23109868, 1.84789179, 1.98568446, 1.80393899],
        [1.70805139, 1.43167372, 1.68269194, 1.51836493, 1.11024581]],

       [[1.75940512, 1.86459817, 1.33724737, 1.31685104, 1.01827302],
        [1.45642219, 1.06604215, 1.06681786, 1.40926918, 1.07042877],
        [1.06643929, 1.48037576, 1.41857826, 1.39690963, 1.37139132]]])



```
# This is formatted as code
```


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [ ]:
### [your code here]
a


array([[[0.33263291, 0.17194177, 0.09545161, 0.07636247, 0.70445134],
        [0.10291983, 0.23109868, 0.84789179, 0.98568446, 0.80393899],
        [0.70805139, 0.43167372, 0.68269194, 0.51836493, 0.11024581]],

       [[0.75940512, 0.86459817, 0.33724737, 0.31685104, 0.01827302],
        [0.45642219, 0.06604215, 0.06681786, 0.40926918, 0.07042877],
        [0.06643929, 0.48037576, 0.41857826, 0.39690963, 0.37139132]]])

In [ ]:
d

array([[[1.33263291, 1.17194177, 1.09545161, 1.07636247, 1.70445134],
        [1.10291983, 1.23109868, 1.84789179, 1.98568446, 1.80393899],
        [1.70805139, 1.43167372, 1.68269194, 1.51836493, 1.11024581]],

       [[1.75940512, 1.86459817, 1.33724737, 1.31685104, 1.01827302],
        [1.45642219, 1.06604215, 1.06681786, 1.40926918, 1.07042877],
        [1.06643929, 1.48037576, 1.41857826, 1.39690963, 1.37139132]]])

In [ ]:
if np.shape(a)==np.shape(d):

  print("The addition of the two array succeeded because they have the same size 2x3x5")
else:
  print("not equal size")

The addition of the two array succeeded because they have the same size 2x3x5



### 12. Multiply a and c. Assign the result to e.


In [ ]:
### [your code here]
e = a*c
e

array([[[0.33263291, 0.17194177, 0.09545161, 0.07636247, 0.70445134],
        [0.10291983, 0.23109868, 0.84789179, 0.98568446, 0.80393899],
        [0.70805139, 0.43167372, 0.68269194, 0.51836493, 0.11024581]],

       [[0.75940512, 0.86459817, 0.33724737, 0.31685104, 0.01827302],
        [0.45642219, 0.06604215, 0.06681786, 0.40926918, 0.07042877],
        [0.06643929, 0.48037576, 0.41857826, 0.39690963, 0.37139132]]])



### 13. Does e equal to a? Why or why not?


In [ ]:
### [your code here]
if np.shape(e)==np.shape(a):

  print("The Multiply of the two array succeeded because they have the same size 2x3x5")
else:
  print("not equal size")


The Multiply of the two array succeeded because they have the same size 2x3x5




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [ ]:
### [your code here]
d_max= np.max(d)

d_max


1.9856844613557278

In [ ]:
d_min= np.min(d)
d_min


1.0182730188347733

In [ ]:
d_mean=np.mean(d)
d_mean

1.3967483584957534


### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [ ]:
### [your code here]
f=np.empty([2,3,5])
f

array([[[1.33263291, 1.17194177, 1.09545161, 1.07636247, 1.70445134],
        [1.10291983, 1.23109868, 1.84789179, 1.98568446, 1.80393899],
        [1.70805139, 1.43167372, 1.68269194, 1.51836493, 1.11024581]],

       [[1.75940512, 1.86459817, 1.33724737, 1.31685104, 1.01827302],
        [1.45642219, 1.06604215, 1.06681786, 1.40926918, 1.07042877],
        [1.06643929, 1.48037576, 1.41857826, 1.39690963, 1.37139132]]])




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [ ]:
### [your code here]
f=np.empty([2,3,5])
f = np.zeros_like(d)

f[(d > d_mean) & (d < d_max)] = 75
f[d == d_mean] = 50
f[d == d_min] = 0
f[d == d_max] = 100
f[(d_min < d)&(d < d_mean)] =25


f

array([[[ 25.,  25.,  25.,  25.,  75.],
        [ 25.,  25.,  75., 100.,  75.],
        [ 75.,  75.,  75.,  75.,  25.]],

       [[ 75.,  75.,  25.,  25.,   0.],
        [ 75.,  25.,  25.,  75.,  25.],
        [ 25.,  75.,  75.,  75.,  25.]]])





### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [ ]:
### [your code here]
d

array([[[1.33263291, 1.17194177, 1.09545161, 1.07636247, 1.70445134],
        [1.10291983, 1.23109868, 1.84789179, 1.98568446, 1.80393899],
        [1.70805139, 1.43167372, 1.68269194, 1.51836493, 1.11024581]],

       [[1.75940512, 1.86459817, 1.33724737, 1.31685104, 1.01827302],
        [1.45642219, 1.06604215, 1.06681786, 1.40926918, 1.07042877],
        [1.06643929, 1.48037576, 1.41857826, 1.39690963, 1.37139132]]])

In [ ]:
f

array([[[ 25.,  25.,  25.,  25.,  75.],
        [ 25.,  25.,  75., 100.,  75.],
        [ 75.,  75.,  75.,  75.,  25.]],

       [[ 75.,  75.,  25.,  25.,   0.],
        [ 75.,  25.,  25.,  75.,  25.],
        [ 25.,  75.,  75.,  75.,  25.]]])

### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [ ]:
### [your code here]
# f=np.empty([2,3,5])
# f = np.zeros_like(d)

f=np.empty([2,3,5], dtype=object)

f[(d > d_mean) & (d < d_max)] = "A"
f[d == d_mean] = "B"
f[d == d_min] = "C"
f[d == d_max] = "D"
f[(d_min < d)&(d < d_mean)] ="E"



f

array([[['E', 'E', 'E', 'E', 'A'],
        ['E', 'E', 'A', 'D', 'A'],
        ['A', 'A', 'A', 'A', 'E']],

       [['A', 'A', 'E', 'E', 'C'],
        ['A', 'E', 'E', 'A', 'E'],
        ['E', 'A', 'A', 'A', 'E']]], dtype=object)