# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:

import numpy as np



### 2. Print the NUMPY version and the configuration.


In [ ]:

print(np.version.version)

1.20.3


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [7]:

a= np.random.random(size=(2,3,5))


### 4. Print a.


In [8]:

print(a)


[[[0.44974867 0.35141082 0.54571103 0.46488434 0.54315124]
  [0.08965893 0.60809019 0.95687891 0.14095824 0.32430297]
  [0.48545217 0.94837591 0.54390187 0.15952138 0.10988457]]

 [[0.53819048 0.33955553 0.87186071 0.8820438  0.61832878]
  [0.12242425 0.07004334 0.78878571 0.22290155 0.65387472]
  [0.50507179 0.66859477 0.4548197  0.93238523 0.52375551]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [ ]:

b= np.ones(shape=(5,2,3))


### 6. Print b.


In [11]:

print(b)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [ ]:

print(a.size,
b.size)

30 30



### 8. Are you able to add a and b? Why or why not?


In [ ]:

a + b = error
#Answer: No i cannot, becuse they have diffrent shapes.

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [31]:
c = b.transpose(1,2,0)
c


array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [86]:
d = a + c
d
#Answer: Becuse a and c have the same shape.


array([[[1.44974867, 1.35141082, 1.54571103, 1.46488434, 1.54315124],
        [1.08965893, 1.60809019, 1.95687891, 1.14095824, 1.32430297],
        [1.48545217, 1.94837591, 1.54390187, 1.15952138, 1.10988457]],

       [[1.53819048, 1.33955553, 1.87186071, 1.8820438 , 1.61832878],
        [1.12242425, 1.07004334, 1.78878571, 1.22290155, 1.65387472],
        [1.50507179, 1.66859477, 1.4548197 , 1.93238523, 1.52375551]]])


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [ ]:
print(a) 
print(d)

#Answer: a and d have the same shape, after we add them together we've notesd that d valuse has increased by 1.

[[[0.44974867 0.35141082 0.54571103 0.46488434 0.54315124]
  [0.08965893 0.60809019 0.95687891 0.14095824 0.32430297]
  [0.48545217 0.94837591 0.54390187 0.15952138 0.10988457]]

 [[0.53819048 0.33955553 0.87186071 0.8820438  0.61832878]
  [0.12242425 0.07004334 0.78878571 0.22290155 0.65387472]
  [0.50507179 0.66859477 0.4548197  0.93238523 0.52375551]]]
[[[1.44974867 1.35141082 1.54571103 1.46488434 1.54315124]
  [1.08965893 1.60809019 1.95687891 1.14095824 1.32430297]
  [1.48545217 1.94837591 1.54390187 1.15952138 1.10988457]]

 [[1.53819048 1.33955553 1.87186071 1.8820438  1.61832878]
  [1.12242425 1.07004334 1.78878571 1.22290155 1.65387472]
  [1.50507179 1.66859477 1.4548197  1.93238523 1.52375551]]]



### 12. Multiply a and c. Assign the result to e.


In [ ]:
e = a * c
e


array([[[0.44974867, 0.35141082, 0.54571103, 0.46488434, 0.54315124],
        [0.08965893, 0.60809019, 0.95687891, 0.14095824, 0.32430297],
        [0.48545217, 0.94837591, 0.54390187, 0.15952138, 0.10988457]],

       [[0.53819048, 0.33955553, 0.87186071, 0.8820438 , 0.61832878],
        [0.12242425, 0.07004334, 0.78878571, 0.22290155, 0.65387472],
        [0.50507179, 0.66859477, 0.4548197 , 0.93238523, 0.52375551]]])



### 13. Does e equal to a? Why or why not?


In [41]:
a,e
#Answer: Yes, becuse c have vlause of ones, any value that is multiplied by 1 results the same.


(array([[[0.44974867, 0.35141082, 0.54571103, 0.46488434, 0.54315124],
         [0.08965893, 0.60809019, 0.95687891, 0.14095824, 0.32430297],
         [0.48545217, 0.94837591, 0.54390187, 0.15952138, 0.10988457]],
 
        [[0.53819048, 0.33955553, 0.87186071, 0.8820438 , 0.61832878],
         [0.12242425, 0.07004334, 0.78878571, 0.22290155, 0.65387472],
         [0.50507179, 0.66859477, 0.4548197 , 0.93238523, 0.52375551]]]),
 array([[[0.44974867, 0.35141082, 0.54571103, 0.46488434, 0.54315124],
         [0.08965893, 0.60809019, 0.95687891, 0.14095824, 0.32430297],
         [0.48545217, 0.94837591, 0.54390187, 0.15952138, 0.10988457]],
 
        [[0.53819048, 0.33955553, 0.87186071, 0.8820438 , 0.61832878],
         [0.12242425, 0.07004334, 0.78878571, 0.22290155, 0.65387472],
         [0.50507179, 0.66859477, 0.4548197 , 0.93238523, 0.52375551]]]))



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [48]:

d_max=d.max()
d_min=d.min()
d_mean=d.mean()

d_max, d_min, d_mean


(1.9568789064280818, 1.0700433381171068, 1.4971522368360661)


### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [81]:
f = np.empty(shape=(2,3,5), dtype=object)





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [ ]:


for i in range(len(d)):
    for j in range(len(d[i])):
      for k in range(len(d[i][j])):
        value = d[i][j][k]
        if d_mean> value > d_min:
            f[i][j][k] = 25
        elif d_max > value > d_mean:
            f[i][j][k] = 75
        elif value == d_mean:
            f[i][j][k] = 50
        elif value == d_min:
            f[i][j][k] = 0
        elif value == d_max:
            f[i][j][k] = 100






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [ ]:

d, f

(array([[[1.44974867, 1.35141082, 1.54571103, 1.46488434, 1.54315124],
         [1.08965893, 1.60809019, 1.95687891, 1.14095824, 1.32430297],
         [1.48545217, 1.94837591, 1.54390187, 1.15952138, 1.10988457]],
 
        [[1.53819048, 1.33955553, 1.87186071, 1.8820438 , 1.61832878],
         [1.12242425, 1.07004334, 1.78878571, 1.22290155, 1.65387472],
         [1.50507179, 1.66859477, 1.4548197 , 1.93238523, 1.52375551]]]),
 array([[[ 25.,  25.,  75.,  25.,  75.],
         [ 25.,  75., 100.,  25.,  25.],
         [ 25.,  75.,  75.,  25.,  25.]],
 
        [[ 75.,  25.,  75.,  75.,  75.],
         [ 25.,   0.,  75.,  25.,  75.],
         [ 75.,  75.,  25.,  75.,  75.]]]))

### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [ ]:

grades = { 0:"A", 25:"B", 50:"C", 75:"D", 100:"E"}
for i in range(len(d)):
    for j in range(len(d[i])):
      for k in range(len(d[i][j])):
        value = d[i][j][k]
        if d_mean> value > d_min:
            f[i][j][k] = grades[25]
        elif d_max > value > d_mean:
            f[i][j][k] = grades[75]
        elif value == d_mean:
            f[i][j][k] = grades[50]
        elif value == d_min:
            f[i][j][k] = grades[0]
        elif value == d_max:
            f[i][j][k] = grades[100]

In [84]:
print(f)

[[['B' 'B' 'D' 'B' 'D']
  ['B' 'D' 'E' 'B' 'B']
  ['B' 'D' 'D' 'B' 'B']]

 [['D' 'B' 'D' 'D' 'D']
  ['B' 'A' 'D' 'B' 'D']
  ['D' 'D' 'B' 'D' 'D']]]
