# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [6]:
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [7]:
print("NumPy Version:", np.__version__)
np.show_config()

NumPy Version: 2.2.2
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/reema/anaconda3/envs/ironhack/Library/include
    lib directory: C:/Users/reema/anaconda3/envs/ironhack/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_56qrev29w_\croot\numpy_and_numpy_base_1738155838326\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/reema/anaconda3/envs/ironhack/Library/include
    lib directory: C:/Users/reema/anaconda3/envs/ironhack/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_56qrev29w_\croot\numpy_and_numpy_base_1738155838326\_h_env\Library\lib\pkgconfig
    version: '2023.1'
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30158
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.2

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [8]:
a = np.random.randint(0, 100, (2, 3, 5))  # Random integers from 0 to 99


### 4. Print a.


In [9]:
print(a)


[[[ 2 84  7 18 88]
  [ 5 65 29 67 59]
  [38 14 28 60  3]]

 [[52  9  2  1 69]
  [65  9 21 33 32]
  [98 14 77 98 48]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [10]:
b = np.ones((5, 2, 3))


### 6. Print b.


In [11]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [12]:
print("Size of a:", a.size)
print("Size of b:", b.size)

if a.size == b.size:
    print("a and b have the same size.")
else:
    print("a and b do not have the same size.")

Size of a: 30
Size of b: 30
a and b have the same size.



### 8. Are you able to add a and b? Why or why not?


In [13]:
print("Shape of a:", a.shape)  
print("Shape of b:", b.shape)  

try:
    c = a + b
    print("Addition successful!")
except ValueError as e:
    print("Error:", e)

Shape of a: (2, 3, 5)
Shape of b: (5, 2, 3)
Error: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [14]:
c = np.transpose(b, (1, 2, 0))

print("Shape of a:", a.shape)
print("Shape of b before transpose:", b.shape)  # (5,2,3)
print("Shape of c after transpose:", c.shape) 

Shape of a: (2, 3, 5)
Shape of b before transpose: (5, 2, 3)
Shape of c after transpose: (2, 3, 5)



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [15]:
d= a + c
print("Shape of a:", a.shape) 
print("Shape of c:", c.shape)  
print("Shape of d:", d.shape)  
print("\n Result (d):\n", d)

Shape of a: (2, 3, 5)
Shape of c: (2, 3, 5)
Shape of d: (2, 3, 5)

 Result (d):
 [[[ 3. 85.  8. 19. 89.]
  [ 6. 66. 30. 68. 60.]
  [39. 15. 29. 61.  4.]]

 [[53. 10.  3.  2. 70.]
  [66. 10. 22. 34. 33.]
  [99. 15. 78. 99. 49.]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [16]:
print("Array a: \n ",a)
print("Array d: \n ",d)

"""
Difference Between a and d:
1. Shape Comparison
Same shape: Both arrays have the exact same structure (2,3,5).
2. Value Relationship
Values in d are all shifted up by 1 compared to a.
No values changed in position, only increased in magnitude by a fixed amount
"""

Array a: 
  [[[ 2 84  7 18 88]
  [ 5 65 29 67 59]
  [38 14 28 60  3]]

 [[52  9  2  1 69]
  [65  9 21 33 32]
  [98 14 77 98 48]]]
Array d: 
  [[[ 3. 85.  8. 19. 89.]
  [ 6. 66. 30. 68. 60.]
  [39. 15. 29. 61.  4.]]

 [[53. 10.  3.  2. 70.]
  [66. 10. 22. 34. 33.]
  [99. 15. 78. 99. 49.]]]


'\nDifference Between a and d:\n1. Shape Comparison\nSame shape: Both arrays have the exact same structure (2,3,5).\n2. Value Relationship\nValues in d are all shifted up by 1 compared to a.\nNo values changed in position, only increased in magnitude by a fixed amount\n'


### 12. Multiply a and c. Assign the result to e.


In [17]:
e = a * c
print (e)

[[[ 2. 84.  7. 18. 88.]
  [ 5. 65. 29. 67. 59.]
  [38. 14. 28. 60.  3.]]

 [[52.  9.  2.  1. 69.]
  [65.  9. 21. 33. 32.]
  [98. 14. 77. 98. 48.]]]




### 13. Does e equal to a? Why or why not?


In [18]:
if np.array_equal(e, a):
    print("Yes, e is equal to a.")
else:
    print("No, e is not equal to a.")

"""
 If c contained values other than 1, e would have different values.
But because c is filled with ones, e remains the same as a.
"""

Yes, e is equal to a.


'\n If c contained values other than 1, e would have different values.\nBut because c is filled with ones, e remains the same as a.\n'



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [20]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print("Maximum value in d:", d_max)
print("Minimum value in d:", d_min)
print("Mean value in d:", d_mean)

Maximum value in d: 99.0
Minimum value in d: 2.0
Mean value in d: 40.833333333333336



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [51]:
f = np.empty_like(d , dtype = int) 
print (f)

[[[4627730092099895296 4634978072750194688 4627730092099895296
   4627730092099895296 4634978072750194688]
  [4627730092099895296 4634978072750194688 4627730092099895296
   4634978072750194688 4634978072750194688]
  [4627730092099895296 4627730092099895296 4627730092099895296
   4634978072750194688 4627730092099895296]]

 [[4634978072750194688 4627730092099895296 4627730092099895296
   4607182418800017408 4634978072750194688]
  [4634978072750194688 4627730092099895296 4627730092099895296
   4627730092099895296 4627730092099895296]
  [4636737291354636288 4627730092099895296 4634978072750194688
   4636737291354636288 4634978072750194688]]]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [52]:
f[d == d_min] = 0       
f[(d > d_min) & (d < d_mean)] = 25  
f[d == d_mean] = 50   
f[(d > d_mean) & (d < d_max)] = 75 
f[d == d_max] = 100    

print("Labeled array f:\n", f)

Labeled array f:
 [[[ 25  75  25  25  75]
  [ 25  75  25  75  75]
  [ 25  25  25  75  25]]

 [[ 75  25  25   0  75]
  [ 75  25  25  25  25]
  [100  25  75 100  75]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [55]:
# Print d and f
print("Array d:\n", d)
print("\nLabeled array f:\n", f)

# Check if f contains only the expected values
print("\nUnique values in f:", np.unique(f))


Array d:
 [[[ 3. 85.  8. 19. 89.]
  [ 6. 66. 30. 68. 60.]
  [39. 15. 29. 61.  4.]]

 [[53. 10.  3.  2. 70.]
  [66. 10. 22. 34. 33.]
  [99. 15. 78. 99. 49.]]]

Labeled array f:
 [[[ 25  75  25  25  75]
  [ 25  75  25  75  75]
  [ 25  25  25  75  25]]

 [[ 75  25  25   0  75]
  [ 75  25  25  25  25]
  [100  25  75 100  75]]]

Unique values in f: [  0  25  75 100]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [58]:
f_str = np.empty(d.shape, dtype=str)  

f_str[f == 0] = 'A'     
f_str[f == 25] = 'B'    
f_str[f == 50] = 'C'   
f_str[f == 75] = 'D'   
f_str[f == 100] = 'E'  

print("Labeled array f (with strings):\n", f_str)

Labeled array f (with strings):
 [[['B' 'D' 'B' 'B' 'D']
  ['B' 'D' 'B' 'D' 'D']
  ['B' 'B' 'B' 'D' 'B']]

 [['D' 'B' 'B' 'A' 'D']
  ['D' 'B' 'B' 'B' 'B']
  ['E' 'B' 'D' 'E' 'D']]]
