# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
### [your code here]
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [2]:
### [your code here]
print(np.version.version)

1.26.3


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [3]:
### [your code here]
'''1. Uniform methods (rand, random, uniform) generate values in the range [0,1) by default.
   2. Normal methods (randn, standard_normal) generate values following the standard normal distribution.'''

#Using np.random.rand
a = np.random.rand(2, 3, 5)



### 4. Print a.


In [4]:
### [your code here]
print(a)


[[[0.79511948 0.44706758 0.16610984 0.2469107  0.96045969]
  [0.28634539 0.4986157  0.56419897 0.36474554 0.17117913]
  [0.39808637 0.85567835 0.18894931 0.31618089 0.12548622]]

 [[0.44920308 0.41552471 0.34880829 0.21458289 0.64806217]
  [0.69913553 0.40355148 0.90943298 0.75380114 0.0314747 ]
  [0.04811625 0.00949341 0.49230418 0.84144298 0.94690425]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [5]:
### [your code here]
b = np.ones((5, 2, 3))


### 6. Print b.


In [6]:
### [your code here]
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [7]:
### [your code here]
#Using (.size) property in NumPy that return how many values the array contains.

# assert that they have the same size
if a.size == b.size:
    print("a and b have the same number of elements.")
else:
    print("a and b do not have the same number of elements.")

a and b have the same number of elements.



### 8. Are you able to add a and b? Why or why not?


In [8]:
### [your code here]
'''No, I cannot directly add a and b element-wise because their shapes are different
 and not compatible for broadcasting.
 '''
print("Shape of a:", a.shape)  # (2, 3, 5)
print("Shape of b:", b.shape)  # (5, 2, 3)

'''When you running this code, it will output an error message 
indicating that the operands could not be broadcast together
 due to incompatible shapes.'''
try:
    c = a + b
except ValueError as e:
    print("Error:", e)

Shape of a: (2, 3, 5)
Shape of b: (5, 2, 3)
Error: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [9]:
### [your code here]
'''The axis with size 2 (currently axis 1) → becomes the first axis.
   The axis with size 3 (currently axis 2) → becomes the second axis.
   The axis with size 5 (currently axis 0) → becomes the third axis.'''

c = b.transpose((1, 2, 0))  # Rearranges b from (5, 2, 3) to (2, 3, 5)
print(c.shape)

(2, 3, 5)



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [10]:
### [your code here]
# cause after transposing b, the resulting array c has shape (2, 3, 5), the same as a.
d = a + c
print(d)

[[[1.79511948 1.44706758 1.16610984 1.2469107  1.96045969]
  [1.28634539 1.4986157  1.56419897 1.36474554 1.17117913]
  [1.39808637 1.85567835 1.18894931 1.31618089 1.12548622]]

 [[1.44920308 1.41552471 1.34880829 1.21458289 1.64806217]
  [1.69913553 1.40355148 1.90943298 1.75380114 1.0314747 ]
  [1.04811625 1.00949341 1.49230418 1.84144298 1.94690425]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [11]:
### [your code here]
'''Array a: Contains random values.
   Array c: Since b was filled with ones, c is also filled with ones.
   Array d: is the result of adding a constant value of 1 to every element of a.'''
print(f"a= {a} \n\nd= {d}")



a= [[[0.79511948 0.44706758 0.16610984 0.2469107  0.96045969]
  [0.28634539 0.4986157  0.56419897 0.36474554 0.17117913]
  [0.39808637 0.85567835 0.18894931 0.31618089 0.12548622]]

 [[0.44920308 0.41552471 0.34880829 0.21458289 0.64806217]
  [0.69913553 0.40355148 0.90943298 0.75380114 0.0314747 ]
  [0.04811625 0.00949341 0.49230418 0.84144298 0.94690425]]] 

d= [[[1.79511948 1.44706758 1.16610984 1.2469107  1.96045969]
  [1.28634539 1.4986157  1.56419897 1.36474554 1.17117913]
  [1.39808637 1.85567835 1.18894931 1.31618089 1.12548622]]

 [[1.44920308 1.41552471 1.34880829 1.21458289 1.64806217]
  [1.69913553 1.40355148 1.90943298 1.75380114 1.0314747 ]
  [1.04811625 1.00949341 1.49230418 1.84144298 1.94690425]]]



### 12. Multiply a and c. Assign the result to e.


In [12]:
### [your code here]
e = a*c




### 13. Does e equal to a? Why or why not?


In [13]:
### [your code here]
'''yes, Since we multiplay a by c that filled with ones, e identecal to a'''
print(e)


[[[0.79511948 0.44706758 0.16610984 0.2469107  0.96045969]
  [0.28634539 0.4986157  0.56419897 0.36474554 0.17117913]
  [0.39808637 0.85567835 0.18894931 0.31618089 0.12548622]]

 [[0.44920308 0.41552471 0.34880829 0.21458289 0.64806217]
  [0.69913553 0.40355148 0.90943298 0.75380114 0.0314747 ]
  [0.04811625 0.00949341 0.49230418 0.84144298 0.94690425]]]




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [14]:
### [your code here]
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(f"The max of d ={d_max}\nThe min of d ={d_min}\nThe mean of d ={d_mean}")



The max of d =1.9604596861622823
The min of d =1.0094934070295352
The mean of d =1.4532323732305508



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [15]:
### [your code here]
f = np.empty((2,3,5))





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [16]:
### [your code here]
# Iterate over all indices of d using np.ndindex
f[(d > d_min) & (d < d_mean)] = 25
f[(d > d_mean) & (d < d_max)] = 75
f[d == d_mean] = 50
f[d == d_min] = 0
f[d == d_max] = 100






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [17]:
### [your code here]
print(f"d= {d} \n\nf= {f}")


d= [[[1.79511948 1.44706758 1.16610984 1.2469107  1.96045969]
  [1.28634539 1.4986157  1.56419897 1.36474554 1.17117913]
  [1.39808637 1.85567835 1.18894931 1.31618089 1.12548622]]

 [[1.44920308 1.41552471 1.34880829 1.21458289 1.64806217]
  [1.69913553 1.40355148 1.90943298 1.75380114 1.0314747 ]
  [1.04811625 1.00949341 1.49230418 1.84144298 1.94690425]]] 

f= [[[ 75.  25.  25.  25. 100.]
  [ 25.  75.  75.  25.  25.]
  [ 25.  75.  25.  25.  25.]]

 [[ 25.  25.  25.  25.  75.]
  [ 75.  25.  75.  75.  25.]
  [ 25.   0.  75.  75.  75.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [18]:
### [your code here]

# Create a new nested list f with the same structure as d.
f = []
for i in range(len(d)):           # iterate over the 2 blocks
    block_labels = []
    for j in range(len(d[i])):    # iterate over the 3 rows in each block
        row_labels = []
        for k in range(len(d[i][j])):  # iterate over the 5 elements in each row
            value = d[i][j][k]
            if value == d_min:
                row_labels.append("A")
            elif value == d_max:
                row_labels.append("E")
            elif value == d_mean:
                row_labels.append("C")
            elif d_min < value < d_mean:
                row_labels.append("B")
            elif d_mean < value < d_max:
                row_labels.append("D")
        block_labels.append(row_labels)
    f.append(block_labels)

# Display the resulting nested list f.
for block in f:
    for row in block:
        print(row)


['D', 'B', 'B', 'B', 'E']
['B', 'D', 'D', 'B', 'B']
['B', 'D', 'B', 'B', 'B']
['B', 'B', 'B', 'B', 'D']
['D', 'B', 'D', 'D', 'B']
['B', 'A', 'D', 'D', 'D']
