# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [92]:
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [95]:
import numpy as np

# to print NumPy version
print("NumPy Version:", np.__version__)

# to print NumPy configuration
np.show_config()




NumPy Version: 1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/deept/anaconda3/Library/include
    lib directory: C:/Users/deept/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1583119523984
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: win

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [181]:
# way 1
a = np.random.rand(2, 3, 5) 
print(a)

# Way 2 
a = np.random.randn(2, 3, 5) 
print(a)

# Way 3
a = np.random.randint(0, 100, (2, 3, 5)) 
print(a)

# Way 4
values = [1, 2, 3, 4, 5, 6]  # Corrected the typo

a = np.random.choice(values, size=(2, 3, 5))
print(a)


[[[0.61185289 0.13949386 0.29214465 0.36636184 0.45606998]
  [0.78517596 0.19967378 0.51423444 0.59241457 0.04645041]
  [0.60754485 0.17052412 0.06505159 0.94888554 0.96563203]]

 [[0.80839735 0.30461377 0.09767211 0.68423303 0.44015249]
  [0.12203823 0.49517691 0.03438852 0.9093204  0.25877998]
  [0.66252228 0.31171108 0.52006802 0.54671028 0.18485446]]]
[[[ 0.73846658  0.17136828 -0.11564828 -0.3011037  -1.47852199]
  [-0.71984421 -0.46063877  1.05712223  0.34361829 -1.76304016]
  [ 0.32408397 -0.38508228 -0.676922    0.61167629  1.03099952]]

 [[ 0.93128012 -0.83921752 -0.30921238  0.33126343  0.97554513]
  [-0.47917424 -0.18565898 -1.10633497 -1.19620662  0.81252582]
  [ 1.35624003 -0.07201012  1.0035329   0.36163603 -0.64511975]]]
[[[ 0  4 89 13 26]
  [ 8 78 14 89 41]
  [76 50 62 95 51]]

 [[95  3 93 22 14]
  [42 28 35 12 31]
  [70 58 85 27 65]]]
[[[2 5 6 1 5]
  [6 4 4 4 4]
  [4 6 6 3 2]]

 [[4 1 6 1 1]
  [1 3 6 1 4]
  [5 1 3 6 3]]]



### 4. Print a.


In [184]:
print(a)

[[[2 5 6 1 5]
  [6 4 4 4 4]
  [4 6 6 3 2]]

 [[4 1 6 1 1]
  [1 3 6 1 4]
  [5 1 3 6 3]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [187]:
# Create a 5x2x3 array & Assign the array to variable "b"
b = np.ones((5, 2, 3) , dtype=int)


### 6. Print b.


In [190]:
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [193]:
a = np.random.choice([1, 2, 3, 4, 5, 6], size=(2, 3, 5))
b = np.ones((5, 2, 3))

# Check the size
if a.size == b.size:
    print("a and b have the same size.")
else:
    print("a and b do not have the same size.")



a and b have the same size.



### 8. Are you able to add a and b? Why or why not?


In [196]:
a = np.random.choice([1, 2, 3, 4, 5, 6], size=(2, 3, 5))
b = np.ones((5, 2, 3))

# Check if the shapes are the same
if a.shape == b.shape:
    result = a + b
    print("Arrays a and b have been added.")
    print(result)
else:
    print("Arrays cannot be added because they are not the same.")


Arrays cannot be added because they are not the same.




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [199]:
a = np.random.choice([1, 2, 3, 4, 5, 6], size=(2, 3, 5))
b = np.ones((5, 2, 3))

#Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array)
c = b.transpose(1, 2, 0) #Assign the transposed array to varialbe "c"

print("Shape of a:", a.shape)
print("Shape of c (transposed b):", c.shape)



Shape of a: (2, 3, 5)
Shape of c (transposed b): (2, 3, 5)



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [202]:
d = a + c  # Try to add a and c & Assign the sum to variable "d"

print(d.astype(int))


[[[4 5 4 3 4]
  [4 5 5 2 2]
  [3 2 4 5 2]]

 [[2 3 7 3 4]
  [5 3 2 5 5]
  [2 3 2 7 5]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [205]:
# Create array a with random values from 1 to 6
a = np.random.choice([1, 2, 3, 4, 5, 6], size=(2, 3, 5))

# Create array b contain ones, but with a different shape
b = np.ones((5, 2, 3))

# Transpose b to match the shape of a (2, 3, 5)
c = b.transpose(1, 2, 0)  

# Add a and c and assign to d
d = a + c  

# Print a and d
print("Array a:")
print(a)

print("\nArray d (a + c):")
print(d.astype(int))

# Explanation:
# - Since `c` is filled with ones, the result `d` is just `a` with every element increased by 1.



Array a:
[[[5 5 3 1 1]
  [3 3 3 4 6]
  [1 4 3 1 4]]

 [[6 4 6 3 6]
  [1 3 1 5 2]
  [6 2 2 6 3]]]

Array d (a + c):
[[[6 6 4 2 2]
  [4 4 4 5 7]
  [2 5 4 2 5]]

 [[7 5 7 4 7]
  [2 4 2 6 3]
  [7 3 3 7 4]]]



### 12. Multiply a and c. Assign the result to e.


In [208]:
# Multiply a and c and assign to e
e = a * c  

print("\nArray e (a * c):")
print(e.astype(int))


Array e (a * c):
[[[5 5 3 1 1]
  [3 3 3 4 6]
  [1 4 3 1 4]]

 [[6 4 6 3 6]
  [1 3 1 5 2]
  [6 2 2 6 3]]]




### 13. Does e equal to a? Why or why not?


In [211]:
print(np.array_equal(a, e))  


True




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [214]:
np.random.seed(42)

#Identify the max, min, and mean values in d. and assign values to variables
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

# Print the values
print("Max value in d:", d_max)
print("Min value in d:", d_min)
print("Mean value in d:", d_mean)

Max value in d: 7.0
Min value in d: 2.0
Mean value in d: 4.433333333333334



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [237]:
np.random.seed(42)

# Create array a with random values from 1 to 6
a = np.random.choice([1, 2, 3, 4, 5, 6], size=(2, 3, 5))

# Create array b contain ones, but with a different shape
b = np.ones((5, 2, 3))

# Transpose b to match the shape of a (2, 3, 5)
c = b.transpose(1, 2, 0)  

# Add a and c and assign to d
d = a + c  

# Create an empty array f with the same shape as d (2x3x5)
f = np.empty_like(d)

# Print 
print(f.shape)
print(f.astype(int))



(2, 3, 5)
[[[5 6 4 6 6]
  [3 4 4 4 6]
  [5 4 7 6 3]]

 [[5 7 7 3 5]
  [6 2 5 3 7]
  [6 5 2 2 4]]]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [273]:
# Create an empty array f with the same shape as d
f = [[[None for _ in range(5)] for _ in range(3)] for _ in range(2)]

# Populate f based on the conditions
for i in range(2):
    for j in range(3):
        for k in range(5):
            if d[i][j][k] == d_min:
                f[i][j][k] = 0  # Minimum value gets 0
            elif d[i][j][k] == d_mean:
                f[i][j][k] = 50  # Mean value gets 50
            elif d[i][j][k] == d_max:
                f[i][j][k] = 100  # Maximum value gets 100
            elif d_min < d[i][j][k] < d_mean:
                f[i][j][k] = 25  # Between min and mean gets 25
            elif d_mean < d[i][j][k] < d_max:
                f[i][j][k] = 75  # Between mean and max gets 75






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [277]:
print("\nArray f (labeled):")
print(f) 



Array f (labeled):
[[[75, 75, 25, 75, 75], [25, 25, 25, 25, 75], [75, 25, 100, 75, 25]], [[75, 100, 100, 25, 75], [75, 0, 75, 25, 100], [75, 75, 0, 0, 25]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [289]:


# Labels instead of numbers
labels = {0: "A", 25: "B", 50: "C", 75: "D", 100: "E"}

# Create an empty array f with the same shape as d (2x3x5)
f = np.empty_like(d, dtype=object)

# Populate f based on the conditions
for i in range(2):
    for j in range(3):
        for k in range(5):
            if d[i][j][k] == d_min:
                f[i][j][k] = labels[0]  # Minimum value gets "A"
            elif d[i][j][k] == d_mean:
                f[i][j][k] = labels[50]  # Mean value gets "C"
            elif d[i][j][k] == d_max:
                f[i][j][k] = labels[100]  # Maximum value gets "E"
            elif d_min < d[i][j][k] < d_mean:
                f[i][j][k] = labels[25]  # Between min and mean gets "B"
            elif d_mean < d[i][j][k] < d_max:
                f[i][j][k] = labels[75]  # Between mean and max gets "D"

# Print the final result
print("\nArray f (labeled with strings):")
print(f)



Array f (labeled with strings):
[[['D' 'D' 'B' 'D' 'D']
  ['B' 'B' 'B' 'B' 'D']
  ['D' 'B' 'E' 'D' 'B']]

 [['D' 'E' 'E' 'B' 'D']
  ['D' 'A' 'D' 'B' 'E']
  ['D' 'D' 'A' 'A' 'B']]]
