# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [2]:
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [7]:
print(np.__version__)
print(np.show_config)

1.21.5
<function show at 0x000001D172650160>


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [81]:
a=np.random.random(size=(2,3,5))
y=np.arange(30).reshape(2,3,5)
x=np.random.randint(1,10,size=(2,3,5))


### 4. Print a.


In [82]:
### [your code here]
a

array([[[0.40450813, 0.8877701 , 0.85092845, 0.93563499, 0.78534065],
        [0.66898825, 0.58068662, 0.37228277, 0.94013344, 0.97366384],
        [0.28392097, 0.30536386, 0.48561375, 0.44842414, 0.99445746]],

       [[0.17592525, 0.01807536, 0.49389372, 0.17882271, 0.36646878],
        [0.74417052, 0.72093992, 0.30806079, 0.54254023, 0.50881408],
        [0.63633262, 0.25046182, 0.58987085, 0.97889286, 0.48674215]]])

### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [83]:
### [your code here]
b=np.ones((5,3,2))



### 6. Print b.


In [84]:
### [your code here]
b

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])


### 7. Do a and b have the same size? How do you prove that in Python code?


In [85]:
### [your code here]
print(a.shape)
print(b.shape)

(2, 3, 5)
(5, 3, 2)



### 8. Are you able to add a and b? Why or why not?


In [86]:
# No, because of the shape
z=a+b


ValueError: operands could not be broadcast together with shapes (2,3,5) (5,3,2) 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [87]:
### [your code here]
c=b.reshape(2,3,5)
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [88]:
### [your code here]
d=a+c


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [89]:
# a has integer values ​​but d has float values
print(f"A={a}\n\nB={d}")


A=[[[0.40450813 0.8877701  0.85092845 0.93563499 0.78534065]
  [0.66898825 0.58068662 0.37228277 0.94013344 0.97366384]
  [0.28392097 0.30536386 0.48561375 0.44842414 0.99445746]]

 [[0.17592525 0.01807536 0.49389372 0.17882271 0.36646878]
  [0.74417052 0.72093992 0.30806079 0.54254023 0.50881408]
  [0.63633262 0.25046182 0.58987085 0.97889286 0.48674215]]]

B=[[[1.40450813 1.8877701  1.85092845 1.93563499 1.78534065]
  [1.66898825 1.58068662 1.37228277 1.94013344 1.97366384]
  [1.28392097 1.30536386 1.48561375 1.44842414 1.99445746]]

 [[1.17592525 1.01807536 1.49389372 1.17882271 1.36646878]
  [1.74417052 1.72093992 1.30806079 1.54254023 1.50881408]
  [1.63633262 1.25046182 1.58987085 1.97889286 1.48674215]]]



### 12. Multiply a and c. Assign the result to e.


In [90]:
### [your code here]
e=a*c



### 13. Does e equal to a? Why or why not?


In [91]:
# yes, because I multiply it with 1 
print(e==a)


[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [92]:
d_min = np.min(d)
d_max = np.max(d)
d_mean = np.mean(d)


### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [93]:
### [your code here]
f=np.empty((2,3,5))




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [94]:

f[d == d_min] = 0
f[d == d_max] = 100
f[d == d_mean] = 50
f[(d > d_min) & (d < d_mean)] = 25
f[(d > d_mean) & (d < d_max)] = 75
    





### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [95]:
print(f'd={d}\n')
print(f'f={f}')

d=[[[1.40450813 1.8877701  1.85092845 1.93563499 1.78534065]
  [1.66898825 1.58068662 1.37228277 1.94013344 1.97366384]
  [1.28392097 1.30536386 1.48561375 1.44842414 1.99445746]]

 [[1.17592525 1.01807536 1.49389372 1.17882271 1.36646878]
  [1.74417052 1.72093992 1.30806079 1.54254023 1.50881408]
  [1.63633262 1.25046182 1.58987085 1.97889286 1.48674215]]]

f=[[[ 25.  75.  75.  75.  75.]
  [ 75.  75.  25.  75.  75.]
  [ 25.  25.  25.  25. 100.]]

 [[ 25.   0.  25.  25.  25.]
  [ 75.  75.  25.  25.  25.]
  [ 75.  25.  75.  75.  25.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [103]:
f=np.empty((2,3,5),dtype=str)
f[d == d_min] = 'E'
f[d == d_max] = 'A'
f[d == d_mean] = 'C'
f[(d > d_min) & (d < d_mean)] = 'D'
f[(d > d_mean) & (d < d_max)] = 'B'