# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [2]:
### [your code here]
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [5]:
### [your code here]
print(np.__version__)
print(np.show_config())

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/anaconda3/include
    lib directory: /opt/anaconda3/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 VORTEX MAX_THREADS=128
    pc file directory: /opt/anaconda3/lib/pkgconfig
    version: 0.3.21
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep4347739648
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -ftree-vectorize, -fPIC, -fPIE, -fstack-protector-strong, -O2, -pipe, -isystem,
      /opt/anaconda3/include, -fdebug-prefix-map=/var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_a51i_mbs7m/croot/numpy_and_numpy_base_1708638620867/work=/usr/local/src/conda/numpy-base-1.26.4,
      -fdebug-prefix-map=/opt/anaconda3=/usr/loca

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [8]:
### [your code here]
a = np.random.rand(2, 3, 5)  # Using uniform distribution
# Alternative methods to generate random arrays:
# 1. np.random.random((2, 3, 5))
# 2. np.random.randn(2, 3, 5)  # Normal distribution
# 3. np.random.randint(low=0, high=100, size=(2, 3, 5))  # Random integers


### 4. Print a.


In [11]:
### [your code here]
print(a)

[[[0.16254161 0.37610328 0.24565589 0.01585035 0.13605578]
  [0.75009274 0.53888482 0.29081214 0.55879196 0.70471459]
  [0.58701225 0.17089418 0.39182005 0.23402822 0.2968932 ]]

 [[0.70257463 0.45307874 0.35958638 0.33992493 0.21864607]
  [0.27779598 0.60931423 0.87540993 0.86748633 0.05230093]
  [0.63038309 0.69266262 0.45547073 0.41484404 0.3133284 ]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [14]:
### [your code here]
b = np.ones((5, 2, 3))


### 6. Print b.


In [19]:
### [your code here]
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [22]:
### [your code here]
print(a.size == b.size)  # Check if sizes are equal

True



### 8. Are you able to add a and b? Why or why not?


In [25]:
### [your code here]
# No, we cannot add a and b because they have different shapes (2x3x5 vs. 5x2x3).



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [28]:
### [your code here]
c = b.transpose(1, 2, 0)  # Change the order of axes


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [31]:
### [your code here]
d = a + c  # Now they both have shape (2, 3, 5)
# It works now because the shapes match (2x3x5).


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [34]:
### [your code here]
print("Array a:")
print(a)
print("Array d (a + c):")
print(d)
# d contains values from a plus 1 (from b).

Array a:
[[[0.16254161 0.37610328 0.24565589 0.01585035 0.13605578]
  [0.75009274 0.53888482 0.29081214 0.55879196 0.70471459]
  [0.58701225 0.17089418 0.39182005 0.23402822 0.2968932 ]]

 [[0.70257463 0.45307874 0.35958638 0.33992493 0.21864607]
  [0.27779598 0.60931423 0.87540993 0.86748633 0.05230093]
  [0.63038309 0.69266262 0.45547073 0.41484404 0.3133284 ]]]
Array d (a + c):
[[[1.16254161 1.37610328 1.24565589 1.01585035 1.13605578]
  [1.75009274 1.53888482 1.29081214 1.55879196 1.70471459]
  [1.58701225 1.17089418 1.39182005 1.23402822 1.2968932 ]]

 [[1.70257463 1.45307874 1.35958638 1.33992493 1.21864607]
  [1.27779598 1.60931423 1.87540993 1.86748633 1.05230093]
  [1.63038309 1.69266262 1.45547073 1.41484404 1.3133284 ]]]



### 12. Multiply a and c. Assign the result to e.


In [36]:
### [your code here]
e = a * c  # Element-wise multiplication



### 13. Does e equal to a? Why or why not?


In [39]:
### [your code here]
print(np.array_equal(e, a))  # Check if e is equal to a
# Yes, e equals a because multiplying by 1 does not change the values.


True




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [42]:
### [your code here]
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [45]:
### [your code here]
f = np.empty(d.shape)




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [48]:
### [your code here]
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d_min < d[i, j, k] < d_mean:
                f[i, j, k] = 25
            elif d_mean < d[i, j, k] < d_max:
                f[i, j, k] = 75
            elif d[i, j, k] == d_mean:
                f[i, j, k] = 50
            elif d[i, j, k] == d_min:
                f[i, j, k] = 0
            elif d[i, j, k] == d_max:
                f[i, j, k] = 100





### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [51]:
### [your code here]
print("Array d:")
print(d)
print("Array f:")
print(f)

Array d:
[[[1.16254161 1.37610328 1.24565589 1.01585035 1.13605578]
  [1.75009274 1.53888482 1.29081214 1.55879196 1.70471459]
  [1.58701225 1.17089418 1.39182005 1.23402822 1.2968932 ]]

 [[1.70257463 1.45307874 1.35958638 1.33992493 1.21864607]
  [1.27779598 1.60931423 1.87540993 1.86748633 1.05230093]
  [1.63038309 1.69266262 1.45547073 1.41484404 1.3133284 ]]]
Array f:
[[[ 25.  25.  25.   0.  25.]
  [ 75.  75.  25.  75.  75.]
  [ 75.  25.  25.  25.  25.]]

 [[ 75.  75.  25.  25.  25.]
  [ 25.  75. 100.  75.  25.]
  [ 75.  75.  75.  25.  25.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [56]:
### [your code here]
# Create an empty list for strings with the same shape as d
f_str = [[['' for _ in range(d.shape[2])] for _ in range(d.shape[1])] for _ in range(d.shape[0])]

# Populate the values in f_str based on the conditions
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d_min < d[i, j, k] < d_mean:
                f_str[i][j][k] = "B"
            elif d_mean < d[i, j, k] < d_max:
                f_str[i][j][k] = "D"
            elif d[i, j, k] == d_mean:
                f_str[i][j][k] = "C"
            elif d[i, j, k] == d_min:
                f_str[i][j][k] = "A"
            elif d[i, j, k] == d_max:
                f_str[i][j][k] = "E"

print("String array f:")
for layer in f_str:
    print(layer)

String array f:
[['B', 'B', 'B', 'A', 'B'], ['D', 'D', 'B', 'D', 'D'], ['D', 'B', 'B', 'B', 'B']]
[['D', 'D', 'B', 'B', 'B'], ['B', 'D', 'E', 'D', 'B'], ['D', 'D', 'D', 'B', 'B']]
