# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [413]:
### [your code here]
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [416]:
### [your code here]
print(np.__version__)

1.24.3


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [419]:
### [your code here]
#Fisrt way
a = np.random.randint(0, 10, size=(2, 3, 5))

#secend way
#a = np.random.rand( 2,3,5)


### 4. Print a.


In [422]:
### [your code here]
print(a)

[[[6 8 4 8 5]
  [9 8 6 7 0]
  [3 4 2 1 0]]

 [[9 4 9 4 5]
  [4 7 2 3 8]
  [3 6 8 2 9]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [425]:
### [your code here]
b = np.ones((5, 2, 3))


### 6. Print b.


In [428]:
### [your code here]
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [431]:
### [your code here]
if a.shape == b.shape:
    print("a and b have the same size.")
else:
    print("a and b have different sizes.")

print(f"Shape of a: {a.shape}")
print(f"Shape of b: {b.shape}")

a and b have different sizes.
Shape of a: (2, 3, 5)
Shape of b: (5, 2, 3)



### 8. Are you able to add a and b? Why or why not?


In [434]:
### [your code here]
a+b
#the shapes are different NumPy will raise a ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [437]:
### [your code here]
c = np.transpose(b, (1, 2, 0))

print("Shape of a:", a.shape)
print("Shape of b:", b.shape)
print("Shape of c (transposed b):", c.shape)

Shape of a: (2, 3, 5)
Shape of b: (5, 2, 3)
Shape of c (transposed b): (2, 3, 5)



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [440]:
### [your code here]
d = a + c
print("Sum of a and c:\n", d)

print(f"Shape of d: {d.shape}")


Sum of a and c:
 [[[ 7.  9.  5.  9.  6.]
  [10.  9.  7.  8.  1.]
  [ 4.  5.  3.  2.  1.]]

 [[10.  5. 10.  5.  6.]
  [ 5.  8.  3.  4.  9.]
  [ 4.  7.  9.  3. 10.]]]
Shape of d: (2, 3, 5)



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [443]:
### [your code here]
print("Array a:\n",a)
print("Array d:\n",d)


Array a:
 [[[6 8 4 8 5]
  [9 8 6 7 0]
  [3 4 2 1 0]]

 [[9 4 9 4 5]
  [4 7 2 3 8]
  [3 6 8 2 9]]]
Array d:
 [[[ 7.  9.  5.  9.  6.]
  [10.  9.  7.  8.  1.]
  [ 4.  5.  3.  2.  1.]]

 [[10.  5. 10.  5.  6.]
  [ 5.  8.  3.  4.  9.]
  [ 4.  7.  9.  3. 10.]]]



### 12. Multiply a and c. Assign the result to e.


In [446]:
### [your code here]
e = a * c
print("Multiply a and c:\n", e)

Multiply a and c:
 [[[6. 8. 4. 8. 5.]
  [9. 8. 6. 7. 0.]
  [3. 4. 2. 1. 0.]]

 [[9. 4. 9. 4. 5.]
  [4. 7. 2. 3. 8.]
  [3. 6. 8. 2. 9.]]]




### 13. Does e equal to a? Why or why not?


In [449]:
### [your code here]
if np.array_equal(e, a):
    print("e is equal to a.")
else:
    print("e is NOT equal to a.")

print("\nArray a:\n", a)
print("\nArray e:\n", e)



e is equal to a.

Array a:
 [[[6 8 4 8 5]
  [9 8 6 7 0]
  [3 4 2 1 0]]

 [[9 4 9 4 5]
  [4 7 2 3 8]
  [3 6 8 2 9]]]

Array e:
 [[[6. 8. 4. 8. 5.]
  [9. 8. 6. 7. 0.]
  [3. 4. 2. 1. 0.]]

 [[9. 4. 9. 4. 5.]
  [4. 7. 2. 3. 8.]
  [3. 6. 8. 2. 9.]]]




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [452]:
### [your code here]
d_max = print('max of d:',d.max())
d_min = print('min of d:',d.min())
d_mean = print('mean of d:',d.mean())


max of d: 10.0
min of d: 1.0
mean of d: 6.133333333333334



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [455]:
### [your code here]
f = np.empty(d.shape)
print(f)

[[[6. 8. 4. 8. 5.]
  [9. 8. 6. 7. 0.]
  [3. 4. 2. 1. 0.]]

 [[9. 4. 9. 4. 5.]
  [4. 7. 2. 3. 8.]
  [3. 6. 8. 2. 9.]]]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [458]:
### [your code here]

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if value > d_min and value < d_mean:
                col.append(25)
            elif value > d_mean and value < d_max:
                col.append(75)
            elif value == d_mean:
                col.append(50)
            elif value == d_min:
                col.append(0)
            elif value == d_max:
                col.append(100)

print(f)

TypeError: '>' not supported between instances of 'float' and 'NoneType'





### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [461]:
### [your code here]
print("Array d:\n",d)
print("Array f:\n",f)

Array d:
 [[[ 7.  9.  5.  9.  6.]
  [10.  9.  7.  8.  1.]
  [ 4.  5.  3.  2.  1.]]

 [[10.  5. 10.  5.  6.]
  [ 5.  8.  3.  4.  9.]
  [ 4.  7.  9.  3. 10.]]]
Array f:
 [[[6. 8. 4. 8. 5.]
  [9. 8. 6. 7. 0.]
  [3. 4. 2. 1. 0.]]

 [[9. 4. 9. 4. 5.]
  [4. 7. 2. 3. 8.]
  [3. 6. 8. 2. 9.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [464]:
### [your code here]
label_map = np.empty(d.shape, dtype=str)
label_map[f == 0] = 'A'
label_map[f == 25] = 'B'
label_map[f == 50] = 'C'
label_map[f == 75] = 'D'
label_map[f == 100] = 'E'


print(label_map)

[[['' '' '' '' '']
  ['' '' '' '' 'A']
  ['' '' '' '' 'A']]

 [['' '' '' '' '']
  ['' '' '' '' '']
  ['' '' '' '' '']]]
