# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
### [your code here]
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [2]:
### [your code here]
print("NumPy Version:", np.__version__)

# Print NumPy configuration
np.show_config()

NumPy Version: 1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/7azmi/anaconda3/Library/include
    lib directory: C:/Users/7azmi/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1868282989520
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: win

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [6]:
### [your code here]
a = np.random.rand(2, 3, 5)



### 4. Print a.


In [7]:
### [your code here]
print(a)



[[[0.14382528 0.76998312 0.54667699 0.1640009  0.2660839 ]
  [0.10991638 0.11684384 0.89988804 0.7226035  0.37679879]
  [0.969858   0.21612367 0.58402354 0.94858856 0.03498101]]

 [[0.86441053 0.52530541 0.5192369  0.89573647 0.06626827]
  [0.14814191 0.23933131 0.03087527 0.29075235 0.15277789]
  [0.62953627 0.40839129 0.02144568 0.36388179 0.43737177]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [8]:
### [your code here]
b = np.ones((5, 2, 3))



### 6. Print b.


In [9]:
### [your code here]
print(b)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [10]:
### [your code here]
same_size = a.size == b.size

print("Size of a:", a.size)
print("Size of b:", b.size)
print("Do a and b have the same size?", same_size)


Size of a: 30
Size of b: 30
Do a and b have the same size? True



### 8. Are you able to add a and b? Why or why not?


In [11]:
### [your code here]
try:
    c = a + b  # Attempting to add
    print("Addition successful!")
    print(c)
except ValueError as e:
    print("Addition failed:", e)


Addition failed: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [12]:
### [your code here]
c = np.transpose(b, (1, 2, 0))  # Change axes order

# Check the new shape
print("Shape of c:", c.shape)
print(c)

Shape of c: (2, 3, 5)
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [13]:
### [your code here]
d = a + c

# Print the result
print("Shape of d:", d.shape)


Shape of d: (2, 3, 5)



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [14]:
### [your code here]

print("Array a:")
print(a)

print("\nArray d (a + c):")
print(d)

#d is just a with 1 added to every element because c was filled with ones.

Array a:
[[[0.14382528 0.76998312 0.54667699 0.1640009  0.2660839 ]
  [0.10991638 0.11684384 0.89988804 0.7226035  0.37679879]
  [0.969858   0.21612367 0.58402354 0.94858856 0.03498101]]

 [[0.86441053 0.52530541 0.5192369  0.89573647 0.06626827]
  [0.14814191 0.23933131 0.03087527 0.29075235 0.15277789]
  [0.62953627 0.40839129 0.02144568 0.36388179 0.43737177]]]

Array d (a + c):
[[[1.14382528 1.76998312 1.54667699 1.1640009  1.2660839 ]
  [1.10991638 1.11684384 1.89988804 1.7226035  1.37679879]
  [1.969858   1.21612367 1.58402354 1.94858856 1.03498101]]

 [[1.86441053 1.52530541 1.5192369  1.89573647 1.06626827]
  [1.14814191 1.23933131 1.03087527 1.29075235 1.15277789]
  [1.62953627 1.40839129 1.02144568 1.36388179 1.43737177]]]



### 12. Multiply a and c. Assign the result to e.


In [15]:
### [your code here]
# Element-wise multiplication of a and c
e = a * c

# Print the result
print("Array e (a * c):")
print(e)


Array e (a * c):
[[[0.14382528 0.76998312 0.54667699 0.1640009  0.2660839 ]
  [0.10991638 0.11684384 0.89988804 0.7226035  0.37679879]
  [0.969858   0.21612367 0.58402354 0.94858856 0.03498101]]

 [[0.86441053 0.52530541 0.5192369  0.89573647 0.06626827]
  [0.14814191 0.23933131 0.03087527 0.29075235 0.15277789]
  [0.62953627 0.40839129 0.02144568 0.36388179 0.43737177]]]




### 13. Does e equal to a? Why or why not?


In [16]:
### [your code here]
#Yes, e is equal to a because when you multiply any number by 1, the value remains unchanged.

equal = np.array_equal(e, a)

print("Does e equal a?", equal)


Does e equal a? True




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [17]:
### [your code here]
# Find the max, min, and mean values of d
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

# Print the results
print("Maximum value in d:", d_max)
print("Minimum value in d:", d_min)
print("Mean value in d:", d_mean)



Maximum value in d: 1.9698579981533961
Minimum value in d: 1.0214456781954375
Mean value in d: 1.41545528644071



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [18]:
### [your code here]
f = np.empty(d.shape)

print("Shape of f:", f.shape)
print(f)



Shape of f: (2, 3, 5)
[[[0.14382528 0.76998312 0.54667699 0.1640009  0.2660839 ]
  [0.10991638 0.11684384 0.89988804 0.7226035  0.37679879]
  [0.969858   0.21612367 0.58402354 0.94858856 0.03498101]]

 [[0.86441053 0.52530541 0.5192369  0.89573647 0.06626827]
  [0.14814191 0.23933131 0.03087527 0.29075235 0.15277789]
  [0.62953627 0.40839129 0.02144568 0.36388179 0.43737177]]]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [19]:
### [your code here]

f[d == d_min] = 0       
f[(d > d_min) & (d < d_mean)] = 25 
f[d == d_mean] = 50       
f[(d > d_mean) & (d < d_max)] = 75  
f[d == d_max] = 100       


print("Array f:")
print(f)



Array f:
[[[ 25.  75.  75.  25.  25.]
  [ 25.  25.  75.  75.  25.]
  [100.  25.  75.  75.  25.]]

 [[ 75.  75.  75.  75.  25.]
  [ 25.  25.  25.  25.  25.]
  [ 75.  25.   0.  25.  75.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [35]:
### [your code here]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [36]:
### [your code here]