# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
### [your code here]
import numpy as np





### 2. Print the NUMPY version and the configuration.


In [2]:
### [your code here]
np.__version__
np.show_config()

Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep140213194937296
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
    name: cython
    versio

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [8]:

### [your code here]
a = np.random.randint(0, 100, size=(2, 3, 5))
a = np.random.rand(2, 3, 5)
a = np.random.random((2, 3, 5))



### 4. Print a.


In [9]:
### [your code here]
print(a)

[[[71 47 81  1  8]
  [65 47 41 53 79]
  [41 32 62 34 84]]

 [[96 17 86 75 71]
  [61  9  1 15  6]
  [45 90 77  6  3]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [15]:
### [your code here]
b = np.ones((5, 2, 3))



### 6. Print b.


In [16]:
### [your code here]
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])


### 7. Do a and b have the same size? How do you prove that in Python code?


In [17]:
### [your code here]
a.shape == b.shape

False


### 8. Are you able to add a and b? Why or why not?


In [18]:
### [your code here]
a + b # different shapes

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [19]:
### [your code here]
c = b.reshape(2, 3 , 5)



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [33]:
### [your code here]
d = a+c



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [37]:
a

array([[[71, 47, 81,  1,  8],
        [65, 47, 41, 53, 79],
        [41, 32, 62, 34, 84]],

       [[96, 17, 86, 75, 71],
        [61,  9,  1, 15,  6],
        [45, 90, 77,  6,  3]]])

In [38]:
### [your code here]
d # d has the same shape as a, but each element in d is the result of adding the corresponding elements of a and c (i.e., d = a + c).
# The differences between a and d are determined by the values in c.


array([[[72., 48., 82.,  2.,  9.],
        [66., 48., 42., 54., 80.],
        [42., 33., 63., 35., 85.]],

       [[97., 18., 87., 76., 72.],
        [62., 10.,  2., 16.,  7.],
        [46., 91., 78.,  7.,  4.]]])


### 12. Multiply a and c. Assign the result to e.


In [26]:
### [your code here]
e = a * c
e

array([[[71., 47., 81.,  1.,  8.],
        [65., 47., 41., 53., 79.],
        [41., 32., 62., 34., 84.]],

       [[96., 17., 86., 75., 71.],
        [61.,  9.,  1., 15.,  6.],
        [45., 90., 77.,  6.,  3.]]])



### 13. Does e equal to a? Why or why not?


In [27]:
### [your code here]

e == a
# e is equal to a because c is a matrix where all elements are 1.
# When multiplying a by c (i.e., e = a * c), each element in a remains unchanged
# since multiplying by 1 does not affect the values.

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [34]:
### [your code here]
d_mean = d.mean()
d_max = d.max()
d_min = d.min()
print(d_mean, d_max, d_min)


47.8 97.0 2.0



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [39]:
### [your code here]
f = np.empty((2, 3, 5))





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [41]:
### [your code here]
f[d == d_min] = 0
f[d == d_max] = 100
f[d == d_mean] = 50
f[(d > d_min) & (d < d_mean)] = 25
f[(d > d_mean) & (d < d_max)] = 75
f



array([[[ 75.,  75.,  75.,   0.,  25.],
        [ 75.,  75.,  25.,  75.,  75.],
        [ 25.,  25.,  75.,  25.,  75.]],

       [[100.,  25.,  75.,  75.,  75.],
        [ 75.,  25.,   0.,  25.,  25.],
        [ 25.,  75.,  75.,  25.,  25.]]])





### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [42]:
### [your code here]
print(d, f) # d_mean=47.8 d_max = 97.0 d_min = 2.0

[[[72. 48. 82.  2.  9.]
  [66. 48. 42. 54. 80.]
  [42. 33. 63. 35. 85.]]

 [[97. 18. 87. 76. 72.]
  [62. 10.  2. 16.  7.]
  [46. 91. 78.  7.  4.]]] [[[ 75.  75.  75.   0.  25.]
  [ 75.  75.  25.  75.  75.]
  [ 25.  25.  75.  25.  75.]]

 [[100.  25.  75.  75.  75.]
  [ 75.  25.   0.  25.  25.]
  [ 25.  75.  75.  25.  25.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [45]:
### [your code here]
g = np.empty((2, 3, 5), dtype=object)

g[f == 0] = "E"
g[f == 25 ] = "D"
g[f == 50] = "C"
g [f == 75] ="B"
g [f == 100] = "A"

g

array([[['B', 'B', 'B', 'E', 'D'],
        ['B', 'B', 'D', 'B', 'B'],
        ['D', 'D', 'B', 'D', 'B']],

       [['A', 'D', 'B', 'B', 'B'],
        ['B', 'D', 'E', 'D', 'D'],
        ['D', 'B', 'B', 'D', 'D']]], dtype=object)