# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [2]:
import numpy as np

# إنشاء مصفوفة NumPy من الأعداد من 1 إلى 10
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# حساب المتوسط الحسابي لعناصر المصفوفة
mean_value = np.mean(arr)

# طباعة النتيجة
print("arry:", arr)
print("avg :", mean_value)


arry: [ 1  2  3  4  5  6  7  8  9 10]
avg : 5.5




### 2. Print the NUMPY version and the configuration.


In [3]:
import numpy as np

# طباعة إصدار NumPy
print("NumPy Version:", np.__version__)

# طباعة معلومات التكوين
np.show_config()


NumPy Version: 1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /Applications/anaconda3/include
    lib directory: /Applications/anaconda3/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 CORE2 MAX_THREADS=128
    pc file directory: /Applications/anaconda3/lib/pkgconfig
    version: 0.3.21
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep4429404432
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -march=core2, -mtune=haswell, -mssse3, -ftree-vectorize, -fPIC, -fPIE, -fstack-protector-strong,
      -O2, -pipe, -isystem, /Applications/anaconda3/include, -fdebug-prefix-map=/var/folders/c_/qfmhj66j0tn016nkx_th4hxm0000gp/T/abs_b7iptlxgej/croot/numpy_and_numpy_base_1708638622773/work=

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [4]:
import numpy as np

# الطريقة 1: np.random.rand() - أعداد عشرية بين 0 و 1
a1 = np.random.rand(2, 3, 5)
print("Random values between 0 and 1:\n", a1, "\n")

# الطريقة 2: np.random.randn() - توزيع طبيعي (قد تحتوي على قيم سالبة)
a2 = np.random.randn(2, 3, 5)
print("Normally distributed random values:\n", a2, "\n")

# الطريقة 3: np.random.randint() - أعداد صحيحة عشوائية بين 0 و 9
a3 = np.random.randint(0, 10, (2, 3, 5))
print("Random integer values between 0 and 9:\n", a3)


Random values between 0 and 1:
 [[[0.58133973 0.46760709 0.34744814 0.19773689 0.06047639]
  [0.83416158 0.63294538 0.48377756 0.35826119 0.02885552]
  [0.83735342 0.93193799 0.89582637 0.3989592  0.05003475]]

 [[0.26116687 0.11244309 0.02747999 0.71143113 0.22902975]
  [0.22694323 0.69219316 0.96897665 0.31383937 0.45281089]
  [0.34344612 0.11869014 0.03760069 0.79431173 0.23259772]]] 

Normally distributed random values:
 [[[ 0.23341947 -0.44473132  0.11400454 -1.65780002 -0.51367849]
  [ 0.34667285  2.05371735 -1.39267871  1.76850682 -0.73232435]
  [ 2.57132883 -0.00261655  1.17041228  0.37445159 -0.10009376]]

 [[-0.68810784 -0.03111867  0.07767973 -0.13151246 -0.25391031]
  [ 1.84674872  0.47675313  0.05000085  0.78471379 -0.01236775]
  [-0.5007185  -0.57556434  1.92848441 -0.18895996 -0.65307805]]] 

Random integer values between 0 and 9:
 [[[7 5 1 3 8]
  [6 3 3 1 5]
  [2 4 5 8 5]]

 [[4 9 3 8 2]
  [1 9 2 3 5]
  [8 9 1 7 1]]]



### 4. Print a.


In [6]:
print("Array a1:\n", a1)  # مصفوفة بأرقام عشوائية بين 0 و 1
print("\nArray a2:\n", a2)  # مصفوفة بتوزيع طبيعي
print("\nArray a3:\n", a3)  # مصفوفة بأرقام صحيحة بين 0 و 9


Array a1:
 [[[0.58133973 0.46760709 0.34744814 0.19773689 0.06047639]
  [0.83416158 0.63294538 0.48377756 0.35826119 0.02885552]
  [0.83735342 0.93193799 0.89582637 0.3989592  0.05003475]]

 [[0.26116687 0.11244309 0.02747999 0.71143113 0.22902975]
  [0.22694323 0.69219316 0.96897665 0.31383937 0.45281089]
  [0.34344612 0.11869014 0.03760069 0.79431173 0.23259772]]]

Array a2:
 [[[ 0.23341947 -0.44473132  0.11400454 -1.65780002 -0.51367849]
  [ 0.34667285  2.05371735 -1.39267871  1.76850682 -0.73232435]
  [ 2.57132883 -0.00261655  1.17041228  0.37445159 -0.10009376]]

 [[-0.68810784 -0.03111867  0.07767973 -0.13151246 -0.25391031]
  [ 1.84674872  0.47675313  0.05000085  0.78471379 -0.01236775]
  [-0.5007185  -0.57556434  1.92848441 -0.18895996 -0.65307805]]]

Array a3:
 [[[7 5 1 3 8]
  [6 3 3 1 5]
  [2 4 5 8 5]]

 [[4 9 3 8 2]
  [1 9 2 3 5]
  [8 9 1 7 1]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [8]:
import numpy as np

# إنشاء المصفوفة المكونة من 1
b = np.ones((5, 2, 3), dtype=int)

# طباعة المصفوفة
print("Array b:\n", b)


Array b:
 [[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]



### 6. Print b.


In [9]:
import numpy as np

# إنشاء مصفوفة 5x2x3 تحتوي على القيم 1
b = np.ones((5, 2, 3), dtype=int)

# طباعة المصفوفة
print("Array b:\n", b)


Array b:
 [[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [12]:
import numpy as np

# توليد المصفوفة العشوائية a
a = np.random.rand(2, 3, 5)

# توليد المصفوفة b
b = np.ones((5, 2, 3))

# التحقق مما إذا كانت a و b لهما نفس الحجم
if a.size == b.size:
    print("Yes, a and b have the same size:", a.size)
else:
    print("No, a and b have different sizes. a:", a.size, ", b:", b.size)


Yes, a and b have the same size: 30



### 8. Are you able to add a and b? Why or why not?


In [13]:
import numpy as np

# توليد المصفوفات
a = np.random.rand(2, 3, 5)
b = np.ones((5, 2, 3))

# محاولة جمع المصفوفات
try:
    result = a + b
    print("Addition successful")
except ValueError as e:
    print("Error:", e)


Error: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [16]:
import numpy as np

# إنشاء المصفوفات a و b
a = np.random.rand(2, 3, 5)
b = np.ones((5, 2, 3))

# تحويل المصفوفة b بحيث يكون شكلها (2, 3, 5)
c = b.transpose(1, 2, 0)

# عرض المصفوفة c
print("Array c (Transposed b):\n", c)


Array c (Transposed b):
 [[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [17]:
# إضافة المصفوفات a و c
d = a + c

# عرض المصفوفة الناتجة d
print("Array d (sum of a and c):\n", d)


Array d (sum of a and c):
 [[[1.9958963  1.63786022 1.45190185 1.44438638 1.83887339]
  [1.5613923  1.09187661 1.2941473  1.06702323 1.54964608]
  [1.59428871 1.07725127 1.1476859  1.22476852 1.23433522]]

 [[1.53849503 1.83396169 1.3737791  1.07404518 1.08175989]
  [1.37756883 1.8204297  1.67952757 1.08229761 1.92186778]
  [1.53642873 1.65200022 1.31227451 1.44842012 1.49978644]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [18]:
# طباعة المصفوفات a و d لمقارنة القيم
print("Array a:\n", a)
print("\nArray d (sum of a and c):\n", d)


Array a:
 [[[0.9958963  0.63786022 0.45190185 0.44438638 0.83887339]
  [0.5613923  0.09187661 0.2941473  0.06702323 0.54964608]
  [0.59428871 0.07725127 0.1476859  0.22476852 0.23433522]]

 [[0.53849503 0.83396169 0.3737791  0.07404518 0.08175989]
  [0.37756883 0.8204297  0.67952757 0.08229761 0.92186778]
  [0.53642873 0.65200022 0.31227451 0.44842012 0.49978644]]]

Array d (sum of a and c):
 [[[1.9958963  1.63786022 1.45190185 1.44438638 1.83887339]
  [1.5613923  1.09187661 1.2941473  1.06702323 1.54964608]
  [1.59428871 1.07725127 1.1476859  1.22476852 1.23433522]]

 [[1.53849503 1.83396169 1.3737791  1.07404518 1.08175989]
  [1.37756883 1.8204297  1.67952757 1.08229761 1.92186778]
  [1.53642873 1.65200022 1.31227451 1.44842012 1.49978644]]]



### 12. Multiply a and c. Assign the result to e.


In [19]:
# ضرب المصفوفات a و c
e = a * c

# طباعة المصفوفة e
print("Array e (product of a and c):\n", e)


Array e (product of a and c):
 [[[0.9958963  0.63786022 0.45190185 0.44438638 0.83887339]
  [0.5613923  0.09187661 0.2941473  0.06702323 0.54964608]
  [0.59428871 0.07725127 0.1476859  0.22476852 0.23433522]]

 [[0.53849503 0.83396169 0.3737791  0.07404518 0.08175989]
  [0.37756883 0.8204297  0.67952757 0.08229761 0.92186778]
  [0.53642873 0.65200022 0.31227451 0.44842012 0.49978644]]]




### 13. Does e equal to a? Why or why not?


In [20]:
import numpy as np

# إنشاء المصفوفة a (2x3x5) مع قيم عشوائية
a = np.random.random((2, 3, 5))

# إنشاء المصفوفة b (5x2x3) تحتوي على 1 في جميع العناصر
b = np.ones((5, 2, 3))

# تحويل b إلى الشكل المطلوب (2x3x5)
c = b.transpose(1, 2, 0)  # التبديل بين الأبعاد للحصول على نفس شكل a

# ضرب a و c
e = a * c

# طباعة a و e لمقارنة النتائج
print("a = \n", a)
print("\nMultiplication of a and c (e): \n", e)

# التحقق إذا كانت a و e متساويتين
print("\nIs e equal to a?", np.array_equal(a, e))  # يجب أن تكون الإجابة True


a = 
 [[[0.59112043 0.06383263 0.95643873 0.78028155 0.70456497]
  [0.69591156 0.67518895 0.77220022 0.37535682 0.85393666]
  [0.51708058 0.10856527 0.08216533 0.08159323 0.19049193]]

 [[0.45954447 0.0679394  0.04534068 0.21700811 0.32040164]
  [0.07575653 0.19592889 0.44580491 0.80531965 0.63153968]
  [0.44318224 0.57428766 0.47446331 0.07259019 0.0078003 ]]]

Multiplication of a and c (e): 
 [[[0.59112043 0.06383263 0.95643873 0.78028155 0.70456497]
  [0.69591156 0.67518895 0.77220022 0.37535682 0.85393666]
  [0.51708058 0.10856527 0.08216533 0.08159323 0.19049193]]

 [[0.45954447 0.0679394  0.04534068 0.21700811 0.32040164]
  [0.07575653 0.19592889 0.44580491 0.80531965 0.63153968]
  [0.44318224 0.57428766 0.47446331 0.07259019 0.0078003 ]]]

Is e equal to a? True




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [21]:
import numpy as np

# استخدام دالة max للحصول على القيمة القصوى
d_max = np.max(d)

# استخدام دالة min للحصول على القيمة الدنيا
d_min = np.min(d)

# استخدام دالة mean للحصول على المتوسط
d_mean = np.mean(d)

# طباعة القيم
print("Max value in d:", d_max)
print("Min value in d:", d_min)
print("Mean value in d:", d_mean)


Max value in d: 1.9958962958962112
Min value in d: 1.0670232347260211
Mean value in d: 1.4481325224238568



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [22]:
import numpy as np

# إنشاء مصفوفة فارغة بنفس الشكل 2x3x5 كما في d
f = np.empty(d.shape)

# طباعة المصفوفة الفارغة
print("Array f:")
print(f)


Array f:
[[[0.59112043 0.06383263 0.95643873 0.78028155 0.70456497]
  [0.69591156 0.67518895 0.77220022 0.37535682 0.85393666]
  [0.51708058 0.10856527 0.08216533 0.08159323 0.19049193]]

 [[0.45954447 0.0679394  0.04534068 0.21700811 0.32040164]
  [0.07575653 0.19592889 0.44580491 0.80531965 0.63153968]
  [0.44318224 0.57428766 0.47446331 0.07259019 0.0078003 ]]]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [23]:
import numpy as np

# إنشاء المصفوفات d و f (تأكد من أن لديك الدالة max و min و mean في المصفوفة d)
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

# إنشاء المصفوفة الفارغة f بنفس الشكل
f = np.empty(d.shape)

# التكرار عبر القيم في d وتحديث الفارغة f بناءً على الشروط
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            value = d[i, j, k]
            if value == d_mean:
                f[i, j, k] = 50
            elif value == d_max:
                f[i, j, k] = 100
            elif value == d_min:
                f[i, j, k] = 0
            elif d_min < value < d_mean:
                f[i, j, k] = 25
            elif d_mean < value < d_max:
                f[i, j, k] = 75

# طباعة المصفوفة f بعد التحديث
print("Updated array f:")
print(f)


Updated array f:
[[[100.  75.  75.  25.  75.]
  [ 75.  25.  25.   0.  75.]
  [ 75.  25.  25.  25.  25.]]

 [[ 75.  75.  25.  25.  25.]
  [ 25.  75.  75.  25.  75.]
  [ 75.  75.  25.  75.  75.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [25]:
import numpy as np

# إنشاء المصفوفة d مثال
d = np.array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
               [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
               [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
              
              [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
               [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
               [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

# حساب القيم العظمى والدنيا والمتوسط
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

# إنشاء المصفوفة الفارغة f بنفس الحجم
f = np.empty(d.shape)

# التكرار عبر القيم في d وتحديث الفارغة f بناءً على الشروط
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            value = d[i, j, k]
            if value == d_mean:
                f[i, j, k] = 50
            elif value == d_max:
                f[i, j, k] = 100
            elif value == d_min:
                f[i, j, k] = 0
            elif d_min < value < d_mean:
                f[i, j, k] = 25
            elif d_mean < value < d_max:
                f[i, j, k] = 75

# طباعة المصفوفات d و f
print("d array:")
print(d)

print("\nf array:")
print(f)


d array:
[[[1.85836099 1.67064465 1.62576044 1.40243961 1.88454931]
  [1.75354326 1.69403643 1.36729252 1.61415071 1.12104981]
  [1.72201435 1.1862918  1.87078449 1.7726778  1.88180042]]

 [[1.44747908 1.31673383 1.02000951 1.52218947 1.97066381]
  [1.79129243 1.74983003 1.96028037 1.85166831 1.65450881]
  [1.18068344 1.9587381  1.00656599 1.93402165 1.73514584]]]

f array:
[[[ 75.  75.  75.  25.  75.]
  [ 75.  75.  25.  25.  25.]
  [ 75.  25.  75.  75.  75.]]

 [[ 25.  25.  25.  25. 100.]
  [ 75.  75.  75.  75.  75.]
  [ 25.  75.   0.  75.  75.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [26]:
import numpy as np

# إنشاء المصفوفة d مثال
d = np.array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
               [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
               [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
              
              [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
               [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
               [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

# حساب القيم العظمى والدنيا والمتوسط
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

# إنشاء المصفوفة الفارغة f بنفس الحجم ولكن باستخدام نصوص بدلاً من الأرقام
f = np.empty(d.shape, dtype=object)

# التكرار عبر القيم في d وتحديث الفارغة f بناءً على الشروط
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            value = d[i, j, k]
            if value == d_mean:
                f[i, j, k] = "C"
            elif value == d_max:
                f[i, j, k] = "E"
            elif value == d_min:
                f[i, j, k] = "A"
            elif d_min < value < d_mean:
                f[i, j, k] = "B"
            elif d_mean < value < d_max:
                f[i, j, k] = "D"

# طباعة المصفوفات d و f
print("d array:")
print(d)

print("\nf array:")
print(f)


d array:
[[[1.85836099 1.67064465 1.62576044 1.40243961 1.88454931]
  [1.75354326 1.69403643 1.36729252 1.61415071 1.12104981]
  [1.72201435 1.1862918  1.87078449 1.7726778  1.88180042]]

 [[1.44747908 1.31673383 1.02000951 1.52218947 1.97066381]
  [1.79129243 1.74983003 1.96028037 1.85166831 1.65450881]
  [1.18068344 1.9587381  1.00656599 1.93402165 1.73514584]]]

f array:
[[['D' 'D' 'D' 'B' 'D']
  ['D' 'D' 'B' 'B' 'B']
  ['D' 'B' 'D' 'D' 'D']]

 [['B' 'B' 'B' 'B' 'E']
  ['D' 'D' 'D' 'D' 'D']
  ['B' 'D' 'A' 'D' 'D']]]
