# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
### [your code here]
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [2]:
### [your code here]
print(np.version.version)

2.2.3


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [5]:
### [your code here]
a = np.random.rand(2,3,5)



### 4. Print a.


In [6]:
### [your code here]
print(a)

[[[4.18393659e-01 2.85984838e-03 6.22533349e-01 4.32660275e-01
   5.87120073e-04]
  [4.66406478e-01 8.07543923e-01 6.13431483e-01 9.61480692e-01
   4.07938445e-01]
  [2.57908204e-01 9.08136809e-01 9.40719151e-01 4.83622616e-02
   8.91798266e-01]]

 [[3.96153616e-02 1.79412611e-01 9.29625569e-01 8.45109125e-01
   4.83687836e-01]
  [5.89874329e-01 7.44889119e-01 6.75560498e-01 4.39685321e-01
   1.18359962e-01]
  [9.30009726e-01 1.95242495e-01 4.92265590e-01 4.73709925e-01
   6.65144810e-01]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [8]:
### [your code here]
b = np.ones((5,3,2))


### 6. Print b.


In [9]:
### [your code here]
print(b)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [10]:
### [your code here]
if a.shape == b.shape:
    print("The arrays have the same size")
else:
    print("They arrays have different sizes")

They arrays have different sizes



### 8. Are you able to add a and b? Why or why not?


In [14]:
### [your code here]
result = a + b
print(result)
"No, as attempted above the 2 arrays cant be added cause of theyr different size"

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,3,2) 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [15]:
### [your code here]
c = b.reshape(2,3,5)


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [ ]:
### [your code here]
d = a + c
"Now it works cause they have the same shape"


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [18]:
### [your code here]
print(a)
print(b)

"the shape are oposite (5x3x2) compared to (2x3x5), one has random generated values and the other has only 1s"


[[[4.18393659e-01 2.85984838e-03 6.22533349e-01 4.32660275e-01
   5.87120073e-04]
  [4.66406478e-01 8.07543923e-01 6.13431483e-01 9.61480692e-01
   4.07938445e-01]
  [2.57908204e-01 9.08136809e-01 9.40719151e-01 4.83622616e-02
   8.91798266e-01]]

 [[3.96153616e-02 1.79412611e-01 9.29625569e-01 8.45109125e-01
   4.83687836e-01]
  [5.89874329e-01 7.44889119e-01 6.75560498e-01 4.39685321e-01
   1.18359962e-01]
  [9.30009726e-01 1.95242495e-01 4.92265590e-01 4.73709925e-01
   6.65144810e-01]]]
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


'the shape are oposite (5x3x2) compared to (2x3x5), one has random generated values and the other has only 1s'


### 12. Multiply a and c. Assign the result to e.


In [19]:
### [your code here]
e = a * c



### 13. Does e equal to a? Why or why not?


In [24]:
### [your code here]
if np.array_equal(e, a):
    print ("Yes, the 2 arrays are equal \nBecause e is a multiplyed by 1")
else:
    print("No, the arrays are different")


Yes, the 2 arrays are equal 
Because e is a multiplyed by 1




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [25]:
### [your code here]
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [27]:
### [your code here]
f = np.empty((2,3,5))




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [ ]:
### [your code here]
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i, j, k] == d_min:
                f[i, j, k] = 0
            elif d_min < d[i, j, k] < d_mean:
                f[i, j, k] = 25
            elif d[i, j, k] == d_mean:
                f[i, j, k] = 50
            elif d_mean < d[i, j, k] < d_max:
                f[i, j, k] = 75
            elif d[i, j, k] == d_max:
                f[i, j, k] = 100





### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [30]:
### [your code here]
print(d)
print(f)

[[[1.41839366 1.00285985 1.62253335 1.43266028 1.00058712]
  [1.46640648 1.80754392 1.61343148 1.96148069 1.40793844]
  [1.2579082  1.90813681 1.94071915 1.04836226 1.89179827]]

 [[1.03961536 1.17941261 1.92962557 1.84510913 1.48368784]
  [1.58987433 1.74488912 1.6755605  1.43968532 1.11835996]
  [1.93000973 1.19524249 1.49226559 1.47370992 1.66514481]]]
[[[ 25.  25.  75.  25.   0.]
  [ 25.  75.  75. 100.  25.]
  [ 25.  75.  75.  25.  75.]]

 [[ 25.  25.  75.  75.  25.]
  [ 75.  75.  75.  25.  25.]
  [ 75.  25.  25.  25.  75.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [ ]:
### [your code here]
f = np.empty_like(d, dtype='<U1')

for i in range(2):
    for j in range(3):
        for k in range(5):
            if d[i][j][k] == d_min:
                f[i][j][k] = 'A'
            elif d_min < d[i][j][k] < d_mean:
                f[i][j][k] = 'B'
            elif d[i][j][k] == d_mean:
                f[i][j][k] = 'C'
            elif d_mean < d[i][j][k] < d_max:
                f[i][j][k] = 'D'
            elif d[i][j][k] == d_max:
                f[i][j][k] = 'E'
            
print(f)

[[['B' 'B' 'D' 'B' 'A']
  ['B' 'D' 'D' 'E' 'B']
  ['B' 'D' 'D' 'B' 'D']]

 [['B' 'B' 'D' 'D' 'B']
  ['D' 'D' 'D' 'B' 'B']
  ['D' 'B' 'B' 'B' 'D']]]
