1. Import the NUMPY package under the name np.

In [2]:
import numpy as np
import random   

2. Print the NUMPY version and the configuration.

[your code here]

In [3]:
print(np.__version__)
np.show_config()

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/anaconda3/include
    lib directory: /opt/anaconda3/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 VORTEX MAX_THREADS=128
    pc file directory: /opt/anaconda3/lib/pkgconfig
    version: 0.3.21
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep4347739648
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -ftree-vectorize, -fPIC, -fPIE, -fstack-protector-strong, -O2, -pipe, -isystem,
      /opt/anaconda3/include, -fdebug-prefix-map=/var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_a51i_mbs7m/croot/numpy_and_numpy_base_1708638620867/work=/usr/local/src/conda/numpy-base-1.26.4,
      -fdebug-prefix-map=/opt/anaconda3=/usr/loca

3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [4]:
        # option 1
a = np.random.random((2, 3, 5))
        # option 2
a2 = np.random.randint(1, 101, size=(2, 3, 5))
        # option 3
a3 = np.array([[[random.randint(1, 100) for _ in range(5)] for _ in range(3)] for _ in range(2)])



4. Print a.

In [5]:
print(f"array a(random): \n {a}")

print(f"array a2(randint): \n {a2}")

print(f"array a3(list): \n {a3}")


array a(random): 
 [[[0.45335576 0.99124496 0.3559175  0.80635825 0.96709701]
  [0.21614108 0.12813469 0.54810469 0.11917113 0.60757167]
  [0.75727739 0.41850778 0.01718322 0.1323822  0.48744152]]

 [[0.04968708 0.35752342 0.36389725 0.45963487 0.62565944]
  [0.38801653 0.08222859 0.29354992 0.20268432 0.82878365]
  [0.11511434 0.64380758 0.81316192 0.04407557 0.22552555]]]
array a2(randint): 
 [[[90 72 66 50 57]
  [ 7 24 42 86 79]
  [61 93 39 19 49]]

 [[27 55 46 12 17]
  [88 95 35 26 16]
  [45 11 26 83 21]]]
array a3(list): 
 [[[ 92  62  40  20  34]
  [ 75  16  60  68  78]
  [ 39  31  42   9  75]]

 [[ 91  54  62  43  54]
  [100  19  44  56  62]
  [ 51  89  43   5   9]]]


5. Create a 5x2x3 3-dimensional array with all values equaling 1.
Assign the array to variable "b"

In [6]:
# b = a3 = np.array([[[1 for _ in range(5)] for _ in range(2)] for _ in range(3)])
b = np.ones((5, 2, 3))

6. Print b.

In [7]:
print(b)
# print(b2)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


7. Do a and b have the same size? How do you prove that in Python code?

In [8]:
size_a = a.size
size_b = b.size

print(size_a== size_b)

True


8. Are you able to add a and b? Why or why not?

In [9]:
# Its not possible, because of the different structure/shape. If I reshape them then it's possible because of the same size.

9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

In [10]:
c = b.reshape(2,3,5)
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [11]:
d = a + c

print(d)

[[[1.45335576 1.99124496 1.3559175  1.80635825 1.96709701]
  [1.21614108 1.12813469 1.54810469 1.11917113 1.60757167]
  [1.75727739 1.41850778 1.01718322 1.1323822  1.48744152]]

 [[1.04968708 1.35752342 1.36389725 1.45963487 1.62565944]
  [1.38801653 1.08222859 1.29354992 1.20268432 1.82878365]
  [1.11511434 1.64380758 1.81316192 1.04407557 1.22552555]]]


11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

In [12]:
print(f" a: \n{a}")
print(f" d: \n{d}")

 a: 
[[[0.45335576 0.99124496 0.3559175  0.80635825 0.96709701]
  [0.21614108 0.12813469 0.54810469 0.11917113 0.60757167]
  [0.75727739 0.41850778 0.01718322 0.1323822  0.48744152]]

 [[0.04968708 0.35752342 0.36389725 0.45963487 0.62565944]
  [0.38801653 0.08222859 0.29354992 0.20268432 0.82878365]
  [0.11511434 0.64380758 0.81316192 0.04407557 0.22552555]]]
 d: 
[[[1.45335576 1.99124496 1.3559175  1.80635825 1.96709701]
  [1.21614108 1.12813469 1.54810469 1.11917113 1.60757167]
  [1.75727739 1.41850778 1.01718322 1.1323822  1.48744152]]

 [[1.04968708 1.35752342 1.36389725 1.45963487 1.62565944]
  [1.38801653 1.08222859 1.29354992 1.20268432 1.82878365]
  [1.11511434 1.64380758 1.81316192 1.04407557 1.22552555]]]


12. Multiply a and c. Assign the result to e.

In [13]:
e = a * c
print(e)


[[[0.45335576 0.99124496 0.3559175  0.80635825 0.96709701]
  [0.21614108 0.12813469 0.54810469 0.11917113 0.60757167]
  [0.75727739 0.41850778 0.01718322 0.1323822  0.48744152]]

 [[0.04968708 0.35752342 0.36389725 0.45963487 0.62565944]
  [0.38801653 0.08222859 0.29354992 0.20268432 0.82878365]
  [0.11511434 0.64380758 0.81316192 0.04407557 0.22552555]]]


13. Does e equal to a? Why or why not?

Yes, it is. Because: 1(c) multiplied with something(a) is always something(a). 

14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [14]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(f"d_max: {d_max} \nd_min_ {d_min} \nd_mean: {d_mean}")

d_max: 1.9912449602010047 
d_min_ 1.0171832243645802 
d_mean: 1.416641295872516


15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [15]:
f = np.empty((2, 3, 5))
print(f)

[[[0.45335576 0.99124496 0.3559175  0.80635825 0.96709701]
  [0.21614108 0.12813469 0.54810469 0.11917113 0.60757167]
  [0.75727739 0.41850778 0.01718322 0.1323822  0.48744152]]

 [[0.04968708 0.35752342 0.36389725 0.45963487 0.62565944]
  [0.38801653 0.08222859 0.29354992 0.20268432 0.82878365]
  [0.11511434 0.64380758 0.81316192 0.04407557 0.22552555]]]


16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.

If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.

If a value equals to d_mean, assign 50 to the corresponding value in f.

Assign 0 to the corresponding value(s) in f for d_min in d.

Assign 100 to the corresponding value(s) in f for d_max in d.

In the end, f should have only the following values: 0, 25, 50, 75, and 100.

Note: you don't have to use Numpy in this question.

In [16]:
d = np.array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(f"d_max: {d_max} \nd_min_ {d_min} \nd_mean: {d_mean}")

for ma, matrix in enumerate(d):
    for ro, row in enumerate(matrix):
        for el, element in enumerate(row):
            if d_mean > element > d_min:
                f[ma][ro][el] = 25
            elif element == d_max:
                f[ma][ro][el] = 100
            elif d_max > element > d_mean: 
                f[ma][ro][el] = 75    
            elif element > d_mean:
                f[ma][ro][el] = 50
            elif element == d_min:
                f[ma][ro][el] = 0
            
print(f" array is: \n {f}")                          

d_max: 1.97066381 
d_min_ 1.00656599 
d_mean: 1.6175069086666667
 array is: 
 [[[ 75.  75.  75.  25.  75.]
  [ 75.  75.  25.  25.  25.]
  [ 75.  25.  75.  75.  75.]]

 [[ 25.  25.  25.  25. 100.]
  [ 75.  75.  75.  75.  75.]
  [ 25.  75.   0.  75.  75.]]]


17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])

In [17]:
print(f"d: \n {d}") 
print(d.ndim)
print(f"f: \n {f}") 
print(f"d_max: {d_max} \nd_min_ {d_min} \nd_mean: {d_mean}")


d: 
 [[[1.85836099 1.67064465 1.62576044 1.40243961 1.88454931]
  [1.75354326 1.69403643 1.36729252 1.61415071 1.12104981]
  [1.72201435 1.1862918  1.87078449 1.7726778  1.88180042]]

 [[1.44747908 1.31673383 1.02000951 1.52218947 1.97066381]
  [1.79129243 1.74983003 1.96028037 1.85166831 1.65450881]
  [1.18068344 1.9587381  1.00656599 1.93402165 1.73514584]]]
3
f: 
 [[[ 75.  75.  75.  25.  75.]
  [ 75.  75.  25.  25.  25.]
  [ 75.  25.  75.  75.  75.]]

 [[ 25.  25.  25.  25. 100.]
  [ 75.  75.  75.  75.  75.]
  [ 25.  75.   0.  75.  75.]]]
d_max: 1.97066381 
d_min_ 1.00656599 
d_mean: 1.6175069086666667


18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [23]:
d = np.array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])
f = np.empty((2, 3, 5), dtype=str)
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(f"d_max: {d_max} \nd_min_ {d_min} \nd_mean: {d_mean}")

for ma, matrix in enumerate(d):
    for ro, row in enumerate(matrix):
        for el, element in enumerate(row):
            if d_mean > element > d_min:
                f[ma][ro][el] = "B" 
            elif element == d_max:
                f[ma][ro][el] = "E"
            elif d_max > element > d_mean: 
                f[ma][ro][el] = "D"    
            elif element > d_mean:
                f[ma][ro][el] = "B"
            elif element == d_min:
                f[ma][ro][el] = "A"

print(f" array is: \n {f}")      


d_max: 1.97066381 
d_min_ 1.00656599 
d_mean: 1.6175069086666667
 array is: 
 [[['D' 'D' 'D' 'B' 'D']
  ['D' 'D' 'B' 'B' 'B']
  ['D' 'B' 'D' 'D' 'D']]

 [['B' 'B' 'B' 'B' 'E']
  ['D' 'D' 'D' 'D' 'D']
  ['B' 'D' 'A' 'D' 'D']]]
