# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
### [your code here]
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [4]:
### [your code here]
print("Current ver of numpy is ", np.__version__)


Current ver of numpy is  2.2.2


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [14]:
### [your code here]
a = np.random.random((2, 3, 5)) # array of float numbers between 0 and 1
a = np.random.randint(-1000, 1001, (2, 3, 5)) #  array of int  numbers between -1000 and  1000
a = np.round(np.random.uniform(-100000, 100001, (2, 3, 5)), 2) # array of float  numbers between -100,000 and  100,000
a


array([[[ 13286.88, -22156.16,  17326.99,  87195.3 , -52872.1 ],
        [-57902.07,  80199.36,  97600.98, -47714.2 ,  98924.68],
        [  2752.82, -91776.78, -45280.8 , -94617.44, -26058.45]],

       [[ 85438.74, -51971.72, -32451.29,   1856.59,  60857.19],
        [ 42721.58,  76269.7 ,  75440.92,  42845.68,  36312.63],
        [ 63891.02,  30795.04,  64508.52, -71720.88,  -6459.73]]])


### 4. Print a.


In [15]:
### [your code here]
print(a)

[[[ 13286.88 -22156.16  17326.99  87195.3  -52872.1 ]
  [-57902.07  80199.36  97600.98 -47714.2   98924.68]
  [  2752.82 -91776.78 -45280.8  -94617.44 -26058.45]]

 [[ 85438.74 -51971.72 -32451.29   1856.59  60857.19]
  [ 42721.58  76269.7   75440.92  42845.68  36312.63]
  [ 63891.02  30795.04  64508.52 -71720.88  -6459.73]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [16]:
### [your code here]
b = np.ones((5, 2, 3), dtype=float)


### 6. Print b.


In [17]:
### [your code here]
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [23]:
### [your code here]
if a.size == b.size:
    print(f" Arrays a and b have the same size: {a.size}")

 Arrays a and b have the same size: 30



### 8. Are you able to add a and b? Why or why not?


In [34]:
### [your code here]
try:
    a + b
except ValueError as e:
    print("Arrays a and b have different shape", e)


Arrays a and b have different shape operands could not be broadcast together with shapes (2,3,5) (5,2,3) 




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [41]:
### [your code here]
c = b.transpose(1,2,0)
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [43]:
### [your code here]
try:
    d = a + c
except ValueError as e:
    print("Arrays a and c have different shape", e)


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [45]:
### [your code here]
print("a =\n", a)
print("d =\n", d)



a =
 [[[ 13286.88 -22156.16  17326.99  87195.3  -52872.1 ]
  [-57902.07  80199.36  97600.98 -47714.2   98924.68]
  [  2752.82 -91776.78 -45280.8  -94617.44 -26058.45]]

 [[ 85438.74 -51971.72 -32451.29   1856.59  60857.19]
  [ 42721.58  76269.7   75440.92  42845.68  36312.63]
  [ 63891.02  30795.04  64508.52 -71720.88  -6459.73]]]
d =
 [[[ 13287.88 -22155.16  17327.99  87196.3  -52871.1 ]
  [-57901.07  80200.36  97601.98 -47713.2   98925.68]
  [  2753.82 -91775.78 -45279.8  -94616.44 -26057.45]]

 [[ 85439.74 -51970.72 -32450.29   1857.59  60858.19]
  [ 42722.58  76270.7   75441.92  42846.68  36313.63]
  [ 63892.02  30796.04  64509.52 -71719.88  -6458.73]]]



### 12. Multiply a and c. Assign the result to e.


In [46]:
### [your code here]
e = a * c



### 13. Does e equal to a? Why or why not?


In [47]:
### [your code here]
print("a =\n", a)
print("e =\n", e)

# a equals e because we mulitiplied each element in a by 1


a =
 [[[ 13286.88 -22156.16  17326.99  87195.3  -52872.1 ]
  [-57902.07  80199.36  97600.98 -47714.2   98924.68]
  [  2752.82 -91776.78 -45280.8  -94617.44 -26058.45]]

 [[ 85438.74 -51971.72 -32451.29   1856.59  60857.19]
  [ 42721.58  76269.7   75440.92  42845.68  36312.63]
  [ 63891.02  30795.04  64508.52 -71720.88  -6459.73]]]
e =
 [[[ 13286.88 -22156.16  17326.99  87195.3  -52872.1 ]
  [-57902.07  80199.36  97600.98 -47714.2   98924.68]
  [  2752.82 -91776.78 -45280.8  -94617.44 -26058.45]]

 [[ 85438.74 -51971.72 -32451.29   1856.59  60857.19]
  [ 42721.58  76269.7   75440.92  42845.68  36312.63]
  [ 63891.02  30795.04  64508.52 -71720.88  -6459.73]]]




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [52]:
### [your code here]
d_max = np.max(d)
d_min = np.min(d)
d_mean = round(np.mean(d), 2)

print(f"d_max = {d_max}, d_min = {d_min}, d_mean = {d_mean}")


d_max = 98925.68, d_min = -94616.44, d_mean = 12575.77



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [55]:
### [your code here]
f = np.empty((2, 3, 5))
print(f)


[[[ 13286.88 -22156.16  17326.99  87195.3  -52872.1 ]
  [-57902.07  80199.36  97600.98 -47714.2   98924.68]
  [  2752.82 -91776.78 -45280.8  -94617.44 -26058.45]]

 [[ 85438.74 -51971.72 -32451.29   1856.59  60857.19]
  [ 42721.58  76269.7   75440.92  42845.68  36312.63]
  [ 63891.02  30795.04  64508.52 -71720.88  -6459.73]]]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [62]:
### [your code here]
for i in range(len(d)):
    for j in range(len(d[i])):
        for h in range(len(d[i][j])):
            if d[i][j][h] == d_min:
                f[i][j][h] = 0
            elif d[i][j][h] == d_max:
                f[i][j][h] = 100
            elif d[i][j][h] == d_mean:
                f[i][j][h] = 50
            elif d[i][j][h] < d_mean:
                f[i][j][h] = 25
            else:
                f[i][j][h] = 75






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [61]:
### [your code here]
print(d)

print(f)

[[[ 13287.88 -22155.16  17327.99  87196.3  -52871.1 ]
  [-57901.07  80200.36  97601.98 -47713.2   98925.68]
  [  2753.82 -91775.78 -45279.8  -94616.44 -26057.45]]

 [[ 85439.74 -51970.72 -32450.29   1857.59  60858.19]
  [ 42722.58  76270.7   75441.92  42846.68  36313.63]
  [ 63892.02  30796.04  64509.52 -71719.88  -6458.73]]]
[[[ 75.  25.  75.  75.  25.]
  [ 25.  75.  75.  25. 100.]
  [ 25.  25.  25.   0.  25.]]

 [[ 75.  25.  25.  25.  75.]
  [ 75.  75.  75.  75.  75.]
  [ 75.  75.  75.  25.  25.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [63]:
### [your code here]

g = np.empty((2, 3, 5), dtype='str')
print(g)
for i in range(len(d)):
    for j in range(len(d[i])):
        for h in range(len(d[i][j])):
            if d[i][j][h] == d_min:
                g[i][j][h] = 'A'
            elif d[i][j][h] == d_max:
                g[i][j][h] = 'E'
            elif d[i][j][h] == d_mean:
                g[i][j][h] = 'C'
            elif d[i][j][h] < d_mean:
                g[i][j][h] = 'B'
            else:
                g[i][j][h] = 'D'

print()
print(g)


[[['' '' '' '' '']
  ['' '' '' '' '']
  ['' '' '' '' '']]

 [['' '' '' '' '']
  ['' '' '' '' '']
  ['' '' '' '' '']]]

[[['D' 'B' 'D' 'D' 'B']
  ['B' 'D' 'D' 'B' 'E']
  ['B' 'B' 'B' 'A' 'B']]

 [['D' 'B' 'B' 'B' 'D']
  ['D' 'D' 'D' 'D' 'D']
  ['D' 'D' 'D' 'B' 'B']]]
