# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
### [your code here]
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [2]:
### [your code here]
print(np.__version__)
print("Loaded", np.__version__, "version of numpy!!!")

1.26.4
Loaded 1.26.4 version of numpy!!!


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [3]:
### [your code here]
a = np.random.rand(2,3,5)
print("Random array with np.random.rand:\n", a)

Random array with np.random.rand:
 [[[0.58428446 0.60607821 0.0541152  0.74299659 0.78550535]
  [0.2086138  0.02785458 0.87894035 0.53654555 0.74639764]
  [0.33292232 0.70652789 0.71349606 0.25996682 0.72466057]]

 [[0.98846808 0.8129031  0.18944792 0.15129836 0.80673251]
  [0.69630725 0.05006484 0.8508381  0.20884948 0.60758762]
  [0.12933301 0.54091726 0.11371774 0.1661586  0.93428604]]]


In [4]:
low, high = 10, 100 # do you have to specify the integers?
random_integers = np.random.randint(low, high, size=(2, 3, 5))
print("Random Integers:\n", random_integers)

Random Integers:
 [[[78 95 80 19 32]
  [85 86 76 17 52]
  [42 74 97 52 86]]

 [[78 95 60 21 81]
  [87 44 32 69 34]
  [92 80 50 20 68]]]



### 4. Print a.


In [5]:
### [your code here]
print("Random array with np.random.rand:\n", a)

Random array with np.random.rand:
 [[[0.58428446 0.60607821 0.0541152  0.74299659 0.78550535]
  [0.2086138  0.02785458 0.87894035 0.53654555 0.74639764]
  [0.33292232 0.70652789 0.71349606 0.25996682 0.72466057]]

 [[0.98846808 0.8129031  0.18944792 0.15129836 0.80673251]
  [0.69630725 0.05006484 0.8508381  0.20884948 0.60758762]
  [0.12933301 0.54091726 0.11371774 0.1661586  0.93428604]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [6]:
### [your code here]
b = np.ones((5,2,3))


### 6. Print b.


In [7]:
### [your code here]
print("array with all values equaling 1:\n", b)

array with all values equaling 1:
 [[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [8]:
### [your code here]
print(a.size)
print(b.size)

same_size = a.size == b.size
print("Do a and b have the same size?", same_size)

30
30
Do a and b have the same size? True



### 8. Are you able to add a and b? Why or why not?


In [9]:
### [your code here]
addition = a + b

# ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 
# -----
# a and b are same size but different shape

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [11]:
### [your code here]
c = b.transpose((1, 2, 0)) # do not understand why these numbers there!
# c = b.transpose()
print("Shape of c after transposition:\n", c.shape)


Shape of c after transposition:
 (2, 3, 5)



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [12]:
### [your code here]

d = a + c

# it works because they are the same shape (and size)!



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [13]:
### [your code here]
print(d)


[[[1.58428446 1.60607821 1.0541152  1.74299659 1.78550535]
  [1.2086138  1.02785458 1.87894035 1.53654555 1.74639764]
  [1.33292232 1.70652789 1.71349606 1.25996682 1.72466057]]

 [[1.98846808 1.8129031  1.18944792 1.15129836 1.80673251]
  [1.69630725 1.05006484 1.8508381  1.20884948 1.60758762]
  [1.12933301 1.54091726 1.11371774 1.1661586  1.93428604]]]



### 12. Multiply a and c. Assign the result to e.


In [15]:
### [your code here]
e = a * c
print(e)

[[[0.58428446 0.60607821 0.0541152  0.74299659 0.78550535]
  [0.2086138  0.02785458 0.87894035 0.53654555 0.74639764]
  [0.33292232 0.70652789 0.71349606 0.25996682 0.72466057]]

 [[0.98846808 0.8129031  0.18944792 0.15129836 0.80673251]
  [0.69630725 0.05006484 0.8508381  0.20884948 0.60758762]
  [0.12933301 0.54091726 0.11371774 0.1661586  0.93428604]]]




### 13. Does e equal to a? Why or why not?


In [17]:
### [your code here]

are_same = a == e
print("Are `a` and `e` the same?", are_same)  

# Do not understand why!!!

Are `a` and `e` the same? [[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [18]:
### [your code here]

d_max = np.max(d)

d_min = np.min(d)

# Find the mean value in the array
d_mean = np.mean(d)

print("Max value in d:", d_max)
print("Min value in d:", d_min)
print("Mean value in d:", d_mean)


Max value in d: 1.9884680765392746
Min value in d: 1.0278545789149813
Mean value in d: 1.5051938432536711


### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [20]:
### [your code here]

f = np.empty((2,3,5))
print(f)

[[[0.58428446 0.60607821 0.0541152  0.74299659 0.78550535]
  [0.2086138  0.02785458 0.87894035 0.53654555 0.74639764]
  [0.33292232 0.70652789 0.71349606 0.25996682 0.72466057]]

 [[0.98846808 0.8129031  0.18944792 0.15129836 0.80673251]
  [0.69630725 0.05006484 0.8508381  0.20884948 0.60758762]
  [0.12933301 0.54091726 0.11371774 0.1661586  0.93428604]]]


### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [21]:
### [your code here]

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i, j, k] == d_min:
                f[i, j, k] = 0
            elif d[i, j, k] == d_max:
                f[i, j, k] = 100
            elif d[i, j, k] == d_mean:
                f[i, j, k] = 50
            elif d[i, j, k] > d_min and d[i, j, k] < d_mean:
                f[i, j, k] = 25
            elif d[i, j, k] > d_mean and d[i, j, k] < d_max:
                f[i, j, k] = 75

# Print the populated array f
print("Array f:\n", f)

Array f:
 [[[ 75.  75.  25.  75.  75.]
  [ 25.   0.  75.  75.  75.]
  [ 25.  75.  75.  25.  75.]]

 [[100.  75.  25.  25.  75.]
  [ 75.  25.  75.  25.  75.]
  [ 25.  75.  25.  25.  75.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [22]:
### [your code here]
print("This is D:", d, "\n")
print("This is F:", f, "\n")

This is D: [[[1.58428446 1.60607821 1.0541152  1.74299659 1.78550535]
  [1.2086138  1.02785458 1.87894035 1.53654555 1.74639764]
  [1.33292232 1.70652789 1.71349606 1.25996682 1.72466057]]

 [[1.98846808 1.8129031  1.18944792 1.15129836 1.80673251]
  [1.69630725 1.05006484 1.8508381  1.20884948 1.60758762]
  [1.12933301 1.54091726 1.11371774 1.1661586  1.93428604]]] 

This is F: [[[ 75.  75.  25.  75.  75.]
  [ 25.   0.  75.  75.  75.]
  [ 25.  75.  75.  25.  75.]]

 [[100.  75.  25.  25.  75.]
  [ 75.  25.  75.  25.  75.]
  [ 25.  75.  25.  25.  75.]]] 



### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [24]:
### [your code here]
g = np.empty(d.shape, dtype=object)


for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i, j, k] == d_min:
                g[i, j, k] = "A"   # Assign label "A" for d_min
            elif d[i, j, k] == d_max:
                g[i, j, k] = "E"   # Assign label "E" for d_max
            elif d[i, j, k] == d_mean:
                g[i, j, k] = "C"   # Assign label "C" for d_mean
            elif d[i, j, k] > d_min and d[i, j, k] < d_mean:
                g[i, j, k] = "B"   # Assign label "B" for values between d_min and d_mean
            elif d[i, j, k] > d_mean and d[i, j, k] < d_max:
                g[i, j, k] = "D"   # Assign label "D" for values between d_mean and d_max

# Print the populated array f
print("Array f with string labels:\n", g)


Array f with string labels:
 [[['D' 'D' 'B' 'D' 'D']
  ['B' 'A' 'D' 'D' 'D']
  ['B' 'D' 'D' 'B' 'D']]

 [['E' 'D' 'B' 'B' 'D']
  ['D' 'B' 'D' 'B' 'D']
  ['B' 'D' 'B' 'B' 'D']]]
