# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [2]:
pip install numpy 

     ---------------------------------------- 0.0/60.8 kB ? eta -:--:--
     ------ --------------------------------- 10.2/60.8 kB ? eta -:--:--
     ------------------- ------------------ 30.7/60.8 kB 262.6 kB/s eta 0:00:01
     ------------------------------- ------ 51.2/60.8 kB 375.8 kB/s eta 0:00:01
     -------------------------------------- 60.8/60.8 kB 404.8 kB/s eta 0:00:00
   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
    --------------------------------------- 0.2/12.9 MB 3.5 MB/s eta 0:00:04
   -- ------------------------------------- 0.8/12.9 MB 8.2 MB/s eta 0:00:02
   ------ --------------------------------- 2.1/12.9 MB 14.7 MB/s eta 0:00:01
   --------- ------------------------------ 3.0/12.9 MB 17.3 MB/s eta 0:00:01
   ----------- ---------------------------- 3.6/12.9 MB 15.2 MB/s eta 0:00:01
   --------------- ------------------------ 4.9/12.9 MB 17.3 MB/s eta 0:00:01
   ------------------ --------------------- 5.9/12.9 MB 19.8 MB/s eta 0:00:01
 

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [5]:
### [your code here]

import numpy as np 



### 2. Print the NUMPY version and the configuration.


In [ ]:
### [your code here]

# always 

import numpy as np

import numpy as np

# Print NumPy version
print("NumPy Version:", np.__version__)

# Print NumPy configuration
np.show_config()

NumPy Version: 2.2.3
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30158",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.12",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30158",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.28",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-3gfa2f0z/cp311-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/includ

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [21]:
### [your code here]

a = np.random.random((2, 3, 5))
a

array([[[0.50788513, 0.65665293, 0.21868339, 0.83983214, 0.85186942],
        [0.81592989, 0.53816361, 0.46757717, 0.96872078, 0.94358588],
        [0.5586492 , 0.96374114, 0.29093958, 0.98790934, 0.16036817]],

       [[0.01731177, 0.72202906, 0.44855114, 0.16559893, 0.52281184],
        [0.16640418, 0.29717067, 0.55946491, 0.7509776 , 0.15224743],
        [0.53429428, 0.02908912, 0.93372087, 0.63861595, 0.53672755]]])


### 4. Print a.


In [8]:
### [your code here]
print(a)

[[[0.55998681 0.68354908 0.08746149 0.09997123 0.75717385]
  [0.94382026 0.30094668 0.22138776 0.20533802 0.96790591]
  [0.88019918 0.50226338 0.8241074  0.20847646 0.78567968]]

 [[0.88366845 0.46698761 0.67422763 0.31368471 0.15919094]
  [0.1885593  0.03501778 0.43721709 0.74512978 0.02186433]
  [0.65133102 0.48294102 0.51996781 0.21624486 0.71661252]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [20]:
### [your code here]


b = np.ones([5, 2, 3]) 
b 

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])


### 6. Print b.


In [22]:
### [your code here]

print(b)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [23]:
### [your code here]

print(a.size == b.size)

print(a.size)
print(b.size) 


True
30
30



### 8. Are you able to add a and b? Why or why not?


In [26]:
### [your code here]

print(a.shape == b.shape)



False




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [53]:
### [your code here]
import numpy as np

# Original shape of b is (5, 2, 3)
# change it to (2, 3, 5) like a

# Transpose b to match a's shape (2x3x5)
c = np.transpose(b, axes=(1, 2, 0))

# Check the shape of c                                                                      
print("Shape of c:", c.shape)



Shape of c: (2, 3, 5)



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [50]:
### [your code here]

# add a and c 

d = a + c 

print("shape of d", d.shape)
d

shape of d (2, 3, 5)


array([[[1.60681024, 1.91065071, 1.21374905, 1.50829009, 1.2344018 ],
        [1.67181749, 1.06177377, 1.812884  , 1.72859356, 1.88680755],
        [1.16309122, 1.32013356, 1.91427227, 1.17460228, 1.76492753]],

       [[1.28257251, 1.60791403, 1.82464372, 1.57963687, 1.22544717],
        [1.46336944, 1.80366873, 1.76957951, 1.53541142, 1.42711622],
        [1.32434053, 1.57062101, 1.3745072 , 1.51123331, 1.01390802]]])


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [57]:
### [your code here]

# Print Array a
print("Array a:")
print(a)
# Dont forget \n for clairty and creates a space

print("\nArray d:")
print(d)


Array a:
[[[0.60681024 0.91065071 0.21374905 0.50829009 0.2344018 ]
  [0.67181749 0.06177377 0.812884   0.72859356 0.88680755]
  [0.16309122 0.32013356 0.91427227 0.17460228 0.76492753]]

 [[0.28257251 0.60791403 0.82464372 0.57963687 0.22544717]
  [0.46336944 0.80366873 0.76957951 0.53541142 0.42711622]
  [0.32434053 0.57062101 0.3745072  0.51123331 0.01390802]]]

Array d:
[[[1.60681024 1.91065071 1.21374905 1.50829009 1.2344018 ]
  [1.67181749 1.06177377 1.812884   1.72859356 1.88680755]
  [1.16309122 1.32013356 1.91427227 1.17460228 1.76492753]]

 [[1.28257251 1.60791403 1.82464372 1.57963687 1.22544717]
  [1.46336944 1.80366873 1.76957951 1.53541142 1.42711622]
  [1.32434053 1.57062101 1.3745072  1.51123331 1.01390802]]]



### 12. Multiply a and c. Assign the result to e.


In [52]:
### [your code here]

e = a * c
e

array([[[0.60681024, 0.91065071, 0.21374905, 0.50829009, 0.2344018 ],
        [0.67181749, 0.06177377, 0.812884  , 0.72859356, 0.88680755],
        [0.16309122, 0.32013356, 0.91427227, 0.17460228, 0.76492753]],

       [[0.28257251, 0.60791403, 0.82464372, 0.57963687, 0.22544717],
        [0.46336944, 0.80366873, 0.76957951, 0.53541142, 0.42711622],
        [0.32434053, 0.57062101, 0.3745072 , 0.51123331, 0.01390802]]])



### 13. Does e equal to a? Why or why not?


In [ ]:
### [your code here]


# Compare if e is equal to a
print(np.array_equal(a, e))  # True if 'a' and 'e' are identical


#Shape: They have the same dimensions both arrays are 2x3x5.
#Values: All corresponding elements are equal (e.g., a[0,0,0] == e[0,0,0], a[1,2,4] == e[1,2,4]



True




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [59]:
### [your code here]

# Assuming d is already defined

# Calculate the max, min, and mean values of d
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)


print("max value in d:", d_max)
print("min value in d:", d_min)
print("mean value in d:", d_mean)

max value in d: 1.914272273710373
min value in d: 1.013908020475434
mean value in d: 1.5095591608143117



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [61]:
### [your code here]   

# Create an empty array with the same shape as d
f = np.empty(d.shape)

# Print the shape of the new array f
print("Shape of f:", f.shape) 

Shape of f: (2, 3, 5)





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [64]:
### [your code here]



# assign 75 to the corresponding value in f. 

# Get the min, mean, and max of d
d_min = np.min(d)
d_mean = np.mean(d)
d_max = np.max(d)

# Create an empty array f with the same shape as d
f = np.empty_like(d)

# Populate f based on the given conditions
f[(d > d_min) & (d < d_mean)] = 25
f[(d > d_mean) & (d < d_max)] = 75
f[d == d_mean] = 50
f[d == d_min] = 0
f[d == d_max] = 100

# Print the results
print("Array d:")
print(d)
print("\nArray f:")
print(f)

Array d:
[[[1.60681024 1.91065071 1.21374905 1.50829009 1.2344018 ]
  [1.67181749 1.06177377 1.812884   1.72859356 1.88680755]
  [1.16309122 1.32013356 1.91427227 1.17460228 1.76492753]]

 [[1.28257251 1.60791403 1.82464372 1.57963687 1.22544717]
  [1.46336944 1.80366873 1.76957951 1.53541142 1.42711622]
  [1.32434053 1.57062101 1.3745072  1.51123331 1.01390802]]]

Array f:
[[[ 75.  75.  25.  25.  25.]
  [ 75.  25.  75.  75.  75.]
  [ 25.  25. 100.  25.  75.]]

 [[ 25.  75.  75.  75.  25.]
  [ 25.  75.  75.  75.  25.]
  [ 25.  75.  25.  75.   0.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [ ]:
### [your code here]
# Print the d and f arrays
print("Array d:")
print(d)

print("\nArray f:")
print(f)

#If d is greater than d_min and smaller than d_mean, it should be assigned 25.
#If d is greater than d_mean and smaller than d_max, it should be assigned 75.
#If d equals d_mean, it should be 50.

 # Close to what i expected but not quite


Array d:
[[[1.60681024 1.91065071 1.21374905 1.50829009 1.2344018 ]
  [1.67181749 1.06177377 1.812884   1.72859356 1.88680755]
  [1.16309122 1.32013356 1.91427227 1.17460228 1.76492753]]

 [[1.28257251 1.60791403 1.82464372 1.57963687 1.22544717]
  [1.46336944 1.80366873 1.76957951 1.53541142 1.42711622]
  [1.32434053 1.57062101 1.3745072  1.51123331 1.01390802]]]

Array f:
[[[ 75.  75.  25.  25.  25.]
  [ 75.  25.  75.  75.  75.]
  [ 25.  25. 100.  25.  75.]]

 [[ 25.  75.  75.  75.  25.]
  [ 25.  75.  75.  75.  25.]
  [ 25.  75.  25.  75.   0.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [79]:
# Define the function to convert numbers to string labels
# if elif method
# use return


def get_label(value):
    if value == 0:
        return "A"
    elif value == 25:
        return "B"
    elif value == 50:
        return "C"
    elif value == 75:
        return "D"
    elif value == 100:
        return "E"
    return None

# f array
# Create the 3D list with integer values (replace them with the corresponding labels)
array = [
    [
        [75, 75, 75, 25, 75],
        [75, 75, 25, 25, 25],
        [75, 25, 75, 75, 75]
    ],
    [
        [25, 25, 25, 25, 100],
        [75, 75, 75, 75, 75],
        [25, 75, 0, 75, 75]
    ]
]

# Convert the array values to string labels
labeled_array = [[[get_label(value) for value in row] for row in matrix] for matrix in array]

# Output the labeled array
for matrix in labeled_array:
    for row in matrix:
        print(row)



['D', 'D', 'D', 'B', 'D']
['D', 'D', 'B', 'B', 'B']
['D', 'B', 'D', 'D', 'D']
['B', 'B', 'B', 'B', 'E']
['D', 'D', 'D', 'D', 'D']
['B', 'D', 'A', 'D', 'D']
