# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
### [your code here]
import numpy as np





### 2. Print the NUMPY version and the configuration.


In [2]:
### [your code here]


print("NumPy Version: ",np.version.version)


NumPy Version:  1.23.5


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [3]:
### [your code here]
a = np.random.rand(2,3,5)



### 4. Print a.


In [4]:
### [your code here]
a

array([[[0.47041945, 0.26701965, 0.69191172, 0.45322405, 0.8613023 ],
        [0.45738351, 0.05629229, 0.99060241, 0.46817383, 0.80825176],
        [0.17037358, 0.80930108, 0.69714712, 0.34917215, 0.58395127]],

       [[0.0994892 , 0.76319404, 0.56291095, 0.9500218 , 0.53167461],
        [0.75589127, 0.96611062, 0.93105762, 0.21958591, 0.99406709],
        [0.17319947, 0.57736346, 0.47957232, 0.20456179, 0.01572689]]])

### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [5]:
### [your code here]
b = np.ones((5,2,3),)



### 6. Print b.


In [6]:
### [your code here]
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])


### 7. Do a and b have the same size? How do you prove that in Python code?


In [7]:
### [your code here]
print(a.size == b.size)


True



### 8. Are you able to add a and b? Why or why not?


In [8]:
### [your code here]
##a_b = a+b

# we cannot add them because they have different shapes 
#operands could not be broadcast together with shapes (2,3,5) (5,2,3) 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [9]:
### [your code here]

c = np.transpose(b,(1,2,0))
c
print(c.shape)

(2, 3, 5)



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [10]:
### [your code here]
d =  a + c
d

array([[[1.47041945, 1.26701965, 1.69191172, 1.45322405, 1.8613023 ],
        [1.45738351, 1.05629229, 1.99060241, 1.46817383, 1.80825176],
        [1.17037358, 1.80930108, 1.69714712, 1.34917215, 1.58395127]],

       [[1.0994892 , 1.76319404, 1.56291095, 1.9500218 , 1.53167461],
        [1.75589127, 1.96611062, 1.93105762, 1.21958591, 1.99406709],
        [1.17319947, 1.57736346, 1.47957232, 1.20456179, 1.01572689]]])


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [16]:
### [your code here]
print('array a\n' ,a)

print('array d \n' ,d)
# nothing change except it added one to every elements 


array a
 [[[0.53132689 0.00423134 0.65010724 0.9867978  0.69092959]
  [0.08436287 0.61680177 0.06151468 0.15796471 0.18481078]
  [0.4583665  0.01628634 0.25347925 0.42785481 0.10516597]]

 [[0.93533328 0.28622853 0.24046432 0.29606169 0.14688571]
  [0.8992071  0.61416002 0.90631764 0.597661   0.65419718]
  [0.34086404 0.89240062 0.09047047 0.22998482 0.18157456]]]
array d 
 [[[1.53132689 1.00423134 1.65010724 1.9867978  1.69092959]
  [1.08436287 1.61680177 1.06151468 1.15796471 1.18481078]
  [1.4583665  1.01628634 1.25347925 1.42785481 1.10516597]]

 [[1.93533328 1.28622853 1.24046432 1.29606169 1.14688571]
  [1.8992071  1.61416002 1.90631764 1.597661   1.65419718]
  [1.34086404 1.89240062 1.09047047 1.22998482 1.18157456]]]



### 12. Multiply a and c. Assign the result to e.


In [12]:
### [your code here]
e = a * c 
e

array([[[0.47041945, 0.26701965, 0.69191172, 0.45322405, 0.8613023 ],
        [0.45738351, 0.05629229, 0.99060241, 0.46817383, 0.80825176],
        [0.17037358, 0.80930108, 0.69714712, 0.34917215, 0.58395127]],

       [[0.0994892 , 0.76319404, 0.56291095, 0.9500218 , 0.53167461],
        [0.75589127, 0.96611062, 0.93105762, 0.21958591, 0.99406709],
        [0.17319947, 0.57736346, 0.47957232, 0.20456179, 0.01572689]]])



### 13. Does e equal to a? Why or why not?


In [13]:
### [your code here]

# e is equal to a because we multiply each elements ia a by 1, so nothing change 



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [ ]:
### [your code here]

d_max = np.max(d)  
d_min = np.min(d)
print('This is the max', d_max)
print('This is the min' , d_min)

This is the max 1.9940670895809396
This is the min 1.0157268936925585



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [18]:
### [your code here]
shape = (2,3,5)
f= np.empty(shape)
print(f)

[[[0.53132689 0.00423134 0.65010724 0.9867978  0.69092959]
  [0.08436287 0.61680177 0.06151468 0.15796471 0.18481078]
  [0.4583665  0.01628634 0.25347925 0.42785481 0.10516597]]

 [[0.93533328 0.28622853 0.24046432 0.29606169 0.14688571]
  [0.8992071  0.61416002 0.90631764 0.597661   0.65419718]
  [0.34086404 0.89240062 0.09047047 0.22998482 0.18157456]]]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [23]:
### [your code here]
d_mean = np.mean(d)

print('This is the mean', d_mean)
print('This is the max', d_max)
print('This is the min', d_min)
print(d)
for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i][j])):
            value = d[i][j][k]
            if value == d_min:
                f[i][j][k] = 0
            elif value == d_mean:
                f[i][j][k] = 50
            elif value == d_max:
                f[i][j][k] = 100
            elif d_min < value < d_mean:
                f[i][j][k] = 25
            elif d_mean < value < d_max:
                f[i][j][k] = 75

print(f)   


This is the mean 1.4180603831788086
This is the max 1.9867977975274058
This is the min 1.0042313386948716
[[[1.53132689 1.00423134 1.65010724 1.9867978  1.69092959]
  [1.08436287 1.61680177 1.06151468 1.15796471 1.18481078]
  [1.4583665  1.01628634 1.25347925 1.42785481 1.10516597]]

 [[1.93533328 1.28622853 1.24046432 1.29606169 1.14688571]
  [1.8992071  1.61416002 1.90631764 1.597661   1.65419718]
  [1.34086404 1.89240062 1.09047047 1.22998482 1.18157456]]]
[[[ 75.   0.  75. 100.  75.]
  [ 25.  75.  25.  25.  25.]
  [ 75.  25.  25.  75.  25.]]

 [[ 75.  25.  25.  25.  25.]
  [ 75.  75.  75.  75.  75.]
  [ 25.  75.  25.  25.  25.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [24]:
### [your code here]
print (d)
print (f)

[[[1.53132689 1.00423134 1.65010724 1.9867978  1.69092959]
  [1.08436287 1.61680177 1.06151468 1.15796471 1.18481078]
  [1.4583665  1.01628634 1.25347925 1.42785481 1.10516597]]

 [[1.93533328 1.28622853 1.24046432 1.29606169 1.14688571]
  [1.8992071  1.61416002 1.90631764 1.597661   1.65419718]
  [1.34086404 1.89240062 1.09047047 1.22998482 1.18157456]]]
[[[ 75.   0.  75. 100.  75.]
  [ 25.  75.  25.  25.  25.]
  [ 75.  25.  25.  75.  25.]]

 [[ 75.  25.  25.  25.  25.]
  [ 75.  75.  75.  75.  75.]
  [ 25.  75.  25.  25.  25.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [26]:
f_s = np.empty(d.shape , dtype=str)

In [35]:
### [your code here]
f_s[f==0] = 'A'
f_s[f==25] = 'B'
f_s[f==50] = 'C'
f_s[f==75] = 'D'
f_s[f==100] = 'E'


f_s

array([[['D', 'A', 'D', 'E', 'D'],
        ['B', 'D', 'B', 'B', 'B'],
        ['D', 'B', 'B', 'D', 'B']],

       [['D', 'B', 'B', 'B', 'B'],
        ['D', 'D', 'D', 'D', 'D'],
        ['B', 'D', 'B', 'B', 'B']]], dtype='<U1')