In [1]:
#1. Import the NUMPY package under the name np.

import numpy as np

#2. Print the NUMPY version and the configuration.

print(np.__version__)


1.26.4


In [10]:
#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

import random
a = np.random.random_sample((2, 3, 5))


In [11]:

#4. Print a.

print(a)

#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

b = np.ones((5, 2, 3))

#6. Print b.
print(b)

[[[0.91348495 0.5109975  0.8441896  0.929895   0.04111266]
  [0.67477574 0.4772293  0.88451976 0.68509855 0.81868317]
  [0.26713979 0.21364707 0.49594592 0.94623803 0.86428632]]

 [[0.13090927 0.7560045  0.02343979 0.78367061 0.15862272]
  [0.26376104 0.80576248 0.34197982 0.68351867 0.1103316 ]
  [0.53309636 0.60835478 0.75403052 0.27273582 0.3209284 ]]]
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [12]:
#7. Do a and b have the same size? How do you prove that in Python code?

if a.size == b.size:
    print("yes")
else:
    print("no")


yes


#8. Are you able to add a and b? Why or why not?

No, they are different shapes


In [23]:
#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

c = np.transpose(b)


#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?
c_transposed = np.transpose(c, (1, 0, 2)) 
d = a +  c_transposed


In [27]:



#12. Multiply a and c. Assign the result to e.

e = a * c_transposed
c = c_transposed




In [32]:

 

#13. Does e equal to a? Why or why not?

if np.array_equal(e, a):
    print("Yes")
else:
    print("No")


Yes


In [35]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(d_max)
print(d_min)
print(d_mean)

1.9462380348597732
1.0234397938475737
1.5371463245378527


In [36]:

#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

f = np.empty_like(d)


In [38]:
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i, j, k] > d_min and d[i, j, k] < d_mean:
                f[i, j, k] = 25
            elif d[i, j, k] > d_mean and d[i, j, k] < d_max:
                f[i, j, k] = 75
            elif d[i, j, k] == d_mean:
                f[i, j, k] = 50
            elif d[i, j, k] == d_min:
                f[i, j, k] = 0
            elif d[i, j, k] == d_max:
                f[i, j, k] = 100

print("Unique values in f:", np.unique(f))


Unique values in f: [  0.  25.  75. 100.]


#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""

#[your code here]


In [39]:
print(d)
print(f)


[[[1.91348495 1.5109975  1.8441896  1.929895   1.04111266]
  [1.67477574 1.4772293  1.88451976 1.68509855 1.81868317]
  [1.26713979 1.21364707 1.49594592 1.94623803 1.86428632]]

 [[1.13090927 1.7560045  1.02343979 1.78367061 1.15862272]
  [1.26376104 1.80576248 1.34197982 1.68351867 1.1103316 ]
  [1.53309636 1.60835478 1.75403052 1.27273582 1.3209284 ]]]
[[[ 75.  25.  75.  75.  25.]
  [ 75.  25.  75.  75.  75.]
  [ 25.  25.  25. 100.  75.]]

 [[ 25.  75.   0.  75.  25.]
  [ 25.  75.  25.  75.  25.]
  [ 25.  75.  75.  25.  25.]]]


#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""

In [40]:
label_map = {0: 'A', 25: 'B', 50: 'C', 75: 'D', 100: 'E'}

f = np.empty_like(d, dtype=str)

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i, j, k] > d_min and d[i, j, k] < d_mean:
                f[i, j, k] = label_map[25]
            elif d[i, j, k] > d_mean and d[i, j, k] < d_max:
                f[i, j, k] = label_map[75]
            elif d[i, j, k] == d_mean:
                f[i, j, k] = label_map[50]
            elif d[i, j, k] == d_min:
                f[i, j, k] = label_map[0]
            elif d[i, j, k] == d_max:
                f[i, j, k] = label_map[100]

In [41]:
print(f)

[[['D' 'B' 'D' 'D' 'B']
  ['D' 'B' 'D' 'D' 'D']
  ['B' 'B' 'B' 'E' 'D']]

 [['B' 'D' 'A' 'D' 'B']
  ['B' 'D' 'B' 'D' 'B']
  ['B' 'D' 'D' 'B' 'B']]]
