# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
### [your code here]
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [3]:
### [your code here]
print(np.__version__)

# Print NumPy configuration
np.show_config()

1.24.3
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/R/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/R/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/R/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/R/anaconda3\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/R/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/R/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/R/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/R/anaconda3\\Library\\include']
Supported

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [4]:
### [your code here]
a = np.random.random((2, 3, 5))
print(a)

[[[0.68969381 0.22268912 0.97799376 0.42351374 0.39780259]
  [0.96327845 0.26295311 0.20990041 0.35455907 0.19635142]
  [0.68223297 0.70961931 0.17439086 0.70267528 0.52303701]]

 [[0.5520434  0.03142683 0.99272793 0.12862603 0.01915772]
  [0.78019738 0.87670073 0.34836149 0.32259399 0.06689156]
  [0.64757714 0.59555015 0.87614697 0.80954382 0.30588421]]]


In [5]:
a = np.random.rand(2, 3, 5)
print(a)

[[[0.3406785  0.06702206 0.422213   0.05959859 0.35536704]
  [0.75330435 0.23107744 0.68383959 0.56494979 0.56730165]
  [0.46641587 0.71829345 0.13480678 0.7412934  0.17666357]]

 [[0.20797848 0.60300107 0.03129519 0.3856378  0.10992449]
  [0.68726108 0.9841687  0.68080466 0.80694393 0.43993041]
  [0.57175163 0.86460607 0.00445044 0.44495053 0.91932154]]]


In [6]:
a = np.random.randn(2, 3, 5)
print(a)

[[[-1.33372631 -0.12498835 -0.18538791 -0.44617081  0.19535807]
  [ 0.37894504  0.60925635 -0.75655296 -0.17534865  1.17173756]
  [ 1.5948379  -1.72292379  0.95927531 -1.65974282  1.99355143]]

 [[-0.40854561  0.65067227  1.03118057 -1.00445565 -0.94374564]
  [ 0.0982821   0.58783     2.03829835  1.24375535  0.62529715]
  [-0.63530782 -1.74161572 -0.26718194 -1.92670015 -0.72089535]]]


In [16]:
a = np.random.randint(0, 100, (2, 3, 5))


### 4. Print a.


In [17]:
### [your code here]
print(a)

[[[82 53 54 12  6]
  [97 21  1 13 48]
  [63 23 22  3 51]]

 [[39 57 23 93 27]
  [88 37 34 71 62]
  [24 14 96  2 27]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [18]:
### [your code here]

b = np.ones((5, 2, 3))



### 6. Print b.


In [19]:
### [your code here]
print(b)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [20]:
### [your code here]
#have diffrent shape but the same size
print("Size of a:", a.size)
print("Size of b:", b.size)

Size of a: 30
Size of b: 30



### 8. Are you able to add a and b? Why or why not?


In [21]:
### [your code here]
# No, because they have difftent shape
c= a+b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [22]:
### [your code here]
c = b.reshape(2, 3, 5)


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [23]:
### [your code here]
# because now have the same shape
d = a + c  
print(d)

[[[83. 54. 55. 13.  7.]
  [98. 22.  2. 14. 49.]
  [64. 24. 23.  4. 52.]]

 [[40. 58. 24. 94. 28.]
  [89. 38. 35. 72. 63.]
  [25. 15. 97.  3. 28.]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [24]:
### [your code here]
#d is 1 unit greater than a. This is because d was adding by array of ones. 
print("Array a:\n", a)
print("\nArray d:\n", d)


Array a:
 [[[82 53 54 12  6]
  [97 21  1 13 48]
  [63 23 22  3 51]]

 [[39 57 23 93 27]
  [88 37 34 71 62]
  [24 14 96  2 27]]]

Array d:
 [[[83. 54. 55. 13.  7.]
  [98. 22.  2. 14. 49.]
  [64. 24. 23.  4. 52.]]

 [[40. 58. 24. 94. 28.]
  [89. 38. 35. 72. 63.]
  [25. 15. 97.  3. 28.]]]



### 12. Multiply a and c. Assign the result to e.


In [25]:
### [your code here]
e = a * c
print(e)

[[[82. 53. 54. 12.  6.]
  [97. 21.  1. 13. 48.]
  [63. 23. 22.  3. 51.]]

 [[39. 57. 23. 93. 27.]
  [88. 37. 34. 71. 62.]
  [24. 14. 96.  2. 27.]]]




### 13. Does e equal to a? Why or why not?


In [31]:
### [your code here]
#Yes, e equals a, where c is array of ones.




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [26]:
### [your code here]

d_max = np.max(d)    
d_min = np.min(d)    
d_mean = np.mean(d)  

print("Maximum:", d_max)
print("Minimum:", d_min)
print("Mean:", d_mean)

Maximum: 98.0
Minimum: 2.0
Mean: 42.43333333333333



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [35]:
### [your code here]
f = np.empty(d.shape)
print(f.shape)


(2, 3, 5)





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [28]:
### [your code here]
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i, j, k] == d_min:
                f[i, j, k] = 0
            elif d[i, j, k] == d_max:
                f[i, j, k] = 100
            elif d_min < d[i, j, k] < d_mean:
                f[i, j, k] = 25
            elif d_mean < d[i, j, k] < d_max:
                f[i, j, k] = 75
            elif d[i, j, k] == d_mean:
                f[i, j, k] = 50


print(f)

[[[ 75.  75.  75.  25.  25.]
  [100.  25.   0.  25.  75.]
  [ 75.  25.  25.  25.  75.]]

 [[ 25.  75.  25.  75.  25.]
  [ 75.  25.  25.  75.  75.]
  [ 25.  25.  75.  25.  25.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [31]:
### [your code here]
#yes as excpected
print("Array d:")
print(d)
print("\nArray f:",f)

[[[83. 54. 55. 13.  7.]
  [98. 22.  2. 14. 49.]
  [64. 24. 23.  4. 52.]]

 [[40. 58. 24. 94. 28.]
  [89. 38. 35. 72. 63.]
  [25. 15. 97.  3. 28.]]]

 [[[ 75.  75.  75.  25.  25.]
  [100.  25.   0.  25.  75.]
  [ 75.  25.  25.  25.  75.]]

 [[ 25.  75.  25.  75.  25.]
  [ 75.  25.  25.  75.  75.]
  [ 25.  25.  75.  25.  25.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [36]:
### [your code here]
f = np.empty(d.shape, dtype='object')

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i, j, k] == d_min:
                f[i, j, k] = "C"  
            elif d[i, j, k] == d_max:
                f[i, j, k] = "E" 
            elif d_min < d[i, j, k] < d_mean:
                f[i, j, k] = "B"  
            elif d_mean < d[i, j, k] < d_max:
                f[i, j, k] = "D" 
            elif d[i, j, k] == d_mean:
                f[i, j, k] = "A"  

print("Array d:")
print(d)

print("\nArray f:")
print(f)

Array d:
[[[83. 54. 55. 13.  7.]
  [98. 22.  2. 14. 49.]
  [64. 24. 23.  4. 52.]]

 [[40. 58. 24. 94. 28.]
  [89. 38. 35. 72. 63.]
  [25. 15. 97.  3. 28.]]]

Array f:
[[['D' 'D' 'D' 'B' 'B']
  ['E' 'B' 'C' 'B' 'D']
  ['D' 'B' 'B' 'B' 'D']]

 [['B' 'D' 'B' 'D' 'B']
  ['D' 'B' 'B' 'D' 'D']
  ['B' 'B' 'D' 'B' 'B']]]
