# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
### [your code here]
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [2]:
### [your code here]
print("Numpy Version ", np.__version__)
np.show_config()

Numpy Version  1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/anaconda3/envs/cs224n/include
    lib directory: /opt/anaconda3/envs/cs224n/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 CORE2 MAX_THREADS=128
    pc file directory: /opt/anaconda3/envs/cs224n/lib/pkgconfig
    version: 0.3.21
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep4429404432
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -march=core2, -mtune=haswell, -mssse3, -ftree-vectorize, -fPIC, -fPIE, -fstack-protector-strong,
      -O2, -pipe, -isystem, /opt/anaconda3/envs/cs224n/include, -fdebug-prefix-map=/var/folders/c_/qfmhj66j0tn016nkx_th4hxm0000gp/T/abs_b7iptlxgej/croot/numpy_and_numpy_base_1708638

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [3]:
### [your code here]
a1 = np.random.random((2,3,5))
a1

array([[[0.39875934, 0.30331461, 0.0172138 , 0.8007775 , 0.48560347],
        [0.26215903, 0.85726059, 0.15479209, 0.00298196, 0.26580418],
        [0.78817659, 0.89652987, 0.03340634, 0.66233332, 0.54025362]],

       [[0.82547383, 0.76291373, 0.49092206, 0.97906443, 0.48142031],
        [0.94514108, 0.38226338, 0.1032817 , 0.48102475, 0.15098888],
        [0.21389749, 0.1086068 , 0.4184716 , 0.62299804, 0.49507971]]])

In [4]:
a = np.random.randint(1,100 , size=(2,3,5))
a

array([[[ 4, 41, 44, 55, 66],
        [26, 35, 69, 42, 65],
        [98, 12, 19, 90, 35]],

       [[30, 10, 77, 42, 19],
        [87, 42, 29,  6, 72],
        [ 4, 52, 69, 53, 74]]])

In [5]:
a3 = np.random.randn(2,3,5)
a3

array([[[-1.80884703, -0.30025219, -1.69032752, -2.30232432,
          0.69578948],
        [-0.38315029,  2.1096043 ,  1.40593438, -3.90387542,
          0.83438954],
        [-0.21852345,  0.65029013,  1.71102319, -0.8712754 ,
         -0.0957882 ]],

       [[ 0.28883363, -0.56764991, -1.3030174 , -1.35016891,
         -0.14482682],
        [ 0.89229901, -1.59166946,  0.42283163,  0.23303898,
         -0.7030351 ],
        [-0.80033825, -0.42129792, -0.20217123, -0.97075134,
         -0.28418562]]])


### 4. Print a.


In [6]:
### [your code here]
a

array([[[ 4, 41, 44, 55, 66],
        [26, 35, 69, 42, 65],
        [98, 12, 19, 90, 35]],

       [[30, 10, 77, 42, 19],
        [87, 42, 29,  6, 72],
        [ 4, 52, 69, 53, 74]]])

### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [7]:
### [your code here]
b = np.ones((5,2,3))



### 6. Print b.


In [8]:
### [your code here]
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])


### 7. Do a and b have the same size? How do you prove that in Python code?


In [9]:
### [your code here]
a.shape == b.shape

False


### 8. Are you able to add a and b? Why or why not?
NO, we can't because arrays a and b have different shapes.

In [10]:
### [your code here]
a + b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [11]:
### [your code here]
c = b.reshape(2,3,5)


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?
works because we reshaped c to match the shape of a

In [12]:
### [your code here]
print("Works because we reshaped c to match the shape of a \n")
d = a + c
d

Works because we reshaped c to match the shape of a 



array([[[ 5., 42., 45., 56., 67.],
        [27., 36., 70., 43., 66.],
        [99., 13., 20., 91., 36.]],

       [[31., 11., 78., 43., 20.],
        [88., 43., 30.,  7., 73.],
        [ 5., 53., 70., 54., 75.]]])


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
- Each element in d is exactly 1 unit larger than the corresponding element in a

In [13]:
### [your code here]
print("Each element in d is exactly 1 unit larger than the corresponding element in a.")
print("\nArray a:\n",a)
print("\nArray d:\n",d)


Each element in d is exactly 1 unit larger than the corresponding element in a.

Array a:
 [[[ 4 41 44 55 66]
  [26 35 69 42 65]
  [98 12 19 90 35]]

 [[30 10 77 42 19]
  [87 42 29  6 72]
  [ 4 52 69 53 74]]]

Array d:
 [[[ 5. 42. 45. 56. 67.]
  [27. 36. 70. 43. 66.]
  [99. 13. 20. 91. 36.]]

 [[31. 11. 78. 43. 20.]
  [88. 43. 30.  7. 73.]
  [ 5. 53. 70. 54. 75.]]]



### 12. Multiply a and c. Assign the result to e.


In [14]:
### [your code here]
e = a * c



### 13. Does e equal to a? Why or why not?


In [15]:
### [your code here]
print("\nYes, because multiply any number by 1 keeps the same.")
print(np.array_equal(a, e))



Yes, because multiply any number by 1 keeps the same.
True




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [16]:
### [your code here]
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(" Max:", d_max)
print(" Min:", d_min)
print(" Mean:", d_mean)

 Max: 99.0
 Min: 5.0
 Mean: 46.56666666666667



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [17]:
### [your code here]
f = np.empty((2,3,5))




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [18]:
f

array([[[ 5., 42., 45., 56., 67.],
        [27., 36., 70., 43., 66.],
        [99., 13., 20., 91., 36.]],

       [[31., 11., 78., 43., 20.],
        [88., 43., 30.,  7., 73.],
        [ 5., 53., 70., 54., 75.]]])

In [19]:
d


array([[[ 5., 42., 45., 56., 67.],
        [27., 36., 70., 43., 66.],
        [99., 13., 20., 91., 36.]],

       [[31., 11., 78., 43., 20.],
        [88., 43., 30.,  7., 73.],
        [ 5., 53., 70., 54., 75.]]])

In [ ]:
### [your code here]
for i in range(len(d)):  
    for j in range(len(d[i])):  
        for k in range(len(d[i][j])):  
            ind = d[i][j][k] 

            if ind == d_max:  
                f[i][j][k] = 100
            elif d_mean < ind < d_max:  
                f[i][j][k] = 75
            elif ind == d_mean:  
                f[i][j][k] = 50
            elif d_min < ind < d_mean:  
                f[i][j][k] = 25
            elif ind == d_min:  
                f[i][j][k] = 0

print(f)

[[[  0.  25.  25.  75.  75.]
  [ 25.  25.  75.  25.  75.]
  [100.  25.  25.  75.  25.]]

 [[ 25.  25.  75.  25.  25.]
  [ 75.  25.  25.  25.  75.]
  [  0.  75.  75.  75.  75.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [25]:
### [your code here]
print("Array d:\n",d)
print("\nArray f:\n",f)

Array d:
 [[[ 5. 42. 45. 56. 67.]
  [27. 36. 70. 43. 66.]
  [99. 13. 20. 91. 36.]]

 [[31. 11. 78. 43. 20.]
  [88. 43. 30.  7. 73.]
  [ 5. 53. 70. 54. 75.]]]

Array f:
 [[[  0.  25.  25.  75.  75.]
  [ 25.  25.  75.  25.  75.]
  [100.  25.  25.  75.  25.]]

 [[ 25.  25.  75.  25.  25.]
  [ 75.  25.  25.  25.  75.]
  [  0.  75.  75.  75.  75.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [32]:
f2 = np.empty(d.shape, dtype=str)  
f2

array([[['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']],

       [['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']]], dtype='<U1')

In [35]:
### [your code here]
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            ind = d[i, j, k]
            if ind == d_max:
                f2[i, j, k] = "E"
            elif d_mean < ind < d_max:
                f2[i, j, k] = "D"
            elif ind == d_mean:
                f2[i, j, k] = "C"
            elif d_min < ind < d_mean:
                f2[i, j, k] = "B"
            elif ind == d_min:
                f2[i, j, k] = "A"

print(f2)

[[['A' 'B' 'B' 'D' 'D']
  ['B' 'B' 'D' 'B' 'D']
  ['E' 'B' 'B' 'D' 'B']]

 [['B' 'B' 'D' 'B' 'B']
  ['D' 'B' 'B' 'B' 'D']
  ['A' 'D' 'D' 'D' 'D']]]
