# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [6]:
### [your code here]
import numpy as np 



### 2. Print the NUMPY version and the configuration.


In [8]:
### [your code here]
np.__version__
np.show_config()


Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/anaconda3/include
    lib directory: /opt/anaconda3/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 VORTEX MAX_THREADS=128
    pc file directory: /opt/anaconda3/lib/pkgconfig
    version: 0.3.21
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep4347739648
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -ftree-vectorize, -fPIC, -fPIE, -fstack-protector-strong, -O2, -pipe, -isystem,
      /opt/anaconda3/include, -fdebug-prefix-map=/var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_a51i_mbs7m/croot/numpy_and_numpy_base_1708638620867/work=/usr/local/src/conda/numpy-base-1.26.4,
      -fdebug-prefix-map=/opt/anaconda3=/usr/local/src/c

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [22]:
### [your code here]
a = np.random.rand(8, 4, 1)
### 
a = np.random.random((8, 4, 1))
###
a = np.random.randn(8, 4, 1)


### 4. Print a.


In [24]:
### [your code here]
print(a)

[[[-0.09168485]
  [ 0.3635068 ]
  [ 1.39163723]
  [-1.13491287]]

 [[-0.39535515]
  [-2.02311138]
  [-0.34148563]
  [-0.82559484]]

 [[ 0.11759468]
  [ 0.40601612]
  [ 1.91801641]
  [ 0.57866866]]

 [[ 1.40130065]
  [-0.18733754]
  [-0.94377161]
  [-0.2492794 ]]

 [[-0.69226107]
  [ 1.47591292]
  [ 0.62466964]
  [ 0.95657027]]

 [[-0.2041672 ]
  [-0.14353093]
  [ 1.07751393]
  [ 1.21510577]]

 [[ 0.11866381]
  [ 0.73091329]
  [-1.15280628]
  [ 0.15970445]]

 [[ 1.5486289 ]
  [-0.44609174]
  [ 0.72708673]
  [-1.1466681 ]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [18]:
### [your code here]
b = np.ones((5, 2, 3))


### 6. Print b.


In [20]:
### [your code here]
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [26]:
### [your code here]

# Create the arrays
a = np.random.rand(8, 4, 1)
b = np.ones((5, 2, 3))

# Check if a and b have the same size
same_size = a.size == b.size

# Print the result
print("Do a and b have the same size?", same_size)


Do a and b have the same size? False



### 8. Are you able to add a and b? Why or why not?


In [30]:
 #Try to add a and b
try:
    c = a + b
    print("Addition successful.")
except ValueError:
    print("Cannot add a and b due to shape mismatch.") 

# So No,cannot add a and b 
# because their shapes are different 
# and their sizes don’t match.

Cannot add a and b due to shape mismatch.




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [32]:
b = np.ones((5 , 2, 3))
c = b.transpose(1,2,0)
print(c)


[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [34]:
### [your code here]
a = np.random.rand(2, 3, 5)
b = np.ones((5, 2, 3)) 
c = b.transpose(1, 2, 0)
d = a + c 

print(d)

[[[1.44193052 1.3237863  1.49009734 1.0445541  1.40997888]
  [1.84449906 1.67057726 1.05407736 1.54519142 1.00737223]
  [1.21448506 1.13948186 1.39973565 1.48444262 1.61342257]]

 [[1.67775191 1.57373731 1.69330629 1.11529353 1.43293298]
  [1.93284362 1.6701106  1.87954842 1.06290544 1.04135073]
  [1.1868263  1.92773578 1.23013307 1.4533722  1.65627445]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [36]:
### [your code here]
print("Array a:")
print(a)

print("/nArray d:")
print(d)

Array a:
[[[0.44193052 0.3237863  0.49009734 0.0445541  0.40997888]
  [0.84449906 0.67057726 0.05407736 0.54519142 0.00737223]
  [0.21448506 0.13948186 0.39973565 0.48444262 0.61342257]]

 [[0.67775191 0.57373731 0.69330629 0.11529353 0.43293298]
  [0.93284362 0.6701106  0.87954842 0.06290544 0.04135073]
  [0.1868263  0.92773578 0.23013307 0.4533722  0.65627445]]]
/nArray d:
[[[1.44193052 1.3237863  1.49009734 1.0445541  1.40997888]
  [1.84449906 1.67057726 1.05407736 1.54519142 1.00737223]
  [1.21448506 1.13948186 1.39973565 1.48444262 1.61342257]]

 [[1.67775191 1.57373731 1.69330629 1.11529353 1.43293298]
  [1.93284362 1.6701106  1.87954842 1.06290544 1.04135073]
  [1.1868263  1.92773578 1.23013307 1.4533722  1.65627445]]]



### 12. Multiply a and c. Assign the result to e.


In [38]:
### [your code here]
e = a * c 

print("Array e:")
print(e)


Array e:
[[[0.44193052 0.3237863  0.49009734 0.0445541  0.40997888]
  [0.84449906 0.67057726 0.05407736 0.54519142 0.00737223]
  [0.21448506 0.13948186 0.39973565 0.48444262 0.61342257]]

 [[0.67775191 0.57373731 0.69330629 0.11529353 0.43293298]
  [0.93284362 0.6701106  0.87954842 0.06290544 0.04135073]
  [0.1868263  0.92773578 0.23013307 0.4533722  0.65627445]]]




### 13. Does e equal to a? Why or why not?


In [42]:
print(np.allclose(a, e)) # This will return True if a and e are the same

# Yes, e equals a because multiplying each element of a by 1 
# (from array c, which contains all ones) 
# leaves the values unchanged.

True




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [44]:
### [your code here]

# Assuming d is already defined as d = a + c
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print("Max value in d:", d_max)
print("Min value in d:", d_min)
print("Mean value in d:", d_mean)

Max value in d: 1.9328436157712598
Min value in d: 1.0073722300912449
Mean value in d: 1.4405918278547027



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [46]:
# Create an empty array f with the same shape as d (2x3x5)
f = np.empty_like(d)

print("Shape of f:", f.shape)


Shape of f: (2, 3, 5)





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [48]:
# Populate f based on the conditions
for i in range(d.shape[0]):  # Iterate over the first dimension (2)
    for j in range(d.shape[1]):  # Iterate over the second dimension (3)
        for k in range(d.shape[2]):  # Iterate over the third dimension (5)
            if d[i, j, k] == d_min:
                f[i, j, k] = 0
            elif d[i, j, k] == d_max:
                f[i, j, k] = 100
            elif d[i, j, k] == d_mean:
                f[i, j, k] = 50
            elif d_min < d[i, j, k] < d_mean:
                f[i, j, k] = 25
            elif d_mean < d[i, j, k] < d_max:
                f[i, j, k] = 75


print(f)

[[[ 75.  25.  75.  25.  25.]
  [ 75.  75.  25.  75.   0.]
  [ 25.  25.  25.  75.  75.]]

 [[ 75.  75.  75.  25.  25.]
  [100.  75.  75.  25.  25.]
  [ 25.  75.  25.  75.  75.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [50]:

# Define d 
d = np.array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
               [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
               [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
              [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
               [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
               [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

# Calculate max, min, and mean for d
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

# Create an empty array f with the same shape as d
f = np.empty_like(d)

# Populate f based on the conditions
for i in range(d.shape[0]):  # Iterate over the first dimension (2)
    for j in range(d.shape[1]):  # Iterate over the second dimension (3)
        for k in range(d.shape[2]):  # Iterate over the third dimension (5)
            if d[i, j, k] == d_min:
                f[i, j, k] = 0
            elif d[i, j, k] == d_max:
                f[i, j, k] = 100
            elif d[i, j, k] == d_mean:
                f[i, j, k] = 50
            elif d_min < d[i, j, k] < d_mean:
                f[i, j, k] = 25
            elif d_mean < d[i, j, k] < d_max:
                f[i, j, k] = 75

# Print d and f to compare
print("Array d:")
print(d)

print("\nArray f:")
print(f)


Array d:
[[[1.85836099 1.67064465 1.62576044 1.40243961 1.88454931]
  [1.75354326 1.69403643 1.36729252 1.61415071 1.12104981]
  [1.72201435 1.1862918  1.87078449 1.7726778  1.88180042]]

 [[1.44747908 1.31673383 1.02000951 1.52218947 1.97066381]
  [1.79129243 1.74983003 1.96028037 1.85166831 1.65450881]
  [1.18068344 1.9587381  1.00656599 1.93402165 1.73514584]]]

Array f:
[[[ 75.  75.  75.  25.  75.]
  [ 75.  75.  25.  25.  25.]
  [ 75.  25.  75.  75.  75.]]

 [[ 25.  25.  25.  25. 100.]
  [ 75.  75.  75.  75.  75.]
  [ 25.  75.   0.  75.  75.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [36]:
### [your code here]