# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [48]:
### [your code here]
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [49]:
### [your code here]

print("NumPy version:", np.__version__)

np.show_config()

NumPy version: 1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/ProgramData/anaconda3/Library/include
    lib directory: C:/ProgramData/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1868282989520
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: win

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [50]:
a = np.random.random((2, 3, 5))
a1 = np.random.randn(2, 3, 5)
a2 = np.random.rand(2, 3, 5)



### 4. Print a.


In [51]:
### [your code here]

a = np.random.rand(2, 3, 5)
print(a)

[[[0.38811115 0.83210304 0.2150176  0.8411417  0.6933241 ]
  [0.34772951 0.23398378 0.21136113 0.38788881 0.1082747 ]
  [0.74836034 0.93757951 0.35301078 0.2393756  0.2306908 ]]

 [[0.64950145 0.96594381 0.97620714 0.86339747 0.04156347]
  [0.08647645 0.78914751 0.27333446 0.60161838 0.73146351]
  [0.77418484 0.4540441  0.07538955 0.02505227 0.69719348]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [52]:
### [your code here]

b = np.ones((5, 2, 3))



### 6. Print b.


In [53]:
### [your code here]
b = np.ones((5, 2, 3))
print(b)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [54]:
### [your code here]
a = np.random.rand(2, 3, 5)
b = np.ones((5, 2, 3))
same_size = a.size == b.size


print("Do a and b have the same size?", same_size)


Do a and b have the same size? True



### 8. Are you able to add a and b? Why or why not?


In [66]:
### [your code here]
a = np.random.rand(2, 3, 5)

b = np.ones((5, 2, 3))

can_add = a.shape == b.shape

print("Can a and b be added?", can_add)
print("No because a and b don't have the same shape")


Can a and b be added? False
No because a and b don't have the same shape




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [56]:
### [your code here]
b = np.ones((5, 2, 3))

c = b.transpose(1, 2, 0)

print(c)


[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [57]:
### [your code here]
a = np.random.rand(2, 3, 5)

b = np.ones((5, 2, 3))

c = b.transpose(1, 2, 0)

d = a + c

print(d)


[[[1.12545567 1.31808126 1.5308554  1.27015523 1.27948316]
  [1.78268139 1.12097266 1.67582497 1.44675642 1.77694926]
  [1.46516108 1.82699521 1.36581353 1.03679072 1.96128943]]

 [[1.7421449  1.81545756 1.4895003  1.72509551 1.20581322]
  [1.84347796 1.25322655 1.07269685 1.86994629 1.051319  ]
  [1.21835284 1.41494133 1.77470319 1.5354121  1.33494174]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [58]:
### [your code here]


a = np.random.rand(2, 3, 5)

b = np.ones((5, 2, 3))

c = b.transpose(1, 2, 0)

d = a + c

print("Array a:")
print(a)
print("\nArray d (a + c):")
print(d)



Array a:
[[[0.86123193 0.25612407 0.35310084 0.44019274 0.54189136]
  [0.28851163 0.76254302 0.59173405 0.45046624 0.24871472]
  [0.32805958 0.96547598 0.57488827 0.95020807 0.48758322]]

 [[0.01414526 0.58253841 0.93717899 0.73847994 0.14199568]
  [0.74463478 0.86043443 0.6590033  0.74300258 0.79354714]
  [0.45395036 0.06705639 0.21060628 0.12736143 0.48782766]]]

Array d (a + c):
[[[1.86123193 1.25612407 1.35310084 1.44019274 1.54189136]
  [1.28851163 1.76254302 1.59173405 1.45046624 1.24871472]
  [1.32805958 1.96547598 1.57488827 1.95020807 1.48758322]]

 [[1.01414526 1.58253841 1.93717899 1.73847994 1.14199568]
  [1.74463478 1.86043443 1.6590033  1.74300258 1.79354714]
  [1.45395036 1.06705639 1.21060628 1.12736143 1.48782766]]]



### 12. Multiply a and c. Assign the result to e.


In [59]:
### [your code here]
a = np.random.rand(2, 3, 5)

b = np.ones((5, 2, 3))
c = b.transpose(1, 2, 0)

e = a * c

print("Array a:")
print(a)
print("\nArray c:")
print(c)
print("\nArray e (a * c):")
print(e)

Array a:
[[[0.22403688 0.40959462 0.569414   0.68631815 0.68500514]
  [0.86583024 0.9851106  0.87491691 0.41966071 0.37647884]
  [0.24697673 0.89020725 0.73216385 0.39710094 0.33773356]]

 [[0.67829828 0.28402251 0.66800824 0.3776723  0.21528081]
  [0.51828019 0.88439152 0.8204211  0.86123559 0.09318252]
  [0.24024664 0.71779588 0.82971987 0.45767104 0.30278398]]]

Array c:
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]

Array e (a * c):
[[[0.22403688 0.40959462 0.569414   0.68631815 0.68500514]
  [0.86583024 0.9851106  0.87491691 0.41966071 0.37647884]
  [0.24697673 0.89020725 0.73216385 0.39710094 0.33773356]]

 [[0.67829828 0.28402251 0.66800824 0.3776723  0.21528081]
  [0.51828019 0.88439152 0.8204211  0.86123559 0.09318252]
  [0.24024664 0.71779588 0.82971987 0.45767104 0.30278398]]]




### 13. Does e equal to a? Why or why not?


In [60]:
### [your code here]
equal = np.array_equal(e, a)
print("Is e equal to a?", equal)

Is e equal to a? True




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [61]:
### [your code here]
a = np.random.rand(2, 3, 5)
b = np.ones((5, 2, 3))
c = b.transpose(1, 2, 0)
d = a + c

d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print("Max value in d:", d_max)
print("Min value in d:", d_min)
print("Mean value in d:", d_mean)



Max value in d: 1.9758655111300132
Min value in d: 1.0414327602555264
Mean value in d: 1.4896031052441103



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [62]:
### [your code here]
b = np.ones((5, 2, 3))
c = b.transpose(1, 2, 0)
d = a + c

f = np.empty(d.shape)

print("Shape of f:", f.shape)


Shape of f: (2, 3, 5)





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [63]:
### [your code here]
a = np.random.rand(2, 3, 5)
b = np.ones((5, 2, 3))
c = b.transpose(1, 2, 0)
d = a + c

d_min = np.min(d)
d_mean = np.mean(d)
d_max = np.max(d)

f = np.empty(d.shape)

for i in range(d.shape[0]):      
    for j in range(d.shape[1]): 
        for k in range(d.shape[2]):  
            if d[i, j, k] == d_min:
                f[i, j, k] = 0
            elif d[i, j, k] == d_mean:
                f[i, j, k] = 50
            elif d[i, j, k] == d_max:
                f[i, j, k] = 100
            elif d_min < d[i, j, k] < d_mean:
                f[i, j, k] = 25
            elif d_mean < d[i, j, k] < d_max:
                f[i, j, k] = 75

print("Populated array f:")
print(f)

Populated array f:
[[[ 75.  75.  25.  25.  75.]
  [ 25.  25.  75.  25.  25.]
  [  0.  75.  75.  75.  75.]]

 [[ 25.  25.  25.  25.  25.]
  [ 75.  25.  25.  25.  75.]
  [ 75. 100.  75.  75.  75.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [64]:
### [your code here]
a = np.random.rand(2, 3, 5)
b = np.ones((5, 2, 3))
c = b.transpose(1, 2, 0)
d = a + c

d_min = np.min(d)
d_mean = np.mean(d)
d_max = np.max(d)

f = np.empty(d.shape)

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i, j, k] == d_min:
                f[i, j, k] = 0
            elif d[i, j, k] == d_mean:
                f[i, j, k] = 50
            elif d[i, j, k] == d_max:
                f[i, j, k] = 100
            elif d_min < d[i, j, k] < d_mean:
                f[i, j, k] = 25
            elif d_mean < d[i, j, k] < d_max:
                f[i, j, k] = 75

print("Array d:")
print(d)
print("\nPopulated array f:")
print(f)

Array d:
[[[1.33487902 1.68249711 1.96080429 1.04630426 1.79143252]
  [1.60720291 1.14613374 1.73831699 1.5988198  1.35317104]
  [1.89198728 1.43312557 1.0204446  1.4842357  1.39317215]]

 [[1.58834905 1.60508135 1.35600677 1.81092382 1.29011376]
  [1.72383288 1.84027107 1.99671002 1.27922437 1.73160512]
  [1.6694039  1.94418519 1.66165713 1.53295667 1.86491511]]]

Populated array f:
[[[ 25.  75.  75.  25.  75.]
  [ 75.  25.  75.  75.  25.]
  [ 75.  25.   0.  25.  25.]]

 [[ 75.  75.  25.  75.  25.]
  [ 75.  75. 100.  25.  75.]
  [ 75.  75.  75.  25.  75.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [65]:
### [your code here]
a = np.random.rand(2, 3, 5)
b = np.ones((5, 2, 3))
c = b.transpose(1, 2, 0)
d = a + c

d_min = np.min(d)
d_mean = np.mean(d)
d_max = np.max(d)

f = np.empty(d.shape, dtype=object)  

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i, j, k] == d_min:
                f[i, j, k] = 'A' 
            elif d[i, j, k] == d_mean:
                f[i, j, k] = 'C' 
            elif d[i, j, k] == d_max:
                f[i, j, k] = 'E' 
            elif d_min < d[i, j, k] < d_mean:
                f[i, j, k] = 'B' 
            elif d_mean < d[i, j, k] < d_max:
                f[i, j, k] = 'D' 
print("Array d:")
print(d)
print("\nPopulated array f with strings:")
print(f)

Array d:
[[[1.28313079 1.74521711 1.92596266 1.47955589 1.82252031]
  [1.21689804 1.50862853 1.9292224  1.34916917 1.56353782]
  [1.61501786 1.06751724 1.3024948  1.98242932 1.49141004]]

 [[1.60078849 1.53068871 1.61243549 1.1427043  1.96893304]
  [1.42185982 1.75813548 1.11589796 1.96335529 1.37153357]
  [1.68914723 1.69091575 1.11235002 1.90360392 1.2031979 ]]]

Populated array f with strings:
[[['B' 'D' 'D' 'B' 'D']
  ['B' 'B' 'D' 'B' 'D']
  ['D' 'A' 'B' 'E' 'B']]

 [['D' 'B' 'D' 'B' 'D']
  ['B' 'D' 'B' 'D' 'B']
  ['D' 'D' 'B' 'D' 'B']]]
