# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [65]:
### [your code here]
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [8]:
### [your code here]
print(np.__version__)
np.show_config()

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/anaconda3/include
    lib directory: /opt/anaconda3/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 VORTEX MAX_THREADS=128
    pc file directory: /opt/anaconda3/lib/pkgconfig
    version: 0.3.21
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep4347739648
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -ftree-vectorize, -fPIC, -fPIE, -fstack-protector-strong, -O2, -pipe, -isystem,
      /opt/anaconda3/include, -fdebug-prefix-map=/var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_a51i_mbs7m/croot/numpy_and_numpy_base_1708638620867/work=/usr/local/src/conda/numpy-base-1.26.4,
      -fdebug-prefix-map=/opt/anaconda3=/usr/loca

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [17]:
a = np.random.rand(2, 3, 5)  # Generates values between 0 and 1

a_normal_dist = np.random.randn(2, 3, 5)  # Generates values from a normal distribution (mean=0, std=1)

a_randint = np.random.randint(10, 100, (2,3,5))


### 4. Print a.


In [18]:
print(a)
print(a_normal_dist)
print(a_randint)

[[[0.2308987  0.95157102 0.11308172 0.26292366 0.70022664]
  [0.5850733  0.72930913 0.52903728 0.6266166  0.17130269]
  [0.57306775 0.78709858 0.77193743 0.76610306 0.53558263]]

 [[0.58941166 0.3729463  0.34140398 0.09163842 0.0550272 ]
  [0.06272358 0.15617385 0.87110526 0.96612195 0.83944623]
  [0.82653597 0.78015353 0.87999142 0.79534223 0.79882763]]]
[[[-1.02563312  1.38300053 -0.00555892 -0.12123539  1.10837304]
  [-0.95932388 -0.23812287 -0.00719638  1.2964394  -0.79676558]
  [-0.42715926  1.91137069 -0.00363406 -0.26406214 -0.23271128]]

 [[-0.12082157  1.7803981  -0.7089879   0.97843754  0.73318859]
  [-0.12366576 -0.07979354  0.15100141 -0.44299813 -2.03649415]
  [ 0.85819569  0.10169208 -1.333902    0.42805996 -0.19954078]]]
[[[21 86 83 25 31]
  [60 80 22 82 40]
  [36 81 28 47 72]]

 [[38 31 27 74 84]
  [80 65 23 53 35]
  [40 94 11 63 24]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [21]:
b = np.full((5,2,3), 1)


### 6. Print b.


In [22]:
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [23]:
print("Size of a:", a.size)
print("Size of b:", b.size)

Size of a: 30
Size of b: 30



### 8. Are you able to add a and b? Why or why not?


In [37]:

try:
    c = a+b
    print (c)
except ValueError as e: 
    print("error", e)

    #no, because the shapes are different

print(a.shape)
print(b.shape)

error operands could not be broadcast together with shapes (2,3,5) (5,2,3) 
(2, 3, 5)
(5, 2, 3)




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [58]:

c = np.transpose(b, (1, 2, 0))

print(c)

[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [43]:
try:
    d = a+c
    print (d)
    print("success")
except ValueError as e: 
    print("error", e)

    #it works not because the shapes are the same.

[[[1.2308987  1.95157102 1.11308172 1.26292366 1.70022664]
  [1.5850733  1.72930913 1.52903728 1.6266166  1.17130269]
  [1.57306775 1.78709858 1.77193743 1.76610306 1.53558263]]

 [[1.58941166 1.3729463  1.34140398 1.09163842 1.0550272 ]
  [1.06272358 1.15617385 1.87110526 1.96612195 1.83944623]
  [1.82653597 1.78015353 1.87999142 1.79534223 1.79882763]]]
success



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [67]:
print(a, "\n\n\n")
print(d)

#d is now values a+c. i.e random values from a +

[[[0.2308987  0.95157102 0.11308172 0.26292366 0.70022664]
  [0.5850733  0.72930913 0.52903728 0.6266166  0.17130269]
  [0.57306775 0.78709858 0.77193743 0.76610306 0.53558263]]

 [[0.58941166 0.3729463  0.34140398 0.09163842 0.0550272 ]
  [0.06272358 0.15617385 0.87110526 0.96612195 0.83944623]
  [0.82653597 0.78015353 0.87999142 0.79534223 0.79882763]]] 



[[[1.2308987  1.95157102 1.11308172 1.26292366 1.70022664]
  [1.5850733  1.72930913 1.52903728 1.6266166  1.17130269]
  [1.57306775 1.78709858 1.77193743 1.76610306 1.53558263]]

 [[1.58941166 1.3729463  1.34140398 1.09163842 1.0550272 ]
  [1.06272358 1.15617385 1.87110526 1.96612195 1.83944623]
  [1.82653597 1.78015353 1.87999142 1.79534223 1.79882763]]]



### 12. Multiply a and c. Assign the result to e.


In [60]:
try:
    e = a*c
    print (e)
    print("success")
except ValueError as e: 
    print("error", e)

[[[0.2308987  0.95157102 0.11308172 0.26292366 0.70022664]
  [0.5850733  0.72930913 0.52903728 0.6266166  0.17130269]
  [0.57306775 0.78709858 0.77193743 0.76610306 0.53558263]]

 [[0.58941166 0.3729463  0.34140398 0.09163842 0.0550272 ]
  [0.06272358 0.15617385 0.87110526 0.96612195 0.83944623]
  [0.82653597 0.78015353 0.87999142 0.79534223 0.79882763]]]
success




### 13. Does e equal to a? Why or why not?


In [31]:
### yes. Multiplying by 1 doesn't change a. 





### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [69]:
### [your code here]

d_max = d.max()

d_min = d.min()

d_mean = d.mean()

print("Max Value (d_max):", d_max)
print("Min Value (d_min):", d_min)
print("Mean Value (d_mean):", d_mean)

Max Value (d_max): 1.966121954297798
Min Value (d_min): 1.0550272048549418
Mean Value (d_mean): 1.5586893142803564



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [117]:
f = np.empty((2,3,5))
print(f)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [118]:
### [your code here]
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

#f = np.zeros_like(d)

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range (d.shape[2]):
            if(d[i,j,k]==d_min):
                f[i,j,k] = 0
            elif(d_min < d[i,j,k] < d_mean):
                f[i,j,k]= 25
            elif d[i, j, k] == d_mean:
                f[i, j, k] = 50
            elif(d_mean < d[i,j,k] < d_max):
                f[i, j, k] = 75
            elif(d[i,j,k]==d_max):
                f[i,j,k] = 100
               


print(f)

[[[ 25.  75.  25.  25.  75.]
  [ 75.  75.  25.  75.  25.]
  [ 75.  75.  75.  75.  25.]]

 [[ 75.  25.  25.  25.   0.]
  [ 25.  25.  75. 100.  75.]
  [ 75.  75.  75.  75.  75.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [119]:
print(d, "\n")
print(f)

[[[1.2308987  1.95157102 1.11308172 1.26292366 1.70022664]
  [1.5850733  1.72930913 1.52903728 1.6266166  1.17130269]
  [1.57306775 1.78709858 1.77193743 1.76610306 1.53558263]]

 [[1.58941166 1.3729463  1.34140398 1.09163842 1.0550272 ]
  [1.06272358 1.15617385 1.87110526 1.96612195 1.83944623]
  [1.82653597 1.78015353 1.87999142 1.79534223 1.79882763]]] 

[[[ 25.  75.  25.  25.  75.]
  [ 75.  75.  25.  75.  25.]
  [ 75.  75.  75.  75.  25.]]

 [[ 75.  25.  25.  25.   0.]
  [ 25.  25.  75. 100.  75.]
  [ 75.  75.  75.  75.  75.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [121]:

f_obj = f.astype(object)

for i in range(f_obj.shape[0]):
    for j in range(f_obj.shape[1]):
        for k in range (f_obj.shape[2]):
            if(f_obj[i,j,k]==0):
                f_obj[i,j,k] = "A"
            elif(f_obj[i,j,k]==25):
                f_obj[i,j,k] = "B"
            elif(f_obj[i,j,k]==50):
                f[i,j,k] = "C"
            elif(f_obj[i,j,k]==75):
                f_obj[i,j,k] = "D"
            elif(f_obj[i,j,k]==100):
                f_obj[i,j,k] = "E"

print(f_obj)
                

[[['B' 'D' 'B' 'B' 'D']
  ['D' 'D' 'B' 'D' 'B']
  ['D' 'D' 'D' 'D' 'B']]

 [['D' 'B' 'B' 'B' 'A']
  ['B' 'B' 'D' 'E' 'D']
  ['D' 'D' 'D' 'D' 'D']]]
