# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [43]:
### [your code here]
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [44]:
### [your code here]
print("NumPy Version:", np.__version__)

np.show_config()


NumPy Version: 1.24.3
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/HUAWEI/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/HUAWEI/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/HUAWEI/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/HUAWEI/anaconda3\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/HUAWEI/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/HUAWEI/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/HUAWEI/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [45]:
### [your code here]
a = np.random.randint(3, size=(2, 3, 5))
a


array([[[0, 1, 0, 0, 1],
        [0, 2, 2, 2, 1],
        [0, 0, 0, 1, 2]],

       [[2, 1, 1, 2, 2],
        [0, 1, 2, 1, 2],
        [0, 2, 2, 0, 2]]])


### 4. Print a.


In [46]:
### [your code here]
print(a)

[[[0 1 0 0 1]
  [0 2 2 2 1]
  [0 0 0 1 2]]

 [[2 1 1 2 2]
  [0 1 2 1 2]
  [0 2 2 0 2]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [47]:
### [your code here]
b = np.ones((5, 2,3))



### 6. Print b.


In [48]:
### [your code here]
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [61]:
### [your code here]
# yes have the same size 


if a.size == b.size:
    print(True)
else:
    print(False)







True



### 8. Are you able to add a and b? Why or why not?


In [50]:
### [your code here]
add_arr= a+b

#no i can'not because they don't have the same shapes


ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [51]:
### [your code here]
c= np.transpose(b, (1, 2, 0))  # Change (5,2,3) → (2,3,5)



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [52]:
### [your code here]
d = a + c
print(d)

[[[1. 2. 1. 1. 2.]
  [1. 3. 3. 3. 2.]
  [1. 1. 1. 2. 3.]]

 [[3. 2. 2. 3. 3.]
  [1. 2. 3. 2. 3.]
  [1. 3. 3. 1. 3.]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [55]:
### [your code here]
print(a)
print(d)



[[[0 1 0 0 1]
  [0 2 2 2 1]
  [0 0 0 1 2]]

 [[2 1 1 2 2]
  [0 1 2 1 2]
  [0 2 2 0 2]]]
[[[1. 2. 1. 1. 2.]
  [1. 3. 3. 3. 2.]
  [1. 1. 1. 2. 3.]]

 [[3. 2. 2. 3. 3.]
  [1. 2. 3. 2. 3.]
  [1. 3. 3. 1. 3.]]]



### 12. Multiply a and c. Assign the result to e.


In [56]:
### [your code here]
e = a*c
e


array([[[0., 1., 0., 0., 1.],
        [0., 2., 2., 2., 1.],
        [0., 0., 0., 1., 2.]],

       [[2., 1., 1., 2., 2.],
        [0., 1., 2., 1., 2.],
        [0., 2., 2., 0., 2.]]])



### 13. Does e equal to a? Why or why not?


In [ ]:
### [your code here]
# yes it is 



array([[[0, 1, 0, 0, 1],
        [0, 2, 2, 2, 1],
        [0, 0, 0, 1, 2]],

       [[2, 1, 1, 2, 2],
        [0, 1, 2, 1, 2],
        [0, 2, 2, 0, 2]]])



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [80]:
### [your code here]
d_max= np.max(d)
d_min= np.min(d)
d_mean= np.mean(d)

print(d_max)
print(d_min)
print(d_mean)





3.0
1.0
2.066666666666667



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [81]:
### [your code here]
f= np.empty([2,3,5])
f


array([[[  0.,  25.,   0.,   0.,  25.],
        [  0., 100., 100., 100.,  25.],
        [  0.,   0.,   0.,  25., 100.]],

       [[100.,  25.,  25., 100., 100.],
        [  0.,  25., 100.,  25., 100.],
        [  0., 100., 100.,   0., 100.]]])




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [83]:
### [your code here]

f = np.empty_like(d)



for i in range(d.shape[0]): 
    for j in range(d.shape[1]):  
        for k in range(d.shape[2]):  
            if d[i, j, k] == d_min:
                f[i, j, k] = 0
            elif d_min < d[i, j, k] < d_mean:
                f[i, j, k] = 25
            elif d[i, j, k] == d_mean:
                f[i, j, k] = 50
            elif d_mean < d[i, j, k] < d_max:
                f[i, j, k] = 75
            elif d[i, j, k] == d_max:
                f[i, j, k] = 100

# Print f to verify the result
print(f)



[[[  0.  25.   0.   0.  25.]
  [  0. 100. 100. 100.  25.]
  [  0.   0.   0.  25. 100.]]

 [[100.  25.  25. 100. 100.]
  [  0.  25. 100.  25. 100.]
  [  0. 100. 100.   0. 100.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [84]:
### [your code here]
print(d)
print(f)


[[[1. 2. 1. 1. 2.]
  [1. 3. 3. 3. 2.]
  [1. 1. 1. 2. 3.]]

 [[3. 2. 2. 3. 3.]
  [1. 2. 3. 2. 3.]
  [1. 3. 3. 1. 3.]]]
[[[  0.  25.   0.   0.  25.]
  [  0. 100. 100. 100.  25.]
  [  0.   0.   0.  25. 100.]]

 [[100.  25.  25. 100. 100.]
  [  0.  25. 100.  25. 100.]
  [  0. 100. 100.   0. 100.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [36]:
### [your code here]