# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
### [your code here]
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [7]:
### [your code here]
print(np.__version__)
np.show_config()

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/anaconda3/include
    lib directory: /opt/anaconda3/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 VORTEX MAX_THREADS=128
    pc file directory: /opt/anaconda3/lib/pkgconfig
    version: 0.3.21
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep4347739648
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -ftree-vectorize, -fPIC, -fPIE, -fstack-protector-strong, -O2, -pipe, -isystem,
      /opt/anaconda3/include, -fdebug-prefix-map=/var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_a51i_mbs7m/croot/numpy_and_numpy_base_1708638620867/work=/usr/local/src/conda/numpy-base-1.26.4,
      -fdebug-prefix-map=/opt/anaconda3=/usr/loca

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [12]:
### [your code here]
a = np.random.rand(2, 3, 5)


### 4. Print a.


In [15]:
### [your code here]
print(a)

[[[0.29756001 0.90119714 0.27942647 0.8040184  0.58635369]
  [0.20661514 0.10446898 0.09520968 0.91970846 0.08984864]
  [0.37691145 0.63516963 0.70950969 0.71228778 0.1612892 ]]

 [[0.59224552 0.77336648 0.72848438 0.08477315 0.00125313]
  [0.84444122 0.71186382 0.0592811  0.04950513 0.26371122]
  [0.44487475 0.39499232 0.85849085 0.82108386 0.98594114]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [17]:
### [your code here]
b = np.ones((5, 2, 3))


### 6. Print b.


In [19]:
### [your code here]
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [28]:
### [your code here]
print("size of a:", a.size)
print("size of b:",b.size)

if a.size == b.size:
    print("a and b have the same size.")
else:
    print("a and b do not have the same size.")

size of a: 30
size of b: 30
a and b have the same size.



### 8. Are you able to add a and b? Why or why not?


In [33]:
### [your code here]
try:
    c = a + b
    print("able to addition!")
except ValueError as e:
    print("Error:", e)

Error: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [38]:
### [your code here]
c = np.transpose(b, (1, 2, 0))
print("shape of a:", (2, 3, 5))
print("shape of c:", c.shape)

shape of a: (2, 3, 5)
shape of c: (2, 3, 5)



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [50]:
### [your code here]
d = a + c
print("shape of a:", a.shape)
print("shape of c:", c.shape)
print("shape of d:", d.shape) 
print("result of d:\n", d)
## because both arrays have the same shape 

shape of a: (2, 3, 5)
shape of c: (2, 3, 5)
shape of d: (2, 3, 5)
result of d:
 [[[1.29756001 1.90119714 1.27942647 1.8040184  1.58635369]
  [1.20661514 1.10446898 1.09520968 1.91970846 1.08984864]
  [1.37691145 1.63516963 1.70950969 1.71228778 1.1612892 ]]

 [[1.59224552 1.77336648 1.72848438 1.08477315 1.00125313]
  [1.84444122 1.71186382 1.0592811  1.04950513 1.26371122]
  [1.44487475 1.39499232 1.85849085 1.82108386 1.98594114]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [58]:
### [your code here]
print("array a:\n", a)
print("\narray d:\n", d)
##The arrays a and d are related because d is the result of adding a with c,

array a:
 [[[0.29756001 0.90119714 0.27942647 0.8040184  0.58635369]
  [0.20661514 0.10446898 0.09520968 0.91970846 0.08984864]
  [0.37691145 0.63516963 0.70950969 0.71228778 0.1612892 ]]

 [[0.59224552 0.77336648 0.72848438 0.08477315 0.00125313]
  [0.84444122 0.71186382 0.0592811  0.04950513 0.26371122]
  [0.44487475 0.39499232 0.85849085 0.82108386 0.98594114]]]

array d:
 [[[1.29756001 1.90119714 1.27942647 1.8040184  1.58635369]
  [1.20661514 1.10446898 1.09520968 1.91970846 1.08984864]
  [1.37691145 1.63516963 1.70950969 1.71228778 1.1612892 ]]

 [[1.59224552 1.77336648 1.72848438 1.08477315 1.00125313]
  [1.84444122 1.71186382 1.0592811  1.04950513 1.26371122]
  [1.44487475 1.39499232 1.85849085 1.82108386 1.98594114]]]



### 12. Multiply a and c. Assign the result to e.


In [65]:
### [your code here]
e = a * c
print("array a:\n", a)
print("\narray c:\n", c)
print("\narray e (result of multiplication):\n", e)

array a:
 [[[0.29756001 0.90119714 0.27942647 0.8040184  0.58635369]
  [0.20661514 0.10446898 0.09520968 0.91970846 0.08984864]
  [0.37691145 0.63516963 0.70950969 0.71228778 0.1612892 ]]

 [[0.59224552 0.77336648 0.72848438 0.08477315 0.00125313]
  [0.84444122 0.71186382 0.0592811  0.04950513 0.26371122]
  [0.44487475 0.39499232 0.85849085 0.82108386 0.98594114]]]

array c:
 [[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]

array e (result of multiplication):
 [[[0.29756001 0.90119714 0.27942647 0.8040184  0.58635369]
  [0.20661514 0.10446898 0.09520968 0.91970846 0.08984864]
  [0.37691145 0.63516963 0.70950969 0.71228778 0.1612892 ]]

 [[0.59224552 0.77336648 0.72848438 0.08477315 0.00125313]
  [0.84444122 0.71186382 0.0592811  0.04950513 0.26371122]
  [0.44487475 0.39499232 0.85849085 0.82108386 0.98594114]]]




### 13. Does e equal to a? Why or why not?


In [76]:
### [your code here]
if a.size == e.size:
    print("a and e have the same size.")
else:
    print("a and e do not have the same size.")
#e equals a because multiplying by 1 leaves the values unchanged.

a and e have the same size.




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [79]:
### [your code here]
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print("max value:", d_max)
print("min value:", d_min)
print("mean value:", d_mean)

max value: 1.9859411435318353
min value: 1.0012531288583522
mean value: 1.4831294146258138



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [88]:
### [your code here]
f = np.empty(d.shape)
print("shape of f:", f.shape)  # Should be (2, 3, 5)
print("result of f:\n", f)

shape of f: (2, 3, 5)
content of f:
 [[[0.29756001 0.90119714 0.27942647 0.8040184  0.58635369]
  [0.20661514 0.10446898 0.09520968 0.91970846 0.08984864]
  [0.37691145 0.63516963 0.70950969 0.71228778 0.1612892 ]]

 [[0.59224552 0.77336648 0.72848438 0.08477315 0.00125313]
  [0.84444122 0.71186382 0.0592811  0.04950513 0.26371122]
  [0.44487475 0.39499232 0.85849085 0.82108386 0.98594114]]]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [93]:
### [your code here]
for i in range(d.shape[0]): 
    for j in range(d.shape[1]):  
        for k in range(d.shape[2]):  
            value = d[i, j, k]
            if value == d_min:
                f[i, j, k] = 0
            elif value == d_max:
                f[i, j, k] = 100
            elif value == d_mean:
                f[i, j, k] = 50
            elif d_min < value < d_mean:
                f[i, j, k] = 25
            elif d_mean < value < d_max:
                f[i, j, k] = 75
print("array f populated:\n", f)

array f populated:
 [[[ 25.  75.  25.  75.  75.]
  [ 25.  25.  25.  75.  25.]
  [ 25.  75.  75.  75.  25.]]

 [[ 75.  75.  75.  25.   0.]
  [ 75.  75.  25.  25.  25.]
  [ 25.  25.  75.  75. 100.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [98]:
### [your code here]
d = np.array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
               [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
               [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

              [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
               [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
               [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

f = np.empty(d.shape)
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
for i in range(d.shape[0]):  
    for j in range(d.shape[1]): 
        for k in range(d.shape[2]): 
            value = d[i, j, k]
            
            if value == d_min:
                f[i, j, k] = 0
            elif value == d_max:
                f[i, j, k] = 100
            elif value == d_mean:
                f[i, j, k] = 50
            elif d_min < value < d_mean:
                f[i, j, k] = 25
            elif d_mean < value < d_max:
                f[i, j, k] = 75

print("array d:\n", d)
print("\narray f (populated):\n", f)

array d:
 [[[1.85836099 1.67064465 1.62576044 1.40243961 1.88454931]
  [1.75354326 1.69403643 1.36729252 1.61415071 1.12104981]
  [1.72201435 1.1862918  1.87078449 1.7726778  1.88180042]]

 [[1.44747908 1.31673383 1.02000951 1.52218947 1.97066381]
  [1.79129243 1.74983003 1.96028037 1.85166831 1.65450881]
  [1.18068344 1.9587381  1.00656599 1.93402165 1.73514584]]]

array f (populated):
 [[[ 75.  75.  75.  25.  75.]
  [ 75.  75.  25.  25.  25.]
  [ 75.  25.  75.  75.  75.]]

 [[ 25.  25.  25.  25. 100.]
  [ 75.  75.  75.  75.  75.]
  [ 25.  75.   0.  75.  75.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [101]:
### [your code here]
d = [
    [
        [1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]
    ],
    [
        [1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]
    ]
]
d_flat = [item for sublist1 in d for sublist2 in sublist1 for item in sublist2]
d_max = max(d_flat)
d_min = min(d_flat)
d_mean = sum(d_flat) / len(d_flat)

f = [[[None for _ in range(5)] for _ in range(3)] for _ in range(2)]

for i in range(len(d)):  
    for j in range(len(d[i])):  
        for k in range(len(d[i][j])): 
            value = d[i][j][k]
            
            if value == d_min:
                f[i][j][k] = "A"
            elif value == d_max:
                f[i][j][k] = "E"
            elif value == d_mean:
                f[i][j][k] = "C"
            elif d_min < value < d_mean:
                f[i][j][k] = "B"
            elif d_mean < value < d_max:
                f[i][j][k] = "D"

print("array d:\n", d)
print("\narray f (populated):\n", f)

array d:
 [[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931], [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981], [1.72201435, 1.1862918, 1.87078449, 1.7726778, 1.88180042]], [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381], [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881], [1.18068344, 1.9587381, 1.00656599, 1.93402165, 1.73514584]]]

array f (populated):
 [[['D', 'D', 'D', 'B', 'D'], ['D', 'D', 'B', 'B', 'B'], ['D', 'B', 'D', 'D', 'D']], [['B', 'B', 'B', 'B', 'E'], ['D', 'D', 'D', 'D', 'D'], ['B', 'D', 'A', 'D', 'D']]]
