# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
### [your code here]
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [9]:
### [your code here]
np.__version__

'1.24.3'

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [29]:
### [your code here]

a = np.random.random((2,3,5))


### 4. Print a.


In [30]:
### [your code here]
print(a)

[[[0.7432884  0.47953327 0.4242703  0.74702452 0.01964373]
  [0.23007317 0.60458851 0.55335955 0.08993429 0.08461763]
  [0.03476007 0.00106678 0.50768356 0.91589495 0.81865693]]

 [[0.13071842 0.42463585 0.65618514 0.57952783 0.36326272]
  [0.51948214 0.11523036 0.67887241 0.25123329 0.09367624]
  [0.14972071 0.73768004 0.07019706 0.76152366 0.13242668]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [31]:
### [your code here]

b = np.ones((5,2,3))


### 6. Print b.


In [32]:
### [your code here]
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [33]:
### [your code here]

np.shape(a) == np.shape(b)

False


### 8. Are you able to add a and b? Why or why not?


In [34]:
### [your code here]

a + b


ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [43]:
np.shape(b)

(5, 2, 3)

In [45]:
### [your code here]

c = np.transpose(b, axes=(1,2,0))
c


array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [ ]:
### [your code here]

d = a + c

# arrays are of same shape now


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [ ]:
### [your code here]
print(a)
print(d)

# d is equal to a + 1

[[[0.7432884  0.47953327 0.4242703  0.74702452 0.01964373]
  [0.23007317 0.60458851 0.55335955 0.08993429 0.08461763]
  [0.03476007 0.00106678 0.50768356 0.91589495 0.81865693]]

 [[0.13071842 0.42463585 0.65618514 0.57952783 0.36326272]
  [0.51948214 0.11523036 0.67887241 0.25123329 0.09367624]
  [0.14972071 0.73768004 0.07019706 0.76152366 0.13242668]]]
[[[1.7432884  1.47953327 1.4242703  1.74702452 1.01964373]
  [1.23007317 1.60458851 1.55335955 1.08993429 1.08461763]
  [1.03476007 1.00106678 1.50768356 1.91589495 1.81865693]]

 [[1.13071842 1.42463585 1.65618514 1.57952783 1.36326272]
  [1.51948214 1.11523036 1.67887241 1.25123329 1.09367624]
  [1.14972071 1.73768004 1.07019706 1.76152366 1.13242668]]]



### 12. Multiply a and c. Assign the result to e.


In [50]:
### [your code here]

e = a * c
e

array([[[0.7432884 , 0.47953327, 0.4242703 , 0.74702452, 0.01964373],
        [0.23007317, 0.60458851, 0.55335955, 0.08993429, 0.08461763],
        [0.03476007, 0.00106678, 0.50768356, 0.91589495, 0.81865693]],

       [[0.13071842, 0.42463585, 0.65618514, 0.57952783, 0.36326272],
        [0.51948214, 0.11523036, 0.67887241, 0.25123329, 0.09367624],
        [0.14972071, 0.73768004, 0.07019706, 0.76152366, 0.13242668]]])



### 13. Does e equal to a? Why or why not?


In [ ]:
### [your code here]

np.array_equal(a,e)

# they are equal cause x * 1 = x

True



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [60]:
### [your code here]

d_max = np.max(d)
print(d_max)

d_min = np.min(d)
print(d_min)

d_mean = np.mean(d)
print(d_mean)

1.9158949545037587
1.0010667782422615
1.3972922738030076



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [67]:
### [your code here]

f = np.empty((2,3,5))
f

array([[[0.7432884 , 0.47953327, 0.4242703 , 0.74702452, 0.01964373],
        [0.23007317, 0.60458851, 0.55335955, 0.08993429, 0.08461763],
        [0.03476007, 0.00106678, 0.50768356, 0.91589495, 0.81865693]],

       [[0.13071842, 0.42463585, 0.65618514, 0.57952783, 0.36326272],
        [0.51948214, 0.11523036, 0.67887241, 0.25123329, 0.09367624],
        [0.14972071, 0.73768004, 0.07019706, 0.76152366, 0.13242668]]])




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [80]:
### [your code here]
for block, content in enumerate(d):
    for row, content1 in enumerate(content):
        for column, content2 in enumerate(content1):
            value = d[block][row][column]
            if value == d_mean:
                f[block][row][column] = 50
            elif value > d_mean and value < d_max:
                f[block][row][column] = 75
            elif value > d_min and value < d_mean:
                f[block][row][column] = 25
            elif value == d_max:
                f[block][row][column] = 100
            elif value == d_min:
                f[block][row][column] = 0

f


array([[[ 75.,  75.,  75.,  75.,  25.],
        [ 25.,  75.,  75.,  25.,  25.],
        [ 25.,   0.,  75., 100.,  75.]],

       [[ 25.,  75.,  75.,  75.,  25.],
        [ 75.,  25.,  75.,  25.,  25.],
        [ 25.,  75.,  25.,  75.,  25.]]])





### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [81]:
### [your code here]
print(d)
print(f)

[[[1.7432884  1.47953327 1.4242703  1.74702452 1.01964373]
  [1.23007317 1.60458851 1.55335955 1.08993429 1.08461763]
  [1.03476007 1.00106678 1.50768356 1.91589495 1.81865693]]

 [[1.13071842 1.42463585 1.65618514 1.57952783 1.36326272]
  [1.51948214 1.11523036 1.67887241 1.25123329 1.09367624]
  [1.14972071 1.73768004 1.07019706 1.76152366 1.13242668]]]
[[[ 75.  75.  75.  75.  25.]
  [ 25.  75.  75.  25.  25.]
  [ 25.   0.  75. 100.  75.]]

 [[ 25.  75.  75.  75.  25.]
  [ 75.  25.  75.  25.  25.]
  [ 25.  75.  25.  75.  25.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [83]:
### [your code here]
g = np.empty((2,3,5),dtype=np.str_)

for block in range(len(d)):
    for row in range(len(d[block])):
        for column in range(len(d[block][row])):
            value = d[block][row][column]
            if value == d_mean:
                g[block][row][column] = "c"
            elif value > d_mean and value < d_max:
                g[block][row][column] = "B"
            elif value > d_min and value < d_mean:
                g[block][row][column] = "D"
            elif value == d_max:
                g[block][row][column] = "A"
            elif value == d_min:
                g[block][row][column] = "E"

g


array([[['B', 'B', 'B', 'B', 'D'],
        ['D', 'B', 'B', 'D', 'D'],
        ['D', 'E', 'B', 'A', 'B']],

       [['D', 'B', 'B', 'B', 'D'],
        ['B', 'D', 'B', 'D', 'D'],
        ['D', 'B', 'D', 'B', 'D']]], dtype='<U1')