# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [4]:
### [your code here]
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [6]:
### [your code here]
print(np.__version__)
np.show_config()

1.22.3
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['/usr/local/lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [10]:
### [your code here]

a = np.random.random((2, 3, 5)) # (rows, columns)




### 4. Print a.


In [11]:
### [your code here]
print(a)

[[[0.70606964 0.79983415 0.22356572 0.38970704 0.15454135]
  [0.47282455 0.68474116 0.15042566 0.17698228 0.16093039]
  [0.24237236 0.78937361 0.56811368 0.36626594 0.17711339]]

 [[0.85002148 0.80765052 0.71904718 0.52005035 0.31753959]
  [0.76044134 0.62263205 0.26347973 0.63593497 0.34927783]
  [0.16761134 0.62298363 0.91189604 0.59003357 0.63220902]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [14]:
### [your code here]
b = np.ones((5, 2, 3))


### 6. Print b.


In [15]:
### [your code here]
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [17]:
### [your code here]
a.shape==b.shape

False


### 8. Are you able to add a and b? Why or why not?


In [ ]:
### [your code here]
# c = np.add(a, b)
print("it wont work because of their shapes")

it wont work because of their shapes




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [25]:
### [your code here]
c=np.transpose(b, (1, 2, 0))
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [26]:
### [your code here]
d = a + c


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [29]:
### [your code here]
print(a)
print('********************')
print(d)
print("a and b has the same random values but the only diffrence that a is between 0 and 1(Probability) and b is one and the same (Probability)")


[[[0.70606964 0.79983415 0.22356572 0.38970704 0.15454135]
  [0.47282455 0.68474116 0.15042566 0.17698228 0.16093039]
  [0.24237236 0.78937361 0.56811368 0.36626594 0.17711339]]

 [[0.85002148 0.80765052 0.71904718 0.52005035 0.31753959]
  [0.76044134 0.62263205 0.26347973 0.63593497 0.34927783]
  [0.16761134 0.62298363 0.91189604 0.59003357 0.63220902]]]
********************
[[[1.70606964 1.79983415 1.22356572 1.38970704 1.15454135]
  [1.47282455 1.68474116 1.15042566 1.17698228 1.16093039]
  [1.24237236 1.78937361 1.56811368 1.36626594 1.17711339]]

 [[1.85002148 1.80765052 1.71904718 1.52005035 1.31753959]
  [1.76044134 1.62263205 1.26347973 1.63593497 1.34927783]
  [1.16761134 1.62298363 1.91189604 1.59003357 1.63220902]]]
a and b has the same random values but the only diffrence that a is between 0 and 1(Probability) and b is one and the same (Probability)



### 12. Multiply a and c. Assign the result to e.


In [33]:
### [your code here]
e = a * c
print(e)

[[[0.70606964 0.79983415 0.22356572 0.38970704 0.15454135]
  [0.47282455 0.68474116 0.15042566 0.17698228 0.16093039]
  [0.24237236 0.78937361 0.56811368 0.36626594 0.17711339]]

 [[0.85002148 0.80765052 0.71904718 0.52005035 0.31753959]
  [0.76044134 0.62263205 0.26347973 0.63593497 0.34927783]
  [0.16761134 0.62298363 0.91189604 0.59003357 0.63220902]]]




### 13. Does e equal to a? Why or why not?


In [34]:
### [your code here]
a==e
print('The reason the result of multiplying arrays a and c is equal to the original array a (in the context of your previous operations) is due to the specific values in the array c that were created from the array b.')



The reason the result of multiplying arrays a and c is equal to the original array a (in the context of your previous operations) is due to the specific values in the array c that were created from the array b.




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [35]:
### [your code here]
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [37]:
### [your code here]
f=np.empty(d.shape)




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [39]:
### [your code here]

for i in range(d.shape[0]): 
    for j in range(d.shape[1]):  
        for k in range(d.shape[2]):  
            value = d[i][j][k]
            if value == d_min:
                f[i][j][k] = 0
            elif value == d_mean:
                f[i][j][k] = 50
            elif value == d_max:
                f[i][j][k] = 100
            elif d_min < value < d_mean:
                f[i][j][k] = 25
            elif d_mean < value < d_max:
                f[i][j][k] = 75






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [40]:
### [your code here]
print(d)
print('*************')
print(f)


[[[1.70606964 1.79983415 1.22356572 1.38970704 1.15454135]
  [1.47282455 1.68474116 1.15042566 1.17698228 1.16093039]
  [1.24237236 1.78937361 1.56811368 1.36626594 1.17711339]]

 [[1.85002148 1.80765052 1.71904718 1.52005035 1.31753959]
  [1.76044134 1.62263205 1.26347973 1.63593497 1.34927783]
  [1.16761134 1.62298363 1.91189604 1.59003357 1.63220902]]]
*************
[[[ 75.  75.  25.  25.  25.]
  [ 25.  75.   0.  25.  25.]
  [ 25.  75.  75.  25.  25.]]

 [[ 75.  75.  75.  75.  25.]
  [ 75.  75.  25.  75.  25.]
  [ 25.  75. 100.  75.  75.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [ ]:
### [your code here]




