# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [160]:
import numpy as np
import pandas as pd



### 2. Print the NUMPY version and the configuration.


In [161]:
np.__version__

'1.23.5'

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [162]:
a = np.random.randint(10,99 , size=(2,3,5))


### 4. Print a.


In [163]:
a


array([[[39, 94, 38, 93, 13],
        [93, 14, 44, 41, 75],
        [49, 24, 77, 80, 35]],

       [[51, 60, 36, 57, 81],
        [75, 38, 65, 83, 66],
        [26, 82, 56, 43, 40]]])

### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [164]:
b = np.ones([5,2,3])


### 6. Print b.


In [165]:
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])


### 7. Do a and b have the same size? How do you prove that in Python code?


In [166]:
def check():
    if a.shape == b.shape:
        return True
    else:
        return False
check()

False


### 8. Are you able to add a and b? Why or why not?


In [167]:
try:   
    able = a + b
except:
    print('That is Error becouse array not same dimensions   a = (2,3,5,)  b = (5,2,3,)')

That is Error becouse array not same dimensions   a = (2,3,5,)  b = (5,2,3,)




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [168]:
c = np.transpose(b,(1,2,0))

In [169]:
c.shape

(2, 3, 5)


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [170]:
d = a + c
d # becuse use transpose same dimensions

array([[[40., 95., 39., 94., 14.],
        [94., 15., 45., 42., 76.],
        [50., 25., 78., 81., 36.]],

       [[52., 61., 37., 58., 82.],
        [76., 39., 66., 84., 67.],
        [27., 83., 57., 44., 41.]]])


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [171]:
print(a)
print('\n\n')
print(d)


# becouce add 1 every element    

[[[39 94 38 93 13]
  [93 14 44 41 75]
  [49 24 77 80 35]]

 [[51 60 36 57 81]
  [75 38 65 83 66]
  [26 82 56 43 40]]]



[[[40. 95. 39. 94. 14.]
  [94. 15. 45. 42. 76.]
  [50. 25. 78. 81. 36.]]

 [[52. 61. 37. 58. 82.]
  [76. 39. 66. 84. 67.]
  [27. 83. 57. 44. 41.]]]



### 12. Multiply a and c. Assign the result to e.


In [172]:
e = a * c
e

array([[[39., 94., 38., 93., 13.],
        [93., 14., 44., 41., 75.],
        [49., 24., 77., 80., 35.]],

       [[51., 60., 36., 57., 81.],
        [75., 38., 65., 83., 66.],
        [26., 82., 56., 43., 40.]]])



### 13. Does e equal to a? Why or why not?


In [173]:
if a.all() == e.all():
    print("True")
else:
    print("False")

# because every number multiplied in 1 = result same number

True




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [174]:
d_max = d.max()
print(f"max number is {d_max}")
d_min = d.min()
print(f"min number is {d_min}")
d_mean = d.mean()
print(f"mean number is {d_mean}")


max number is 95.0
min number is 14.0
mean number is 56.6



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [175]:
f = np.empty([2,3,5])
f

array([[[39., 94., 38., 93., 13.],
        [93., 14., 44., 41., 75.],
        [49., 24., 77., 80., 35.]],

       [[51., 60., 36., 57., 81.],
        [75., 38., 65., 83., 66.],
        [26., 82., 56., 43., 40.]]])




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [176]:
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for z in range(d.shape[2]):
            value = d[i][j][z]
            if value == d_max:
                f[i][j][z] = 100
            elif value == d_mean:
                f[i][j][z] = 50
            elif value == d_min:
                f[i][j][z] = 0
            elif value > d_min and value < d_mean:
                f[i][j][z] = 25
            else:
                f[i][j][z] = 75


In [177]:
f

array([[[ 25., 100.,  25.,  75.,   0.],
        [ 75.,  25.,  25.,  25.,  75.],
        [ 25.,  25.,  75.,  75.,  25.]],

       [[ 25.,  75.,  25.,  75.,  75.],
        [ 75.,  25.,  75.,  75.,  75.],
        [ 25.,  75.,  75.,  25.,  25.]]])





### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [178]:
print(f'Arry d \n {d}\n')
print(f'Arry f \n {f}')

Arry d 
 [[[40. 95. 39. 94. 14.]
  [94. 15. 45. 42. 76.]
  [50. 25. 78. 81. 36.]]

 [[52. 61. 37. 58. 82.]
  [76. 39. 66. 84. 67.]
  [27. 83. 57. 44. 41.]]]

Arry f 
 [[[ 25. 100.  25.  75.   0.]
  [ 75.  25.  25.  25.  75.]
  [ 25.  25.  75.  75.  25.]]

 [[ 25.  75.  25.  75.  75.]
  [ 75.  25.  75.  75.  75.]
  [ 25.  75.  75.  25.  25.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [179]:
f_char = np.empty(f.shape, dtype=str)

# تطبيق الشروط لتحويل القيم إلى حروف
f_char[f == 0] = "A"
f_char[f == 25] = "B"
f_char[f == 50] = "C"
f_char[f == 75] = "D"
f_char[f == 100] = "E"

In [180]:
print(f_char)

[[['B' 'E' 'B' 'D' 'A']
  ['D' 'B' 'B' 'B' 'D']
  ['B' 'B' 'D' 'D' 'B']]

 [['B' 'D' 'B' 'D' 'D']
  ['D' 'B' 'D' 'D' 'D']
  ['B' 'D' 'D' 'B' 'B']]]
