# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [2]:
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [3]:
print(np.__version__)


2.2.3


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [5]:
a = np.random.rand(2, 3, 5)


### 4. Print a.


In [6]:
print(a)

[[[0.87860651 0.92077227 0.21262997 0.48554365 0.9372853 ]
  [0.70861208 0.18884171 0.3183815  0.50941561 0.96022178]
  [0.46827591 0.80086935 0.69757676 0.8575967  0.49181767]]

 [[0.01137793 0.74226323 0.30126172 0.64679946 0.4125845 ]
  [0.7471693  0.08877189 0.60246005 0.58103283 0.75498586]
  [0.78177947 0.72871877 0.23729971 0.70181209 0.84612777]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [8]:
b = np.ones((5, 2, 3))



### 6. Print b.


In [9]:
print(b)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [10]:
print(a.size == b.size)


True



### 8. Are you able to add a and b? Why or why not?


In [ ]:
print(a.shape)
print(b.shape)

# No, not without transposing. As seen from the code, 'a' and 'b' have incompatible dimensions. 

(2, 3, 5)
(5, 2, 3)




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [22]:

c = b.transpose(1, 2, 0)
# still have questions regarding transpose 


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [ ]:
d = a + c
print(d)

# it works because now they are the same shape. 


[[[1.87860651 1.92077227 1.21262997 1.48554365 1.9372853 ]
  [1.70861208 1.18884171 1.3183815  1.50941561 1.96022178]
  [1.46827591 1.80086935 1.69757676 1.8575967  1.49181767]]

 [[1.01137793 1.74226323 1.30126172 1.64679946 1.4125845 ]
  [1.7471693  1.08877189 1.60246005 1.58103283 1.75498586]
  [1.78177947 1.72871877 1.23729971 1.70181209 1.84612777]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [ ]:
print(a)
print(d)

# since 'c' only consists of ones, the value in 'd' is 'c' + 1.


[[[0.87860651 0.92077227 0.21262997 0.48554365 0.9372853 ]
  [0.70861208 0.18884171 0.3183815  0.50941561 0.96022178]
  [0.46827591 0.80086935 0.69757676 0.8575967  0.49181767]]

 [[0.01137793 0.74226323 0.30126172 0.64679946 0.4125845 ]
  [0.7471693  0.08877189 0.60246005 0.58103283 0.75498586]
  [0.78177947 0.72871877 0.23729971 0.70181209 0.84612777]]]
[[[1.87860651 1.92077227 1.21262997 1.48554365 1.9372853 ]
  [1.70861208 1.18884171 1.3183815  1.50941561 1.96022178]
  [1.46827591 1.80086935 1.69757676 1.8575967  1.49181767]]

 [[1.01137793 1.74226323 1.30126172 1.64679946 1.4125845 ]
  [1.7471693  1.08877189 1.60246005 1.58103283 1.75498586]
  [1.78177947 1.72871877 1.23729971 1.70181209 1.84612777]]]



### 12. Multiply a and c. Assign the result to e.


In [26]:
e = a * c




### 13. Does e equal to a? Why or why not?


In [ ]:
np.array_equal(e, a)
# e is identical to a.

True



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [28]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(d_max, d_min, d_mean)


1.9602217763388978 1.0113779296381553 1.5873630446775604



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [33]:
f = np.empty(d.shape)





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [40]:
f[d == d_min] = 0
f[(d > d_min) & (d < d_mean)] = 25
f[d == d_mean] = 50
f[(d > d_mean) & (d < d_max)] = 75
f[d == d_max] = 100





### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [41]:
print(d)
print(f)

[[[1.87860651 1.92077227 1.21262997 1.48554365 1.9372853 ]
  [1.70861208 1.18884171 1.3183815  1.50941561 1.96022178]
  [1.46827591 1.80086935 1.69757676 1.8575967  1.49181767]]

 [[1.01137793 1.74226323 1.30126172 1.64679946 1.4125845 ]
  [1.7471693  1.08877189 1.60246005 1.58103283 1.75498586]
  [1.78177947 1.72871877 1.23729971 1.70181209 1.84612777]]]
[[[ 75.  75.  25.  25.  75.]
  [ 75.  25.  25.  25. 100.]
  [ 25.  75.  75.  75.  25.]]

 [[  0.  75.  25.  75.  25.]
  [ 75.  25.  75.  25.  75.]
  [ 75.  75.  25.  75.  75.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [44]:
f_labels[f == 0] = "A"
f_labels[f == 25] = "B"
f_labels[f == 50] = "C"
f_labels[f == 75] = "D"
f_labels[f == 100] = "E"

print(f_labels)

[[['D' 'D' 'B' 'B' 'D']
  ['D' 'B' 'B' 'B' 'E']
  ['B' 'D' 'D' 'D' 'B']]

 [['A' 'D' 'B' 'D' 'B']
  ['D' 'B' 'D' 'B' 'D']
  ['D' 'D' 'B' 'D' 'D']]]
