# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [103]:
### [your code here]
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [104]:
### [your code here]
print(np.__version__)
print(np.show_config())

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/asus/anaconda3/envs/YAZEED/Library/include
    lib directory: C:/Users/asus/anaconda3/envs/YAZEED/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep2252572576928
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    syst

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [105]:
### [your code here]
a = np.random.random((2, 3, 5))

In [106]:

### 4. Print a.


In [107]:
### [your code here]
print(a)

[[[0.75598474 0.66719156 0.90264844 0.13981531 0.94529945]
  [0.10283402 0.09006537 0.64109482 0.00388422 0.30780654]
  [0.18772612 0.44548212 0.95409085 0.93241467 0.63866948]]

 [[0.00636513 0.69762396 0.56650476 0.0680885  0.09529761]
  [0.15868182 0.22209389 0.26487881 0.37993852 0.27436599]
  [0.4747637  0.35087413 0.85727901 0.39992271 0.45974113]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [108]:
### [your code here]
b = np.ones((5,2,3))


### 6. Print b.


In [109]:
### [your code here]
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [110]:
### [your code here]
print(a.size == b.size)

True



### 8. Are you able to add a and b? Why or why not?


In [111]:
### [your code here]
a = np.random.random((2, 3, 5))
b = np.ones((5,2,3))
result = a + b

print(result)
#operands could not be broadcast together with shapes (2,3,5) (5,2,3)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [116]:
### [your code here]
c = np.transpose(b, (1, 2, 0))
print(c)
print(c.shape)


[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
(2, 3, 5)



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [117]:
### [your code here]
d = a+c


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [118]:
### [your code here]
print("a:")
print(a)
print("d:")
print(d)
"""The array a contains random floating-point values, while the array d consists entirely of ones.
The relation between the two arrays is that d is used as a matrix of ones,
and when operations are performed between a and d,
the result is influenced by the values in a since multiplying any value by 1 will leave it unchanged.
This is the key difference: a holds varying data, while d is constant and uniform."""


a:
[[[0.02823104 0.88593231 0.08815    0.80564611 0.41568977]
  [0.41400386 0.25020303 0.97522745 0.38536942 0.10670396]
  [0.9422176  0.46021285 0.41037201 0.39683828 0.82956795]]

 [[0.53100404 0.39572743 0.87055042 0.60750661 0.03238996]
  [0.00715071 0.60954628 0.54812901 0.3089171  0.49815988]
  [0.14342585 0.52151998 0.50268411 0.22675801 0.31411156]]]
d:
[[[1.02823104 1.88593231 1.08815    1.80564611 1.41568977]
  [1.41400386 1.25020303 1.97522745 1.38536942 1.10670396]
  [1.9422176  1.46021285 1.41037201 1.39683828 1.82956795]]

 [[1.53100404 1.39572743 1.87055042 1.60750661 1.03238996]
  [1.00715071 1.60954628 1.54812901 1.3089171  1.49815988]
  [1.14342585 1.52151998 1.50268411 1.22675801 1.31411156]]]



### 12. Multiply a and c. Assign the result to e.


In [119]:
### [your code here]

e = a * c


print("e:\n", e)

e:
 [[[0.02823104 0.88593231 0.08815    0.80564611 0.41568977]
  [0.41400386 0.25020303 0.97522745 0.38536942 0.10670396]
  [0.9422176  0.46021285 0.41037201 0.39683828 0.82956795]]

 [[0.53100404 0.39572743 0.87055042 0.60750661 0.03238996]
  [0.00715071 0.60954628 0.54812901 0.3089171  0.49815988]
  [0.14342585 0.52151998 0.50268411 0.22675801 0.31411156]]]




### 13. Does e equal to a? Why or why not?


In [120]:
### [your code here]
e == a


array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [83]:
### [your code here]
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print("Max:", d_max)
print("Min:", d_min)
print("Mean:", d_mean)

Max: 1.5147426072673962
Min: 0.16737051296078587
Mean: 1.1116918282179762



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [122]:
### [your code here]
emp = np.empty(d.shape)
print(emp)

[[[0.02823104 0.88593231 0.08815    0.80564611 0.41568977]
  [0.41400386 0.25020303 0.97522745 0.38536942 0.10670396]
  [0.9422176  0.46021285 0.41037201 0.39683828 0.82956795]]

 [[0.53100404 0.39572743 0.87055042 0.60750661 0.03238996]
  [0.00715071 0.60954628 0.54812901 0.3089171  0.49815988]
  [0.14342585 0.52151998 0.50268411 0.22675801 0.31411156]]]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [131]:
for i in range(d.shape[0]):  
    for j in range(d.shape[1]):  
        for k in range(d.shape[2]): 
            value = d[i, j, k]
            if value == d_min:
                f[i, j, k] = 0
            elif value == d_max:
                f[i, j, k] = 100
            elif value == d_mean:
                f[i, j, k] = 50
            elif d_min < value < d_mean:
                f[i, j, k] = 25
            elif d_mean < value < d_max:
                f[i, j, k] = 75
print("Array d:\n", d)
print("Array f:\n", f)

Array d:
 [[[0.61948167 1.76736867 0.18890111]
  [1.49218209 1.78140008 1.592553  ]
  [0.3766279  1.3957658  0.45110866]]

 [[1.35004235 0.74686658 0.54544565]
  [0.69595985 1.39284695 0.04000634]
  [1.3373043  0.87924971 0.76160111]]

 [[0.43978811 0.27663961 0.44521212]
  [1.61779998 0.57212343 0.70992114]
  [1.42006578 1.19511146 1.77320464]]]
Array f:
 [[[ 25.  75.  25.]
  [ 75. 100.  75.]
  [ 25.  75.  25.]]

 [[ 75.  25.  25.]
  [ 25.  75.   0.]
  [ 75.  25.  25.]]

 [[ 25.  25.  25.]
  [ 75.  25.  25.]
  [ 75.  75.  75.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [132]:
for i in range(d.shape[0]):  
    for j in range(d.shape[1]):  
        for k in range(d.shape[2]):
            value = d[i, j, k]
            if value == d_min:
                f[i, j, k] = 0
            elif value == d_max:
                f[i, j, k] = 100
            elif value == d_mean:
                f[i, j, k] = 50
            elif d_min < value < d_mean:
                f[i, j, k] = 25
            elif d_mean < value < d_max:
                f[i, j, k] = 75
print("Array d:\n", d)
print("Array f:\n", f)

Array d:
 [[[0.61948167 1.76736867 0.18890111]
  [1.49218209 1.78140008 1.592553  ]
  [0.3766279  1.3957658  0.45110866]]

 [[1.35004235 0.74686658 0.54544565]
  [0.69595985 1.39284695 0.04000634]
  [1.3373043  0.87924971 0.76160111]]

 [[0.43978811 0.27663961 0.44521212]
  [1.61779998 0.57212343 0.70992114]
  [1.42006578 1.19511146 1.77320464]]]
Array f:
 [[[ 25.  75.  25.]
  [ 75. 100.  75.]
  [ 25.  75.  25.]]

 [[ 75.  25.  25.]
  [ 25.  75.   0.]
  [ 75.  25.  25.]]

 [[ 25.  25.  25.]
  [ 75.  25.  25.]
  [ 75.  75.  75.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [137]:
f = np.empty_like(d, dtype=object)
for i in range(d.shape[0]):  
    for j in range(d.shape[1]): 
        for k in range(d.shape[2]):  
            value = d[i, j, k]
            if value == d_min:
                f[i, j, k] = 'A'
            elif value == d_max:
                f[i, j, k] = 'E'
            elif value == d_mean:
                f[i, j, k] = 'C'
            elif d_min < value < d_mean:
                f[i, j, k] = 'B'
            elif d_mean < value < d_max:
                f[i, j, k] = 'D'


print("Array f:\n", f)

Array f:
 [[['B' 'D' 'B']
  ['D' 'E' 'D']
  ['B' 'D' 'B']]

 [['D' 'B' 'B']
  ['B' 'D' 'A']
  ['D' 'B' 'B']]

 [['B' 'B' 'B']
  ['D' 'B' 'B']
  ['D' 'D' 'D']]]
