# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
### [your code here]
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [2]:
### [your code here]
print("Version of numpy:", np.__version__)
print("Numpy configuration:")
np.show_config()

Version of numpy: 1.26.4
Numpy configuration:
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/ProgramData/anaconda3/Library/include
    lib directory: C:/ProgramData/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1583119523984
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [5]:
### [your code here]
a=np.random.random((2,3,5))


a=np.random.randint(5, size=(2,3,5))


a=np.random.uniform(10,20, size=(2,3,5))



### 4. Print a.


In [6]:
### [your code here]
print(a)

[[[15.49660004 10.92690018 16.77802012 10.90358561 14.00964668]
  [18.12728054 17.93503132 18.38386346 18.0313192  12.20957923]
  [17.2722531  18.81439503 18.62513584 13.34819673 18.81745318]]

 [[13.80131435 13.87552441 15.06819442 17.35342489 17.23728229]
  [17.65633887 17.92320931 19.86750258 10.74076138 17.33723111]
  [16.06558369 12.33165448 17.0722685  17.41962202 19.90701733]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [8]:
### [your code here]
b = np.ones((5, 2, 3))


### 6. Print b.


In [9]:
### [your code here]
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [11]:
### [your code here]
np.size(a) == np.size(b)

True


### 8. Are you able to add a and b? Why or why not?


In [16]:
### [your code here]
try:
    a+b
except ValueError as e:
    print(f"Due to different array shapes, the operation is not possible.\n",e)

Due to different array shapes, the operation is not possible.
 operands could not be broadcast together with shapes (2,3,5) (5,2,3) 




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [19]:
### [your code here]
c=np.transpose(b,(1,2,0))


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [ ]:
### [your code here]
try:
   d=a+c
except ValueError as e:
    print(f"Due to different array shapes, the operation is not possible.\n",e)  #Because they have the same shape now.


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [22]:
### [your code here]
print("a:\n",a)
print("d:\n",d)

#each element in a is incremented by 1 so now d is equal to a+1.

a:
 [[[15.49660004 10.92690018 16.77802012 10.90358561 14.00964668]
  [18.12728054 17.93503132 18.38386346 18.0313192  12.20957923]
  [17.2722531  18.81439503 18.62513584 13.34819673 18.81745318]]

 [[13.80131435 13.87552441 15.06819442 17.35342489 17.23728229]
  [17.65633887 17.92320931 19.86750258 10.74076138 17.33723111]
  [16.06558369 12.33165448 17.0722685  17.41962202 19.90701733]]]
d:
 [[[16.49660004 11.92690018 17.77802012 11.90358561 15.00964668]
  [19.12728054 18.93503132 19.38386346 19.0313192  13.20957923]
  [18.2722531  19.81439503 19.62513584 14.34819673 19.81745318]]

 [[14.80131435 14.87552441 16.06819442 18.35342489 18.23728229]
  [18.65633887 18.92320931 20.86750258 11.74076138 18.33723111]
  [17.06558369 13.33165448 18.0722685  18.41962202 20.90701733]]]



### 12. Multiply a and c. Assign the result to e.


In [25]:
### [your code here]
e=a*c
e

array([[[15.49660004, 10.92690018, 16.77802012, 10.90358561,
         14.00964668],
        [18.12728054, 17.93503132, 18.38386346, 18.0313192 ,
         12.20957923],
        [17.2722531 , 18.81439503, 18.62513584, 13.34819673,
         18.81745318]],

       [[13.80131435, 13.87552441, 15.06819442, 17.35342489,
         17.23728229],
        [17.65633887, 17.92320931, 19.86750258, 10.74076138,
         17.33723111],
        [16.06558369, 12.33165448, 17.0722685 , 17.41962202,
         19.90701733]]])



### 13. Does e equal to a? Why or why not?


In [27]:
### [your code here]
are_equal=np.array_equal(a,e)

print(are_equal)   # Because the elements in the array c were all 1.

True




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [30]:
### [your code here]

d_max=np.max(d)
print(d_max)

d_min=np.min(d)
print(d_min)

d_mean=np.mean(d)
print(d_mean)


20.907017334507486
11.740761375203867
17.111206328228928



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [31]:
### [your code here]
f=np.empty((2,3,5))
print(f)

[[[16.49660004 11.92690018 17.77802012 11.90358561 15.00964668]
  [19.12728054 18.93503132 19.38386346 19.0313192  13.20957923]
  [18.2722531  19.81439503 19.62513584 14.34819673 19.81745318]]

 [[14.80131435 14.87552441 16.06819442 18.35342489 18.23728229]
  [18.65633887 18.92320931 20.86750258 11.74076138 18.33723111]
  [17.06558369 13.33165448 18.0722685  18.41962202 20.90701733]]]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [39]:
### [your code here]
f[(d > d_min) & (d < d_mean)] = 25
f[(d > d_mean) & (d < d_max)] = 75 
f[d == d_mean] = 50
f[d == d_min] = 0
f[d == d_max] = 100

print(f)


[[[25 25 75 25 25]
  [75 75 75 75 25]
  [75 75 75 25 75]]

 [[25 25 25 75 75]
  [75 75 75 0 75]
  [25 25 75 75 100]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [40]:
### [your code here]
print(d)
print(f)

[[[16.49660004 11.92690018 17.77802012 11.90358561 15.00964668]
  [19.12728054 18.93503132 19.38386346 19.0313192  13.20957923]
  [18.2722531  19.81439503 19.62513584 14.34819673 19.81745318]]

 [[14.80131435 14.87552441 16.06819442 18.35342489 18.23728229]
  [18.65633887 18.92320931 20.86750258 11.74076138 18.33723111]
  [17.06558369 13.33165448 18.0722685  18.41962202 20.90701733]]]
[[[25 25 75 25 25]
  [75 75 75 75 25]
  [75 75 75 25 75]]

 [[25 25 25 75 75]
  [75 75 75 0 75]
  [25 25 75 75 100]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [42]:
### [your code here]

f[(d > d_min) & (d < d_mean)] = 'B'
f[(d > d_mean) & (d < d_max)] = 'D'
f[d == d_mean] = 'C'
f[d == d_min] = 'A'
f[d == d_max] = 'E'

print(f)

[[['B' 'B' 'D' 'B' 'B']
  ['D' 'D' 'D' 'D' 'B']
  ['D' 'D' 'D' 'B' 'D']]

 [['B' 'B' 'B' 'D' 'D']
  ['D' 'D' 'D' 'A' 'D']
  ['B' 'B' 'D' 'D' 'E']]]
