# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
!pip install numpy




### 2. Print the NUMPY version and the configuration.


In [2]:

import numpy as np

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [3]:

a = np.random.randint(4, size=(2,3,5))


### 4. Print a.


In [44]:
print(a)


[[[0 3 1 2 2]
  [2 1 3 1 3]
  [2 3 2 2 3]]

 [[0 3 0 0 0]
  [3 2 0 0 3]
  [1 2 1 0 0]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [4]:
b= np.ones((5, 2, 3))



### 6. Print b.


In [5]:
print(b)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [44]:
print(a.size, b.size)
a.size == b.size

30 30


True


### 8. Are you able to add a and b? Why or why not?


In [46]:
print(a.shape )
print(b.shape)
a.shape == b.shape
print("you cannot add a different shape of array together")

(2, 3, 5)
(5, 2, 3)
you cannot add a different shape of array together




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [54]:
c= np.reshape(b, (2, 3, 5))


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [57]:
d= a + c


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [56]:
print(d)


[[[1. 2. 4. 3. 3.]
  [4. 2. 4. 3. 3.]
  [4. 3. 1. 3. 4.]]

 [[4. 2. 2. 4. 2.]
  [2. 3. 3. 2. 1.]
  [2. 4. 2. 3. 2.]]]



### 12. Multiply a and c. Assign the result to e.


In [59]:
e= a * c
print(e)


[[[0. 1. 3. 2. 2.]
  [3. 1. 3. 2. 2.]
  [3. 2. 0. 2. 3.]]

 [[3. 1. 1. 3. 1.]
  [1. 2. 2. 1. 0.]
  [1. 3. 1. 2. 1.]]]




### 13. Does e equal to a? Why or why not?


In [60]:
e == a 



array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [63]:
d_max = np.max(d)
d_min= np.min(d)
d_mean= np.mean(d)
print('d max:', d_max)
print('d min:', d_min)
print('d mean:', d_mean)



d max: 4.0
d min: 1.0
d mean: 2.7333333333333334



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [83]:
f= np.empty_like(d)




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [89]:
f= np.where((d > d_min) & (d < d_mean), 25, f)
f= np.where((d > d_mean) & (d < d_max), 75, f)
f= np.where((d == d_mean), 50, f)
f= np.where((d == d_min), 0, f)
f= np.where((d == d_max), 100, f)






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [95]:
print(d) , print(f)

[[[1. 2. 4. 3. 3.]
  [4. 2. 4. 3. 3.]
  [4. 3. 1. 3. 4.]]

 [[4. 2. 2. 4. 2.]
  [2. 3. 3. 2. 1.]
  [2. 4. 2. 3. 2.]]]
[[[  0.  25. 100.  75.  75.]
  [100.  25. 100.  75.  75.]
  [100.  75.   0.  75. 100.]]

 [[100.  25.  25. 100.  25.]
  [ 25.  75.  75.  25.   0.]
  [ 25. 100.  25.  75.  25.]]]


(None, None)

### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [36]:
### [your code here]