# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [2]:
print("numpy verison:", np.__version__)
np.show_config()

numpy verison: 2.2.3
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30158",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.12",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30158",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.28",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-3gfa2f0z/cp311-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/includ

C:\Users\hp\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [3]:
a = np.random.random((2, 3, 5))


### 4. Print a.


In [4]:
print(a)


[[[0.16173591 0.03737299 0.91235002 0.16265448 0.91905932]
  [0.27349784 0.00553347 0.23532739 0.48006478 0.77489887]
  [0.32462704 0.31002902 0.70771584 0.61280649 0.04219424]]

 [[0.43425878 0.45269097 0.50104704 0.7388026  0.32855965]
  [0.9882214  0.37139443 0.87392476 0.80188663 0.95761069]
  [0.61434116 0.42076881 0.65591944 0.95719671 0.74914967]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [5]:
b = np.ones((5, 2, 3))



### 6. Print b.


In [6]:
print(b)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [7]:
sizea = np.size(a)
sizeb = np.size(b)
print(f"Is a have the same size to b? {sizea == sizeb}")

Is a have the same size to b? True



### 8. Are you able to add a and b? Why or why not?


In [10]:
try:
    add = a + b
    print("a and b are able to add")
except TypeError:
    print("a anf b are not able to add")

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [61]:
c = np.transpose(b, axes= (1,2,0))
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [62]:
d = a + c
try:  
    d = a + c
    print("we can a and c because they have the same size")
except TypeError:
    print("we can not add a and c")

we can a and c because they have the same size



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [74]:
print(f"a:{a}")
print(f"shape a: {a.shape}")
print(f"d:{d}")
print(f"shape d: {d.shape}")

a:[[[0.97901782 0.94441709 0.35188322 0.07353255 0.04386022]
  [0.9158778  0.45563806 0.03783118 0.87739392 0.89482554]
  [0.71482935 0.08430902 0.27480399 0.19143848 0.82216133]]

 [[0.79679816 0.70116496 0.40817567 0.94452684 0.40806582]
  [0.50907947 0.22880744 0.53248259 0.54468359 0.17117991]
  [0.18772744 0.25974109 0.49564376 0.32598226 0.34723456]]]
shape a: (2, 3, 5)
d:[[[1.97901782 1.94441709 1.35188322 1.07353255 1.04386022]
  [1.9158778  1.45563806 1.03783118 1.87739392 1.89482554]
  [1.71482935 1.08430902 1.27480399 1.19143848 1.82216133]]

 [[1.79679816 1.70116496 1.40817567 1.94452684 1.40806582]
  [1.50907947 1.22880744 1.53248259 1.54468359 1.17117991]
  [1.18772744 1.25974109 1.49564376 1.32598226 1.34723456]]]
shape d: (2, 3, 5)



### 12. Multiply a and c. Assign the result to e.


In [64]:
e = a * c
print(e)


[[[0.97901782 0.94441709 0.35188322 0.07353255 0.04386022]
  [0.9158778  0.45563806 0.03783118 0.87739392 0.89482554]
  [0.71482935 0.08430902 0.27480399 0.19143848 0.82216133]]

 [[0.79679816 0.70116496 0.40817567 0.94452684 0.40806582]
  [0.50907947 0.22880744 0.53248259 0.54468359 0.17117991]
  [0.18772744 0.25974109 0.49564376 0.32598226 0.34723456]]]




### 13. Does e equal to a? Why or why not?


In [65]:
try:
    e == a 
    print("e = a")
except TypeError:
    print("not equal")



e = a




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [69]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(f"d_max: {d_max}, d_min: {d_min}, d_mean: {d_mean}")


d_max: 1.9790178209384601, d_min: 1.0378311830889886, d_mean: 1.484103770718376



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [71]:
f = np.empty_like(d)
print(f)

[[[0.97901782 0.94441709 0.35188322 0.07353255 0.04386022]
  [0.9158778  0.45563806 0.03783118 0.87739392 0.89482554]
  [0.71482935 0.08430902 0.27480399 0.19143848 0.82216133]]

 [[0.79679816 0.70116496 0.40817567 0.94452684 0.40806582]
  [0.50907947 0.22880744 0.53248259 0.54468359 0.17117991]
  [0.18772744 0.25974109 0.49564376 0.32598226 0.34723456]]]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [78]:
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i, j, k] == d_min:
                f[i, j, k] = 0
            elif d[i, j, k] == d_max:
                f[i, j, k] = 100
            elif d[i, j, k] == d_mean:
                f[i, j, k] = 50
            elif d_min < d[i, j, k] < d_mean:
                f[i, j, k] = 25
            elif d_mean < d[i, j, k] < d_max:
                f[i, j, k] = 75






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [79]:
print("d:")
print(d)
print("f:")
print(f)


d:
[[[1.97901782 1.94441709 1.35188322 1.07353255 1.04386022]
  [1.9158778  1.45563806 1.03783118 1.87739392 1.89482554]
  [1.71482935 1.08430902 1.27480399 1.19143848 1.82216133]]

 [[1.79679816 1.70116496 1.40817567 1.94452684 1.40806582]
  [1.50907947 1.22880744 1.53248259 1.54468359 1.17117991]
  [1.18772744 1.25974109 1.49564376 1.32598226 1.34723456]]]
f:
[[[100.  75.  25.  25.  25.]
  [ 75.  25.   0.  75.  75.]
  [ 75.  25.  25.  25.  75.]]

 [[ 75.  75.  25.  75.  25.]
  [ 75.  25.  75.  75.  25.]
  [ 25.  25.  75.  25.  25.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [80]:
f_string = np.empty_like(f, dtype=object)
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i, j, k] == d_min:
                f_string[i, j, k] = 'A'
            elif d[i, j, k] == d_max:
                f_string[i, j, k] = 'E'
            elif d[i, j, k] == d_mean:
                f_string[i, j, k] = 'C'
            elif d_min < d[i, j, k] < d_mean:
                f_string[i, j, k] = 'B'
            elif d_mean < d[i, j, k] < d_max:
                f_string[i, j, k] = 'D'

print("f with string labels:")
print(f_string)

f with string labels:
[[['E' 'D' 'B' 'B' 'B']
  ['D' 'B' 'A' 'D' 'D']
  ['D' 'B' 'B' 'B' 'D']]

 [['D' 'D' 'B' 'D' 'B']
  ['D' 'B' 'D' 'D' 'B']
  ['B' 'B' 'D' 'B' 'B']]]
