# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [4]:
pip install numpy


     ---------------------------------------- 0.0/60.8 kB ? eta -:--:--
     -------------------- ------------------- 30.7/60.8 kB ? eta -:--:--
     -------------------- ------------------- 30.7/60.8 kB ? eta -:--:--
     ------------------------------- ------ 51.2/60.8 kB 327.7 kB/s eta 0:00:01
     -------------------------------------- 60.8/60.8 kB 324.4 kB/s eta 0:00:00
   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
   ---------------------------------------- 0.1/12.9 MB 5.1 MB/s eta 0:00:03
   ---------------------------------------- 0.1/12.9 MB 5.1 MB/s eta 0:00:03
   ---------------------------------------- 0.1/12.9 MB 5.1 MB/s eta 0:00:03
   - -------------------------------------- 0.3/12.9 MB 1.6 MB/s eta 0:00:09
   -- ------------------------------------- 0.7/12.9 MB 2.9 MB/s eta 0:00:05
   -- ---------------------


[notice] A new release of pip is available: 24.0 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [1]:
### [your code here] 
import numpy as np





### 2. Print the NUMPY version and the configuration.


In [2]:
### [your code here]
print (np.__version__)


2.2.3


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [3]:
### [your code here]
a=np.random.randint(100,size=(2,3,5))


### 4. Print a.


In [4]:
### [your code here]
print(a)

[[[62 36 43 26  9]
  [36 16 75 43 95]
  [96 71 94  8 16]]

 [[23 67  5 98 58]
  [26 63  4 67 72]
  [92 52 90 19 50]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [7]:
### [your code here]
b = np.ones((5, 2, 3))




### 6. Print b.


In [6]:
### [your code here]
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [8]:
### [your code here]
are_shapes_equal = a.shape == b.shape
print(f"Do a and b have the same shape? {are_shapes_equal}")


Do a and b have the same shape? False



### 8. Are you able to add a and b? Why or why not?


In [9]:
### [your code here]
if a.shape==b.shape:
   result(a+b)
   print ("Addition successful!")
else:
   print("Arrays cannot be added due to shape mismatch.")




Arrays cannot be added due to shape mismatch.




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [10]:
### [your code here]
c = np.transpose(b, (1, 2, 0))




### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [11]:
### [your code here]
d = a + c
print(d)
print("Addition successful!")


[[[63. 37. 44. 27. 10.]
  [37. 17. 76. 44. 96.]
  [97. 72. 95.  9. 17.]]

 [[24. 68.  6. 99. 59.]
  [27. 64.  5. 68. 73.]
  [93. 53. 91. 20. 51.]]]
Addition successful!



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [12]:
### [your code here]
print(a)
print(d)
print("")



[[[62 36 43 26  9]
  [36 16 75 43 95]
  [96 71 94  8 16]]

 [[23 67  5 98 58]
  [26 63  4 67 72]
  [92 52 90 19 50]]]
[[[63. 37. 44. 27. 10.]
  [37. 17. 76. 44. 96.]
  [97. 72. 95.  9. 17.]]

 [[24. 68.  6. 99. 59.]
  [27. 64.  5. 68. 73.]
  [93. 53. 91. 20. 51.]]]




### 12. Multiply a and c. Assign the result to e.


In [13]:
### [your code here]
e = a * c
print("Multiplication successful!")



Multiplication successful!




### 13. Does e equal to a? Why or why not?


In [14]:
### [your code here]
are_equal = np.array_equal(a, e)
print(f"Is e equal to a? {are_equal}")


Is e equal to a? True




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [15]:
### [your code here]
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)


print(f"Max value in d: {d_max}")
print(f"Min value in d: {d_min}")
print(f"Mean value in d: {d_mean}")



Max value in d: 99.0
Min value in d: 5.0
Mean value in d: 51.4



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [16]:
### [your code here]
f = np.empty_like(d)
print(f)

[[[63. 37. 44. 27. 10.]
  [37. 17. 76. 44. 96.]
  [97. 72. 95.  9. 17.]]

 [[24. 68.  6. 99. 59.]
  [27. 64.  5. 68. 73.]
  [93. 53. 91. 20. 51.]]]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [17]:
### [your code here]

f[(d > d_min) & (d < d_mean)] = 25

print(f)



[[[63. 25. 25. 25. 25.]
  [25. 25. 76. 25. 96.]
  [97. 72. 95. 25. 25.]]

 [[25. 68. 25. 99. 59.]
  [25. 64.  5. 68. 73.]
  [93. 53. 91. 25. 25.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [18]:
### [your code here]
print (d)
print (f)

[[[63. 37. 44. 27. 10.]
  [37. 17. 76. 44. 96.]
  [97. 72. 95.  9. 17.]]

 [[24. 68.  6. 99. 59.]
  [27. 64.  5. 68. 73.]
  [93. 53. 91. 20. 51.]]]
[[[63. 25. 25. 25. 25.]
  [25. 25. 76. 25. 96.]
  [97. 72. 95. 25. 25.]]

 [[25. 68. 25. 99. 59.]
  [25. 64.  5. 68. 73.]
  [93. 53. 91. 25. 25.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [19]:
### [your code here]
labels = ["A", "B", "C", "D", "E"]


f_str = np.empty_like(f, dtype="<U1")  


d_min = np.min(d)
d_mean = np.mean(d)


f_str[(d > d_min) & (d < d_mean)] = "B"
f_str[d >= d_mean] = "D"
f_str[d <= d_min] = "A"


print("Array with labeled values:")
print(f_str)

Array with labeled values:
[[['D' 'B' 'B' 'B' 'B']
  ['B' 'B' 'D' 'B' 'D']
  ['D' 'D' 'D' 'B' 'B']]

 [['B' 'D' 'B' 'D' 'D']
  ['B' 'D' 'A' 'D' 'D']
  ['D' 'D' 'D' 'B' 'B']]]
