# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [63]:
### [your code here]
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [64]:
### [your code here]
print(np.__version__)
np.show_config()

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/rkhm3/anaconda3/Library/include
    lib directory: C:/Users/rkhm3/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1583119523984
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  host:
  

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [65]:
### [your code here]
a = np.random.random(size=(2, 3, 5)) 


### 4. Print a.


In [66]:
### [your code here]
print(a)

[[[0.62971224 0.89730071 0.35492579 0.4218182  0.87085444]
  [0.76594119 0.82154549 0.15170909 0.18721966 0.78316255]
  [0.424561   0.73728422 0.20746249 0.72274387 0.34622124]]

 [[0.25602177 0.26324516 0.50564498 0.03529049 0.32461571]
  [0.01439851 0.36996806 0.50957881 0.89648666 0.14316236]
  [0.00220158 0.08955834 0.35130022 0.16388627 0.68117168]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [67]:
### [your code here]
b = np.ones((5,2,3))


### 6. Print b.


In [68]:
### [your code here]
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])


### 7. Do a and b have the same size? How do you prove that in Python code?


In [69]:
### [your code here]
print(a.size == b.size)
print(f"a size is {a.size} and b size is {b.size}")

True
a size is 30 and b size is 30



### 8. Are you able to add a and b? Why or why not?


In [70]:
### [your code here]
print(f"a and b could not be add together becouse there shapes dose not match.\n a shape is {a.shape}, b shape is {b.shape}")

a and b could not be add together becouse there shapes dose not match.
 a shape is (2, 3, 5), b shape is (5, 2, 3)




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [71]:
### [your code here]
c = np.transpose(b, (1,2,0))
c.shape

(2, 3, 5)


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [72]:
### [your code here]
d= a + c 
print(d)
print("We can add a and c becouse they have the same shape")

[[[1.62971224 1.89730071 1.35492579 1.4218182  1.87085444]
  [1.76594119 1.82154549 1.15170909 1.18721966 1.78316255]
  [1.424561   1.73728422 1.20746249 1.72274387 1.34622124]]

 [[1.25602177 1.26324516 1.50564498 1.03529049 1.32461571]
  [1.01439851 1.36996806 1.50957881 1.89648666 1.14316236]
  [1.00220158 1.08955834 1.35130022 1.16388627 1.68117168]]]
We can add a and c becouse they have the same shape



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [73]:
### [your code here]
print(a)
print(d)


[[[0.62971224 0.89730071 0.35492579 0.4218182  0.87085444]
  [0.76594119 0.82154549 0.15170909 0.18721966 0.78316255]
  [0.424561   0.73728422 0.20746249 0.72274387 0.34622124]]

 [[0.25602177 0.26324516 0.50564498 0.03529049 0.32461571]
  [0.01439851 0.36996806 0.50957881 0.89648666 0.14316236]
  [0.00220158 0.08955834 0.35130022 0.16388627 0.68117168]]]
[[[1.62971224 1.89730071 1.35492579 1.4218182  1.87085444]
  [1.76594119 1.82154549 1.15170909 1.18721966 1.78316255]
  [1.424561   1.73728422 1.20746249 1.72274387 1.34622124]]

 [[1.25602177 1.26324516 1.50564498 1.03529049 1.32461571]
  [1.01439851 1.36996806 1.50957881 1.89648666 1.14316236]
  [1.00220158 1.08955834 1.35130022 1.16388627 1.68117168]]]



### 12. Multiply a and c. Assign the result to e.


In [74]:
### [your code here]
e = a * c
e

array([[[0.62971224, 0.89730071, 0.35492579, 0.4218182 , 0.87085444],
        [0.76594119, 0.82154549, 0.15170909, 0.18721966, 0.78316255],
        [0.424561  , 0.73728422, 0.20746249, 0.72274387, 0.34622124]],

       [[0.25602177, 0.26324516, 0.50564498, 0.03529049, 0.32461571],
        [0.01439851, 0.36996806, 0.50957881, 0.89648666, 0.14316236],
        [0.00220158, 0.08955834, 0.35130022, 0.16388627, 0.68117168]]])



### 13. Does e equal to a? Why or why not?


In [75]:
### [your code here]
print(e == a) 
print("True becouse they have the same values")

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]
True becouse they have the same values




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [76]:
### [your code here]
d_max = np.max(d)
print(d_max)

1.8973007146880128


In [77]:
d_min = np.min(d) 
print(d_min)

1.0022015791607208


In [78]:
d_mean = np.mean(d)
print(d_mean)

1.430966425820721



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [79]:
### [your code here]
f = np.empty((2,3,5))
f

array([[[0.62971224, 0.89730071, 0.35492579, 0.4218182 , 0.87085444],
        [0.76594119, 0.82154549, 0.15170909, 0.18721966, 0.78316255],
        [0.424561  , 0.73728422, 0.20746249, 0.72274387, 0.34622124]],

       [[0.25602177, 0.26324516, 0.50564498, 0.03529049, 0.32461571],
        [0.01439851, 0.36996806, 0.50957881, 0.89648666, 0.14316236],
        [0.00220158, 0.08955834, 0.35130022, 0.16388627, 0.68117168]]])




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [80]:
### [your code here]
for i in range(2):
    for j in range(3):
        for k in range(5):
            if d[i,j,k] > d_min and d[i,j,k] < d_mean:
                f[i,j,k] = 25
            elif d[i,j,k] > d_mean and d[i,j,k] < d_max:
                f[i,j,k] = 75
            elif d[i,j,k] == d_mean:
                f[i,j,k] = 50
            elif d[i,j,k] == d_min:
                f[i,j,k] = 0
            elif d[i,j,k] == d_max:
                f[i,j,k] = 100
            else:
                f[i,j,k] = d[i,j,k]
            
print(f)

[[[ 75. 100.  25.  25.  75.]
  [ 75.  75.  25.  25.  75.]
  [ 25.  75.  25.  75.  25.]]

 [[ 25.  25.  75.  25.  25.]
  [ 25.  25.  75.  75.  25.]
  [  0.  25.  25.  25.  75.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [81]:
### [your code here]
print(d)
print(f)

[[[1.62971224 1.89730071 1.35492579 1.4218182  1.87085444]
  [1.76594119 1.82154549 1.15170909 1.18721966 1.78316255]
  [1.424561   1.73728422 1.20746249 1.72274387 1.34622124]]

 [[1.25602177 1.26324516 1.50564498 1.03529049 1.32461571]
  [1.01439851 1.36996806 1.50957881 1.89648666 1.14316236]
  [1.00220158 1.08955834 1.35130022 1.16388627 1.68117168]]]
[[[ 75. 100.  25.  25.  75.]
  [ 75.  75.  25.  25.  75.]
  [ 25.  75.  25.  75.  25.]]

 [[ 25.  25.  75.  25.  25.]
  [ 25.  25.  75.  75.  25.]
  [  0.  25.  25.  25.  75.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [ ]:
value_map = {0: 'A', 25: 'B', 50: 'C', 75: 'D', 100: 'E'}

labeled_array = np.vectorize(value_map.get)(f)
labeled_array

array([[['D', 'E', 'B', 'B', 'D'],
        ['D', 'D', 'B', 'B', 'D'],
        ['B', 'D', 'B', 'D', 'B']],

       [['B', 'B', 'D', 'B', 'B'],
        ['B', 'B', 'D', 'D', 'B'],
        ['A', 'B', 'B', 'B', 'D']]], dtype='<U1')