# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [187]:
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [190]:
print("NumPy Version:", np.__version__)
np.show_config()

NumPy Version: 1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/Lano/anaconda3/Library/include
    lib directory: C:/Users/Lano/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1583119523984
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windo

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [193]:
# 1 way to use numpy randome array
a = np.random.rand(2, 3, 5)
# 2 way to use numpy randome array
a = np.random.randn(2, 3, 5)
# 3 way to use numpy randome array
a = np.random.randint(0, 100, (2, 3, 5))
print(a)

[[[96 90 70 79 46]
  [59 47 96 21 47]
  [ 2 94 27 77 83]]

 [[36 82 60  6 24]
  [72 38  3 34  6]
  [43 73 38 68 38]]]



### 4. Print a.


In [196]:
print(a)

[[[96 90 70 79 46]
  [59 47 96 21 47]
  [ 2 94 27 77 83]]

 [[36 82 60  6 24]
  [72 38  3 34  6]
  [43 73 38 68 38]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [199]:
b = np.ones((5, 2, 3), dtype=int)


### 6. Print b.


In [202]:
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [205]:
print("Size of a:", a.size)
print("Size of b:", b.size)

same_size = a.size == b.size
print("Do a and b have the same size?", same_size)

Size of a: 30
Size of b: 30
Do a and b have the same size? True



### 8. Are you able to add a and b? Why or why not?


In [208]:
#No, we cannot add a and b directly because of the difference in shape between them.
# Try to add a and b
try:
    result = a + b
    print("Addition successful!")
except ValueError as e:
    print("Error:", e)


Error: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [211]:
# Change the order of the axes to (2,3,5)
c = np.transpose(b, (1, 2, 0))  
# print shape to confirm
print("Shape of b:", b.shape)  # (5,2,3)
print("Shape of c:", c.shape)  # (2,3,5) 



Shape of b: (5, 2, 3)
Shape of c: (2, 3, 5)



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [214]:
#After converting b to c using np.transpose(): the shape becomes (2, 3, 5), which is the same as a
d = a + c  
print(d)


[[[97 91 71 80 47]
  [60 48 97 22 48]
  [ 3 95 28 78 84]]

 [[37 83 61  7 25]
  [73 39  4 35  7]
  [44 74 39 69 39]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [217]:
"""The difference between a and d:
a contains random values between 0 and 100, d contains the same random values as a but 1 has been added to each value.
The relationship between a and d:
d is a modified version of a where 1 has been added to every element in a.
If an element in a is x, then the same element in d will be x + 1.

"""
print("Array a:\n",a)
print("\nArray d:\n",d)

Array a:
 [[[96 90 70 79 46]
  [59 47 96 21 47]
  [ 2 94 27 77 83]]

 [[36 82 60  6 24]
  [72 38  3 34  6]
  [43 73 38 68 38]]]

Array d:
 [[[97 91 71 80 47]
  [60 48 97 22 48]
  [ 3 95 28 78 84]]

 [[37 83 61  7 25]
  [73 39  4 35  7]
  [44 74 39 69 39]]]



### 12. Multiply a and c. Assign the result to e.


In [220]:
e = a * c 
print("Array a:\n",e)

Array a:
 [[[96 90 70 79 46]
  [59 47 96 21 47]
  [ 2 94 27 77 83]]

 [[36 82 60  6 24]
  [72 38  3 34  6]
  [43 73 38 68 38]]]




### 13. Does e equal to a? Why or why not?


In [223]:
#Yes, matrix e is equal to matrix a, because we multiplied matrix a by matrix c, which has values equal to 1 in all its elements.
are_ab__equal = np.array_equal(a, e)
print("Are e and a equal?", are_ab__equal)


Are e and a equal? True




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [226]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print("Max value in d:", d_max)
print("Min value in d:", d_min)
print("Mean value in d:", d_mean)


Max value in d: 97
Min value in d: 3
Mean value in d: 52.833333333333336



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [229]:
f = np.empty(d.shape)

print("Shape of f:", f.shape)


Shape of f: (2, 3, 5)





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [232]:
for i in range(len(d)):  
    for j in range(len(d[i])): 
        for k in range(len(d[i][j])):  
            if d[i, j, k] == d_min:
                f[i, j, k] = 0
            elif d[i, j, k] == d_max:
                f[i, j, k] = 100
            elif d[i, j, k] == d_mean:
                f[i, j, k] = 50
            elif d_min < d[i, j, k] < d_mean:
                f[i, j, k] = 25
            elif d_mean < d[i, j, k] < d_max:
                f[i, j, k] = 75
                
print("Array f:\n",f)

Array f:
 [[[100.  75.  75.  75.  25.]
  [ 75.  25. 100.  25.  25.]
  [  0.  75.  25.  75.  75.]]

 [[ 25.  75.  75.  25.  25.]
  [ 75.  25.  25.  25.  25.]
  [ 25.  75.  25.  75.  25.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [235]:
print("Array a:\n",d)
print("Array f:\n",f)

Array a:
 [[[97 91 71 80 47]
  [60 48 97 22 48]
  [ 3 95 28 78 84]]

 [[37 83 61  7 25]
  [73 39  4 35  7]
  [44 74 39 69 39]]]
Array f:
 [[[100.  75.  75.  75.  25.]
  [ 75.  25. 100.  25.  25.]
  [  0.  75.  25.  75.  75.]]

 [[ 25.  75.  75.  25.  25.]
  [ 75.  25.  25.  25.  25.]
  [ 25.  75.  25.  75.  25.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [238]:
f = np.empty_like(d, dtype=object)
for i in range(len(d)):  
    for j in range(len(d[i])):  
        for k in range(len(d[i][j])): 
            if d[i, j, k] == d_min:
                f[i, j, k] = 'A'  
            elif d[i, j, k] == d_max:
                f[i, j, k] = 'E' 
            elif d[i, j, k] == d_mean:
                f[i, j, k] = 'C' 
            elif d_min < d[i, j, k] < d_mean:
                f[i, j, k] = 'B'  
            elif d_mean < d[i, j, k] < d_max:
                f[i, j, k] = 'D'

print("Array f:\n", f)

Array f:
 [[['E' 'D' 'D' 'D' 'B']
  ['D' 'B' 'E' 'B' 'B']
  ['A' 'D' 'B' 'D' 'D']]

 [['B' 'D' 'D' 'B' 'B']
  ['D' 'B' 'B' 'B' 'B']
  ['B' 'D' 'B' 'D' 'B']]]
