# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [3]:
### [your code here]
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [4]:
print(np.__version__)

1.26.4


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [5]:
### [your code here]
a = np.random.random(size=(2,3,5))


### 4. Print a.


In [6]:
### [your code here]
print(a)

[[[0.76095205 0.75222261 0.48477716 0.02746439 0.31286769]
  [0.93469079 0.52113769 0.87888511 0.75722512 0.97832949]
  [0.87818213 0.84405128 0.39802762 0.51556884 0.14761184]]

 [[0.74406698 0.23767507 0.24759737 0.77231217 0.68416323]
  [0.16787847 0.73419601 0.30064182 0.09884701 0.36064287]
  [0.21730134 0.98698378 0.94499348 0.98475382 0.9736853 ]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [7]:
### [your code here]
b = np.ones((5,2,3))


### 6. Print b.


In [8]:
### [your code here]
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [9]:
### [your code here]
if a.size == b.size:
    print("a and b have same size.")
else:
    print("a and b NOT same size")

a and b have same size.



### 8. Are you able to add a and b? Why or why not?


In [10]:
### [your code here]
np.add(a,b)

#could not add 'a' to 'b' because there are not same shape

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [11]:
### [your code here]
c = np.transpose(b,(1,2,0))
print(c.shape)

(2, 3, 5)



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [82]:
### [your code here]
d = a + c
print(d)
#it works because the 'a' is same shape with 'b'

[[[1.76095205 1.75222261 1.48477716 1.02746439 1.31286769]
  [1.93469079 1.52113769 1.87888511 1.75722512 1.97832949]
  [1.87818213 1.84405128 1.39802762 1.51556884 1.14761184]]

 [[1.74406698 1.23767507 1.24759737 1.77231217 1.68416323]
  [1.16787847 1.73419601 1.30064182 1.09884701 1.36064287]
  [1.21730134 1.98698378 1.94499348 1.98475382 1.9736853 ]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [83]:
### [your code here]
print('a:',a)
print("a dimention: ",a.ndim,'\na shape: ',a.shape,'\na size: ',a.size)
print('\nd:',d)
print("d dimention: ",d.ndim,'\nd shape: ',d.shape,'\nd size: ',d.size)


a: [[[0.76095205 0.75222261 0.48477716 0.02746439 0.31286769]
  [0.93469079 0.52113769 0.87888511 0.75722512 0.97832949]
  [0.87818213 0.84405128 0.39802762 0.51556884 0.14761184]]

 [[0.74406698 0.23767507 0.24759737 0.77231217 0.68416323]
  [0.16787847 0.73419601 0.30064182 0.09884701 0.36064287]
  [0.21730134 0.98698378 0.94499348 0.98475382 0.9736853 ]]]
a dimention:  3 
a shape:  (2, 3, 5) 
a size:  30

d: [[[1.76095205 1.75222261 1.48477716 1.02746439 1.31286769]
  [1.93469079 1.52113769 1.87888511 1.75722512 1.97832949]
  [1.87818213 1.84405128 1.39802762 1.51556884 1.14761184]]

 [[1.74406698 1.23767507 1.24759737 1.77231217 1.68416323]
  [1.16787847 1.73419601 1.30064182 1.09884701 1.36064287]
  [1.21730134 1.98698378 1.94499348 1.98475382 1.9736853 ]]]
d dimention:  3 
d shape:  (2, 3, 5) 
d size:  30



### 12. Multiply a and c. Assign the result to e.


In [84]:
### [your code here]
e = a*c
print("Multiply 'a' and 'c'= \n",e)

Multiply 'a' and 'c'= 
 [[[0.76095205 0.75222261 0.48477716 0.02746439 0.31286769]
  [0.93469079 0.52113769 0.87888511 0.75722512 0.97832949]
  [0.87818213 0.84405128 0.39802762 0.51556884 0.14761184]]

 [[0.74406698 0.23767507 0.24759737 0.77231217 0.68416323]
  [0.16787847 0.73419601 0.30064182 0.09884701 0.36064287]
  [0.21730134 0.98698378 0.94499348 0.98475382 0.9736853 ]]]




### 13. Does e equal to a? Why or why not?


In [85]:
### [your code here]
if e.size == a.size:
    print("e and a have same size.")
else:
    print("e and a NOT same size")


e and a have same size.




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [86]:
### [your code here]
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print("d_max=",d_max,"\nd_min=",d_min,"\nd_mean=",d_mean)

d_max= 1.9869837775392698 
d_min= 1.027464392576243 
d_mean= 1.5882577509687261



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [87]:
### [your code here]
f = np.empty(d.shape)
print(f)

[[[0.76095205 0.75222261 0.48477716 0.02746439 0.31286769]
  [0.93469079 0.52113769 0.87888511 0.75722512 0.97832949]
  [0.87818213 0.84405128 0.39802762 0.51556884 0.14761184]]

 [[0.74406698 0.23767507 0.24759737 0.77231217 0.68416323]
  [0.16787847 0.73419601 0.30064182 0.09884701 0.36064287]
  [0.21730134 0.98698378 0.94499348 0.98475382 0.9736853 ]]]


In [91]:
print(d)
print(f)

[[[1.76095205 1.75222261 1.48477716 1.02746439 1.31286769]
  [1.93469079 1.52113769 1.87888511 1.75722512 1.97832949]
  [1.87818213 1.84405128 1.39802762 1.51556884 1.14761184]]

 [[1.74406698 1.23767507 1.24759737 1.77231217 1.68416323]
  [1.16787847 1.73419601 1.30064182 1.09884701 1.36064287]
  [1.21730134 1.98698378 1.94499348 1.98475382 1.9736853 ]]]
[[[0.76095205 0.75222261 0.48477716 0.02746439 0.31286769]
  [0.93469079 0.52113769 0.87888511 0.75722512 0.97832949]
  [0.87818213 0.84405128 0.39802762 0.51556884 0.14761184]]

 [[0.74406698 0.23767507 0.24759737 0.77231217 0.68416323]
  [0.16787847 0.73419601 0.30064182 0.09884701 0.36064287]
  [0.21730134 0.98698378 0.94499348 0.98475382 0.9736853 ]]]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [ ]:
### [your code here]
for i in range(f.shape[0]):
    for j in range(f.shape[1]):
        for k in range(f.shape[2]):
            value = d[i, j, k]
            if value == d_min:
                f[i, j, k] = 0
            elif value == d_max:
                f[i, j, k] = 100
            elif value == d_mean:
                f[i, j, k] = 50
            elif d_min < value < d_mean:
                f[i, j, k] = 25
            elif d_mean < value < d_max:
                f[i, j, k] = 75


 [[[ 75.  75.  25.   0.  25.]
  [ 75.  25.  75.  75.  75.]
  [ 75.  75.  25.  25.  25.]]

 [[ 75.  25.  25.  75.  75.]
  [ 25.  75.  25.  25.  25.]
  [ 25. 100.  75.  75.  75.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [100]:
### [your code here]
print(d)
print('\n',f)

[[[1.76095205 1.75222261 1.48477716 1.02746439 1.31286769]
  [1.93469079 1.52113769 1.87888511 1.75722512 1.97832949]
  [1.87818213 1.84405128 1.39802762 1.51556884 1.14761184]]

 [[1.74406698 1.23767507 1.24759737 1.77231217 1.68416323]
  [1.16787847 1.73419601 1.30064182 1.09884701 1.36064287]
  [1.21730134 1.98698378 1.94499348 1.98475382 1.9736853 ]]]

 [[[ 75.  75.  25.   0.  25.]
  [ 75.  25.  75.  75.  75.]
  [ 75.  75.  25.  25.  25.]]

 [[ 75.  25.  25.  75.  75.]
  [ 25.  75.  25.  25.  25.]
  [ 25. 100.  75.  75.  75.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [102]:
### [your code here]
f = np.empty_like(d, dtype=object)
for i in range(f.shape[0]):
    for j in range(f.shape[1]):
        for k in range(f.shape[2]):
            value = d[i, j, k]
            if value == d_min:
                f[i, j, k] = 'A'
            elif value == d_max:
                f[i, j, k] = 'B'
            elif value == d_mean:
                f[i, j, k] = 'C'
            elif d_min < value < d_mean:
                f[i, j, k] = 'D'
            elif d_mean < value < d_max:
                f[i, j, k] = 'E'

In [103]:
print(f)

[[['E' 'E' 'D' 'A' 'D']
  ['E' 'D' 'E' 'E' 'E']
  ['E' 'E' 'D' 'D' 'D']]

 [['E' 'D' 'D' 'E' 'E']
  ['D' 'E' 'D' 'D' 'D']
  ['D' 'B' 'E' 'E' 'E']]]
