# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [2]:
print(np.version.version)


2.2.3


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [91]:
a = np.random.rand(2,3,5)



### 4. Print a.


In [92]:
print("\na:")
print(a)



a:
[[[0.60571655 0.56758587 0.16215694 0.05165878 0.9581245 ]
  [0.03308898 0.09812579 0.52496867 0.47925435 0.91026106]
  [0.19973755 0.68043439 0.20254275 0.72489806 0.37171133]]

 [[0.6048057  0.54244354 0.61450157 0.47360174 0.19561611]
  [0.75985882 0.07547208 0.82692792 0.39837969 0.06907573]
  [0.40016749 0.7452215  0.75099786 0.07135298 0.53115444]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [93]:
b = np.ones((5, 2, 3))



### 6. Print b.


In [94]:
print("\nb:")
print(b)



b:
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [95]:
a_size = a.size
b_size = b.size

if a_size == b_size:
  print(f"{a_size} and {b_size} have same size")
else:
    print(f"{a_size} and {b_size} have different size")

30 and 30 have same size



### 8. Are you able to add a and b? Why or why not?


In [97]:
#No, because they have different shape.




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [120]:
b = np.ones((5, 2, 3))
c = b.transpose(1, 2, 0)
print("\nc:")
print(c)
c_shape = c.shape
print(c_shape)


c:
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
(2, 3, 5)



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [121]:
d =(a +c)
print(d)



[[[1.60571655 1.56758587 1.16215694 1.05165878 1.9581245 ]
  [1.03308898 1.09812579 1.52496867 1.47925435 1.91026106]
  [1.19973755 1.68043439 1.20254275 1.72489806 1.37171133]]

 [[1.6048057  1.54244354 1.61450157 1.47360174 1.19561611]
  [1.75985882 1.07547208 1.82692792 1.39837969 1.06907573]
  [1.40016749 1.7452215  1.75099786 1.07135298 1.53115444]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [122]:
print("\na:")
print(a)
print("\nd:")
print(d)
 #c = ones array, the result is:
#Meaning every element in d is exactly 1 unit greater than the corresponding element in a.



a:
[[[0.60571655 0.56758587 0.16215694 0.05165878 0.9581245 ]
  [0.03308898 0.09812579 0.52496867 0.47925435 0.91026106]
  [0.19973755 0.68043439 0.20254275 0.72489806 0.37171133]]

 [[0.6048057  0.54244354 0.61450157 0.47360174 0.19561611]
  [0.75985882 0.07547208 0.82692792 0.39837969 0.06907573]
  [0.40016749 0.7452215  0.75099786 0.07135298 0.53115444]]]

d:
[[[1.60571655 1.56758587 1.16215694 1.05165878 1.9581245 ]
  [1.03308898 1.09812579 1.52496867 1.47925435 1.91026106]
  [1.19973755 1.68043439 1.20254275 1.72489806 1.37171133]]

 [[1.6048057  1.54244354 1.61450157 1.47360174 1.19561611]
  [1.75985882 1.07547208 1.82692792 1.39837969 1.06907573]
  [1.40016749 1.7452215  1.75099786 1.07135298 1.53115444]]]



### 12. Multiply a and c. Assign the result to e.


In [123]:
e = a * c
print(e)


[[[0.60571655 0.56758587 0.16215694 0.05165878 0.9581245 ]
  [0.03308898 0.09812579 0.52496867 0.47925435 0.91026106]
  [0.19973755 0.68043439 0.20254275 0.72489806 0.37171133]]

 [[0.6048057  0.54244354 0.61450157 0.47360174 0.19561611]
  [0.75985882 0.07547208 0.82692792 0.39837969 0.06907573]
  [0.40016749 0.7452215  0.75099786 0.07135298 0.53115444]]]




### 13. Does e equal to a? Why or why not?


In [124]:
#yes, it is because: c = ones array
equal = np.array_equal(e, a)  
print(f"Does e equal a? {equal}")



Does e equal a? True




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [125]:

d_max = np.max(d)    
d_min = np.min(d)   
d_mean = np.mean(d)  

print(f"d_max: {d_max}, d_min: {d_min}, d_mean: {d_mean}")

d_max: 1.958124496773266, d_min: 1.0330889764058209, d_mean: 1.454328091280846



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [126]:
f = np.empty(d.shape)
print("Shape of f:", f.shape)



Shape of f: (2, 3, 5)





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [142]:
f = np.empty(d.shape)


f[d == d_min] = 0
f[d == d_max] = 100
f[(d > d_min) & (d < d_mean)] = 25
f[d == d_mean] = 50
f[(d > d_mean) & (d < d_max)] = 75

print("Corrected f:")
print(f)

Corrected f:
[[[ 75.  75.  25.  25. 100.]
  [  0.  25.  75.  75.  75.]
  [ 25.  75.  25.  75.  25.]]

 [[ 75.  75.  75.  75.  25.]
  [ 75.  25.  75.  25.  25.]
  [ 25.  75.  75.  25.  75.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [140]:
print("\nd:")
print(d)
print("\nf:")
print(f)



d:
[[[1.60571655 1.56758587 1.16215694 1.05165878 1.9581245 ]
  [1.03308898 1.09812579 1.52496867 1.47925435 1.91026106]
  [1.19973755 1.68043439 1.20254275 1.72489806 1.37171133]]

 [[1.6048057  1.54244354 1.61450157 1.47360174 1.19561611]
  [1.75985882 1.07547208 1.82692792 1.39837969 1.06907573]
  [1.40016749 1.7452215  1.75099786 1.07135298 1.53115444]]]

f:
[[[ 75.  75.  25.  25. 100.]
  [  0.  25.  75.  75.  75.]
  [ 25.  75.  25.  75.  25.]]

 [[ 75.  75.  75.  75.  25.]
  [ 75.  25.  75.  25.  25.]
  [ 25.  75.  75.  25.  75.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [144]:
f = np.empty(d.shape, dtype=object)  

f[d == d_min] = 'A'
f[d == d_max] = 'E'
f[(d > d_min) & (d < d_mean)] = 'B'
f[d == d_mean] = 'C'
f[(d > d_mean) & (d < d_max)] = 'D'


print("String-labeled array f:")
print(f)

String-labeled array f:
[[['D' 'D' 'B' 'B' 'E']
  ['A' 'B' 'D' 'D' 'D']
  ['B' 'D' 'B' 'D' 'B']]

 [['D' 'D' 'D' 'D' 'B']
  ['D' 'B' 'D' 'B' 'B']
  ['B' 'D' 'D' 'B' 'D']]]
