# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [2]:
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [3]:
print("NumPy Version : ",np.__version__)
print(np.show_config())

NumPy Version :  1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /Users/raneem/Library/jupyterlab-desktop/jlab_server/include
    lib directory: /Users/raneem/Library/jupyterlab-desktop/jlab_server/lib
    name: blas
    openblas configuration: unknown
    pc file directory: /Users/raneem/Library/jupyterlab-desktop/jlab_server/lib/pkgconfig
    version: 3.9.0
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep4569863840
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -ftree-vectorize, -fPIC, -fstack-protector-strong, -O2, -pipe, -isystem,
      /Users/raneem/Library/jupyterlab-desktop/jlab_server/include, -fdebug-prefix-map=/Users/runner/miniforge3/conda-bld/numpy_1707225421156/work=/usr/local/src/conda/numpy-1.26.4,
      -fdebug-prefix-map=/Users/raneem/Library/jupyterlab-desktop/jlab_se

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [6]:
# Using np.random.random
a1 = np.random.random((2, 3, 5))
# Using np.random.randn
a2 = np.random.randn(2, 3, 5)
# Using np.random.randint
a3 = np.random.randint(0, 20, size=(2, 3, 5))

print('\nrandom floats in uniform distribution between 0 and 1\n', a1)
print('\nnormal distribution >> mean = 0 standard deviation = 1(can be both positive and negative)\n', a2)
print('\nrandom integers 0-19\n', a3)



random floats in uniform distribution between 0 and 1
 [[[0.90162153 0.88144622 0.49349419 0.35558175 0.84493856]
  [0.93092726 0.36407179 0.10524194 0.39186887 0.74093651]
  [0.27484242 0.74271467 0.63717276 0.04864882 0.8644318 ]]

 [[0.48593123 0.03507415 0.58824881 0.92584532 0.79219012]
  [0.93051969 0.28328232 0.70889347 0.03873169 0.01270208]
  [0.33079798 0.72876582 0.72975943 0.15007449 0.68437399]]]

normal distribution >> mean = 0 standard deviation = 1(can be both positive and negative)
 [[[ 1.37368151  0.03232225  2.90982198  0.61089735 -1.86346501]
  [ 0.40475646  0.34603765  1.37388877 -0.39717519 -1.31174552]
  [-0.80400979 -0.56927043  0.70885477  0.91982925 -0.78799151]]

 [[-1.85391869  1.01582235  0.64182281 -0.47066815  0.56188038]
  [-1.84020922 -1.25470449 -1.38019997  0.83650637 -0.48839436]
  [ 0.95580056  0.55127553 -1.4256024   0.71558222  1.47897894]]]

random integers 0-19
 [[[ 3  1 19  0 12]
  [14  5 12 19 15]
  [ 0 10  6  1  4]]

 [[ 7 18 14  3 18]
  [12


### 4. Print a.


In [7]:
a = a3
a

array([[[ 3,  1, 19,  0, 12],
        [14,  5, 12, 19, 15],
        [ 0, 10,  6,  1,  4]],

       [[ 7, 18, 14,  3, 18],
        [12, 10,  9,  3,  2],
        [ 2, 17, 10, 13,  0]]])

### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [8]:
b = np.ones((5, 2, 3))


### 6. Print b.


In [9]:
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])


### 7. Do a and b have the same size? How do you prove that in Python code?


In [11]:
# Compare their shapes
if a.shape == b.shape:
    print(f"Have the same shape: {a.shape}")
else:
    print(f"Have different shapes: {a.shape} - {b.shape}")

# Compare their sizes (total number of elements)
if a.size == b.size:
    print(f"Have the same size: {a.size} ")
else:
    print(f"Have different sizes: {a.size} - {b.size} ")

Have different shapes: (2, 3, 5) - (5, 2, 3)
Have the same size: 30 



### 8. Are you able to add a and b? Why or why not?


In [13]:
# Using the + Operator
result1 = a + b
print("\nAddition using + operator:\n" , result1 )
# Using np.add()
result2 = np.add(a, b)
print("\nResult of addition (using np.add):\n", result2)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [ ]:
''' both metheds dont work.
a has the shape (2, 3, 5) and b has the shape (5, 2, 3)
so they cant be added (broadcast)
the arrays need to have compatible shapes '''



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [15]:
c = np.transpose(b, (1, 2, 0))
print("\nArray c :\n", c)
print("\nShape of c:\n", c.shape)


Array c :
 [[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]

Shape of c:
 (2, 3, 5)



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [16]:
# Using the + Operator
result1 = a + c
print("\nAddition using + operator:\n" , result1 )
# Using np.add()
result2 = np.add(a, c)
print("\nResult of addition (using np.add):\n", result2)


Addition using + operator:
 [[[ 4.  2. 20.  1. 13.]
  [15.  6. 13. 20. 16.]
  [ 1. 11.  7.  2.  5.]]

 [[ 8. 19. 15.  4. 19.]
  [13. 11. 10.  4.  3.]
  [ 3. 18. 11. 14.  1.]]]

Result of addition (using np.add):
 [[[ 4.  2. 20.  1. 13.]
  [15.  6. 13. 20. 16.]
  [ 1. 11.  7.  2.  5.]]

 [[ 8. 19. 15.  4. 19.]
  [13. 11. 10.  4.  3.]
  [ 3. 18. 11. 14.  1.]]]


In [17]:
d = result1

In [ ]:
'''  they become "compatible" arrays
because the dimension number and the size match up '''


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [18]:
print("\nArray a :\n", a)
print("\nArray d :\n", d)


Array a :
 [[[ 3  1 19  0 12]
  [14  5 12 19 15]
  [ 0 10  6  1  4]]

 [[ 7 18 14  3 18]
  [12 10  9  3  2]
  [ 2 17 10 13  0]]]

Array d :
 [[[ 4.  2. 20.  1. 13.]
  [15.  6. 13. 20. 16.]
  [ 1. 11.  7.  2.  5.]]

 [[ 8. 19. 15.  4. 19.]
  [13. 11. 10.  4.  3.]
  [ 3. 18. 11. 14.  1.]]]


In [ ]:
''' 
1. both 3D arrays of shape (2, 3, 5) 
2. values in a are integers while the values in d are floats
3. needs scaling
'''


### 12. Multiply a and c. Assign the result to e.


In [19]:
e = a * c
print("\nArray e (after multiplication):\n", e)


Array e (after multiplication):
 [[[ 3.  1. 19.  0. 12.]
  [14.  5. 12. 19. 15.]
  [ 0. 10.  6.  1.  4.]]

 [[ 7. 18. 14.  3. 18.]
  [12. 10.  9.  3.  2.]
  [ 2. 17. 10. 13.  0.]]]




### 13. Does e equal to a? Why or why not?


In [21]:
''' Every corresponding element in e must be the same as in a to be equal
So, for e to be equal to a, every element in c must be equal to 1 
this means every element of c is 1, and thus a * c will be equal to a for all elements.'''
# Checking if e is equal to a
if np.allclose(e, a):
    print("e is equal to a")
else:
    print("e is not equal to a")

e is equal to a




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [22]:
# max, min , mean for d
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

# Display results
print("Max value in d:", d_max)
print("Min value in d:", d_min)
print("Mean value in d:", d_mean)

Max value in d: 20.0
Min value in d: 1.0
Mean value in d: 9.633333333333333



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [27]:
#np.empty(d) creates an empty array with the same shape as d
f = np.empty(d.shape)

# Display the araay with the shape
print("Array f:\n", f)
print("Shape of f:", f.shape)

Array f:
 [[[ 3.  1. 19.  0. 12.]
  [14.  5. 12. 19. 15.]
  [ 0. 10.  6.  1.  4.]]

 [[ 7. 18. 14.  3. 18.]
  [12. 10.  9.  3.  2.]
  [ 2. 17. 10. 13.  0.]]]
Shape of f: (2, 3, 5)





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [28]:
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i, j, k] == d_min:
                f[i, j, k] = 0
            elif d[i, j, k] == d_max:
                f[i, j, k] = 100
            elif d[i, j, k] == d_mean:
                f[i, j, k] = 50
            elif d_min < d[i, j, k] < d_mean:
                f[i, j, k] = 25
            elif d_mean < d[i, j, k] < d_max:
                f[i, j, k] = 75

# Display the populated array f
print("result f:\n", f)

result f:
 [[[ 25.  25. 100.   0.  75.]
  [ 75.  25.  75. 100.  75.]
  [  0.  75.  25.  25.  25.]]

 [[ 25.  75.  75.  25.  75.]
  [ 75.  75.  75.  25.  25.]
  [ 25.  75.  75.  75.   0.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [29]:
print("Array d:\n", d)
print("Array f:\n", f)

Array d:
 [[[ 4.  2. 20.  1. 13.]
  [15.  6. 13. 20. 16.]
  [ 1. 11.  7.  2.  5.]]

 [[ 8. 19. 15.  4. 19.]
  [13. 11. 10.  4.  3.]
  [ 3. 18. 11. 14.  1.]]]
Array f:
 [[[ 25.  25. 100.   0.  75.]
  [ 75.  25.  75. 100.  75.]
  [  0.  75.  25.  25.  25.]]

 [[ 25.  75.  75.  25.  75.]
  [ 75.  75.  75.  25.  25.]
  [ 25.  75.  75.  75.   0.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [30]:

f = np.empty(d.shape, dtype=object)  # we will use dtype=object for strings

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i, j, k] == d_min:
                f[i, j, k] = "A"
            elif d[i, j, k] == d_max:
                f[i, j, k] = "E"
            elif d[i, j, k] == d_mean:
                f[i, j, k] = "C"
            elif d_min < d[i, j, k] < d_mean:
                f[i, j, k] = "B"
            elif d_mean < d[i, j, k] < d_max:
                f[i, j, k] = "D"


print("Array d:\n", d)
print("Array f:\n", f)

Array d:
 [[[ 4.  2. 20.  1. 13.]
  [15.  6. 13. 20. 16.]
  [ 1. 11.  7.  2.  5.]]

 [[ 8. 19. 15.  4. 19.]
  [13. 11. 10.  4.  3.]
  [ 3. 18. 11. 14.  1.]]]
Array f:
 [[['B' 'B' 'E' 'A' 'D']
  ['D' 'B' 'D' 'E' 'D']
  ['A' 'D' 'B' 'B' 'B']]

 [['B' 'D' 'D' 'B' 'D']
  ['D' 'D' 'D' 'B' 'B']
  ['B' 'D' 'D' 'D' 'A']]]
