# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [53]:
### [your code here]
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [54]:
### [your code here]
print(np.__version__)


print(np.show_config())


2.2.3
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30158",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.12",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30158",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.28",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-3gfa2f0z/cp311-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include",
      "lib 

C:\Users\Lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [55]:
### [your code here]
a = np.random.random((2, 3,5))


### 4. Print a.


In [56]:
a

array([[[0.54776334, 0.53207097, 0.39265895, 0.06818047, 0.034017  ],
        [0.14307153, 0.67243983, 0.13472981, 0.6064509 , 0.85756736],
        [0.89801329, 0.88129011, 0.41070076, 0.09781839, 0.81759086]],

       [[0.3338339 , 0.38645456, 0.13888304, 0.34026389, 0.32002999],
        [0.2486071 , 0.77103116, 0.69568309, 0.71760188, 0.54461973],
        [0.01406888, 0.66332998, 0.11981287, 0.51870882, 0.57249528]]])

### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [57]:
### [your code here]
b = np.random.random((5,2, 3))


### 6. Print b.


In [58]:
### [your code here]
b

array([[[0.38222564, 0.09588583, 0.8512544 ],
        [0.39405671, 0.37555512, 0.75932659]],

       [[0.0428931 , 0.30582191, 0.39512301],
        [0.40088414, 0.80590537, 0.92306833]],

       [[0.06791161, 0.37526467, 0.54016434],
        [0.56093943, 0.93452972, 0.5030781 ]],

       [[0.89133246, 0.89650803, 0.25311548],
        [0.24606182, 0.07629307, 0.57761429]],

       [[0.88511945, 0.30694504, 0.75723279],
        [0.43707199, 0.78721616, 0.32579167]]])


### 7. Do a and b have the same size? How do you prove that in Python code?


In [59]:
### [your code here]

if a.size==b.size:
    print('the are the sam')
else:
    print('the are not the sam')

the are the sam



### 8. Are you able to add a and b? Why or why not?


In [60]:
### [your code here]

add_arry=a+b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [ ]:
### [your code here]
c=np.transpose(b,(1,2,0))


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [ ]:
### [your code here]
d==a+c
d

array([[[1.15898157, 1.15881595, 1.89064598, 0.71877174, 1.76054453],
        [1.31122703, 1.07580822, 1.03526665, 0.76313833, 1.38944818],
        [0.56931449, 1.47826811, 0.99650863, 1.05011874, 0.71502221]],

       [[0.64616515, 0.97416275, 0.53981586, 0.51290629, 1.23383201],
        [1.85614803, 0.92445662, 1.00511623, 0.96377511, 0.47682757],
        [0.93089754, 0.64631468, 1.12258521, 1.21148172, 0.91418911]]])


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [ ]:
### [your code here]
a
d


array([[[1.15898157, 1.15881595, 1.89064598, 0.71877174, 1.76054453],
        [1.31122703, 1.07580822, 1.03526665, 0.76313833, 1.38944818],
        [0.56931449, 1.47826811, 0.99650863, 1.05011874, 0.71502221]],

       [[0.64616515, 0.97416275, 0.53981586, 0.51290629, 1.23383201],
        [1.85614803, 0.92445662, 1.00511623, 0.96377511, 0.47682757],
        [0.93089754, 0.64631468, 1.12258521, 1.21148172, 0.91418911]]])


### 12. Multiply a and c. Assign the result to e.


In [ ]:
### [your code here]
e=a**c
e

array([[[0.48694902, 0.81265457, 0.9865151 , 0.77652536, 0.94917974],
        [0.56195284, 0.8117554 , 0.53626733, 0.66807706, 0.76135087],
        [0.6202604 , 0.47924103, 0.85585284, 0.61418857, 0.06064827]],

       [[0.91962256, 0.97870423, 0.15154732, 0.18395982, 0.80128677],
        [0.94425522, 0.84512469, 0.99912904, 0.98618749, 0.42095303],
        [0.63230189, 0.93403842, 0.97768105, 0.84273302, 0.1839896 ]]])



### 13. Does e equal to a? Why or why not?


In [ ]:
### [your code here]


if np.array_equal(a, e):
    print("e is equal to a")
else:
    print("e is not equal to a")

e is not equal to a




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [ ]:
### [your code here]

d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print("d_max:", d_max)
print("d_min:", d_min)
print("d_mean:", d_mean)

d_max: 1.8906459828412798
d_min: 0.4768275746862455
d_mean: 1.0343518082922787



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [ ]:
### [your code here]

f = np.empty(d.shape)

print("Array f (empty):")
f

Array f (empty):


array([[[0.48694902, 0.81265457, 0.9865151 , 0.77652536, 0.94917974],
        [0.56195284, 0.8117554 , 0.53626733, 0.66807706, 0.76135087],
        [0.6202604 , 0.47924103, 0.85585284, 0.61418857, 0.06064827]],

       [[0.91962256, 0.97870423, 0.15154732, 0.18395982, 0.80128677],
        [0.94425522, 0.84512469, 0.99912904, 0.98618749, 0.42095303],
        [0.63230189, 0.93403842, 0.97768105, 0.84273302, 0.1839896 ]]])




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [ ]:
### [your code here]

for index, value in np.ndenumerate(d):
    if value == d_min:
        f[index] = 0
    elif value == d_max:
        f[index] = 100
    elif value == d_mean:
        f[index] = 50
    elif d_min < value < d_mean:
        f[index] = 25
    elif d_mean < value < d_max:
        f[index] = 75







### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [ ]:
### [your code here]
print("Array d :",d)

print("Array f :", f)




Array d : [[[1.15898157 1.15881595 1.89064598 0.71877174 1.76054453]
  [1.31122703 1.07580822 1.03526665 0.76313833 1.38944818]
  [0.56931449 1.47826811 0.99650863 1.05011874 0.71502221]]

 [[0.64616515 0.97416275 0.53981586 0.51290629 1.23383201]
  [1.85614803 0.92445662 1.00511623 0.96377511 0.47682757]
  [0.93089754 0.64631468 1.12258521 1.21148172 0.91418911]]]
Array f : [[[ 75.  75. 100.  25.  75.]
  [ 75.  75.  75.  25.  75.]
  [ 25.  75.  25.  75.  25.]]

 [[ 25.  25.  25.  25.  75.]
  [ 75.  25.  25.  25.   0.]
  [ 25.  25.  75.  75.  25.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [ ]:
### [your code here]