# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [79]:

### [your code here]
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [80]:
### [your code here]


# Print the NumPy version
print("NumPy Version:", np.__version__)

# Print the NumPy configuration
print("\nNumPy Configuration:")
print(np.__config__.show())

NumPy Version: 2.2.3

NumPy Configuration:
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30158",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.12",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30158",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.28",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-3gfa2f0z/cp311-win_amd64/build/venv/Lib/site-packages/s

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [81]:
### [your code here]


# Generate a 2x3x5 array with random values between 0 and 1
a = np.random.rand(2, 3, 5)


### 4. Print a.
print(a)

In [82]:
### [your code here]
print(a)

[[[0.53360424 0.91114928 0.69397748 0.09398885 0.08292049]
  [0.89017324 0.77754051 0.24053356 0.50946528 0.41772239]
  [0.35592435 0.97075706 0.02162282 0.10365266 0.17322282]]

 [[0.35192967 0.96960264 0.78808972 0.70811572 0.55312485]
  [0.63886339 0.188977   0.50049999 0.46283781 0.86428015]
  [0.47686216 0.20478907 0.17625372 0.94818778 0.06344612]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [83]:
### [your code here]
import numpy as np

# Create a 5x2x3 array filled with 1s
b = np.ones((5, 2, 3))


### 6. Print b.


In [84]:
### [your code here]
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [85]:
### [your code here]
a = [1, 2, 3]
b = [4, 5, 6]

# Check if they have the same length
if len(a) == len(b):
    print("a and b have the same size.")
else:
    print("a and b do not have the same size.")



a and b have the same size.



### 8. Are you able to add a and b? Why or why not?


In [86]:
### [your code here]
a = [1, 2]
b = [3, 4]

try:
    result = a + b
    print("a and b can be added:", result)
except TypeError:
    print("a and b cannot be added.")



a and b can be added: [1, 2, 3, 4]




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [87]:
### [your code here]
import numpy as np

# Define array a with shape (2, 3, 5)
a = np.random.rand(2, 3, 5)  # Random array with shape 2x3x5

# Define array b (let's assume b needs reshaping and transposition)
b = np.random.rand(30)  # A flat array with 30 elements (can be reshaped into 2x3x5)

# Reshape b into a 2x3x5 array
c = b.reshape(2, 3, 5)

# If you need to transpose the array (for example, swapping axes), you can do:
c = np.transpose(c, (0, 2, 1))  # This swaps axis 1 and axis 2 (i.e., transposing)

print("Array a shape:", a.shape)
print("Array c shape:", c.shape)



Array a shape: (2, 3, 5)
Array c shape: (2, 5, 3)



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [88]:
### [your code here]
import numpy as np

# Define array a with shape (2, 3, 5)
a = np.random.rand(2, 3, 5)  # Random array with shape 2x3x5

# Define array c (reshaped version of b, with shape 2x3x5)
b = np.random.rand(30)  # A flat array with 30 elements (can be reshaped into 2x3x5)
c = b.reshape(2, 3, 5)

# Add a and c
d = a + c

print("Shape of a:", a.shape)
print("Shape of c:", c.shape)
print("Shape of d:", d.shape)



Shape of a: (2, 3, 5)
Shape of c: (2, 3, 5)
Shape of d: (2, 3, 5)



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [89]:
### [your code here]
import numpy as np

# Define array a with shape (2, 3, 5)
a = np.random.rand(2, 3, 5)  # Random array with shape 2x3x5

# Define array b and reshape it to create array c with shape (2, 3, 5)
b = np.random.rand(30)  # A flat array with 30 elements
c = b.reshape(2, 3, 5)

# Add a and c to create d
d = a + c

# Print a and d to observe the difference
print("Array a:")
print(a)
print("\nArray d (a + c):")
print(d)




Array a:
[[[0.86957179 0.76352836 0.06973478 0.81868002 0.51268995]
  [0.87735397 0.43165005 0.65630393 0.51182094 0.80432768]
  [0.64020868 0.50382825 0.21500627 0.86025542 0.3596153 ]]

 [[0.23169214 0.11487558 0.81772194 0.90446443 0.19828134]
  [0.13585446 0.69563387 0.09926271 0.34601072 0.60563945]
  [0.6410796  0.38033035 0.4749656  0.38812228 0.80685834]]]

Array d (a + c):
[[[1.63959066 1.53995931 0.40175945 1.03299774 1.26309   ]
  [1.33049459 1.37490989 1.54751156 0.76737236 0.91158408]
  [0.88505842 1.17018875 1.03501159 1.33670855 0.86626994]]

 [[0.9273837  0.30618983 0.88560232 0.99959566 1.11907745]
  [0.2437043  1.67469423 0.14405876 1.1054777  0.89733593]
  [1.05096449 0.55578811 1.11783951 1.15834502 1.21293669]]]



### 12. Multiply a and c. Assign the result to e.


In [90]:
### [your code here]
import numpy as np

# Define array a with shape (2, 3, 5)
a = np.random.rand(2, 3, 5)  # Random array with shape 2x3x5

# Define array b and reshape it to create array c with shape (2, 3, 5)
b = np.random.rand(30)  # A flat array with 30 elements
c = b.reshape(2, 3, 5)

# Multiply a and c to create e
e = a * c

# Print a, c, and e to observe the results
print("Array a:")
print(a)
print("\nArray c:")
print(c)
print("\nArray e (a * c):")
print(e)


Array a:
[[[0.28550239 0.67709426 0.02236335 0.53521869 0.48509861]
  [0.97117863 0.0440058  0.46942061 0.2412323  0.17513189]
  [0.79908734 0.31491812 0.85214478 0.34693329 0.45908051]]

 [[0.96608513 0.52750806 0.83217682 0.93501046 0.49079997]
  [0.51887958 0.79906517 0.47654502 0.25761487 0.83123207]
  [0.22844891 0.60132523 0.52079654 0.34078342 0.72861728]]]

Array c:
[[[0.62348174 0.73318727 0.08798872 0.10408885 0.91017234]
  [0.58181524 0.80878395 0.89522657 0.95029967 0.814464  ]
  [0.80022744 0.23488111 0.4499478  0.12021203 0.37441796]]

 [[0.47384323 0.86039282 0.66858765 0.88639496 0.64526675]
  [0.58802082 0.86851906 0.94658048 0.5691381  0.86549196]
  [0.00533437 0.10744962 0.88512324 0.73258527 0.62693382]]]

Array e (a * c):
[[[0.17800552 0.49643689 0.00196772 0.0557103  0.44152334]
  [0.56504653 0.03559119 0.42023781 0.22924297 0.14263862]
  [0.63945162 0.07396832 0.38342067 0.04170555 0.17188799]]

 [[0.4577729  0.45386415 0.55638315 0.82878856 0.3166969 ]
  [0.3051



### 13. Does e equal to a? Why or why not?


In [91]:
### [your code here]
import numpy as np

# Define array a with shape (2, 3, 5)
a = np.random.rand(2, 3, 5)  # Random array with shape 2x3x5

# Define array b and reshape it to create array c with shape (2, 3, 5)
b = np.random.rand(30)  # A flat array with 30 elements
c = b.reshape(2, 3, 5)

# Multiply a and c to create e
e = a * c

# Check if e is equal to a
print("Does e equal a?", np.array_equal(a, e))




Does e equal a? False




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [92]:
### [your code here]

#import numpy as np

# Define array a with shape (2, 3, 5)
a = np.random.rand(2, 3, 5)  # Random array with shape 2x3x5

# Define array b and reshape it to create array c with shape (2, 3, 5)
b = np.random.rand(30)  # A flat array with 30 elements
c = b.reshape(2, 3, 5)

# Add a and c to create d
d = a + c

# Identify the max, min, and mean values in d
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

# Print the results
print("Max value in d:", d_max)
print("Min value in d:", d_min)
print("Mean value in d:", d_mean)


Max value in d: 1.7681675835026789
Min value in d: 0.1529372179109395
Mean value in d: 0.9634413513778627



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [93]:
### [your code here]
import numpy as np

# Define array a with shape (2, 3, 5)
a = np.random.rand(2, 3, 5)  # Random array with shape 2x3x5

# Define array b and reshape it to create array c with shape (2, 3, 5)
b = np.random.rand(30)  # A flat array with 30 elements
c = b.reshape(2, 3, 5)

# Add a and c to create d
d = a + c

# Create an empty array f with the same shape as d (2x3x5)
f = np.empty_like(d)

# Print the shape of f to verify
print("Shape of f:", f.shape)


Shape of f: (2, 3, 5)





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [94]:
### [your code here]
import numpy as np

# Define array a with shape (2, 3, 5)
a = np.random.rand(2, 3, 5)  # Random array with shape 2x3x5

# Define array b and reshape it to create array c with shape (2, 3, 5)
b = np.random.rand(30)  # A flat array with 30 elements
c = b.reshape(2, 3, 5)

# Add a and c to create d
d = a + c

# Identify the max, min, and mean values in d
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

# Create an empty array f with the same shape as d (2x3x5)
f = np.empty_like(d)

# Loop through the elements in d and populate f according to the rules
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i, j, k] == d_max:
                f[i, j, k] = 100
            elif d[i, j, k] == d_min:
                f[i, j, k] = 0
            elif d[i, j, k] == d_mean:
                f[i, j, k] = 50
            elif d_min < d[i, j, k] < d_mean:
                f[i, j, k] = 25
            elif d_mean < d[i, j, k] < d_max:
                f[i, j, k] = 75

# Print the populated array f
print("Array f:")
print(f)


Array f:
[[[ 75.  75.  75.  75.  75.]
  [ 75.  75.  75.  75.  25.]
  [ 25.  75.  25.  75.  25.]]

 [[ 25.  25.  25.  25.  25.]
  [ 25.  25.  75.   0.  25.]
  [100.  75.  25.  25.  25.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [95]:
### [your code here]
import numpy as np

# Define array a with shape (2, 3, 5)
a = np.random.rand(2, 3, 5)  # Random array with shape 2x3x5

# Define array b and reshape it to create array c with shape (2, 3, 5)
b = np.random.rand(30)  # A flat array with 30 elements
c = b.reshape(2, 3, 5)

# Add a and c to create d
d = a + c

# Identify the max, min, and mean values in d
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

# Create an empty array f with the same shape as d (2x3x5)
f = np.empty_like(d)

# Loop through the elements in d and populate f according to the rules
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i, j, k] == d_max:
                f[i, j, k] = 100
            elif d[i, j, k] == d_min:
                f[i, j, k] = 0
            elif d[i, j, k] == d_mean:
                f[i, j, k] = 50
            elif d_min < d[i, j, k] < d_mean:
                f[i, j, k] = 25
            elif d_mean < d[i, j, k] < d_max:
                f[i, j, k] = 75

# Print d and f to compare the results
print("Array d:")
print(d)

print("\nArray f:")
print(f)


Array d:
[[[0.99586207 1.25871687 0.1890006  0.39251305 1.46121676]
  [1.03066494 0.4617753  0.95548433 1.79436628 0.43994675]
  [1.0628669  0.40287496 0.88726965 0.46767786 0.79350207]]

 [[0.897615   1.52202763 0.62384282 1.7182908  1.62067589]
  [0.65915345 0.63650289 0.66864251 1.2644239  0.29061894]
  [1.58048417 1.04685666 0.67499225 1.8491108  1.67117976]]]

Array f:
[[[ 75.  75.   0.  25.  75.]
  [ 75.  25.  25.  75.  25.]
  [ 75.  25.  25.  25.  25.]]

 [[ 25.  75.  25.  75.  75.]
  [ 25.  25.  25.  75.  25.]
  [ 75.  75.  25. 100.  75.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [96]:
### [your code here]
import numpy as np

# Define array a with shape (2, 3, 5)
a = np.random.rand(2, 3, 5)  # Random array with shape 2x3x5

# Define array b and reshape it to create array c with shape (2, 3, 5)
b = np.random.rand(30)  # A flat array with 30 elements
c = b.reshape(2, 3, 5)

# Add a and c to create d
d = a + c

# Identify the max, min, and mean values in d
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

# Create an empty array f with the same shape as d (2x3x5), but with string data type
f = np.empty_like(d, dtype=object)  # Use dtype=object to store strings

# Loop through the elements in d and populate f according to the rules
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i, j, k] == d_max:
                f[i, j, k] = "E"
            elif d[i, j, k] == d_min:
                f[i, j, k] = "A"
            elif d[i, j, k] == d_mean:
                f[i, j, k] = "C"
            elif d_min < d[i, j, k] < d_mean:
                f[i, j, k] = "B"
            elif d_mean < d[i, j, k] < d_max:
                f[i, j, k] = "D"

# Print the populated array f
print("Array f with string labels:")
print(f)


Array f with string labels:
[[['D' 'B' 'B' 'D' 'B']
  ['B' 'B' 'B' 'B' 'D']
  ['B' 'B' 'D' 'D' 'D']]

 [['B' 'D' 'B' 'D' 'B']
  ['B' 'B' 'B' 'A' 'E']
  ['D' 'D' 'B' 'D' 'B']]]
