# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
### [your code here]
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [4]:
### [your code here]
print(np.__version__)
np.show_config()

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/ProgramData/anaconda3/Library/include
    lib directory: C:/ProgramData/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1583119523984
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  host:
  

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [12]:
### [your code here]
# a = np.random.random(size=(2,3,5))
# a = np.random.randint(1,100,size=(2,3,5)) # random integer from 1 to 100
a = np.random.rand(2,3,5)


### 4. Print a.


In [13]:
### [your code here]
a

array([[[0.87626532, 0.30140123, 0.52034905, 0.95784735, 0.0636006 ],
        [0.92211151, 0.58985708, 0.92458176, 0.65441748, 0.13166717],
        [0.03880952, 0.54416541, 0.44854759, 0.83871387, 0.59674343]],

       [[0.14580653, 0.47899802, 0.08080715, 0.45439566, 0.28626968],
        [0.23116211, 0.17799256, 0.41032731, 0.64727982, 0.33145156],
        [0.79771503, 0.53526517, 0.80136672, 0.81377244, 0.11862269]]])

### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [14]:
### [your code here]
b = np.ones((5,2,3))


### 6. Print b.


In [15]:
### [your code here]
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])


### 7. Do a and b have the same size? How do you prove that in Python code?


In [ ]:
### [your code here]
print(f"a shape: {a.size}, b shape:{b.size}. equality test: {a.size == b.size}") # both of size 30!

a shape: 30, b shape:30. equality test: True



### 8. Are you able to add a and b? Why or why not?


In [21]:
### [your code here]
a + b # Error! ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 
# For broadcasting to work,
# the shapes must be compatible from the rightmost dimension to the left,
# meaning dimensions should either be equal or one of them must be 1.

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [30]:
### [your code here]
c = b.transpose(1,2,0) # from the shape (5,3,2) swapping them to (2,3,5) to match "a" shape


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [31]:
### [your code here]
d = a + c


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [ ]:
### [your code here]
print(a)
print(d)

# Both "a" and "d" have the exact shape. but in terms of values, all of "d" values are bigger by one than "a"
# and that's expected since we added to "d" the values of "a" + an array of ones.

[[[0.87626532 0.30140123 0.52034905 0.95784735 0.0636006 ]
  [0.92211151 0.58985708 0.92458176 0.65441748 0.13166717]
  [0.03880952 0.54416541 0.44854759 0.83871387 0.59674343]]

 [[0.14580653 0.47899802 0.08080715 0.45439566 0.28626968]
  [0.23116211 0.17799256 0.41032731 0.64727982 0.33145156]
  [0.79771503 0.53526517 0.80136672 0.81377244 0.11862269]]]
[[[1.87626532 1.30140123 1.52034905 1.95784735 1.0636006 ]
  [1.92211151 1.58985708 1.92458176 1.65441748 1.13166717]
  [1.03880952 1.54416541 1.44854759 1.83871387 1.59674343]]

 [[1.14580653 1.47899802 1.08080715 1.45439566 1.28626968]
  [1.23116211 1.17799256 1.41032731 1.64727982 1.33145156]
  [1.79771503 1.53526517 1.80136672 1.81377244 1.11862269]]]



### 12. Multiply a and c. Assign the result to e.


In [34]:
### [your code here]
e = a * c



### 13. Does e equal to a? Why or why not?


In [38]:
### [your code here]
e == a # True of all values
# That's because we performed an element-wise multiplication by
# multiplying each "a" value to each corresponding "c" value and "c" is made out of ones
# so "e" equals "a"


array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [40]:
### [your code here]
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print(f"Max={d_max}, Min={d_min}, Mean={d_mean}")


Max=1.9578473454214573, Min=1.038809516378628, Mean=1.4906770267322749



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [42]:
### [your code here]
f = np.empty((2,3,5))




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [ ]:
### [your code here]
# for x in range(f.shape[0]):
#     for y in range(f.shape[1]):
#         for z in range(f.shape[2]):
#             if d[x,y,z] == d_max:
#                 f[x,y,z] = 100
#             elif d[x,y,z] == d_min:
#                 f[x,y,z] = 0
#             elif d[x,y,z] > d_min and d[x,y,z] < d_mean:
#                 f[x,y,z] = 25
#             elif d[x,y,z] == d_mean:
#                 f[x,y,z] = 50
#             elif d[x,y,z] < d_max and d[x,y,z] > d_mean:
#                 f[x,y,z] = 75
# WOW, looks scary but works! 

# Found out about vectorized conditions using numpy
f[d == d_max] = 100
f[d == d_min] = 0
f[d == d_mean] = 50
f[(d > d_min) & (d < d_mean)] = 25
f[(d < d_max) & (d > d_mean)] = 75

f

array([[[ 75.,  25.,  75., 100.,  25.],
        [ 75.,  75.,  75.,  75.,  25.],
        [  0.,  75.,  25.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25.,  25.],
        [ 25.,  25.,  25.,  75.,  25.],
        [ 75.,  75.,  75.,  75.,  25.]]])





### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [ ]:
### [your code here]
print(d)
print(f) # f values as expected!

[[[1.87626532 1.30140123 1.52034905 1.95784735 1.0636006 ]
  [1.92211151 1.58985708 1.92458176 1.65441748 1.13166717]
  [1.03880952 1.54416541 1.44854759 1.83871387 1.59674343]]

 [[1.14580653 1.47899802 1.08080715 1.45439566 1.28626968]
  [1.23116211 1.17799256 1.41032731 1.64727982 1.33145156]
  [1.79771503 1.53526517 1.80136672 1.81377244 1.11862269]]]
[[[ 75.  25.  75. 100.  25.]
  [ 75.  75.  75.  75.  25.]
  [  0.  75.  25.  75.  75.]]

 [[ 25.  25.  25.  25.  25.]
  [ 25.  25.  25.  75.  25.]
  [ 75.  75.  75.  75.  25.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [54]:
### [your code here]
g = np.empty((2,3,5),dtype=str)

g[d == d_max] = "A"
g[d == d_min] = "E"
g[d == d_mean] = "C"
g[(d > d_min) & (d < d_mean)] = "D"
g[(d < d_max) & (d > d_mean)] = "B"

In [55]:
g

array([[['B', 'D', 'B', 'A', 'D'],
        ['B', 'B', 'B', 'B', 'D'],
        ['E', 'B', 'D', 'B', 'B']],

       [['D', 'D', 'D', 'D', 'D'],
        ['D', 'D', 'D', 'B', 'D'],
        ['B', 'B', 'B', 'B', 'D']]], dtype='<U1')