1. Import the NUMPY package under the name np.

In [1]:
import numpy as np

2. Print the NUMPY version and the configuration.

[your code here]

In [2]:
print("Numpy version:", np.__version__)

np.show_config()

Numpy version: 1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/anaconda3/include
    lib directory: /opt/anaconda3/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 CORE2 MAX_THREADS=128
    pc file directory: /opt/anaconda3/lib/pkgconfig
    version: 0.3.21
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep4429404432
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -march=core2, -mtune=haswell, -mssse3, -ftree-vectorize, -fPIC, -fPIE, -fstack-protector-strong,
      -O2, -pipe, -isystem, /opt/anaconda3/include, -fdebug-prefix-map=/var/folders/c_/qfmhj66j0tn016nkx_th4hxm0000gp/T/abs_b7iptlxgej/croot/numpy_and_numpy_base_1708638622773/work=/usr/local/src/conda/numpy-base-1.26

3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

[your code here]

In [23]:
a = np.random.random((2,3,5)) #notes


a_2 = np.random.rand(2, 3, 5)  



4. Print a.

In [24]:
#[your code here]
print(a)
print(a_2)


[[[0.85515449 0.31564983 0.23462567 0.84323575 0.17745826]
  [0.25513796 0.21608448 0.45699394 0.60927631 0.28166128]
  [0.17188883 0.80710571 0.0974135  0.03851219 0.84287429]]

 [[0.4437699  0.2306105  0.27660413 0.55533812 0.46590897]
  [0.39899074 0.37936201 0.73951726 0.63281721 0.29538599]
  [0.46367786 0.33599235 0.387887   0.11778694 0.02415669]]]
[[[0.93294023 0.36583869 0.30024405 0.58900829 0.45568019]
  [0.37707407 0.86263994 0.31036339 0.93957125 0.49595668]
  [0.29934769 0.9663739  0.01048008 0.74569364 0.74569809]]

 [[0.24642374 0.32231325 0.41513314 0.9440735  0.33155953]
  [0.9473509  0.24232668 0.03647347 0.94609658 0.98335145]
  [0.35154415 0.12346745 0.28430598 0.34996737 0.91832455]]]


In [25]:
#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"

#[your code here]

b = np.ones((5, 2, 3))

6. Print b.

In [26]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


7. Do a and b have the same size? How do you prove that in Python code?

In [31]:
#your code here

same_size = a.size == b.size  
print(f"Do a and b have the same size? {same_size}")
print(same_size)


Do a and b have the same size? True
True


8. Are you able to add a and b? Why or why not?

In [ ]:
#[your code here]
#a and b have to be compatible but they are not, (2, 3, 5) != (5, 2, 3) -> dimensions do not align properly



9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

In [49]:
c = b = np.ones((2,3,5))

10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [50]:
#[your code here]
d =a + c
print(d)
# it works now because they bothe have the same dimensions

[[[1.85515449 1.31564983 1.23462567 1.84323575 1.17745826]
  [1.25513796 1.21608448 1.45699394 1.60927631 1.28166128]
  [1.17188883 1.80710571 1.0974135  1.03851219 1.84287429]]

 [[1.4437699  1.2306105  1.27660413 1.55533812 1.46590897]
  [1.39899074 1.37936201 1.73951726 1.63281721 1.29538599]
  [1.46367786 1.33599235 1.387887   1.11778694 1.02415669]]]


11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

In [51]:
#[your code here]
print(a)
print(d)

# because b was made only out od 1s they d is a but with the addition of 1 in each number

[[[0.85515449 0.31564983 0.23462567 0.84323575 0.17745826]
  [0.25513796 0.21608448 0.45699394 0.60927631 0.28166128]
  [0.17188883 0.80710571 0.0974135  0.03851219 0.84287429]]

 [[0.4437699  0.2306105  0.27660413 0.55533812 0.46590897]
  [0.39899074 0.37936201 0.73951726 0.63281721 0.29538599]
  [0.46367786 0.33599235 0.387887   0.11778694 0.02415669]]]
[[[1.85515449 1.31564983 1.23462567 1.84323575 1.17745826]
  [1.25513796 1.21608448 1.45699394 1.60927631 1.28166128]
  [1.17188883 1.80710571 1.0974135  1.03851219 1.84287429]]

 [[1.4437699  1.2306105  1.27660413 1.55533812 1.46590897]
  [1.39899074 1.37936201 1.73951726 1.63281721 1.29538599]
  [1.46367786 1.33599235 1.387887   1.11778694 1.02415669]]]


12. Multiply a and c. Assign the result to e.

In [52]:
e = a * c
print(e)

[[[0.85515449 0.31564983 0.23462567 0.84323575 0.17745826]
  [0.25513796 0.21608448 0.45699394 0.60927631 0.28166128]
  [0.17188883 0.80710571 0.0974135  0.03851219 0.84287429]]

 [[0.4437699  0.2306105  0.27660413 0.55533812 0.46590897]
  [0.39899074 0.37936201 0.73951726 0.63281721 0.29538599]
  [0.46367786 0.33599235 0.387887   0.11778694 0.02415669]]]


13. Does e equal to a? Why or why not?

In [53]:
a == e
#it equals because a number times 1 is the number itsself 

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [60]:
print(d)
d_max = d.max()
d_min = d.min()
d_mean = d.mean()
print(d_max, d_min, d_mean)

[[[1.85515449 1.31564983 1.23462567 1.84323575 1.17745826]
  [1.25513796 1.21608448 1.45699394 1.60927631 1.28166128]
  [1.17188883 1.80710571 1.0974135  1.03851219 1.84287429]]

 [[1.4437699  1.2306105  1.27660413 1.55533812 1.46590897]
  [1.39899074 1.37936201 1.73951726 1.63281721 1.29538599]
  [1.46367786 1.33599235 1.387887   1.11778694 1.02415669]]]
1.8551544914365654 1.0241566860614015 1.3983626054157527


15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [67]:
f =np.empty((2,3,5))

In [ ]:
""""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""

In [68]:
for value in d:
    if value == d_min:
        f.append(0)  
    elif value == d_max:
        f.append(100) 
    elif value == d_mean:
        f.append(50)  
    elif d_min < value < d_mean:
        f.append(25) 
    elif d_mean < value < d_max:
        f.append(75)  

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""

[your code here]

In [ ]:
#i don't know

In [ ]:
"""
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""

[your code here]