# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
### [your code here]
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [2]:
### [your code here]
print("NumPy version:", np.__version__)
np.show_config()

NumPy version: 1.24.4
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['openblas\\lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HA

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [3]:
### [your code here]
# method 1: using np.random.random()
a = np.random.random((2, 3, 5))

# method 2: using np.random.rand()
a_method2 = np.random.rand(2, 3, 5)

# method 3: using np.random.randn()
a_method3 =  np.random.randn(2, 3, 5)


### 4. Print a.


In [4]:
### [your code here]
print(a)

[[[0.1661653  0.81219888 0.36453847 0.69836094 0.76520299]
  [0.23732629 0.62620049 0.4648139  0.24080551 0.12889016]
  [0.69633406 0.42300373 0.98576263 0.23659659 0.64661012]]

 [[0.20251204 0.67847384 0.9682248  0.03103942 0.96900619]
  [0.18395775 0.85875034 0.67840509 0.53572915 0.02911582]
  [0.54258346 0.31363564 0.87521669 0.88345906 0.91433007]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [5]:
### [your code here]
b = np.ones((5, 2, 3))


### 6. Print b.


In [6]:
### [your code here]
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [7]:
### [your code here]
# checking shapes
if a.shape == b.shape:
    print(f"a and b have the same shape {a.shape} and size {a.size}")
elif a.size == b.size:
    print("a and b have different shapes but the same size {a.size}")
else:
    print("a and b have different shapes and sizes")
# it's clear that the equality of shape guarantees the equality of size but the reverse is not true

a and b have different shapes but the same size {a.size}



### 8. Are you able to add a and b? Why or why not?


In [8]:
### [your code here]
# We get an error adding up a and b, since they have different shapes
a + b

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [9]:
### [your code here]
c = b.reshape(2, 3, 5)


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [10]:
### [your code here]
# Now a and c have the same shape and can be added together
d = a + c


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [11]:
### [your code here]
# d is simply a shifted by +1 because c contains only ones
# The shape of the arrays matters. Reshaping b was necessary for element-wise addition
# The structure of a remains unchanged in d, only the values shift 
print(a)
print(d)

[[[0.1661653  0.81219888 0.36453847 0.69836094 0.76520299]
  [0.23732629 0.62620049 0.4648139  0.24080551 0.12889016]
  [0.69633406 0.42300373 0.98576263 0.23659659 0.64661012]]

 [[0.20251204 0.67847384 0.9682248  0.03103942 0.96900619]
  [0.18395775 0.85875034 0.67840509 0.53572915 0.02911582]
  [0.54258346 0.31363564 0.87521669 0.88345906 0.91433007]]]
[[[1.1661653  1.81219888 1.36453847 1.69836094 1.76520299]
  [1.23732629 1.62620049 1.4648139  1.24080551 1.12889016]
  [1.69633406 1.42300373 1.98576263 1.23659659 1.64661012]]

 [[1.20251204 1.67847384 1.9682248  1.03103942 1.96900619]
  [1.18395775 1.85875034 1.67840509 1.53572915 1.02911582]
  [1.54258346 1.31363564 1.87521669 1.88345906 1.91433007]]]



### 12. Multiply a and c. Assign the result to e.


In [12]:
### [your code here]
# The element-wise multiplication using * operator or np.multiply() works,
# since both arrays have the same shape (2, 3, 5)
e = a * c



### 13. Does e equal to a? Why or why not?


In [13]:
### [your code here]

if (e == a).any():
    print("a and e are equal")

# e and a are the same since c is filled entirely with ones and 
# multiplying each element of a by 1 does not change the values.

a and e are equal




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [14]:
### [your code here]
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)


### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [15]:
### [your code here]
f = np.empty(d.shape)  # Creates an empty array with the same shape as d




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [16]:
### [your code here]
# Iterate through all elements and assign values based on conditions
for i in range(d.shape[0]):  
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i, j, k] == d_min:
                f[i, j, k] = 0
            elif d[i, j, k] == d_max:
                f[i, j, k] = 100
            elif d_min < d[i, j, k] < d_mean:
                f[i, j, k] = 25
            elif d[i, j, k] == d_mean:
                f[i, j, k] = 50
            elif d_mean < d[i, j, k] < d_max:
                f[i, j, k] = 75





### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [17]:
### [your code here]
# Print d and f to verify the results
print("Array f:\n", f)
print("Array d:\n", d)

# To verify if f is as expected, we can print both d and f after applying the classification rules.
if (f == d).any():
    print("The logic is correct")
else:
    print("Check the computation of d_min, d_max, and d_mean!")

Array f:
 [[[ 25.  75.  25.  75.  75.]
  [ 25.  75.  25.  25.  25.]
  [ 75.  25. 100.  25.  75.]]

 [[ 25.  75.  75.  25.  75.]
  [ 25.  75.  75.  25.   0.]
  [ 75.  25.  75.  75.  75.]]]
Array d:
 [[[1.1661653  1.81219888 1.36453847 1.69836094 1.76520299]
  [1.23732629 1.62620049 1.4648139  1.24080551 1.12889016]
  [1.69633406 1.42300373 1.98576263 1.23659659 1.64661012]]

 [[1.20251204 1.67847384 1.9682248  1.03103942 1.96900619]
  [1.18395775 1.85875034 1.67840509 1.53572915 1.02911582]
  [1.54258346 1.31363564 1.87521669 1.88345906 1.91433007]]]
Check the computation of d_min, d_max, and d_mean!


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [18]:
# Create an empty string array with the same shape as d
f = np.empty(d.shape, dtype=str)

# Populate f based on the given rules
for i in range(d.shape[0]):  
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i, j, k] == d_min:
                f[i, j, k] = "A"  # Replacing 0 with "A"
            elif d[i, j, k] == d_max:
                f[i, j, k] = "E"  # Replacing 100 with "E"
            elif d_min < d[i, j, k] < d_mean:
                f[i, j, k] = "B"  # Replacing 25 with "B"
            elif d[i, j, k] == d_mean:
                f[i, j, k] = "C"  # Replacing 50 with "C"
            elif d_mean < d[i, j, k] < d_max:
                f[i, j, k] = "D"  # Replacing 75 with "D"

# Print d and f to verify results
print("Array d:\n", d)
print("\nArray f:\n", f)

Array d:
 [[[1.1661653  1.81219888 1.36453847 1.69836094 1.76520299]
  [1.23732629 1.62620049 1.4648139  1.24080551 1.12889016]
  [1.69633406 1.42300373 1.98576263 1.23659659 1.64661012]]

 [[1.20251204 1.67847384 1.9682248  1.03103942 1.96900619]
  [1.18395775 1.85875034 1.67840509 1.53572915 1.02911582]
  [1.54258346 1.31363564 1.87521669 1.88345906 1.91433007]]]

Array f:
 [[['B' 'D' 'B' 'D' 'D']
  ['B' 'D' 'B' 'B' 'B']
  ['D' 'B' 'E' 'B' 'D']]

 [['B' 'D' 'D' 'B' 'D']
  ['B' 'D' 'D' 'B' 'A']
  ['D' 'B' 'D' 'D' 'D']]]
