1. Import the NUMPY package under the name np.

In [1]:
#[your code here]
import numpy as np

2. Print the NUMPY version and the configuration.

In [ ]:
#[your code here]
print(np.version.version)
"""
1.15.2
"""

1.26.4


'\n1.15.2\n'

3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [ ]:
#[your code here]

#metodo 1

# Generar un array 2x3x5 con valores aleatorios entre 0 y 1
a = np.random.rand(2, 3, 5)
print("Array generado con np.random.rand:")

# I found more than 3 ways to do it




Array generado con np.random.rand:
[[[0.31400412 0.89094671 0.3568243  0.53912641 0.55370618]
  [0.40161218 0.5996011  0.13521672 0.802483   0.71030026]
  [0.05669969 0.33912242 0.05662264 0.58302488 0.69219882]]

 [[0.69915132 0.07248887 0.11511851 0.93140531 0.3895057 ]
  [0.26723976 0.34164203 0.84205182 0.56821298 0.99510543]
  [0.93597404 0.23256409 0.05958396 0.7021813  0.05616356]]]


4. Print a.

In [4]:
print (a)

[[[0.31400412 0.89094671 0.3568243  0.53912641 0.55370618]
  [0.40161218 0.5996011  0.13521672 0.802483   0.71030026]
  [0.05669969 0.33912242 0.05662264 0.58302488 0.69219882]]

 [[0.69915132 0.07248887 0.11511851 0.93140531 0.3895057 ]
  [0.26723976 0.34164203 0.84205182 0.56821298 0.99510543]
  [0.93597404 0.23256409 0.05958396 0.7021813  0.05616356]]]



5. Create a 5x2x3 3-dimensional array with all values equaling 1.
Assign the array to variable "b"

In [5]:
#[your code here]
b = np.ones((5, 2, 3))
print("Array creado con np.ones:")

Array creado con np.ones:


6. Print b.

In [6]:
print (b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


7. Do a and b have the same size? How do you prove that in Python code?

In [7]:
#[your code here]
print("Size of a:", a.size)
print("Size of b:", b.size)

if a.size == b.size:
    print("a and b have the same size.")
else:
    print("a and b do not have the same size.")

Size of a: 30
Size of b: 30
a and b have the same size.


8. Are you able to add a and b? Why or why not?

In [9]:
#[your code here]
try:
    # Attempt to add a and b
    result = a + b
    print("a and b can be added. Result:")
    print(result)
except ValueError as e:
    print("a and b cannot be added. Reason:")
    print(e)

a and b cannot be added. Reason:
operands could not be broadcast together with shapes (2,3,5) (5,2,3) 


9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

In [10]:
#[your code here]
c = np.transpose(b, (1, 2, 0))  # Reorder axes: (5, 2, 3) -> (2, 3, 5)

# Check the shape of c
print("Shape of c:", c.shape)
print("Transposed array c:")
print(c)

Shape of c: (2, 3, 5)
Transposed array c:
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [11]:
#[your code here]
d = a + c

11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

In [13]:
#[your code here]
print("Array a:")
print(a)
print("\nArray b:")
print(b)
print("\nArray d:")
print(d)

# Compare their shapes
print("\nShape of a:", a.shape)
print("Shape of b:", b.shape)
print("Shape of d:", d.shape)

Array a:
[[[0.31400412 0.89094671 0.3568243  0.53912641 0.55370618]
  [0.40161218 0.5996011  0.13521672 0.802483   0.71030026]
  [0.05669969 0.33912242 0.05662264 0.58302488 0.69219882]]

 [[0.69915132 0.07248887 0.11511851 0.93140531 0.3895057 ]
  [0.26723976 0.34164203 0.84205182 0.56821298 0.99510543]
  [0.93597404 0.23256409 0.05958396 0.7021813  0.05616356]]]

Array b:
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]

Array d:
[[[1.31400412 1.89094671 1.3568243  1.53912641 1.55370618]
  [1.40161218 1.5996011  1.13521672 1.802483   1.71030026]
  [1.05669969 1.33912242 1.05662264 1.58302488 1.69219882]]

 [[1.69915132 1.07248887 1.11511851 1.93140531 1.3895057 ]
  [1.26723976 1.34164203 1.84205182 1.56821298 1.99510543]
  [1.93597404 1.23256409 1.05958396 1.7021813  1.05616356]]]

Shape of a: (2, 3, 5)
Shape of b: (5, 2, 3)
Shape of d: (2, 3, 5)


12. Multiply a and c. Assign the result to e.

In [14]:
#[your code here]
# Assuming a and c are already defined and have the same shape
e = a * c  # Element-wise multiplication

# Print the result
print("Array e (product of a and c):")
print(e)


Array e (product of a and c):
[[[0.31400412 0.89094671 0.3568243  0.53912641 0.55370618]
  [0.40161218 0.5996011  0.13521672 0.802483   0.71030026]
  [0.05669969 0.33912242 0.05662264 0.58302488 0.69219882]]

 [[0.69915132 0.07248887 0.11511851 0.93140531 0.3895057 ]
  [0.26723976 0.34164203 0.84205182 0.56821298 0.99510543]
  [0.93597404 0.23256409 0.05958396 0.7021813  0.05616356]]]


13. Does e equal to a? Why or why not?

In [15]:
#[your code here]
# Check if e is equal to a
are_equal = np.array_equal(e, a)

print("Does e equal a?", are_equal)

# Explanation if they are not equal
if not are_equal:
    print("e and a are not equal because their values differ.")
else:
    print("e and a are equal.")


Does e equal a? True
e and a are equal.


14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [16]:
#[your code here]

d_max = np.max(d)  # Maximum value in d
d_min = np.min(d)  # Minimum value in d
d_mean = np.mean(d)  # Mean value in d

# Print the results
print("Maximum value in d:", d_max)
print("Minimum value in d:", d_min)
print("Mean value in d:", d_mean)


Maximum value in d: 1.9951054315912282
Minimum value in d: 1.0561635630138002
Mean value in d: 1.474662603980286


15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.

In [24]:
#[your code here]
f = np.empty(d.shape)

# Print the result
print("Array f (empty, same shape as d):")
print(f)

Array f (empty, same shape as d):
[[[0.31400412 0.89094671 0.3568243  0.53912641 0.55370618]
  [0.40161218 0.5996011  0.13521672 0.802483   0.71030026]
  [0.05669969 0.33912242 0.05662264 0.58302488 0.69219882]]

 [[0.69915132 0.07248887 0.11511851 0.93140531 0.3895057 ]
  [0.26723976 0.34164203 0.84205182 0.56821298 0.99510543]
  [0.93597404 0.23256409 0.05958396 0.7021813  0.05616356]]]


In [ ]:
"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""

In [25]:
#[your code here]
for i in range(d.shape[0]):  # Iterate over the first dimension
    for j in range(d.shape[1]):  # Iterate over the second dimension
        for k in range(d.shape[2]):  # Iterate over the third dimension
            value = d[i][j][k]  # Get the value at the current position
            if value == d_min:
                f[i][j][k] = 0
            elif value == d_max:
                f[i][j][k] = 100
            elif value == d_mean:
                f[i][j][k] = 50
            elif d_min < value < d_mean:
                f[i][j][k] = 25
            elif d_mean < value < d_max:
                f[i][j][k] = 75

# Print the populated f
print("Array f after populating values:")
print(f)

Array f after populating values:
[[[ 25.  75.  25.  75.  75.]
  [ 25.  75.  25.  75.  75.]
  [ 25.  25.  25.  75.  75.]]

 [[ 75.  25.  25.  75.  25.]
  [ 25.  25.  75.  75. 100.]
  [ 75.  25.  25.  75.   0.]]]


In [ ]:
"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""

In [27]:
#[your code here]
print("Array d:")
print(d)

# Print the array f
print("\nArray f (labeled values):")
print(f)

Array d:
[[[1.31400412 1.89094671 1.3568243  1.53912641 1.55370618]
  [1.40161218 1.5996011  1.13521672 1.802483   1.71030026]
  [1.05669969 1.33912242 1.05662264 1.58302488 1.69219882]]

 [[1.69915132 1.07248887 1.11511851 1.93140531 1.3895057 ]
  [1.26723976 1.34164203 1.84205182 1.56821298 1.99510543]
  [1.93597404 1.23256409 1.05958396 1.7021813  1.05616356]]]

Array f (labeled values):
[[[ 25.  75.  25.  75.  75.]
  [ 25.  75.  25.  75.  75.]
  [ 25.  25.  25.  75.  75.]]

 [[ 75.  25.  25.  75.  25.]
  [ 25.  25.  75.  75. 100.]
  [ 75.  25.  25.  75.   0.]]]


In [ ]:
"""
#18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.
"""