# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [37]:
### [your code here]
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [68]:
### [your code here]
print (np.__version__)
print(np.show_config())



2.2.3
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30158",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.12",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30158",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.28",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-3gfa2f0z/cp311-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include",
      "lib 

C:\Users\GAMING\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [45]:
### [your code here]
a= np.random.randint(5, size=(2,3,5))



### 4. Print a.


In [46]:
### [your code here]
print(a)

[[[2 1 4 1 2]
  [1 2 3 0 2]
  [2 4 2 1 3]]

 [[4 0 3 1 3]
  [1 3 1 1 1]
  [3 3 2 0 3]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [63]:
### [your code here]
b=np.ones((5,2,3))



### 6. Print b.


In [64]:
### [your code here]
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [ ]:
### [your code here]

same_size = a.size == b.size
same_shape = a.shape == b.shape

print("Array a shape:", a.shape)
print("Array b shape:", b.shape)
print("Do a and b have the same size?", same_size)
print("Do a and b have the same shape?", same_shape)

Array a shape: (2, 3, 5)
Array b shape: (5, 2, 3)
Do a and b have the same size? True
Do a and b have the same shape? False



### 8. Are you able to add a and b? Why or why not?


In [70]:
### [your code here]
can_add = a.shape == b.shape or (a.shape[0] == b.shape[1] and a.shape[1] == b.shape[2])

print("Shape of a:", a.shape)
print("Shape of b:", b.shape)
print("Can a and b be added?", can_add)

Shape of a: (2, 3, 5)
Shape of b: (5, 2, 3)
Can a and b be added? True




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [71]:
### [your code here]

c = np.transpose(b, (1, 2, 0))  

print("Shape of a:", a.shape)
print("Shape of b:", b.shape)
print("Shape of c:", c.shape)

Shape of a: (2, 3, 5)
Shape of b: (5, 2, 3)
Shape of c: (2, 3, 5)



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [72]:
### [your code here]
d = a + c

print("Shape of a:", a.shape)
print("Shape of c:", c.shape)
print("Shape of d (sum):", d.shape)
print("Sum array d:\n", d)


Shape of a: (2, 3, 5)
Shape of c: (2, 3, 5)
Shape of d (sum): (2, 3, 5)
Sum array d:
 [[[3. 2. 5. 2. 3.]
  [2. 3. 4. 1. 3.]
  [3. 5. 3. 2. 4.]]

 [[5. 1. 4. 2. 4.]
  [2. 4. 2. 2. 2.]
  [4. 4. 3. 1. 4.]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [73]:
### [your code here]

d = a + c

print("Array a:\n", a)
print("Array d (a + c):\n", d)

Array a:
 [[[2 1 4 1 2]
  [1 2 3 0 2]
  [2 4 2 1 3]]

 [[4 0 3 1 3]
  [1 3 1 1 1]
  [3 3 2 0 3]]]
Array d (a + c):
 [[[3. 2. 5. 2. 3.]
  [2. 3. 4. 1. 3.]
  [3. 5. 3. 2. 4.]]

 [[5. 1. 4. 2. 4.]
  [2. 4. 2. 2. 2.]
  [4. 4. 3. 1. 4.]]]



### 12. Multiply a and c. Assign the result to e.


In [74]:
### [your code here]
e = a * c

print("Array a:\n", a)
print("Array c:\n", c)
print("Array e (a * c):\n", e)

Array a:
 [[[2 1 4 1 2]
  [1 2 3 0 2]
  [2 4 2 1 3]]

 [[4 0 3 1 3]
  [1 3 1 1 1]
  [3 3 2 0 3]]]
Array c:
 [[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
Array e (a * c):
 [[[2. 1. 4. 1. 2.]
  [1. 2. 3. 0. 2.]
  [2. 4. 2. 1. 3.]]

 [[4. 0. 3. 1. 3.]
  [1. 3. 1. 1. 1.]
  [3. 3. 2. 0. 3.]]]




### 13. Does e equal to a? Why or why not?


In [75]:
### [your code here]
are_equal = np.array_equal(e, a)
print("Is e equal to a?", are_equal)


Is e equal to a? True




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [76]:
### [your code here]

d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print("Max value in d:", d_max)
print("Min value in d:", d_min)
print("Mean value in d:", d_mean)

Max value in d: 5.0
Min value in d: 1.0
Mean value in d: 2.966666666666667



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [78]:
### [your code here]
f = np.empty(d.shape)

print("Shape of f:", f.shape)

Shape of f: (2, 3, 5)





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [79]:
### [your code here]
for i in range(d.shape[0]):  

    for j in range(d.shape[1]):     

        for k in range(d.shape[2]): 

            if d[i][j][k] == d_min:
                f[i][j][k] = 0

            elif d[i][j][k] == d_mean:
                f[i][j][k] = 50

            elif d[i][j][k] > d_mean and d[i][j][k] < d_max:
                f[i][j][k] = 75

            elif d[i][j][k] > d_min and d[i][j][k] < d_mean:
                f[i][j][k] = 25
                
            elif d[i][j][k] == d_max:
                f[i][j][k] = 100

print("Array f:\n", f)

Array f:
 [[[ 75.  25. 100.  25.  75.]
  [ 25.  75.  75.   0.  75.]
  [ 75. 100.  75.  25.  75.]]

 [[100.   0.  75.  25.  75.]
  [ 25.  75.  25.  25.  25.]
  [ 75.  75.  75.   0.  75.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [82]:
### [your code here]

print("Array d:\n", d)
print("Array f:\n", f)

Array d:
 [[[3. 2. 5. 2. 3.]
  [2. 3. 4. 1. 3.]
  [3. 5. 3. 2. 4.]]

 [[5. 1. 4. 2. 4.]
  [2. 4. 2. 2. 2.]
  [4. 4. 3. 1. 4.]]]
Array f:
 [[[ 75.  25. 100.  25.  75.]
  [ 25.  75.  75.   0.  75.]
  [ 75. 100.  75.  25.  75.]]

 [[100.   0.  75.  25.  75.]
  [ 25.  75.  25.  25.  25.]
  [ 75.  75.  75.   0.  75.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [85]:
### [your code here]

for i in range(d.shape[0]):  

    for j in range(d.shape[1]): 

        for k in range(d.shape[2]): 

            if d[i][j][k] == d_min:
                f[i][j][k] = 'A'  

            elif d[i][j][k] == d_mean:
                f[i][j][k] = 'C'  

            elif d[i][j][k] > d_mean and d[i][j][k] < d_max:
                f[i][j][k] = 'D'  

            elif d[i][j][k] > d_min and d[i][j][k] < d_mean:
                f[i][j][k] = 'B'  

            elif d[i][j][k] == d_max:
                f[i][j][k] = 'E'  
                
print("Array f with string labels:\n", f)

Array f with string labels:
 [[['D', 'B', 'E', 'B', 'D'], ['B', 'D', 'D', 'A', 'D'], ['D', 'E', 'D', 'B', 'D']], [['E', 'A', 'D', 'B', 'D'], ['B', 'D', 'B', 'B', 'B'], ['D', 'D', 'D', 'A', 'D']]]
