# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [2]:
### [your code here]
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [3]:
### [your code here]
print("NumPy Version:", np.__version__)
np.show_config()  # Displays NumPy configuration details

NumPy Version: 1.25.2
openblas64__info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
blas_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None)]
    runtime_library_dirs = ['openblas\\lib']
openblas64__lapack_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HAVE_CBLAS', None), ('BLAS_SYMBOL_SUFFIX', '64_'), ('HAVE_BLAS_ILP64', None), ('HAVE_LAPACKE', None)]
    runtime_library_dirs = ['openblas\\lib']
lapack_ilp64_opt_info:
    libraries = ['openblas64_', 'openblas64_']
    library_dirs = ['openblas\\lib']
    language = c
    define_macros = [('HA

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [4]:
### [your code here]
# Method 1
a = np.random.random((2, 3, 5))   # Generates random floats between 0 and 1

# Method 2
a = np.random.uniform(10, 50, (2, 3, 5))  # Random floats between 10 and 50

# Method 3
a = np.random.randint(0, 100, (2, 3, 5))  # Random integers from 0 to 99



### 4. Print a.


In [5]:
### [your code here]
print(a) # Method 3

[[[77 62 25  7 14]
  [64 25 20 80 44]
  [36 72 87 93 88]]

 [[21 98 65 19 44]
  [13 91 43 88  5]
  [34 23 84 39 71]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [6]:
### [your code here]
b = np.ones((5,2,3))


### 6. Print b.


In [7]:
### [your code here]
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [8]:
### [your code here]

print("Do a and b have the same size?", a.size == b.size)

# Print sizes 
print("Size of a:", a.size)
print("Size of b:", b.size)

Do a and b have the same size? True
Size of a: 30
Size of b: 30



### 8. Are you able to add a and b? Why or why not?


In [9]:
### [your code here]
a + b
# No, we cannot directly add a and b because their shapes are different and incompatible for broadcasting.

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

In [10]:
# To fix it we must reshape one of the arrays to match the other.
b_reshaped = b.reshape(2, 3, 5) # Change shape from (5,2,3) to (2,3,5)
result = a + b_reshaped
print(result)

[[[78. 63. 26.  8. 15.]
  [65. 26. 21. 81. 45.]
  [37. 73. 88. 94. 89.]]

 [[22. 99. 66. 20. 45.]
  [14. 92. 44. 89.  6.]
  [35. 24. 85. 40. 72.]]]




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [11]:
### [your code here]
# We want to move the first axis (size 5) to the end, 
# so the new order is: axis 1 (size 2), axis 2 (size 3), axis 0 (size 5).
c = b.transpose(1, 2, 0)  # Change shape from (5,2,3) to (2,3,5)


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [12]:
### [your code here]
d = a + c
# After transposing, the addition worked because we restructured b to have the same shape as a.


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [13]:
### [your code here]

print("-------------------------- a --------------------------")
print(a)
print("-------------------------- d --------------------------")
print(d)

# When we printed a and d, I likely noticed that d has the same shape as a but different (usually larger) values. 
# This is because d was created by adding a to another array c (which is b transposed to match a’s shape).


-------------------------- a --------------------------
[[[77 62 25  7 14]
  [64 25 20 80 44]
  [36 72 87 93 88]]

 [[21 98 65 19 44]
  [13 91 43 88  5]
  [34 23 84 39 71]]]
-------------------------- d --------------------------
[[[78. 63. 26.  8. 15.]
  [65. 26. 21. 81. 45.]
  [37. 73. 88. 94. 89.]]

 [[22. 99. 66. 20. 45.]
  [14. 92. 44. 89.  6.]
  [35. 24. 85. 40. 72.]]]



### 12. Multiply a and c. Assign the result to e.


In [14]:
### [your code here]
e = a * c
e

array([[[77., 62., 25.,  7., 14.],
        [64., 25., 20., 80., 44.],
        [36., 72., 87., 93., 88.]],

       [[21., 98., 65., 19., 44.],
        [13., 91., 43., 88.,  5.],
        [34., 23., 84., 39., 71.]]])



### 13. Does e equal to a? Why or why not?


In [15]:
### [your code here]
print("Does e equal to a? \n" , a == e)

# Since 'c' consists entirely of 1s, multiplying 'a' by 'c' does not change the values in 'a'.
# Therefore, 'e' will be the same as 'a', and element-wise comparison 'a == e' will be True for all elements.

Does e equal to a? 
 [[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [16]:
### [your code here]
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

print("The max of d : " , d_max)
print("The min of d : " , d_min)
print("The mean of d : " , d_mean)


The max of d :  99.0
The min of d :  6.0
The mean of d :  52.06666666666667



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [17]:
### [your code here]
f = np.empty((2,3,5))




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [18]:
### [your code here]
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d_min < d[i, j, k] < d_mean:
                f[i, j, k] = 25
            elif d_mean < d[i, j, k] < d_max:
                f[i, j, k] = 75
            elif d[i, j, k] == d_mean:
                f[i, j, k] = 50
            elif d[i, j, k] == d_min:
                f[i, j, k] = 0
            else:  # d[i, j, k] == d_max
                f[i, j, k] = 100 





### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [19]:
### [your code here]
print("-------------------------- d --------------------------")
print(d)
print("-------------------------- f --------------------------")
print(f)

-------------------------- d --------------------------
[[[78. 63. 26.  8. 15.]
  [65. 26. 21. 81. 45.]
  [37. 73. 88. 94. 89.]]

 [[22. 99. 66. 20. 45.]
  [14. 92. 44. 89.  6.]
  [35. 24. 85. 40. 72.]]]
-------------------------- f --------------------------
[[[ 75.  75.  25.  25.  25.]
  [ 75.  25.  25.  75.  25.]
  [ 25.  75.  75.  75.  75.]]

 [[ 25. 100.  75.  25.  25.]
  [ 25.  75.  25.  75.   0.]
  [ 25.  25.  75.  25.  75.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [24]:
### [your code here]

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d_min < d[i, j, k] < d_mean:
                f[i, j, k] = "B"
            elif d_mean < d[i, j, k] < d_max:
                f[i, j, k] = "D"
            elif d[i, j, k] == d_mean:
                f[i, j, k] = "C"
            elif d[i, j, k] == d_min:
                f[i, j, k] = "A"
            else:  # d[i, j, k] == d_max
                f[i, j, k] = "E" 

print(f)

[[['D' 'D' 'B' 'B' 'B']
  ['D' 'B' 'B' 'D' 'B']
  ['B' 'D' 'D' 'D' 'D']]

 [['B' 'E' 'D' 'B' 'B']
  ['B' 'D' 'B' 'D' 'A']
  ['B' 'B' 'D' 'B' 'D']]]
