# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [31]:
### [your code here]
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [32]:
### [your code here]
print(np.__version__)

1.24.1


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [33]:


a = np.random.rand(2,3,5) # random
a2 = np.random.randint(low=0, high=100, size=(2, 3, 5)) #random integers
a3 = np.random.randn(2,3,5)  #normal distribution




### 4. Print a.


In [34]:

print(a)
print(a2)
print(a3)

[[[0.03603205 0.32622793 0.76755201 0.22657145 0.03607696]
  [0.30631933 0.24346376 0.14202934 0.33594679 0.35293681]
  [0.74846405 0.54312228 0.87561326 0.80882994 0.80692789]]

 [[0.63661704 0.26738321 0.61149809 0.46729431 0.93275384]
  [0.09732154 0.25129205 0.22602031 0.69394947 0.79843082]
  [0.57320044 0.90105587 0.0023414  0.25067835 0.24640423]]]
[[[42  9 56 27 33]
  [ 5 78 60  8 94]
  [35 72 85 31 15]]

 [[70 70 95 61 33]
  [51 97  5 44 54]
  [39 13  1 65 67]]]
[[[-0.88865644  0.711199    1.15606955 -0.83001708  0.24845695]
  [ 0.4356947  -0.28229373 -1.71333889  0.40103155  0.90508492]
  [ 0.33394599  0.01723525 -3.02583812  1.13040174 -0.46172913]]

 [[-0.83638343  0.21249555 -0.79382412 -0.51240501  1.70575814]
  [ 1.30067262  0.25599023 -0.11294832  0.41527694  1.79685815]
  [-0.01628515  1.88232589  0.98477062 -0.75251403 -1.06173301]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [35]:

b = np.ones((5,2,3))


### 6. Print b.


In [36]:

print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [37]:

if a.size == b.size:
    print("same size")

else:
    print("not same size")


same size



### 8. Are you able to add a and b? Why or why not?


In [38]:
# No, because thir shapes are not compatible.



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [39]:
# a -> 2 3 5
# b -> 5 2 3


c = np.transpose(b, (1, 2, 0))

c


array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [40]:
d = a + c

d

array([[[1.03603205, 1.32622793, 1.76755201, 1.22657145, 1.03607696],
        [1.30631933, 1.24346376, 1.14202934, 1.33594679, 1.35293681],
        [1.74846405, 1.54312228, 1.87561326, 1.80882994, 1.80692789]],

       [[1.63661704, 1.26738321, 1.61149809, 1.46729431, 1.93275384],
        [1.09732154, 1.25129205, 1.22602031, 1.69394947, 1.79843082],
        [1.57320044, 1.90105587, 1.0023414 , 1.25067835, 1.24640423]]])


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [41]:
### [your code here]

print(a)
print(d)

# values inside a and d have been added

[[[0.03603205 0.32622793 0.76755201 0.22657145 0.03607696]
  [0.30631933 0.24346376 0.14202934 0.33594679 0.35293681]
  [0.74846405 0.54312228 0.87561326 0.80882994 0.80692789]]

 [[0.63661704 0.26738321 0.61149809 0.46729431 0.93275384]
  [0.09732154 0.25129205 0.22602031 0.69394947 0.79843082]
  [0.57320044 0.90105587 0.0023414  0.25067835 0.24640423]]]
[[[1.03603205 1.32622793 1.76755201 1.22657145 1.03607696]
  [1.30631933 1.24346376 1.14202934 1.33594679 1.35293681]
  [1.74846405 1.54312228 1.87561326 1.80882994 1.80692789]]

 [[1.63661704 1.26738321 1.61149809 1.46729431 1.93275384]
  [1.09732154 1.25129205 1.22602031 1.69394947 1.79843082]
  [1.57320044 1.90105587 1.0023414  1.25067835 1.24640423]]]



### 12. Multiply a and c. Assign the result to e.


In [42]:

e = a * c

e

array([[[0.03603205, 0.32622793, 0.76755201, 0.22657145, 0.03607696],
        [0.30631933, 0.24346376, 0.14202934, 0.33594679, 0.35293681],
        [0.74846405, 0.54312228, 0.87561326, 0.80882994, 0.80692789]],

       [[0.63661704, 0.26738321, 0.61149809, 0.46729431, 0.93275384],
        [0.09732154, 0.25129205, 0.22602031, 0.69394947, 0.79843082],
        [0.57320044, 0.90105587, 0.0023414 , 0.25067835, 0.24640423]]])



### 13. Does e equal to a? Why or why not?


In [ ]:
# yes, because we multiplied with 1





### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [46]:

d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(d_max)
print(d_min)
print(d_mean)

1.9327538381581282
1.002341402895092
1.4504118272315794



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [48]:
f = np.empty((2,3,5))





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [ ]:

f[(d == d_min)] = 0
f[(d > d_min) & (d < d_mean)] = 25
f[(d == d_mean)] = 50
f[(d > d_mean) & (d < d_max)] = 75
f[(d == d_max)] = 50

# this technique is called boolen indexing



f

array([[[25., 25., 75., 25., 25.],
        [25., 25., 25., 25., 25.],
        [75., 75., 75., 75., 75.]],

       [[75., 25., 75., 75., 50.],
        [25., 25., 25., 75., 75.],
        [75., 75.,  0., 25., 25.]]])





### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [58]:
print(d)
print(f)

#yes

[[[1.03603205 1.32622793 1.76755201 1.22657145 1.03607696]
  [1.30631933 1.24346376 1.14202934 1.33594679 1.35293681]
  [1.74846405 1.54312228 1.87561326 1.80882994 1.80692789]]

 [[1.63661704 1.26738321 1.61149809 1.46729431 1.93275384]
  [1.09732154 1.25129205 1.22602031 1.69394947 1.79843082]
  [1.57320044 1.90105587 1.0023414  1.25067835 1.24640423]]]
[[[25. 25. 75. 25. 25.]
  [25. 25. 25. 25. 25.]
  [75. 75. 75. 75. 75.]]

 [[75. 25. 75. 75. 50.]
  [25. 25. 25. 75. 75.]
  [75. 75.  0. 25. 25.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [62]:

f_char = np.empty(f.shape, dtype=str) # "copy" shape of f but use str instead of float

f_char[(d == d_min)] = "A"
f_char[(d > d_min) & (d < d_mean)] = "B"
f_char[(d == d_mean)] = "C"
f_char[(d > d_mean) & (d < d_max)] = "D"
f_char[(d == d_max)] = "E"

# this technique is called boolen indexing



f_char

array([[['B', 'B', 'D', 'B', 'B'],
        ['B', 'B', 'B', 'B', 'B'],
        ['D', 'D', 'D', 'D', 'D']],

       [['D', 'B', 'D', 'D', 'E'],
        ['B', 'B', 'B', 'D', 'D'],
        ['D', 'D', 'A', 'B', 'B']]], dtype='<U1')