# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [ ]:
!pip install numpy

In [ ]:
import numpy as np


: 



### 2. Print the NUMPY version and the configuration.


In [ ]:


print("NumPy version:", np.__version__)


print("\nNumPy configuration:")
np.show_config()



NumPy version: 1.26.4

NumPy configuration:
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep140213194937296
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
  

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [ ]:
a = np.random.randint(0, 100, size=(2, 3, 5))
print(a)

[[[26 76 35 59  1]
  [19 74 14 94 60]
  [89 60 37 43 65]]

 [[70 85 49 83 32]
  [63 93 20 36 87]
  [17 71 65 63 28]]]



### 4. Print a.


In [ ]:
print(a)


[[[26 76 35 59  1]
  [19 74 14 94 60]
  [89 60 37 43 65]]

 [[70 85 49 83 32]
  [63 93 20 36 87]
  [17 71 65 63 28]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [ ]:
b = np.ones((5, 2, 3))
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 6. Print b.


In [ ]:
print(b)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [ ]:
if a.shape == b.shape:
    print("yes")
else:
    print("no")




no


In [ ]:
if a.size == b.size:
    print("yes")
else:
    print("no")


yes



### 8. Are you able to add a and b? Why or why not?


no, because they do not have the same dimensional



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [ ]:
c = b.reshape(2, 3, 5)

print(c)


[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [ ]:
d = a + c

print(d)


[[[27. 77. 36. 60.  2.]
  [20. 75. 15. 95. 61.]
  [90. 61. 38. 44. 66.]]

 [[71. 86. 50. 84. 33.]
  [64. 94. 21. 37. 88.]
  [18. 72. 66. 64. 29.]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [ ]:
print(a,d)



[[[26 76 35 59  1]
  [19 74 14 94 60]
  [89 60 37 43 65]]

 [[70 85 49 83 32]
  [63 93 20 36 87]
  [17 71 65 63 28]]] [[[27. 77. 36. 60.  2.]
  [20. 75. 15. 95. 61.]
  [90. 61. 38. 44. 66.]]

 [[71. 86. 50. 84. 33.]
  [64. 94. 21. 37. 88.]
  [18. 72. 66. 64. 29.]]]


couldn’t be added because they had different shapes


### 12. Multiply a and c. Assign the result to e.


In [ ]:
e = a * c
print(e)

[[[26. 76. 35. 59.  1.]
  [19. 74. 14. 94. 60.]
  [89. 60. 37. 43. 65.]]

 [[70. 85. 49. 83. 32.]
  [63. 93. 20. 36. 87.]
  [17. 71. 65. 63. 28.]]]




### 13. Does e equal to a? Why or why not?


yes,Since c is an array of ones (1.0), multiplying any number by 1 gives the same number.




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [ ]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print("Max value:", d_max)
print("Min value:", d_min)
print("Mean value:", d_mean)



Max value: 95.0
Min value: 2.0
Mean value: 54.8



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [ ]:
f = np.empty(d.shape)
print(f)

[[[27. 77. 36. 60.  2.]
  [20. 75. 15. 95. 61.]
  [90. 61. 38. 44. 66.]]

 [[71. 86. 50. 84. 33.]
  [64. 94. 21. 37. 88.]
  [18. 72. 66. 64. 29.]]]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [ ]:

for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i][j][k] == d_min:
                f[i][j][k] = 0
            elif d[i][j][k] == d_max:
                f[i][j][k] = 100
            elif d[i][j][k] == d_mean:
                f[i][j][k] = 50
            elif d_min < d[i][j][k] < d_mean:
                f[i][j][k] = 25
            elif d_mean < d[i][j][k] < d_max:
                f[i][j][k] = 75

print(f)


[[[ 25.  75.  25.  75.   0.]
  [ 25.  75.  25. 100.  75.]
  [ 75.  75.  25.  25.  75.]]

 [[ 75.  75.  25.  75.  25.]
  [ 75.  75.  25.  25.  75.]
  [ 25.  75.  75.  75.  25.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [ ]:
print("Array d:\n", d)
print("\nArray f (Labeled Values):\n", f)

Array d:
 [[[27. 77. 36. 60.  2.]
  [20. 75. 15. 95. 61.]
  [90. 61. 38. 44. 66.]]

 [[71. 86. 50. 84. 33.]
  [64. 94. 21. 37. 88.]
  [18. 72. 66. 64. 29.]]]

Array f (Labeled Values):
 [[[ 25.  75.  25.  75.   0.]
  [ 25.  75.  25. 100.  75.]
  [ 75.  75.  25.  25.  75.]]

 [[ 75.  75.  25.  75.  25.]
  [ 75.  75.  25.  25.  75.]
  [ 25.  75.  75.  75.  25.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [ ]:

f_str = [[[None for _ in range(d.shape[2])] for _ in range(d.shape[1])] for _ in range(d.shape[0])]


for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i][j][k] == d_min:
                f_str[i][j][k] = "A"
            elif d[i][j][k] == d_max:
                f_str[i][j][k] = "E"
            elif d[i][j][k] == d_mean:
                f_str[i][j][k] = "C"
            elif d_min < d[i][j][k] < d_mean:
                f_str[i][j][k] = "B"
            elif d_mean < d[i][j][k] < d_max:
                f_str[i][j][k] = "D"

print(f_str)


[[['B', 'D', 'B', 'D', 'A'], ['B', 'D', 'B', 'E', 'D'], ['D', 'D', 'B', 'B', 'D']], [['D', 'D', 'B', 'D', 'B'], ['D', 'D', 'B', 'B', 'D'], ['B', 'D', 'D', 'D', 'B']]]
