# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [53]:
import numpy as np




### 2. Print the NUMPY version and the configuration.


In [54]:
print("NumPy Version:", np.version)
np.show_config()

NumPy Version: <module 'numpy.version' from 'C:\\Users\\Hano\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python311\\site-packages\\numpy\\version.py'>
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30158",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.12",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30158",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.28",


C:\Users\Hano\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [77]:
a = np.random.rand(2, 3, 5)



### 4. Print a.


In [56]:
a = np.random.rand(2, 3, 5)
print(a)

[[[0.64277583 0.29669636 0.73240605 0.220352   0.19581006]
  [0.72910094 0.09060656 0.47596916 0.50083967 0.83039564]
  [0.62757973 0.72426695 0.43022499 0.94069789 0.65763865]]

 [[0.44048733 0.23848404 0.45730751 0.9156309  0.34792164]
  [0.05818873 0.14378616 0.27851733 0.28245203 0.50091253]
  [0.29710005 0.18026062 0.85662992 0.76198963 0.42432745]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [83]:
b = np.ones((5, 2, 3))


### 6. Print b.


In [84]:
b = np.ones((5, 2, 3))
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [59]:
if len(a) == len(b):
    print("is equal")

else :
    print("not equal")


not equal



### 8. Are you able to add a and b? Why or why not?


In [ ]:

array3 = a+b
print(array3)
print("i can not  add  a and b becose we dont have the same sheap  ")


ValueError: operands could not be broadcast together with shapes (2,3,5) (5,3,3) 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [112]:


c = np.transpose(b, axes=(1, 2, 0))


print("Array a shape:", a.shape)
print("Array b shape:", b.shape)
print("Transposed array c shape:", c.shape)


Array a shape: (2, 3, 5)
Array b shape: (5, 2, 3)
Transposed array c shape: (2, 3, 5)



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [72]:
rray3 =np.add(a,c)
print(array3)
print("i can  add  a + c  becose we have the same sheap  ")

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]
i can  add  a + c  becose we have the same sheap  



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [86]:
print(a)
print(b)
print("the difference in the sheap and relation .....")


[[[0.82307659 0.21964863 0.09134314 0.43025835 0.54870191]
  [0.11656264 0.417652   0.29535733 0.01714874 0.31298977]
  [0.89302856 0.12115005 0.50103552 0.55753699 0.90042431]]

 [[0.06316824 0.94300582 0.6567622  0.56624928 0.02688891]
  [0.64392982 0.79069485 0.49036052 0.89507377 0.02177952]
  [0.18738318 0.00983885 0.66641957 0.57638864 0.74039345]]]
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]
the difference in the sheap and relation .....



### 12. Multiply a and c. Assign the result to e.


In [75]:
e =np.multiply(a,c)
print(e)


[[[0.41316076 0.08802873 0.53641862 0.048555   0.03834158]
  [0.53158818 0.00820955 0.22654664 0.25084038 0.68955692]
  [0.39385631 0.52456262 0.18509354 0.88491253 0.43248859]]

 [[0.19402909 0.05687464 0.20913016 0.83837994 0.12104947]
  [0.00338593 0.02067446 0.0775719  0.07977915 0.25091336]
  [0.08826844 0.03249389 0.73381482 0.5806282  0.18005379]]]




### 13. Does e equal to a? Why or why not?


In [90]:
e.size == e.size
print("e it is equal a ")


e it is equal a 




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [124]:
d= np.array([2 , 20 , 19 , 199 ,300 ,0 ,3 ])
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print("Max Value:", d_max)
print("Min Value:", d_min)
print("mean value :" , d_mean)


Max Value: 300
Min Value: 0
mean value : 77.57142857142857



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [125]:
f = np.empty([2,3,5])
print(f)




[[[0.41316076 0.08802873 0.53641862 0.048555   0.03834158]
  [0.53158818 0.00820955 0.22654664 0.25084038 0.68955692]
  [0.39385631 0.52456262 0.18509354 0.88491253 0.43248859]]

 [[0.19402909 0.05687464 0.20913016 0.83837994 0.12104947]
  [0.00338593 0.02067446 0.0775719  0.07977915 0.25091336]
  [0.08826844 0.03249389 0.73381482 0.5806282  0.18005379]]]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [130]:
d = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
f = [0] * len(d)
for i in range(len(d)):
    if d[i] == d_min:
        f[i] = 100
    elif d[i] == d_max:
        f[i] = 0
    elif d[i] == d_mean:
        f[i] = 50
    elif d_min < d[i] < d_mean:
        f[i] = 25
    elif d_mean < d[i] < d_max:
        f[i] = 75

print(f)






[25, 25, 25, 25, 25, 25, 25, 75, 75, 75]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [ ]:
print(d)
print(f)

### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [89]:

bonus__mapping = {
    "zero": 0,
    "twenty_five": 25,
    "fifty": 50,
    "seventy_five": 75,
    "hundred": 100
}


def get_bonus_value(bonus_string):
    return bonus__mapping.get(bonus_string.lower(), "Invalid bonus value")

# Example usage
bonus_string = "fifty"
bonus_value = get_bonus_value(bonus_string)
print(f"The bonus value for '{bonus_string}' is: {bonus_value}")

The bonus value for 'fifty' is: 50
