# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
### [your code here]

import numpy as np




### 2. Print the NUMPY version and the configuration.


In [3]:
### [your code here]

print(np.__version__)

np.show_config()


2.2.2
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30157",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.11",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30157",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.28",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-fwtr2gmz/cp313-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include",
      "lib 

c:\Users\fee10\Downloads\.venv\Lib\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [16]:
### [your code here]

a = np.random.random([2,3,5])
a = np.random.rand(2,3,5)
a= np.random.randn(2,3,5)
a=np.random.uniform(1,10, size = [2,3,5])
a= np.random.randint(10, size=[2,3,5])



[[[7 2 0 8 8]
  [4 0 7 3 0]
  [8 0 7 7 1]]

 [[0 5 1 5 4]
  [7 0 5 8 6]
  [9 1 6 3 1]]]



### 4. Print a.


In [17]:
### [your code here]
print(a)


[[[7 2 0 8 8]
  [4 0 7 3 0]
  [8 0 7 7 1]]

 [[0 5 1 5 4]
  [7 0 5 8 6]
  [9 1 6 3 1]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [24]:
### [your code here]
b = np.ones([5, 2, 3])



### 6. Print b.


In [25]:
### [your code here]
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [29]:
### [your code here]

equal_result = (a.size == b.size)
print(equal_result)

#Yes, they have the same size.


True



### 8. Are you able to add a and b? Why or why not?


In [28]:
### [your code here]
added = a + b
print(added)

#No, because they have not the same structure (2, 3, 5 vs. 5, 3, 2)

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [31]:
### [your code here]
c = np.reshape(b , (2, 3, 5))
print(c)


[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [33]:
### [your code here]
d = a + c
print(d)



[[[ 8.  3.  1.  9.  9.]
  [ 5.  1.  8.  4.  1.]
  [ 9.  1.  8.  8.  2.]]

 [[ 1.  6.  2.  6.  5.]
  [ 8.  1.  6.  9.  7.]
  [10.  2.  7.  4.  2.]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [35]:
### [your code here]

print(a)


print(b)

# a has random values from 0-9 and b has only "1" values. However, both arrays have the same size.


[[[7 2 0 8 8]
  [4 0 7 3 0]
  [8 0 7 7 1]]

 [[0 5 1 5 4]
  [7 0 5 8 6]
  [9 1 6 3 1]]]
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 12. Multiply a and c. Assign the result to e.


In [37]:
### [your code here]

e = a + c
print(e)


[[[ 8.  3.  1.  9.  9.]
  [ 5.  1.  8.  4.  1.]
  [ 9.  1.  8.  8.  2.]]

 [[ 1.  6.  2.  6.  5.]
  [ 8.  1.  6.  9.  7.]
  [10.  2.  7.  4.  2.]]]




### 13. Does e equal to a? Why or why not?


In [40]:
### [your code here]
equal = (e == a)
print(equal)

# a and e are not equal since they differ in their values.


[[[False False False False False]
  [False False False False False]
  [False False False False False]]

 [[False False False False False]
  [False False False False False]
  [False False False False False]]]




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [43]:
### [your code here]

d_max = np.max(d)
print(d_max)

d_min = np.min(d)
print(d_min)

d_mean = np.mean(d)
print(d_mean)



10.0
1.0
5.1



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [44]:
### [your code here]

f = np.empty([2,3,5])
print(f)


[[[ 8.  3.  1.  9.  9.]
  [ 5.  1.  8.  4.  1.]
  [ 9.  1.  8.  8.  2.]]

 [[ 1.  6.  2.  6.  5.]
  [ 8.  1.  6.  9.  7.]
  [10.  2.  7.  4.  2.]]]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [62]:
f[(d > d_mean) & (d < d_max)] = 75

f[(d == d_mean)] = 50

f[(d == d_min)] = 0

print(f)

[[[75.  3.  0. 75. 75.]
  [ 5.  0. 75.  4.  0.]
  [75.  0. 75. 75.  2.]]

 [[ 0. 75.  2. 75.  5.]
  [75.  0. 75. 75. 75.]
  [10.  2. 75.  4.  2.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [64]:
### [your code here]
print(d)
print(f)

[[[ 8.  3.  1.  9.  9.]
  [ 5.  1.  8.  4.  1.]
  [ 9.  1.  8.  8.  2.]]

 [[ 1.  6.  2.  6.  5.]
  [ 8.  1.  6.  9.  7.]
  [10.  2.  7.  4.  2.]]]
[[[75.  3.  0. 75. 75.]
  [ 5.  0. 75.  4.  0.]
  [75.  0. 75. 75.  2.]]

 [[ 0. 75.  2. 75.  5.]
  [75.  0. 75. 75. 75.]
  [10.  2. 75.  4.  2.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [ ]:
### [your code here]

# for the conditions, instead of assigning numbers, we assign strings.