# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [2]:
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [3]:
import numpy as np

# طباعة إصدار NumPy
print("NumPy Version:", np.__version__)

# طباعة تفاصيل التكوين
np.show_config()


NumPy Version: 2.0.2
{
  "Compilers": {
    "c": {
      "name": "clang",
      "linker": "ld64",
      "version": "15.0.0",
      "commands": "cc"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.11",
      "commands": "cython"
    },
    "c++": {
      "name": "clang",
      "linker": "ld64",
      "version": "15.0.0",
      "commands": "c++"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "aarch64",
      "family": "aarch64",
      "endian": "little",
      "system": "darwin"
    },
    "build": {
      "cpu": "aarch64",
      "family": "aarch64",
      "endian": "little",
      "system": "darwin"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "accelerate",
      "found": true,
      "version": "unknown",
      "detection method": "system",
      "include directory": "unknown",
      "lib directory": "unknown",
      "openblas configuration": "unknown",
      "pc file directory": "unknown"
    },
    "l

/Users/wafaalqahtani/Library/Python/3.9/lib/python/site-packages/numpy/__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [6]:
import numpy as np

# إنشاء مصفوفة 3D بحجم (2,3,5) تحتوي على قيم عشوائية بين 0 و 1
a = np.random.rand(2, 3, 5)



### 4. Print a.


In [7]:
print(a)

[[[0.54871377 0.91256418 0.42609697 0.91895222 0.36465436]
  [0.35711955 0.42282524 0.64164883 0.73895101 0.57523504]
  [0.1810825  0.32556026 0.06870768 0.85253036 0.1037896 ]]

 [[0.63582097 0.84473961 0.44000823 0.99573325 0.56570751]
  [0.17607012 0.6018077  0.38375794 0.32016845 0.27886076]
  [0.38785441 0.90603751 0.36088925 0.36973559 0.25499985]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [11]:
import numpy as np

# إنشاء مصفوفة 3D بحجم (5,2,3) تحتوي على القيم 1
b = np.ones((5, 2, 3))




### 6. Print b.


In [9]:

print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [30]:
import numpy as np

# a 
a = np.random.rand(2, 3, 5)

# b
b = np.ones((5, 2, 3))

# التحقق مما إذا كان لهما نفس الحجم
same_size = a.size == b.size

print("Size of a:", a.size)
print("Size of b:", b.size)
print("Do a and b have the same size?", same_size)


Size of a: 30
Size of b: 30
Do a and b have the same size? True



### 8. Are you able to add a and b? Why or why not?
yes it's can added as it's shwoen below.

In [31]:
import numpy as np

# a
a = np.random.rand(2, 3, 5)

# b
b = np.ones((2, 3, 5))

# sum a,b 
sum_ = a + b

print(sum_)


[[[1.77502006 1.9110054  1.39834262 1.21033457 1.13819011]
  [1.0559052  1.78190578 1.32726615 1.48771567 1.01397213]
  [1.27630744 1.18086654 1.45177915 1.78162774 1.5892984 ]]

 [[1.12888397 1.85954782 1.9079591  1.82439769 1.1620299 ]
  [1.01453994 1.56372224 1.00079671 1.82222621 1.35427405]
  [1.76734316 1.14939468 1.05113015 1.10891142 1.65933074]]]




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [32]:
import numpy as np

# إنشاء المصفوفة a بحجم (2,3,5) بقيم عشوائية
a = np.random.rand(2, 3, 5)

# إنشاء المصفوفة b بحجم (5,2,3) تحتوي على قيم 1
b = np.ones((5, 2, 3))

# تبديل محاور b لتصبح بحجم (2,3,5)
c = np.transpose(b, (1, 2, 0))

# جمع a و c
sum_ = a + c

# طباعة النتيجة
print(sum_)



[[[1.54772438 1.01373621 1.16747364 1.12795403 1.58510393]
  [1.5648133  1.67250432 1.39429557 1.34970507 1.64436271]
  [1.29999596 1.08061015 1.14187782 1.76063628 1.86402371]]

 [[1.06972439 1.5724748  1.13067011 1.99730321 1.67096408]
  [1.03981112 1.78808984 1.91337915 1.0561826  1.87958489]
  [1.12158304 1.22268262 1.10184846 1.90220822 1.94819615]]]



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?
Yes, the addition worked because we used `np.transpose(b, (1, 2, 0))` to make **`c` match the shape of `a`**.  

In [33]:
import numpy as np

# a
a = np.random.rand(2, 3, 5)

# إنشاء المصفوفة b بحجم (5,2,3) تحتوي على قيم 1
b = np.ones((5, 2, 3))

# تبديل محاور b لتصبح بحجم (2,3,5)
c = np.transpose(b, (1, 2, 0))

# الآن c له نفس أبعاد a، لذا يمكن جمعهما
d = a + c

# طباعة النتيجة
print(d)


[[[1.4777212  1.59350885 1.83572052 1.40411704 1.49523762]
  [1.69209023 1.37070497 1.49893102 1.48811065 1.80253105]
  [1.05086685 1.11120644 1.14148086 1.21746884 1.04507528]]

 [[1.32136273 1.45370756 1.94511244 1.74364928 1.46492186]
  [1.98636565 1.49589694 1.3031381  1.41497525 1.75631386]
  [1.44215879 1.11613882 1.78488072 1.10694851 1.59253041]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
d is just a + 1, so every element in d is exactly 1 unit greater than in a.
 Since c contains only ones, it acts like a "shift" where all values in a are increased by 1.
 a and d have the same structure, but d is just a shifted by 1!


In [34]:
import numpy as np

# Create array 'a' 
a = np.random.rand(2, 3, 5)

# Create array 'b' 
b = np.ones((5, 2, 3))

# Transpose 'b' to match 'a' 
c = np.transpose(b, (1, 2, 0))

# Add 'a' and 'c' to get 'd'
d = a + c

# Print 'a' and 'd'
print("Array a:\n", a)
print("\nArray d (a + c):\n", d)



Array a:
 [[[0.27444746 0.99332938 0.1048822  0.99571605 0.64180872]
  [0.34250613 0.61204469 0.14868605 0.58201914 0.67235379]
  [0.94744519 0.69855631 0.71026609 0.06967281 0.78185863]]

 [[0.09960125 0.79389107 0.18795438 0.62740258 0.84088889]
  [0.51948551 0.41328787 0.96225065 0.48413627 0.85572089]
  [0.13220576 0.78477462 0.08634868 0.277321   0.04511325]]]

Array d (a + c):
 [[[1.27444746 1.99332938 1.1048822  1.99571605 1.64180872]
  [1.34250613 1.61204469 1.14868605 1.58201914 1.67235379]
  [1.94744519 1.69855631 1.71026609 1.06967281 1.78185863]]

 [[1.09960125 1.79389107 1.18795438 1.62740258 1.84088889]
  [1.51948551 1.41328787 1.96225065 1.48413627 1.85572089]
  [1.13220576 1.78477462 1.08634868 1.277321   1.04511325]]]



### 12. Multiply a and c. Assign the result to e.


In [35]:
import numpy as np


# Create array 'a' 
a = np.random.rand(2, 3, 5)

# Create array 'c' 
c = np.transpose(b, (1, 2, 0))

#multiply a , c and assign it TO e 
e = a * c

# Print the result
print("Array e (a * c):\n", e)





Array e (a * c):
 [[[0.64203552 0.18247732 0.44564965 0.33841189 0.98404987]
  [0.01674372 0.22961863 0.29792957 0.84407807 0.45241009]
  [0.94546945 0.93413066 0.51055666 0.78234898 0.04029481]]

 [[0.95168849 0.33991306 0.41360669 0.44753704 0.62995732]
  [0.92532504 0.59015151 0.93113078 0.8522555  0.49320586]
  [0.54188385 0.2691343  0.00765889 0.45920043 0.11288805]]]




### 13. Does e equal to a? Why or why not?
 Because all they are the same elements and then we can multiply it

In [37]:
print(np.array_equal(e, a))  


True




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [ ]:
import numpy as np

# Create array 'a' with shape (2,3,5) containing random values
a = np.random.rand(2, 3, 5)

# Create array 'b' with shape (5,2,3) containing only ones
b = np.ones((5, 2, 3))

# Transpose 'b' to match 'a' in shape (2,3,5)
c = np.transpose(b, (1, 2, 0))

# Add 'a' and 'c' to get 'd'
d = a + c

# Identify max, min, and mean values in 'd'
d_max = np.max(d)   # Maximum value
d_min = np.min(d)   # Minimum value
d_mean = np.mean(d) # Mean value




### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [38]:
import numpy as np

# Create array 'a' with shape (2,3,5) containing random values
a = np.random.rand(2, 3, 5)

# Create array 'b' with shape (5,2,3) containing only ones
b = np.ones((5, 2, 3))

# Transpose 'b' to match 'a' in shape (2,3,5)
c = np.transpose(b, (1, 2, 0))

# Add 'a' and 'c' to get 'd'
d = a + c

# Create an empty array 'f' with the same shape as 'd'
f = np.empty_like(d)

# Print 'f' (it contains uninitialized random values)
print("Empty array f:\n", f)


Empty array f:
 [[[1.27444746 1.99332938 1.1048822  1.99571605 1.64180872]
  [1.34250613 1.61204469 1.14868605 1.58201914 1.67235379]
  [1.94744519 1.69855631 1.71026609 1.06967281 1.78185863]]

 [[1.09960125 1.79389107 1.18795438 1.62740258 1.84088889]
  [1.51948551 1.41328787 1.96225065 1.48413627 1.85572089]
  [1.13220576 1.78477462 1.08634868 1.277321   1.04511325]]]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [39]:
import numpy as np

# Create array 'a' with shape (2,3,5) containing random values
a = np.random.rand(2, 3, 5)

# Create array 'b' with shape (5,2,3) containing only ones
b = np.ones((5, 2, 3))

# Transpose 'b' to match 'a' in shape (2,3,5)
c = np.transpose(b, (1, 2, 0))

# Add 'a' and 'c' to get 'd'
d = a + c

# Identify max, min, and mean values in 'd'
d_max = np.max(d)   # Maximum value
d_min = np.min(d)   # Minimum value
d_mean = np.mean(d) # Mean value

# Create an empty array 'f' with the same shape as 'd'
f = np.empty_like(d)

# Populate 'f' based on conditions
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i, j, k] == d_min:
                f[i, j, k] = 0
            elif d[i, j, k] == d_max:
                f[i, j, k] = 100
            elif d_min < d[i, j, k] < d_mean:
                f[i, j, k] = 25
            elif d[i, j, k] == d_mean:
                f[i, j, k] = 50
            elif d_mean < d[i, j, k] < d_max:
                f[i, j, k] = 75

# Print the final labeled array
print("Labeled array f:\n", f)


Labeled array f:
 [[[ 25. 100.  75.  75.  75.]
  [ 25.  25.  25.  75.  75.]
  [ 75.  75.  25.  75.  75.]]

 [[ 75.  75.  25.  25.  25.]
  [ 25.  25.  75.  75.  25.]
  [ 75.  25.  25.  25.   0.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [40]:
import numpy as np

# Create array 'a' with shape (2,3,5) containing random values
a = np.random.rand(2, 3, 5)

# Create array 'b' with shape (5,2,3) containing only ones
b = np.ones((5, 2, 3))

# Transpose 'b' to match 'a' in shape (2,3,5)
c = np.transpose(b, (1, 2, 0))

# Add 'a' and 'c' to get 'd'
d = a + c

# Identify max, min, and mean values in 'd'
d_max = np.max(d)   # Maximum value
d_min = np.min(d)   # Minimum value
d_mean = np.mean(d) # Mean value

# Create an empty array 'f' with the same shape as 'd'
f = np.empty_like(d)

# Populate 'f' based on conditions
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i, j, k] == d_min:
                f[i, j, k] = 0
            elif d[i, j, k] == d_max:
                f[i, j, k] = 100
            elif d_min < d[i, j, k] < d_mean:
                f[i, j, k] = 25
            elif d[i, j, k] == d_mean:
                f[i, j, k] = 50
            elif d_mean < d[i, j, k] < d_max:
                f[i, j, k] = 75

# Print the arrays
print("Array d:\n", d)
print("\nLabeled Array f:\n", f)


Array d:
 [[[1.85558077 1.26446805 1.38031988 1.83397031 1.09636529]
  [1.03888522 1.64159797 1.30054562 1.64327676 1.64732147]
  [1.87158054 1.49504625 1.03074718 1.6174318  1.78245645]]

 [[1.22819984 1.02023909 1.59189757 1.95497926 1.69358197]
  [1.53841933 1.92566388 1.68506739 1.33708322 1.97946458]
  [1.57333557 1.10049028 1.27598452 1.46026274 1.33145269]]]

Labeled Array f:
 [[[ 75.  25.  25.  75.  25.]
  [ 25.  75.  25.  75.  75.]
  [ 75.  25.  25.  75.  75.]]

 [[ 25.   0.  75.  75.  75.]
  [ 75.  75.  75.  25. 100.]
  [ 75.  25.  25.  25.  25.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [41]:
import numpy as np

# Create array 'a' with shape (2,3,5) containing random values
a = np.random.rand(2, 3, 5)

# Create array 'b' with shape (5,2,3) containing only ones
b = np.ones((5, 2, 3))

# Transpose 'b' to match 'a' in shape (2,3,5)
c = np.transpose(b, (1, 2, 0))

# Add 'a' and 'c' to get 'd'
d = a + c

# Identify max, min, and mean values in 'd'
d_max = np.max(d)   # Maximum value
d_min = np.min(d)   # Minimum value
d_mean = np.mean(d) # Mean value

# Create an empty array 'f' with the same shape as 'd' but with string type
f = np.empty(d.shape, dtype='<U1')  # '<U1' means a string of length 1

# Populate 'f' based on conditions using strings
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i, j, k] == d_min:
                f[i, j, k] = "A"  # Minimum value
            elif d[i, j, k] == d_max:
                f[i, j, k] = "E"  # Maximum value
            elif d_min < d[i, j, k] < d_mean:
                f[i, j, k] = "B"  # Between min and mean
            elif d[i, j, k] == d_mean:
                f[i, j, k] = "C"  # Equal to mean
            elif d_mean < d[i, j, k] < d_max:
                f[i, j, k] = "D"  # Between mean and max

# Print the labeled array
print("Labeled Array f:\n", f)


Labeled Array f:
 [[['B' 'A' 'D' 'B' 'D']
  ['B' 'B' 'B' 'B' 'B']
  ['D' 'D' 'E' 'D' 'B']]

 [['B' 'B' 'D' 'D' 'D']
  ['D' 'B' 'B' 'D' 'B']
  ['D' 'D' 'D' 'B' 'D']]]
