#Import the NUMPY package under the name np.

In [3]:
import numpy as np
import random   

Print the NUMPY version and the configuration.

In [4]:
print(np.__version__)
np.show_config()

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/anaconda3/include
    lib directory: /opt/anaconda3/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 VORTEX MAX_THREADS=128
    pc file directory: /opt/anaconda3/lib/pkgconfig
    version: 0.3.21
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep4347739648
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -ftree-vectorize, -fPIC, -fPIE, -fstack-protector-strong, -O2, -pipe, -isystem,
      /opt/anaconda3/include, -fdebug-prefix-map=/var/folders/k1/30mswbxs7r1g6zwn8y4fyt500000gp/T/abs_a51i_mbs7m/croot/numpy_and_numpy_base_1708638620867/work=/usr/local/src/conda/numpy-base-1.26.4,
      -fdebug-prefix-map=/opt/anaconda3=/usr/loca

3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a" Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [5]:
#Option 1
a = np.random.random((2, 3, 5))
#Option 2
a2 = np.random.randint(1, 101, size=(2, 3, 5))
#Option 3
a3 = np.array([[[random.randint(1, 100) for _ in range(5)] for _ in range(3)] for _ in range(2)])

4. Print a.

In [6]:
print(f"array a(random): \n {a}")

print(f"array a2(randint): \n {a2}")

print(f"array a3(list): \n {a3}")

array a(random): 
 [[[0.51240238 0.13965048 0.81677329 0.14906089 0.04307697]
  [0.868377   0.07001214 0.5157456  0.30566046 0.22735932]
  [0.97308628 0.14652076 0.41214279 0.34456002 0.57598029]]

 [[0.94609191 0.63929019 0.97996358 0.4500628  0.4509456 ]
  [0.10914408 0.38154968 0.52138138 0.79060221 0.94087444]
  [0.40692559 0.29052491 0.13116664 0.39691956 0.47559041]]]
array a2(randint): 
 [[[ 4 56  2 82 19]
  [16 48 74 61 23]
  [84  7 67 21 42]]

 [[14 39 95 69 94]
  [51 16 75 77 86]
  [31 87 43 11 91]]]
array a3(list): 
 [[[ 77  90  14  51  52]
  [ 71  73  27  43  89]
  [ 29  75  40   3  43]]

 [[ 13  47  36  22 100]
  [ 52  91  17  17  21]
  [  6  95  75  78   4]]]


5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable "b"

In [7]:
# b = a3 = np.array([[[1 for _ in range(5)] for _ in range(2)] for _ in range(3)])
b = np.ones((5, 2, 3))

6. Print B

In [8]:
print(b)
# print(b2)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


7. Do a and b have the same size? How do you prove that in Python code?

In [9]:
size_a = a.size
size_b = b.size

print(size_a== size_b)

True


8. Are you able to add a and b? Why or why not?

In [ ]:
#Not possible due to the different shape, but it could work if reshaped to the same size.

9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".

In [10]:
c = b.reshape(2,3,5)
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

In [11]:
d = a + c

print(d)

[[[1.51240238 1.13965048 1.81677329 1.14906089 1.04307697]
  [1.868377   1.07001214 1.5157456  1.30566046 1.22735932]
  [1.97308628 1.14652076 1.41214279 1.34456002 1.57598029]]

 [[1.94609191 1.63929019 1.97996358 1.4500628  1.4509456 ]
  [1.10914408 1.38154968 1.52138138 1.79060221 1.94087444]
  [1.40692559 1.29052491 1.13116664 1.39691956 1.47559041]]]


11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.

In [12]:
print(f" a: \n{a}")
print(f" d: \n{d}")

 a: 
[[[0.51240238 0.13965048 0.81677329 0.14906089 0.04307697]
  [0.868377   0.07001214 0.5157456  0.30566046 0.22735932]
  [0.97308628 0.14652076 0.41214279 0.34456002 0.57598029]]

 [[0.94609191 0.63929019 0.97996358 0.4500628  0.4509456 ]
  [0.10914408 0.38154968 0.52138138 0.79060221 0.94087444]
  [0.40692559 0.29052491 0.13116664 0.39691956 0.47559041]]]
 d: 
[[[1.51240238 1.13965048 1.81677329 1.14906089 1.04307697]
  [1.868377   1.07001214 1.5157456  1.30566046 1.22735932]
  [1.97308628 1.14652076 1.41214279 1.34456002 1.57598029]]

 [[1.94609191 1.63929019 1.97996358 1.4500628  1.4509456 ]
  [1.10914408 1.38154968 1.52138138 1.79060221 1.94087444]
  [1.40692559 1.29052491 1.13116664 1.39691956 1.47559041]]]


12. Multiply a and c. Assign the result to e.

In [13]:
e = a * c
print(e)

[[[0.51240238 0.13965048 0.81677329 0.14906089 0.04307697]
  [0.868377   0.07001214 0.5157456  0.30566046 0.22735932]
  [0.97308628 0.14652076 0.41214279 0.34456002 0.57598029]]

 [[0.94609191 0.63929019 0.97996358 0.4500628  0.4509456 ]
  [0.10914408 0.38154968 0.52138138 0.79060221 0.94087444]
  [0.40692559 0.29052491 0.13116664 0.39691956 0.47559041]]]


13. Does e equal to a? Why or why not?

In [ ]:
# Yes, because 1(c) times anything (a) is always (a).

14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"

In [14]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(f"d_max: {d_max} \nd_min_ {d_min} \nd_mean: {d_mean}")

d_max: 1.9799635841962366 
d_min_ 1.0430769692883715 
d_mean: 1.4670480558944556


15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using

In [15]:
f = np.empty((2, 3, 5))
print(f)

[[[0.51240238 0.13965048 0.81677329 0.14906089 0.04307697]
  [0.868377   0.07001214 0.5157456  0.30566046 0.22735932]
  [0.97308628 0.14652076 0.41214279 0.34456002 0.57598029]]

 [[0.94609191 0.63929019 0.97996358 0.4500628  0.4509456 ]
  [0.10914408 0.38154968 0.52138138 0.79060221 0.94087444]
  [0.40692559 0.29052491 0.13116664 0.39691956 0.47559041]]]


16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.

If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.

If a value equals to d_mean, assign 50 to the corresponding value in f.

Assign 0 to the corresponding value(s) in f for d_min in d.

Assign 100 to the corresponding value(s) in f for d_max in d.

In the end, f should have only the following values: 0, 25, 50, 75, and 100.

Note: you don't have to use Numpy in this question

In [16]:
d = np.array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(f"d_max: {d_max} \nd_min_ {d_min} \nd_mean: {d_mean}")

for ma, matrix in enumerate(d):
    for ro, row in enumerate(matrix):
        for el, element in enumerate(row):
            if d_mean > element > d_min:
                f[ma][ro][el] = 25
            elif element == d_max:
                f[ma][ro][el] = 100
            elif d_max > element > d_mean: 
                f[ma][ro][el] = 75    
            elif element > d_mean:
                f[ma][ro][el] = 50
            elif element == d_min:
                f[ma][ro][el] = 0
            
print(f" array is: \n {f}")     

d_max: 1.97066381 
d_min_ 1.00656599 
d_mean: 1.6175069086666667
 array is: 
 [[[ 75.  75.  75.  25.  75.]
  [ 75.  75.  25.  25.  25.]
  [ 75.  25.  75.  75.  75.]]

 [[ 25.  25.  25.  25. 100.]
  [ 75.  75.  75.  75.  75.]
  [ 25.  75.   0.  75.  75.]]]


17. Print d and f. Do you have your expected f? For instance, if your d is: array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931], [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981], [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381], [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881], [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be: array([[[ 75., 75., 75., 25., 75.], [ 75., 75., 25., 25., 25.], [ 75., 25., 75., 75., 75.]],

   [[ 25.,  25.,  25.,  25., 100.],
    [ 75.,  75.,  75.,  75.,  75.],
    [ 25.,  75.,   0.,  75.,  75.]]])

In [17]:
print(f"d: \n {d}") 
print(d.ndim)
print(f"f: \n {f}") 
print(f"d_max: {d_max} \nd_min_ {d_min} \nd_mean: {d_mean}")

d: 
 [[[1.85836099 1.67064465 1.62576044 1.40243961 1.88454931]
  [1.75354326 1.69403643 1.36729252 1.61415071 1.12104981]
  [1.72201435 1.1862918  1.87078449 1.7726778  1.88180042]]

 [[1.44747908 1.31673383 1.02000951 1.52218947 1.97066381]
  [1.79129243 1.74983003 1.96028037 1.85166831 1.65450881]
  [1.18068344 1.9587381  1.00656599 1.93402165 1.73514584]]]
3
f: 
 [[[ 75.  75.  75.  25.  75.]
  [ 75.  75.  25.  25.  25.]
  [ 75.  25.  75.  75.  75.]]

 [[ 25.  25.  25.  25. 100.]
  [ 75.  75.  75.  75.  75.]
  [ 25.  75.   0.  75.  75.]]]
d_max: 1.97066381 
d_min_ 1.00656599 
d_mean: 1.6175069086666667


18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values ("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be: array([[[ 'D', 'D', 'D', 'B', 'D'], [ 'D', 'D', 'B', 'B', 'B'], [ 'D', 'B', 'D', 'D', 'D']],

[[ 'B', 'B', 'B', 'B', 'E'], [ 'D', 'D', 'D', 'D', 'D'], [ 'B', 'D', 'A', 'D', 'D']]]) Again, you don't need Numpy in this question.

In [18]:
d = np.array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])
f = np.empty((2, 3, 5), dtype=str)
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(f"d_max: {d_max} \nd_min_ {d_min} \nd_mean: {d_mean}")

for ma, matrix in enumerate(d):
    for ro, row in enumerate(matrix):
        for el, element in enumerate(row):
            if d_mean > element > d_min:
                f[ma][ro][el] = "B" 
            elif element == d_max:
                f[ma][ro][el] = "E"
            elif d_max > element > d_mean: 
                f[ma][ro][el] = "D"    
            elif element > d_mean:
                f[ma][ro][el] = "B"
            elif element == d_min:
                f[ma][ro][el] = "A"

print(f" array is: \n {f}")     

d_max: 1.97066381 
d_min_ 1.00656599 
d_mean: 1.6175069086666667
 array is: 
 [[['D' 'D' 'D' 'B' 'D']
  ['D' 'D' 'B' 'B' 'B']
  ['D' 'B' 'D' 'D' 'D']]

 [['B' 'B' 'B' 'B' 'E']
  ['D' 'D' 'D' 'D' 'D']
  ['B' 'D' 'A' 'D' 'D']]]
