In [2]:
# %% 

#1. Import the NUMPY package under the name np.
import numpy as np


In [3]:
# %% 

#2. Print the NUMPY version and the configuration.
print(np.__version__)

#[your code here]

2.1.3


In [4]:
# %% 

#3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
# Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

from numpy import random

a = np.random.randint(1, 10, (2, 3, 5))
a1 = np.random.choice(range(1, 11), size=(2, 3, 5))
a2 = np.random.rand(2, 3, 5)

print(a)




[[[9 7 3 4 8]
  [4 9 5 3 3]
  [7 7 4 7 5]]

 [[2 3 2 5 6]
  [6 7 3 7 9]
  [9 8 8 6 1]]]


In [5]:

#4. Print a.

print(a)

[[[9 7 3 4 8]
  [4 9 5 3 3]
  [7 7 4 7 5]]

 [[2 3 2 5 6]
  [6 7 3 7 9]
  [9 8 8 6 1]]]


In [6]:
# %% 

#5. Create a 5x2x3 3-dimensional array with all values equaling 1.
#Assign the array to variable "b"
b = np.random.randint(1,2,(5,2,3))
b

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]], dtype=int32)

In [7]:
# %% 

#6. Print b.
print(b)

#[your code here]

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [8]:
# %% 

#7. Do a and b have the same size? How do you prove that in Python code?

a.size == b.size

True

In [9]:
# %% 

#8. Are you able to add a and b? Why or why not?
# array = matrix
a.shape == b.shape

# no because the arrays were with different shapes - a have 2 bigger blocks and b 5 blocks // rows and columns are different
# to fix this:

b_reshaped = b.reshape(2, 3, 5)  
print(b_reshaped.shape)  # (2, 3, 5)

combined = np.concatenate((a, b_reshaped), axis=0)
print(combined.shape)  # (4, 3, 5)
combined

# Now we have, the same numbers of columns and rows and we can merge both arrays

(2, 3, 5)
(4, 3, 5)


array([[[9, 7, 3, 4, 8],
        [4, 9, 5, 3, 3],
        [7, 7, 4, 7, 5]],

       [[2, 3, 2, 5, 6],
        [6, 7, 3, 7, 9],
        [9, 8, 8, 6, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]], dtype=int32)

In [10]:
# %% 

#9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".
c = b.transpose(1, 2, 0)
c



array([[[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]]], dtype=int32)

In [11]:
# %% 

#10. Try to add a and c. Now it should work. Assign the sum to varialbe "d". But why does it work now?

d = a + c 
a.shape == c.shape # they have the same shape

True

In [12]:
# %% 

#11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.
a
d


array([[[10,  8,  4,  5,  9],
        [ 5, 10,  6,  4,  4],
        [ 8,  8,  5,  8,  6]],

       [[ 3,  4,  3,  6,  7],
        [ 7,  8,  4,  8, 10],
        [10,  9,  9,  7,  2]]], dtype=int32)

In [22]:
# %% 

#12. Multiply a and c. Assign the result to e.


e = a * c  


print("Array a:")
print(a)
print("\nArray c:")
print(c)
print("\nArray e (a * c):")
print(e)


Array a:
[[[9 7 3 4 8]
  [4 9 5 3 3]
  [7 7 4 7 5]]

 [[2 3 2 5 6]
  [6 7 3 7 9]
  [9 8 8 6 1]]]

Array c:
[[[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]

 [[1 1 1 1 1]
  [1 1 1 1 1]
  [1 1 1 1 1]]]

Array e (a * c):
[[[9 7 3 4 8]
  [4 9 5 3 3]
  [7 7 4 7 5]]

 [[2 3 2 5 6]
  [6 7 3 7 9]
  [9 8 8 6 1]]]


In [ ]:
# %% 

#13. Does e equal to a? Why or why not?

# memory space (data stored in 2 different locations) - e = new array, new location // e = new object // separate object

print(np.may_share_memory(a, e))  #This confirms that a and e do not share memory as they are separate arrays.
print(id(a))  #memory_id
print(id(e))  #memory_id

# Check if e is equal to a
are_equal = np.array_equal(a, e) # their values are the same


#summary:
# Parent Table:The original array (a) that contains the initial data.

# Child Table:Created from the parent array (a) through operations like slicing, transposing, or others that do not duplicate the data.
# These arrays share memory with the parent table.

# New Arrays (Independent) = e 
# Created by explicit copies (.copy()) or operations that allocate new memory, such as concatenation. 
#These arrays do not share memory with the original array.




False
2256986703600
2256986702064


In [ ]:
# %% 

#14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


d_max = np.max(d)   
d_min = np.min(d)  
d_mean = np.mean(d) 


print("Max value in d:", d_max)
print("Min value in d:", d_min)
print("Mean value in d:", d_mean)


Max value in d: 10
Min value in d: 2
Mean value in d: 6.566666666666666


In [ ]:
# %% 

#15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


d = np.random.randint(1, 10, (2, 3, 5))  

# np.empty like - copies the structure of the original array,  matches the shape (blocks, columns, rows) and data type.
# but without initializing the values (random /garbage from previous array)
f = np.empty_like(d)  

# Print the result
print("Empty array f:")
print(f)


#other different functions
np.zeros_like #new array with the same shape and data type as the input array, but with all elements initialized to zero.
np.ones_like new array with the same shape and data type as the input array, but with all elements initialized to one.


Empty array f:
[[[3 6 9 3 7]
  [9 8 1 1 4]
  [2 4 4 7 4]]

 [[2 6 3 8 5]
  [8 3 4 7 1]
  [3 3 6 3 2]]]


In [46]:
# %% 


"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""


d_flat = [value for sublist1 in d for sublist2 in sublist1 for value in sublist2]
d_min = min(d_flat)
d_mean = sum(d_flat) / len(d_flat)
d_max = max(d_flat)


f = [[[0 for _ in range(len(d[0][0]))] for _ in range(len(d[0]))] for _ in range(len(d))]


for i in range(len(d)):
    for j in range(len(d[i])):
        for k in range(len(d[i][j])):
            value = d[i][j][k]
            if value == d_min:
                f[i][j][k] = 0
            elif value == d_max:
                f[i][j][k] = 100
            elif value == d_mean:
                f[i][j][k] = 50
            elif d_min < value < d_mean:
                f[i][j][k] = 25
            elif d_mean < value < d_max:
                f[i][j][k] = 75


for row in f:
    print(row)

[[75, 25, 0, 75, 100], [75, 0, 100, 25, 75], [25, 100, 25, 25, 100]]
[[75, 25, 25, 25, 0], [0, 75, 75, 75, 25], [50, 75, 100, 25, 75]]


In [47]:
# %% 


"""
#17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

[[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])
"""

import numpy as np




d_min = np.min(d)
d_mean = np.mean(d)
d_max = np.max(d)


f = np.empty_like(d)


for i in range(d.shape[0]):  # Iterate over the first dimension
    for j in range(d.shape[1]):  # Iterate over the second dimension
        for k in range(d.shape[2]):  # Iterate over the third dimension
            value = d[i, j, k]
            if value == d_min:
                f[i, j, k] = 0
            elif value == d_max:
                f[i, j, k] = 100
            elif value == d_mean:
                f[i, j, k] = 50
            elif d_min < value < d_mean:
                f[i, j, k] = 25
            elif d_mean < value < d_max:
                f[i, j, k] = 75



print("d:")
print(d)
print("\nf:")
print(f)


d:
[[[8 2 1 8 9]
  [6 1 9 3 7]
  [2 9 2 2 9]]

 [[6 2 3 3 1]
  [1 8 7 8 2]
  [5 8 9 2 7]]]

f:
[[[ 75  25   0  75 100]
  [ 75   0 100  25  75]
  [ 25 100  25  25 100]]

 [[ 75  25  25  25   0]
  [  0  75  75  75  25]
  [ 50  75 100  25  75]]]
