# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [2]:

import numpy as np



### 2. Print the NUMPY version and the configuration.


In [3]:
print(np.__version__)
np.show_config()

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/Lsula/anaconda3/Library/include
    lib directory: C:/Users/Lsula/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1868282989520
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  host:
  

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [19]:
# the first
# a = np.random.random((2,3,5))

#the second
#a = np.random.random_sample((2, 3, 5))

# the third
a = np.random.randint(100, size =(2, 3, 5))

print(a.shape)
a


(2, 3, 5)


array([[[ 7, 14, 44, 30, 77],
        [82, 21, 24, 30, 41],
        [88, 33, 76, 42, 95]],

       [[41, 14, 36, 55,  9],
        [89, 66, 18, 92, 17],
        [55, 61, 95, 51, 70]]])


### 4. Print a.


In [20]:
print(a)



[[[ 7 14 44 30 77]
  [82 21 24 30 41]
  [88 33 76 42 95]]

 [[41 14 36 55  9]
  [89 66 18 92 17]
  [55 61 95 51 70]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [21]:
b = np.ones((5, 2, 3))
print(b.shape)
b

(5, 2, 3)


array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])


### 6. Print b.


In [24]:
print(b)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [26]:
if a.size ==b.size:
    print("Yes, a and b have the same size")
else:
    print("No, a and b do not have the same size")

Yes, a and b have the same size



### 8. Are you able to add a and b? Why or why not?


In [27]:
# they can be added if they have the same shape
if (a.shape ==b.shape):
    print("Yes, it can be added")
else:
    print("No, diffrent shapes")


No, diffrent shapes




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [ ]:
#a.shape # 2, 3, 5
#b.shape # 5 ,2 ,3
c = np.transpose(b, (1, 2, 0)) # re arrnge the index of the axes
c.shape # should match a

(2, 3, 5)


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [32]:
d = a + c
d
# it works because now they have the same shape

array([[[ 8., 15., 45., 31., 78.],
        [83., 22., 25., 31., 42.],
        [89., 34., 77., 43., 96.]],

       [[42., 15., 37., 56., 10.],
        [90., 67., 19., 93., 18.],
        [56., 62., 96., 52., 71.]]])


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [ ]:
print("array a\n:", a)
print("\n\narray d:\n", d)

# the have the same shape, and each value in d = a value +1, which is logical beacuse array c was all ones
# we can say that array d is array a shifted by adding 1

array a
: [[[ 7 14 44 30 77]
  [82 21 24 30 41]
  [88 33 76 42 95]]

 [[41 14 36 55  9]
  [89 66 18 92 17]
  [55 61 95 51 70]]]


array d:
 [[[ 8. 15. 45. 31. 78.]
  [83. 22. 25. 31. 42.]
  [89. 34. 77. 43. 96.]]

 [[42. 15. 37. 56. 10.]
  [90. 67. 19. 93. 18.]
  [56. 62. 96. 52. 71.]]]



### 12. Multiply a and c. Assign the result to e.


In [35]:
e = a * c
e

array([[[ 7., 14., 44., 30., 77.],
        [82., 21., 24., 30., 41.],
        [88., 33., 76., 42., 95.]],

       [[41., 14., 36., 55.,  9.],
        [89., 66., 18., 92., 17.],
        [55., 61., 95., 51., 70.]]])



### 13. Does e equal to a? Why or why not?


In [36]:


if np.array_equal(a, e):
    print(" a = e")

else:
    print("a != e")
    
# yes a = e, because each value of [a] was multiplied be the coordinater value in c which all = 1
# so a will remain the same


 a = e




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [32]:
### [your code here]




### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [33]:
### [your code here]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [34]:
### [your code here]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [35]:
### [your code here]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [36]:
### [your code here]