# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [2]:
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [3]:
# Print NumPy version
print("My NumPy Version:", np.__version__)

# Print NumPy configuration
np.show_config()

My NumPy Version: 1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /usr/local/include
    lib directory: /usr/local/lib
    name: openblas64
    openblas configuration: USE_64BITINT=1 DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK= NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP= HASWELL MAX_THREADS=2
    pc file directory: /usr/local/lib/pkgconfig
    version: 0.3.23.dev
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep140213194937296
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -fno-strict-aliasing
    commands: cc
    linker: ld.bfd
    linker args: -Wl,--strip-debug, -fno-strict-aliasing
    name: gcc
    version: 10.2.1
  c++:
    commands: c++
    linker: ld.bfd
    linker args: -Wl,--strip-debug
    name: gcc
    version: 10.2.1
  cython:
    commands: cython
    linker: cython
  

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


# **Method 1: By using numpy.random.rand**

In [4]:
a = np.random.rand(2, 3, 5)

# **Method 1: By using numpy.random.random**

In [5]:
a = np.random.random((2, 3, 5))

#**Method 3: Using numpy.random.uniform**

In [6]:
a = np.random.uniform(size=(2, 3, 5))


### 4. Print a.


In [7]:
# Method 1: Using numpy.random.rand
a1 = np.random.rand(2, 3, 5)
print("Method 1 (np.random.rand):\n", a1, "\n")

# Method 2: Using numpy.random.random
a2 = np.random.random((2, 3, 5))
print("Method 2 (np.random.random):\n", a2, "\n")

# Method 3: Using numpy.random.uniform
a3 = np.random.uniform(size=(2, 3, 5))
print("Method 3 (np.random.uniform):\n", a3, "\n")

Method 1 (np.random.rand):
 [[[9.55836657e-01 4.01549248e-01 3.21213573e-01 1.09158570e-01
   2.50713757e-01]
  [6.28348482e-01 5.34857236e-01 2.69615345e-01 9.39979329e-01
   1.45400935e-01]
  [6.60295873e-01 1.70502632e-01 9.31533019e-01 2.31609590e-01
   6.42998781e-01]]

 [[3.52957653e-01 3.02137753e-01 3.57875136e-01 9.57324029e-01
   8.88823939e-01]
  [1.43360344e-04 7.47960598e-01 3.83666609e-01 2.87991439e-01
   4.30923730e-01]
  [6.93447407e-01 2.84264791e-02 6.84144514e-01 3.73773627e-01
   7.57016336e-01]]] 

Method 2 (np.random.random):
 [[[0.20801282 0.22500396 0.75751093 0.02630721 0.68099895]
  [0.91873919 0.63708878 0.23178478 0.26949466 0.02775869]
  [0.1270278  0.73395329 0.32793912 0.1796207  0.39185736]]

 [[0.08371259 0.08013276 0.73609269 0.91691718 0.97672055]
  [0.29987502 0.75218577 0.71638579 0.27759371 0.49027512]
  [0.70102642 0.46165214 0.60038984 0.93332892 0.03748993]]] 

Method 3 (np.random.uniform):
 [[[0.55794549 0.81748271 0.1720665  0.5005519  0.6099

### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [9]:
#The function that ensures all values in the array are 1 is np.ones().
b = np.ones((5, 2, 3))


### 6. Print b.


In [10]:
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [11]:
# shape of (2,3,5), meaning:
# - 2 blocks
# - 3 rows per block
# - 5 columns per row
a = np.random.random((2, 3, 5))

# shape of (5,2,3), meaning:
# - 5 blocks
# - 2 rows per block
# - 3 columns per row
b = np.ones((5, 2, 3))

# Even though the shapes are different, let's check if they have the same total number of elements.
# We can do this using the `.size` attribute, which tells us how many elements are in the array.
same_size = a.size == b.size  # This checks if both arrays contain the same number of elements.

# Finally, let's print the result so we can see if they match.
print(f"Do a and b have the same size? {same_size}")  # Should print: True, since both have 30 elements.

Do a and b have the same size? True



### 8. Are you able to add a and b? Why or why not?


In [12]:
### No, We cannot directly add a and b because their shapes are different and they are not compatible for broadcasting.
c = a + b  # This will raise a ValueError

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [13]:
# Transpose b to match a's shape (2,3,5)
c = b.transpose(1, 2, 0)

# Check if shapes now match
print(f"Shape of a: {a.shape}")  # (2,3,5)
print(f"Shape of c: {c.shape}")  # (2,3,5) - Now matches 'a'


Shape of a: (2, 3, 5)
Shape of c: (2, 3, 5)



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [16]:
# Since c was transposed to match a's shape, NumPy can now perform element-wise addition, resulting in d
d = a + c


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [17]:
# d is the result of a + c, and since c is filled with ones, every element in d is simply a’s value + 1.
# This means d will have the same structure as a, but all values are exactly 1 greater than those in a.
# Print a and d to compare their values
print("Array a:\n", a)
print("\nArray d:\n", d)

Array a:
 [[[0.42474088 0.48502958 0.49921963 0.55732436 0.60934613]
  [0.1333806  0.54001488 0.61218565 0.36259096 0.13171725]
  [0.72785147 0.53346469 0.11601564 0.6322377  0.13626094]]

 [[0.71555449 0.77552663 0.3052462  0.04965102 0.60585723]
  [0.76086678 0.81762341 0.23896837 0.56612    0.27217505]
  [0.6342143  0.9356203  0.60974595 0.47277977 0.77902548]]]

Array d:
 [[[1.42474088 1.48502958 1.49921963 1.55732436 1.60934613]
  [1.1333806  1.54001488 1.61218565 1.36259096 1.13171725]
  [1.72785147 1.53346469 1.11601564 1.6322377  1.13626094]]

 [[1.71555449 1.77552663 1.3052462  1.04965102 1.60585723]
  [1.76086678 1.81762341 1.23896837 1.56612    1.27217505]
  [1.6342143  1.9356203  1.60974595 1.47277977 1.77902548]]]



### 12. Multiply a and c. Assign the result to e.


In [18]:
# Multiply a and c element-wise
e = a * c
print(e)

[[[0.42474088 0.48502958 0.49921963 0.55732436 0.60934613]
  [0.1333806  0.54001488 0.61218565 0.36259096 0.13171725]
  [0.72785147 0.53346469 0.11601564 0.6322377  0.13626094]]

 [[0.71555449 0.77552663 0.3052462  0.04965102 0.60585723]
  [0.76086678 0.81762341 0.23896837 0.56612    0.27217505]
  [0.6342143  0.9356203  0.60974595 0.47277977 0.77902548]]]




### 13. Does e equal to a? Why or why not?


In [ ]:
# Yes ,Since c is filled with ones, multiplying a by c doesn’t change a's values.
# This means e will be exactly the same as a because multiplying by 1 has no effect.



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [20]:
# Identify the max, min, and mean values in d
d_max = d.max()   # Maximum value in d
d_min = d.min()   # Minimum value in d
d_mean = d.mean() # Mean (average) value in d


### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [21]:
# Create an empty array 'f' with the same shape as d (2, 3, 5)
f = np.empty(d.shape)




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [23]:
# Populate the values in f based on the conditions given
for i in range(d.shape[0]):  # Loop through the first dimension (2)
    for j in range(d.shape[1]):  # Loop through the second dimension (3)
        for k in range(d.shape[2]):  # Loop through the third dimension (5)
            value = d[i, j, k]  # Get the value from d
            if value == d_min:
                f[i, j, k] = 0  # If value equals d_min, assign 0
            elif value == d_max:
                f[i, j, k] = 100  # If value equals d_max, assign 100
            elif value == d_mean:
                f[i, j, k] = 50  # If value equals d_mean, assign 50
            elif d_min < value < d_mean:
                f[i, j, k] = 25  # If value is between d_min and d_mean, assign 25
            elif d_mean < value < d_max:
                f[i, j, k] = 75  # If value is between d_mean and d_max, assign 75





### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [24]:
# The values in f should match the conditions that set based on d's values
# f will contain:
# 0 for d_min, 25 for values between d_min and d_mean,
# 50 for d_mean, 75 for values between d_mean and d_max,
# 100 for d_max.

# Print d and f
print("Array d:\n", d)
print("\nArray f (labeled values):\n", f)

Array d:
 [[[1.42474088 1.48502958 1.49921963 1.55732436 1.60934613]
  [1.1333806  1.54001488 1.61218565 1.36259096 1.13171725]
  [1.72785147 1.53346469 1.11601564 1.6322377  1.13626094]]

 [[1.71555449 1.77552663 1.3052462  1.04965102 1.60585723]
  [1.76086678 1.81762341 1.23896837 1.56612    1.27217505]
  [1.6342143  1.9356203  1.60974595 1.47277977 1.77902548]]]

Array f (labeled values):
 [[[ 25.  25.  25.  75.  75.]
  [ 25.  75.  75.  25.  25.]
  [ 75.  75.  25.  75.  25.]]

 [[ 75.  75.  25.   0.  75.]
  [ 75.  75.  25.  75.  25.]
  [ 75. 100.  75.  25.  75.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [29]:
# Create an empty 2x3x5 list for 'f' with string type
f = [[[None for _ in range(d.shape[2])] for _ in range(d.shape[1])] for _ in range(d.shape[0])]

# Populate 'f' with string labels instead of numbers
for i in range(len(d)):  # Loop through the first dimension
    for j in range(len(d[i])):  # Loop through the second dimension
        for k in range(len(d[i][j])):  # Loop through the third dimension
            value = d[i][j][k]
            if value == d_min:
                f[i][j][k] = 'A'  # d_min gets 'A'
            elif value == d_max:
                f[i][j][k] = 'E'  # d_max gets 'E'
            elif value == d_mean:
                f[i][j][k] = 'C'  # d_mean gets 'C'
            elif d_min < value < d_mean:
                f[i][j][k] = 'B'  # Between d_min and d_mean gets 'B'
            elif d_mean < value < d_max:
                f[i][j][k] = 'D'  # Between d_mean and d_max gets 'D'

# Print d and f to verify the result
print("\nArray f (labeled with strings):\n", f)


Array f (labeled with strings):
 [[['B', 'B', 'B', 'D', 'D'], ['B', 'D', 'D', 'B', 'B'], ['D', 'D', 'B', 'D', 'B']], [['D', 'D', 'B', 'A', 'D'], ['D', 'D', 'B', 'D', 'B'], ['D', 'E', 'D', 'B', 'D']]]
