In [20]:
import numpy as np


#2. Print the NUMPY version and the configuration.

In [21]:
np.show_config()


Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/fmrol/anaconda3/Library/include
    lib directory: C:/Users/fmrol/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\b\abs_c1ywpu18ar\croot\numpy_and_numpy_base_1708638681471\_h_env\Library\lib\pkgconfig
    version: '2023.1'
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep1583119523984
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30154
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.0.8
Machine Information:
  build:
    cpu: x86_64
    endian: little
    family: x86_64
    system: windows
  host:
    cpu: 

In [22]:
a = np.random.random((2,3,5))
print(a)

[[[0.53967888 0.74429601 0.37419904 0.76533769 0.00834976]
  [0.85540665 0.28509141 0.68049377 0.11676625 0.28732249]
  [0.23351077 0.95956195 0.8239157  0.27629942 0.56566266]]

 [[0.58173632 0.77888439 0.61294269 0.32342604 0.857298  ]
  [0.30220625 0.98701708 0.41668816 0.58120163 0.04168982]
  [0.3657115  0.54287139 0.98487898 0.57812147 0.2333867 ]]]


In [23]:
b = np.ones((5,2,3))
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [24]:
if a.size == b.size:
    print("yes, they have the same size")
else:
    print("No they don't have the same size")


yes, they have the same size


In [25]:
a is b

False

In [26]:
if a.shape == b.shape:
    result = a + b
    print("Addition Result:")
    print(result)
else:
    print("Arrays have different shapes and cannot be added.")

Arrays have different shapes and cannot be added.


In [27]:
c = np.transpose(b, (1, 2, 0))
print("Array c (transposed b):")
print(c)

Array c (transposed b):
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [28]:
d = a + c
print("Addition of a and c:")
print(d)
print("The addition works because 'a' and 'c' now have the same shape.")

Addition of a and c:
[[[1.53967888 1.74429601 1.37419904 1.76533769 1.00834976]
  [1.85540665 1.28509141 1.68049377 1.11676625 1.28732249]
  [1.23351077 1.95956195 1.8239157  1.27629942 1.56566266]]

 [[1.58173632 1.77888439 1.61294269 1.32342604 1.857298  ]
  [1.30220625 1.98701708 1.41668816 1.58120163 1.04168982]
  [1.3657115  1.54287139 1.98487898 1.57812147 1.2333867 ]]]
The addition works because 'a' and 'c' now have the same shape.


In [30]:
e = a*c
print("Multiplication of a and c results in 'e':")
print(e)


Multiplication of a and c results in 'e':
[[[0.53967888 0.74429601 0.37419904 0.76533769 0.00834976]
  [0.85540665 0.28509141 0.68049377 0.11676625 0.28732249]
  [0.23351077 0.95956195 0.8239157  0.27629942 0.56566266]]

 [[0.58173632 0.77888439 0.61294269 0.32342604 0.857298  ]
  [0.30220625 0.98701708 0.41668816 0.58120163 0.04168982]
  [0.3657115  0.54287139 0.98487898 0.57812147 0.2333867 ]]]


In [31]:
if np.array_equal(e, a):
    print("Yes, e equals a.")
else:
    print("No, e does not equal a.")

print("Explanation: 'e' equals 'a' because multiplying any number by 1 results in the same number. Since 'c' is an array of ones, the multiplication doesn't change the values of 'a'.")


Yes, e equals a.
Explanation: 'e' equals 'a' because multiplying any number by 1 results in the same number. Since 'c' is an array of ones, the multiplication doesn't change the values of 'a'.


In [32]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print("d_max:", d_max)
print("d_min:", d_min)
print("d_mean:", d_mean)

d_max: 1.9870170786877568
d_min: 1.0083497626823468
d_mean: 1.523465095845555


In [33]:
f = np.empty(d.shape)
print("Array f (empty):")
print(f)

Array f (empty):
[[[0.53967888 0.74429601 0.37419904 0.76533769 0.00834976]
  [0.85540665 0.28509141 0.68049377 0.11676625 0.28732249]
  [0.23351077 0.95956195 0.8239157  0.27629942 0.56566266]]

 [[0.58173632 0.77888439 0.61294269 0.32342604 0.857298  ]
  [0.30220625 0.98701708 0.41668816 0.58120163 0.04168982]
  [0.3657115  0.54287139 0.98487898 0.57812147 0.2333867 ]]]


In [34]:
"""
#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.
"""


"\n#16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.\nIf a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.\nIf a value equals to d_mean, assign 50 to the corresponding value in f.\nAssign 0 to the corresponding value(s) in f for d_min in d.\nAssign 100 to the corresponding value(s) in f for d_max in d.\nIn the end, f should have only the following values: 0, 25, 50, 75, and 100.\nNote: you don't have to use Numpy in this question.\n"

In [35]:
for i in range(d.shape[0]):  # Loop over the first dimension
    for j in range(d.shape[1]):  # Loop over the second dimension
        for k in range(d.shape[2]):  # Loop over the third dimension
            # Apply conditions
            if d[i, j, k] == d_min:
                f[i, j, k] = 0
            elif d[i, j, k] == d_max:
                f[i, j, k] = 100
            elif d[i, j, k] == d_mean:
                f[i, j, k] = 50
            elif d_min < d[i, j, k] < d_mean:
                f[i, j, k] = 25
            elif d_mean < d[i, j, k] < d_max:
                f[i, j, k] = 75

print("Array f after populating values:")
print(f)

Array f after populating values:
[[[ 75.  75.  25.  75.   0.]
  [ 75.  25.  75.  25.  25.]
  [ 25.  75.  75.  25.  75.]]

 [[ 75.  75.  75.  25.  75.]
  [ 25. 100.  25.  75.  25.]
  [ 25.  75.  75.  75.  25.]]]


In [36]:
print(d)
print(f)

[[[1.53967888 1.74429601 1.37419904 1.76533769 1.00834976]
  [1.85540665 1.28509141 1.68049377 1.11676625 1.28732249]
  [1.23351077 1.95956195 1.8239157  1.27629942 1.56566266]]

 [[1.58173632 1.77888439 1.61294269 1.32342604 1.857298  ]
  [1.30220625 1.98701708 1.41668816 1.58120163 1.04168982]
  [1.3657115  1.54287139 1.98487898 1.57812147 1.2333867 ]]]
[[[ 75.  75.  25.  75.   0.]
  [ 75.  25.  75.  25.  25.]
  [ 25.  75.  75.  25.  75.]]

 [[ 75.  75.  75.  25.  75.]
  [ 25. 100.  25.  75.  25.]
  [ 25.  75.  75.  75.  25.]]]
